### PR TITLE
graph-tool 2.27: upstream fix and with-expat option added

### PR DESCRIPTION
**Pull request by vasikos**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Upstream fix solves [issue](https://git.skewed.de/count0/graph-tool/commit/aa39e4a6b42d43fac30c841d176c75aff92cc01a) with graph-tool compilation with CGAL 4.13

Adding --with-expat option solves problem with using expat from brew.

### CODE REVIEW

**Comment by fxcoudert** [comment]
This should fix it.

**Comment by fxcoudert** [comment]
Now fails only on High Sierra:

```
    In file included from src/ft2font_wrapper.cpp:5:
    In file included from src/numpy_cpp.h:19:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:246:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
    using ::signbit;
          ~~^
```

**Comment by kbaegis** [comment]
My homebrew is failing expat as well. `Mojave 10.14 (18A391)` and `Homebrew 1.7.7, Homebrew/homebrew-core (git revision e1318; last commit 2018-10-21), Homebrew/homebrew-cask (git revision 26a26; last commit 2018-10-21)`

```
....
checking whether to enable cairo drawing... yes
checking for Expat XML Parser... no
configure: error: expat library not found

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
graph-tool failed to build on 10.14 https://github.com/Homebrew/homebrew-core/issues/32592
graph-tool 2.27: upstream fix and with-expat option added https://github.com/Homebrew/homebrew-core/pull/32851```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
I am going to merge this in its current state: even though it's not perfect, it puts us in better shape than we are currently (especially with respect to CGAL 4.13).

**Comment by fxcoudert** [comment]
Thanks @vasikos for the pull request!
