### ISSUE TITLE
libzip installation doesn't link zipconf.h file

### ISSUE THREAD

**Issue by richsage** [Homebrew/homebrew-core#22700]
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

- What you were trying to do (and why)

Compile PHP 7.2 against `libzip` (compiling PHP 7.2 using homebrew-php, but believe the issue would be the same across other packages that use `libzip`)

- What happened (include command output)

Build gets to the `make` stage and fails on the inclusion of `zipconf.h`, because this file isn't symlinked from the library into `/usr/local/include`

```
Last 15 lines from /Users/rich/Library/Logs/Homebrew/php72/02.make:
In file included from /private/tmp/php72-20180110-61786-195g8ru/php-7.2.1/ext/zip/php_zip.c:36:
In file included from ext/zip/php_zip.h:31:
/usr/local/opt/libzip/include/zip.h:59:10: fatal error: 'zipconf.h' file not found
#include <zipconf.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [ext/zip/php_zip.lo] Error 1
make: *** Waiting for unfinished jobs....
In file included from /private/tmp/php72-20180110-61786-195g8ru/php-7.2.1/ext/zip/zip_stream.c:29:
In file included from ext/zip/php_zip.h:31:
/usr/local/opt/libzip/include/zip.h:59:10: fatal error: 'zipconf.h' file not found
#include <zipconf.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [ext/zip/zip_stream.lo] Error 1
READ THIS: https://docs.brew.sh/Troubleshooting.html
These open issues may also help:
php72 after update enchant to 2.1.2 error https://github.com/Homebrew/homebrew-php/issues/4650
php72-uuid 1.0.4 (new formula) https://github.com/Homebrew/homebrew-php/pull/4247
```

- What you expected to happen

Build to complete successfully, linking against the Homebrew-installed `libzip` library

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install libzip
brew install php72 --with-libzip
```

(this last one relies on [this PR](https://github.com/Homebrew/homebrew-php/pull/4705) to allow compilation of PHP using a defined `libzip` directory)

Note that compilation of PHP 7.2 by default uses whatever `libzip` version it can find, which currently is an older version by default on macOS - this will build fine (1.15.x) on my local machine. Compiling against the latest version in Homebrew (via the PR listed above) causes the error, as otherwise the Homebrew `libzip` installation isn't used when building PHP.

There is a solution listed [here](https://github.com/brimworks/lua-zip/issues/11#issuecomment-322807782), reproduced as follows:

```
cp /usr/local/Cellar/libzip/1.2.0/lib/libzip/include/zipconf.h /usr/local/Cellar/libzip/1.2.0/include/zipconf.h
ln -sf ../Cellar/libzip/1.2.0/include/zipconf.h /usr/local/include/zipconf.h
```
(adjusting version numbers as appropriate - I installed with libzip 1.3.0). This solves the issue, but I'm not au fait enough with Homebrew to determine whereabouts to ensure this file is linked as part of the `libzip` installation process 🙂  or indeed whether this is an issue with the `libzip` library itself and not Homebrew...

---

## `brew config` output

```
HOMEBREW_VERSION: 1.4.3-16-gb29213a
ORIGIN: https://github.com/Homebrew/brew
HEAD: b29213a663c547c64b1cda55f622249c90320604
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 57c92ffbfcd84a9f3ad16e4e46c28e52b4ad0736
Core tap last commit: 50 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/rich/.rvm/rubies/ruby-2.2.3/bin/ruby
Java: 1.8.0_131, 1.8.0_101
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

**Comment by ilovezfs** [comment]
The file's location is now /usr/local/Cellar/libzip/1.3.0/lib/libzip/include/zipconf.h. You'll need to contact php upstream and get them to look for it in the current location.
