### PR TITLE
docker-machine-driver-xhyve: update to opam 2.x

### LINKED ISSUE #31740: docker-machine-driver-xhyve fails to build on macOS 10.14 Mojave
See #28817. Error is:

```
==> opam config exec -- make lib9p
vendor/lib9p/request.c:28:10: vendor/lib9p/pack.c:32:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
vendor/lib9p/connection.c:28:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
vendor/lib9p/log.c:28:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [vendor/build/lib9p/log.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
1 error generated.
make: *** [vendor/build/lib9p/connection.o] Error 1
make: *** [vendor/build/lib9p/request.o] Error 1
make: *** [vendor/build/lib9p/pack.o] Error 1
```

### PR DESCRIPTION
**Pull request by infrequentcoder**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Updates docker-machine-driver-xhyve to compile with opam 2.x on Mojave.
Fixes #31740.

### CODE REVIEW

**Comment by jarrtt** [comment]
Accidentally left the ~ backup file from emacs. Will submit again without that file.
