### PR TITLE
openssl@1.1 1.1.0c

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
10.12
```
==> brew linkage --test passenger
==> FAILED
Missing libraries:
  /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib
  /usr/local/opt/apr/libexec/lib/libapr-1.0.dylib
```
:(

**Comment by DomT4** [comment]
Oh, of course. Homebrew Apr's aren't `build` only.

**Comment by DomT4** [comment]
Should be fixed whenever CI picks the new push up.

**Comment by ilovezfs** [comment]
Dropping 1.1 support from passenger?

**Comment by ilovezfs** [comment]
@DomT4 if we back out openssl 1.1 from passenger (which I don't necessarily oppose), then I think we also need to back it out from nginx. The reason we added openssl 1.1 to passenger was that a PR adding openssl 1.1 to nginx was merged, and then I noticed that nginx has a `--with-passenger` option, and that passenger also depends on openssl. So to avoid mixing and matching openssl versions, we also added 1.1 to passenger, but it would have been equally valid to revert the nginx PR, which probably never should have been merged,

**Comment by DomT4** [comment]
Will reply properly when at laptop & commit again, but Apr-util uses OpenSSL, and IIRC doesn't yet build with the 1.1 branch, so to avoid mixing crypto libraries if the Homebrew Apr is used the 1.0.2 OpenSSL needs to be used as well.

**Comment by ilovezfs** [comment]
@DomT4 that's fine. We'll just need to back it out from nginx as well then, I think, or drop the passenger option from nginx.

**Comment by DomT4** [comment]
Let me know how you feel about those changes.

**Comment by ilovezfs** [comment]
I like it, given my current understanding of the constraints.

But Is it possible to build passenger without apr-util or to build apr-util without the openssl dep?

I'm a little concerned that the proliferation of the apr/apr-utils formula dependencies is going to interfere with the overall transition to openssl 1.1, not that I'm actually in any rush for us to transition to 1.1.

I noticed apr-util has been subsumed by apr in apr svn trunk. Do we know if apr svn trunk builds with openssl 1.1?

**Comment by DomT4** [comment]
> But Is it possible to build passenger without apr-util 

Apparently not:
```
In file included from src/apache2_module/mod_passenger.c:26:
In file included from /usr/include/apache2/httpd.h:44:
In file included from /usr/include/apache2/ap_config.h:25:
/usr/include/apache2/ap_hooks.h:40:10: fatal error: 'apr_hooks.h' file not found
#include "apr_hooks.h"
         ^
1 error generated.
```

> build apr-util without the openssl dep

This is possible, yes, but I'm not sure it wouldn't cause issues with other formulae. I believe `subversion` relies on Apr's crypto elements for some aspects, for example, but don't quote me.

> I'm a little concerned that the proliferation of the apr/apr-utils formula dependencies is going to interfere with the overall transition to openssl 1.1, not that I'm actually in any rush for us to transition to 1.1.

Agreed. 1.0.2 is LTS, so there's no rush at all, but the cleaner codebase and feature set of 1.1.0 is certainly desirable. To have an important backbone of an increasing number of formulae unable to use 1.1.0 is a pain.

> I noticed apr-util has been subsumed by apr in apr svn trunk. Do we know if apr svn trunk builds with openssl 1.1?

Yup. Always thought them being separate was a bit odd, so glad to see them come together formally. Not sure about `HEAD`, I had a look and `configure` finds all the elements it specifically checks for, but `make` blows up for a seemingly unrelated reason:

```
==> make
Makefile:52: /private/tmp/apr-util-20161111-38356-qv8syg/build-outputs.mk: No such file or directory
make: *** No rule to make target `/private/tmp/apr-util-20161111-38356-qv8syg/build-outputs.mk'.  Stop.
```

**Comment by ilovezfs** [comment]
Thanks, Dominyk.

**Comment by DomT4** [comment]
Thanks ILZ ❤️
