### ISSUE TITLE
Test and build failures found during python 3.9 testing

### ISSUE THREAD

**Issue by Rylan12** [Homebrew/homebrew-core#66450]
Here are a list of issues that need to be resolved after the most recent `python@3.9` run (https://github.com/Homebrew/homebrew-core/pull/66268):

- [x] `asuka` — test (11.0) dd308e73fd63f639eb62bf6e4975d7a0b22628ed
- [x] `augustus` — test (11.0) 2d6844e96066c034cacf0b03d0ab1bc7bb0504b0
- [x] `cargo-edit` — test 51524bdaf8a381016c08345cb27d79fe50136141
- [x] `corral` — test (11.0) d0b6db00c22002a7f6d56b3ed1bd2e21ca4a5bfd
- [ ] `couchdb-lucene` — test
- [x] `creduce` — test (11.0) eb6abcfe69ba84d017c488853edf6462b34e46ef
- [x] `cucumber-cpp` — test (10.14) #67689
- [x] `diff-pdf` — fetch #66369
- [x] `envoy` — install (11.0) d275c9406b729c782a87bca9def979519183a707
- [x] `glyr` — test #70505
- [ ] `get-flash-videos` — test (11.0)
- [ ] `hyperkit` — test
- [x] `innotop` — test (11.0) 024786559cafa53cc7dfb780da8fc8c7809e7821
- [x] `mapnik` — linkage, fetch  #65895
- [x] `mariadb` — install #66727
- [x] `mariadb@10.1` — install #66727
- [x] `mariadb@10.2` — install #66727
- [x] `mariadb@10.3` — install #66727
- [x] `mariadb@10.4` — install #66727
- [x] `mysql@5.6` — test #66727
- [x] `mysql@5.7` — test #66727
- [x] `networkit` — test (11.0) 5bf8e35d5243c2db8be9d34df822e12058dc2ffe
- [x] `oclgrind` — install (11.0) https://github.com/Homebrew/homebrew-core/pull/87696
- [x] `odin` — test (11.0) https://github.com/odin-lang/Odin/issues/792, #66906
- [x] `pcl` — test #66792
- [x] `percona-server` — install #66727
- [x] `pipgrip` — test (10.14, 11.0) #66814
- [x] `pony-stable` — test (11.0) c0ef8041296d339b948fd5654f47c38ec3cbf9bb
- [x] `ponyc` — test (11.0) #67765
- [x] `pypy` — install (11.0) 1eaf5df3ad8a112318fd99afd56e691513f20cd6
- [x] `pypy3` — install (11.0) 9eacad0e0bd1a2765ea2c3e74ae16b6008f204cf
- [x] `root` — test (11.0) a5af79755368aa9cc9be1521016f55817f17a295
- [x] `stubby` — test (11.0) 15b1fb8e4836fa51daf09f8b78267cd3e88eb85a
- [x] `wrangler` — install --only-dependencies (11.0) 8d4fa244f879b5f4e60066cfbb6489cc3a0708de

<details><summary>CI logs</summary>
<br>
10.14:
<pre>Error: 15 failed steps!
brew test --retry --verbose cargo-edit
brew test --retry --verbose cucumber-cpp
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew linkage --test mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose pcl
brew install percona-server
brew test --retry --verbose pipgrip
</pre>

10.15:
<pre>
Error: 13 failed steps!
brew test --retry --verbose cargo-edit
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew linkage --test mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose pcl
brew install percona-server
</pre>

11.0:
<pre>
Error: 26 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose augustus
brew test --retry --verbose cargo-edit
brew test --retry --verbose corral
brew test --retry --verbose creduce
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew test --retry --verbose innotop
brew linkage --test mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose networkit
brew install --only-dependencies oclgrind
brew install oclgrind
brew test --retry --verbose odin
brew test --retry --verbose pcl
brew install percona-server
brew test --retry --verbose pipgrip
brew test --retry --verbose pony-stable
brew test --retry --verbose ponyc
brew test --retry --verbose root
</pre></details>

**Comment by carlocab** [comment]
Odin is broken on Big Sur; I've tried looking into it but there's little I could do without diving into their codebase: https://github.com/odin-lang/Odin/issues/792

**Comment by carlocab** [comment]
CI Logs here may also be helpful:

10.14 https://github.com/Homebrew/homebrew-core/suites/1617574284/artifacts/29929186
10.15 https://github.com/Homebrew/homebrew-core/suites/1617574284/artifacts/29929187
11.0 https://github.com/Homebrew/homebrew-core/suites/1617574284/artifacts/29929188

**Comment by EwoutH** [comment]
FYI: [Python 3.9.1](https://www.python.org/downloads/release/python-391/) got released today! It might help resolve a few of the bugs and it also supports macOS 11 Big Sur.

**Comment by fxcoudert** [comment]
@EwoutH the title was misleading, these are not actually Python-related bugs, they were just found during our systematic testing of the latest python build

**Comment by sharris40** [comment]
At least one problem with all the MySQL forks is because they all use the same data directory, and it’s obviously a really bad idea to nuke that directory automatically outside of testing. This begs the question: Why are they all using the same data directory?

**Comment by carlocab** [comment]
openssl was merged in order to ship a security update. The following failures also need to be investigated:

- [ ]`asuka` (test, 11.0)
- [ ]`augustus` (test, 11.0)
- [ ]`cargo-edit` (test)
- [ ]`corral` (test, 11.0)
- [ ]`couchdb-lucene` (test)
- [ ]`creduce` (test, 11.0)
- [ ]`cucumber-cpp` (test, 10.14)
- [ ]`diff-pdf` (fetch)
- [ ]`envoy` (install, 11.0)
- [ ]`get-flash-videos` (test, 11.0)
- [ ]`glyr` (test, 10.14, 11.0)
- [ ]`hyperkit` (test, 10.14, 10.15)
- [ ]`innotop` (test, 11.0)
- [ ]`mapnik` (fetch, 10.14, 10.15, 11.0)
- [ ]`mariadb` (install)
- [ ]`mariadb@10.1` (install)
- [ ]`mariadb@10.2` (install)
- [ ]`mariadb@10.3` (install)
- [ ]`mariadb@10.4` (install)
- [ ]`mysql@5.6` (test)
- [ ]`mysql@5.7` (test)
- [ ]`networkit` (test, 11.0)
- [ ]`oclgrind` (install, 11.0)
- [ ]`odin` (test, 11.0)
- [ ]`pcl` (test)
- [ ]`percona-server` (install)
- [ ]`pipgrip` (test, 10.14, 11.0)
- [ ]`pony-stable` (test, 11.0)
- [ ]`ponyc` (test, 11.0)
- [ ]`pypy` (install, 11.0)
- [ ]`pypy3` (install, 11.0)
- [ ]`root` (test, 11.0)
- [ ]`stubby` (test, 11.0)
- [ ]`wrangler` (install --only-dependencies, 11.0)

Some (many?) of these are duplicates of failures in the original post. I'll clean them up shortly.

**Comment by carlocab** [comment]
Tried building `mariadb` locally. Built and tested fine. Not sure why CI is stuck on it. Will take a closer look at the logs.

**Comment by carlocab** [comment]
All versions of mariadb (at least, in the openssl CI run) are failing in the post-install step: [post_install.01.mysql_install_db.txt](https://github.com/Homebrew/homebrew-core/files/5672361/post_install.01.mysql_install_db.txt)

Looks to me like a CI problem rather than a build problem. Could be wrong though.

If you've got a minute, maybe you want to take a look, @fxcoudert.

**Comment by fxcoudert** [comment]
I've looked at mariadb and I have no idea. I can't reproduce it locally. I think it may be because it's reading conflicting configuration files from another DB-related formula that gets installed before during CI.

**Comment by mitchblank** [comment]
innotop is unrelated breakage -- attempting a fix here: #66699

likely creduce is the same root-cause since they both use the TermReadKey perl package which requires build tweaks on newer MacOS

**Comment by gromgit** [comment]
For MariaDB, I think it makes more sense to take a page from the PostgreSQL formulae and make post-install `return if ENV["CI"]`, instead of trying to touch whatever crud is left over in `/usr/local/var/mysql` on the CI box. Then the test block can do a proper `mysql_install_db` in the sandbox, plus whatever else makes sense.

Just opened #66727 as PoC.

**Comment by SMillerDev** [comment]
See https://github.com/Homebrew/homebrew-core/pull/60190 as well for a running attempt

**Comment by sharris40** [comment]
`percona-server` is another MySQL fork that should get similar treatment.

**Comment by carlocab** [comment]
No new failures from the version bump to 3.9.1: https://github.com/Homebrew/homebrew-core/pull/66489

@fxcoudert

**Comment by Rylan12** [comment]
Just updated the original list with some links to open PRs. Also added the new failures that @carlocab mentioned [above](https://github.com/Homebrew/homebrew-core/issues/66450#issuecomment-742434815).

**Comment by carlocab** [comment]
I _think_ I've fixed `pcl` here: https://github.com/Homebrew/homebrew-core/pull/66792

**Comment by carlocab** [comment]
Also, I think the `mapnik` bottle is missing, which is causing `fetch` errors:
```
❯ brew fetch mapnik
==> Downloading https://homebrew.bintray.com/bottles/mapnik-3.0.23_4.catalina.bottle.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mapnik"
Download failed: https://homebrew.bintray.com/bottles/mapnik-3.0.23_4.catalina.bottle.tar.gz
```

**Comment by Rylan12** [comment]
Yep, looking at that now. They're definitely missing. Not sure what happened. I'll see if I can find them and upload them.

**Comment by carlocab** [comment]
I've confirmed that `pcl` is fixed at #66792. However, there are some other CI failures I'd appreciate some help with.

**Comment by gromgit** [comment]
#66727 is merged, so all of `mariadb*`, `mysql*` and `percona-server` should be OK now.

**Comment by carlocab** [comment]
There are some additional failures from https://github.com/Homebrew/homebrew-core/pull/66168 that aren't yet documented here:
- aws-google-auth (`test`, 10.15, 11.0)
- include-what-you-use (`install`, 11.0)
- swift (`install`, 11.0)

**Comment by iMichka** [comment]
Mapnik was fixed: #65895

**Comment by gromgit** [comment]
@carlocab Didn't you fix `include-what-you-use` in #66857?

**Comment by carlocab** [comment]
Can't repro include-what-you-use and aws-google-auth locally though (Big Sur).

It might be that IWYU was fixed here: https://github.com/Homebrew/homebrew-core/pull/66857

**Comment by carlocab** [comment]
Yes, I'm just not 100% clear on whether the test there was run including the version update + build fix or not.

**Comment by gromgit** [comment]
`swift` on 11.0 seemed to have suffered from a mundane issue:
```
fatal error: error in backend: IO failure on output stream: No space left on device
```
The 11.0 CI box also ran out of space unbottling `llvm@9`.

**Comment by carlocab** [comment]
Yea, I'm beginning to think those extra failures were nothing. Good catch on `swift` though.

**Comment by Rylan12** [comment]
`include-what-you-use` and `aws-google-auth` both seem fine locally (11.0), so I'm not going to include them here. If the resurface they can be re-added.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/66792 has been merged, so `pcl` should be fixed.

**Comment by carlocab** [comment]
From https://github.com/Homebrew/homebrew-core/pull/67378:

10.14
```
Error: 14 failed steps!
brew test --retry --verbose cargo-edit
brew fetch --retry cucumber-cpp
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew test --retry --verbose mariadb
brew test --retry --verbose mariadb@10.2
brew test --retry --verbose mariadb@10.3
brew test --retry --verbose mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose pcl
brew test --retry --verbose swift
brew test --retry --verbose treefrog
brew fetch --retry youtube-dlc
```

It looks like `treefrog` is new, and fixes for `mariadb[@x.y]` and `pcl` didn't take.

**Comment by carlocab** [comment]
`cucumber-cpp` fixed here: https://github.com/Homebrew/homebrew-core/pull/67689

**Comment by carlocab** [comment]
From #67718, which contained a bug fix:

<details><summary>10.14</summary>
<p>

```
Error: 19 failed steps!
brew test --retry --verbose adios2
brew test --retry --verbose arcade-learning-environment
brew test --retry --verbose astrometry-net
brew test --retry --verbose aubio
brew test --retry --verbose csound
brew test --retry --verbose glyr
brew test --retry --verbose gnuradio
brew test --retry --verbose graph-tool
brew test --retry --verbose hyperkit
brew test --retry --verbose networkit
brew test --retry --verbose numpy
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
brew test --retry --verbose pcl
brew test --retry --verbose scipy
brew test --retry --verbose swift
brew test --retry --verbose treefrog
brew test --retry --verbose urh
brew test --retry --verbose xdot
```

</p>
</details>

<details><summary>10.15</summary>
<p>


```
Error: 5 failed steps!
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew test --retry --verbose pcl
brew test --retry --verbose qxmpp
brew test --retry --verbose treefrog
```

</p>
</details>

<details><summary>11.0</summary>
<p>

```
Error: 17 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose augustus
brew test --retry --verbose corral
brew test --retry --verbose creduce
brew test --retry --verbose geant4
brew test --retry --verbose glyr
brew test --retry --verbose hyperkit
brew test --retry --verbose llvm
brew test --retry --verbose networkit
brew install --only-dependencies oclgrind
brew install oclgrind
brew test --retry --verbose opencascade
brew test --retry --verbose pcl
brew test --retry --verbose pony-stable
brew test --retry --verbose ponyc
brew test --retry --verbose qxmpp
brew test --retry --verbose treefrog
```

</p>
</details>

Will check for non-duplicates shortly.

**Comment by carlocab** [comment]
New from #68365, only on (Intel) Big Sur:
- [ ] `aws-google-auth`
- [ ] `lensfun`
I suspect these failures can be safely ignored, but putting them here so we have them on record.

**Comment by Alittlefly** [comment]
When install ffmpeg, error was founded by MacOS Big Sur

==> ./configure --prefix=/usr/local/Cellar/python@3.9/3.9.0_2 --enable-ipv6 --datarootdir=/usr/local/Cellar/python@3.9/3.9.0_2/share --datadir=/usr/local/Cellar/python



==> make
Last 15 lines from /Users/gaochao/Library/Logs/Homebrew/python@3.9/02.make:
    self.run_command(cmd_name)
  File "/private/tmp/python-3.9-20210111-1850-gjuazd/Python-3.9.0/Lib/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/private/tmp/python-3.9-20210111-1850-gjuazd/Python-3.9.0/Lib/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/private/tmp/python-3.9-20210111-1850-gjuazd/Python-3.9.0/Lib/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/private/tmp/python-3.9-20210111-1850-gjuazd/Python-3.9.0/./setup.py", line 470, in build_extensions
    self.detect_modules()
  File "/private/tmp/python-3.9-20210111-1850-gjuazd/Python-3.9.0/./setup.py", line 1807, in detect_modules
    self.detect_readline_curses()
  File "/private/tmp/python-3.9-20210111-1850-gjuazd/Python-3.9.0/./setup.py", line 1038, in detect_readline_curses
    (tuple(int(n) for n in dep_target.split('.')[0:2])
AttributeError: 'int' object has no attribute 'split'
make: *** [sharedmods] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Test and build failures found during python 3.9 testing https://github.com/Homebrew/homebrew-core/issues/66450

**Comment by dtrodrigues** [comment]
From https://github.com/Homebrew/homebrew-core/pull/69668
```
ARM
brew test --retry --verbose emscripten
brew test --retry --verbose tree-sitter

11.0
brew test --retry --verbose howdoi
brew test --retry --verbose pinboard-notes-backup

10.15
brew test --retry --verbose pinboard-notes-backup

10.14
brew test --retry --verbose cp2k
brew test --retry --verbose howdoi
brew test --retry --verbose nwchem
brew test --retry --verbose swift
```

**Comment by carlocab** [comment]
Merged #71329 for CVE fixes.

Mojave only:

```
brew test --retry --verbose gallery-dl
brew test --retry --verbose opencascade
```

All Intel nodes:

```
brew test --retry --verbose wasm-pack
```

**Comment by carlocab** [comment]
`howdoi` and `youtube-dlc` need new tests. From #74538. (Will try to find time to do this soon.)

**Comment by Git-Jiro** [comment]
Hi!
Is the list in the first post still up to date?

I just tried:
> brew install asuka --include-test --build-from-source
> brew test asuka
> brew install augustus --include-test --build-from-source
> brew test augustus
> brew install cargo-edit --include-test --build-from-source
> brew test cargo-edit

And that seems to work fine on macOS 11.6 (intel)

**Comment by carlocab** [comment]
Thanks for having a look, @Git-Jiro. Most of those failures have been fixed. I think there may be a few that are still outstanding. I'll try to update the checklist.

**Comment by Git-Jiro** [comment]
Another small update:

> brew install corral --include-test --build-from-source

This did NOT work on my machine.
I got some compiler errors, from the pony compiler.

Those here:
> brew install couchdb-lucene --include-test --build-from-source
> brew test couchdb-lucene
> brew install get-flash-videos --include-test --build-from-source
> brew test getf-flash-videos
> brew install oclgrind --include-test --build-from-source
> brew test oclgrind

also worked fine.

**Comment by mitchblank** [comment]
`oclgrind` got updated today including a `brew test` fix which may have been the cause of the earlier failure: #87696   So it can be checked off now

**Comment by iMichka** [comment]
I'm going to close this. This has started with a tracking list and then more issues have been added, so that an issue initially started in Dec 2020 is still open now. We will fix the remaining issues as they pop up, or re-open a new tracking list if necessary.

I also think we should look for a better tool to track known broken tests/formulae, maybe with some database / service. Not sure what exists out there.
