### PR TITLE
xtrans: restore fix for missing `stropts.h`

### PR DESCRIPTION
**Pull request by branchv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

This was removed in #132710, but is causing build failures in #133898:

```
/opt/homebrew/Cellar/xtrans/1.5.0/include/X11/Xtrans/Xtranslcl.c:81:11: fatal error: 'stropts.h' file not found
  # include <stropts.h>
```

### CODE REVIEW

**Comment by Bo98** [comment]
Can we have the test block try compile at least `#{include}/X11/Xtrans/Xtranslcl.c`?

This is a unique formula where the build stage doesn't actually do much compiling (if any), and it simply ships the whole source in `include`, because of how `xtrans` works.

**Review by p-linnane — APPROVED** [review]

**Comment by branchvincent** [comment]
> Can we have the test block try compile at least #{include}/X11/Xtrans/Xtranslcl.c?

Thanks for mentioning this, while trying locally I realized that `Xtranslcl.c` actually only supports Solaris: 
* This upstream [commit](https://gitlab.freedesktop.org/xorg/lib/libxtrans/-/merge_requests/5/diffs?commit_id=d0d471579ca69365d4cd5a548ce6fc8b4662d467#7294f1d8b2be2b81a5de34b81fa0c2cd111868d4_81_81) removed non-Solaris support
* [`xtrans.m4`](https://gitlab.freedesktop.org/xorg/lib/libxtrans/-/blob/master/xtrans.m4#L125) only enables it on Solaris

So #133898 just needs to remove `--enable-local-transport`, which was already mentioned in that thread: https://github.com/Homebrew/homebrew-core/pull/133898#issuecomment-1598514161

still, any thoughts on how to better test this formula? Not super familiar with C build tools but I guess we can create a `configure.ac` script that includes the default `xtrans.m4` options and then try compiling?

**Comment by Bo98** [comment]
Ok I didn't see that seems like the fix should have been over on the libx11 PR rather than merging this. It's explicitly documented as SYSV only.

**Comment by branchvincent** [comment]
Yup I'll revert this
