### PR TITLE
mkvtoolnix: build with gettext by default, remove qt option.

### LINKED ISSUE #35256: mkvtoolnix failed to build on 10.14.2
```
==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/29.0.0_1 --with-boost=/usr/local/opt/boost --with-docbook-xsl-root=/usr/local/opt/docbook-xsl/docbook-xsl 
==> rake -j8
Last 15 lines from /Volumes/Users/nikola/Library/Logs/Homebrew/mkvtoolnix/02.rake:
         CXX src/mkvtoolnix-gui/util/waiting_spinner_widget.cpp
         CXX src/mkvtoolnix-gui/util/widget.cpp
         CXX src/mkvtoolnix-gui/watch_jobs/tab.cpp
         CXX src/mkvtoolnix-gui/watch_jobs/tool.cpp
         RCC src/mkvtoolnix-gui/qt_resources.qrc
         CXX src/mkvtoolnix-gui/qt_resources.cpp
        LINK src/mkvtoolnix-gui/mkvtoolnix-gui
ld: warning: object file (/usr/local/lib/libfmt.a(format.cc.o)) was built for newer OSX version (10.14) than being linked (10.9)
ld: warning: object file (/usr/local/Cellar/pugixml/1.9/lib/pugixml-1.9/libpugixml.a(pugixml.cpp.o)) was built for newer OSX version (10.13) than being linked (10.9)
Undefined symbols for architecture x86_64:
  "___CFConstantStringClassReference", referenced from:
      CFString in macos.o
      CFString in macos.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
[https://gist.github.com/c740aacaa0439d0ab926c398589c629c](https://gist.github.com/c740aacaa0439d0ab926c398589c629c)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Fixes #35256.
Replaces #35364.
References https://github.com/Homebrew/homebrew-cask/pull/56633

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by retokromer** [comment]
+1

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Some audit:

```
mkvtoolnix:
  * C: 34: col 3: dependency "gettext" (line 34) should be put before dependency "libvorbis" (line 33)
  * C: 36: col 3: dependency "cmark" (line 36) should be put before dependency "qt" (line 35)
```

and some build issues:

```
ld: warning: object file (/usr/local/lib/libfmt.a(format.cc.o)) was built for newer OSX version (10.14) than being linked (10.9)
ld: warning: object file (/usr/local/Cellar/pugixml/1.9/lib/pugixml-1.9/libpugixml.a(pugixml.cpp.o)) was built for newer OSX version (10.14) than being linked (10.9)
Undefined symbols for architecture x86_64:
  "___CFConstantStringClassReference", referenced from:
      CFString in macos.o
      CFString in macos.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by MikeMcQuaid** [comment]
Removed the Qt GUI here. Pending cask PR: https://github.com/Homebrew/homebrew-cask/pull/56633
