### PR TITLE
spotify-tui: patch Cargo.lock to build on Rust 1.64+

### PR DESCRIPTION
**Pull request by cho-m**
We need to rebuild `spotify-tui` due to Linux relocation issue (https://github.com/Homebrew/homebrew-core/actions/runs/3442457231/jobs/5743120009#step:11:11225):
```
  ==> Pouring spotify-tui--0.25.0.x86_64_linux.bottle.tar.gz
  Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
  Do not report this issue until you've run `brew update` and tried again.
```

However, `spotify-tui` has been broken since Rust 1.64 update (https://github.com/Homebrew/homebrew-core/actions/runs/3448615226/jobs/5755791901#step:7:398)
```
  Compiling socket2 v0.3.12
  error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
     --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.12/src/sockaddr.rs:176:9
```

Easiest workaround is to patch the Cargo.lock with unmerged dependabot PR to update socket2, which is what NixOS did https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/spotify-tui/default.nix#L31-L43

---

Alternative fix would be to use older Rust, maybe via `rustup-init`.

### CODE REVIEW

**Comment by chenrui333** [comment]
also linked to [the project health issue](https://github.com/Rigellute/spotify-tui/issues/1000)

**Review by chenrui333 — APPROVED** [review]
