### PR TITLE
gdb 8.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
clang++ -x c++ -std=gnu++11 -g -O2   -I. -I. -I./common -I./config -DLOCALEDIR="\"/usr/local/Cellar/gdb/8.1/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../opcodes/.. -I./../readline/.. -I./../zlib -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber -I./../intl -I./gnulib/import -Ibuild-gnulib/import   -DTUI=1  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wno-sign-compare -Wno-narrowing -Wno-mismatched-tags -Wformat-nonliteral  -c -o probe.o -MT probe.o -MMD -MP -MF ./.deps/probe.Tpo probe.c
clang++ -x c++ -std=gnu++11 -g -O2   -I. -I. -I./common -I./config -DLOCALEDIR="\"/usr/local/Cellar/gdb/8.1/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../opcodes/.. -I./../readline/.. -I./../zlib -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber -I./../intl -I./gnulib/import -Ibuild-gnulib/import   -DTUI=1  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wno-sign-compare -Wno-narrowing -Wno-mismatched-tags -Wformat-nonliteral  -c -o producer.o -MT producer.o -MMD -MP -MF ./.deps/producer.Tpo producer.c
probe.c:63:28: error: default initialization of an object of const type 'const any_static_probe_ops' without a user-provided default constructor
const any_static_probe_ops any_static_probe_ops;
                           ^
                                               {}
1 error generated.
make[2]: *** [probe.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-gdb] Error 2
make: *** [all] Error 2
```

**Comment by nyx0** [comment]
It works on `10.12.6`
