### PR TITLE
nettle 3.6

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
> gnutls: revision bump

oh no

**Comment by SMillerDev** [comment]
Pijul 
```
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/local/opt/llvm@10/lib/libclang.dylib could not be opened: dlopen(/usr/local/opt/llvm@10/lib/libclang.dylib, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib\n  Referenced from: /usr/local/Cellar/llvm/10.0.0_1/lib/libLLVM.dylib\n  Reason: image not found"', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1664:13
```

Gnutls + everything that depends on it.
```
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by miccal** [comment]
@SMillerDev nettle is now at 3.6, which may help.

**Comment by SMillerDev** [comment]
Thanks @miccal

**Comment by SMillerDev** [comment]
Everything works except pijul, which is using a deprecated feature and doesn't seem to be maintained. @Bo98 how do you feel about removing it?

**Comment by SMillerDev** [comment]
gst-plugins-bad on 10.13 is failing
```
avfvideosrc.m:461:41: error: 'AVAuthorizationStatusAuthorized' is unavailable: not available on macOS
        if (videoAuthorizationStatus != AVAuthorizationStatusAuthorized) {
                                        ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1456:28: note: 'AVAuthorizationStatus' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVAuthorizationStatus) {
                           ^
10 errors generated.
make[3]: *** [libgstapplemedia_la-avfvideosrc.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [applemedia] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by Bo98** [comment]
I think I might be able to fix Pijul by using LLVM. I'll try it out in a separate pull request.

**Comment by SMillerDev** [comment]
@tschoonj any ideas? You seem to be the one that updates it most.

**Comment by tschoonj** [comment]
`AVAuthorizationStatusAuthorized ` was added in the 10.14 SDK. But the Xcode version used in this build on 10.13 provides support for the 10.14 SDK so not sure why this fails. Pretty sure this used to work on Jenkins.

**Comment by tschoonj** [comment]
@smillerdev this should fix things on High Sierra and older. Very surprised to see this though... could also reproduce it locally on my old MacBook Pro running High Sierra.

**Comment by tschoonj** [comment]
Does this need a rebase or so? There were some changes to `gnutls` lately I think

**Comment by SMillerDev** [comment]
OMG it worked.

**Review by tschoonj — APPROVED** [review]
