### ISSUE TITLE
tesseract failed to build on 10.12.4

### ISSUE THREAD

**Issue by kolen** [Homebrew/homebrew-core#12823]
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/anonymous/8d742045b8d2832682debeac28e55373

Occured when running `brew upgrade`

```
==> make install
Last 15 lines from /Users/kolen/Library/Logs/Homebrew/tesseract/03.make:
                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__hash_table:710:30: error: use of undeclared identifier '__get_const_db'
        _LIBCPP_DEBUG_ASSERT(__get_const_db()->__dereferenceable(this),
                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__hash_table:717:30: error: use of undeclared identifier '__get_const_db'
        _LIBCPP_DEBUG_ASSERT(__get_const_db()->__dereferenceable(this),
                             ^
18 errors generated.
```

**Comment by dunn** [comment]
This mismatch may be related:
```
Xcode: 8.3.2
CLT: 8.3.0.0.1.1490382677
```
Try updating the Command-Line Tools first.
