### PR TITLE
fceux: fix build with SCons 3.0 and with Xcode 9

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
src/cheat.cpp:219:30: error: ordered comparison between pointer and zero ('char *' and 'int')
        while(fgets(linebuf,2048,fp)>0)
              ~~~~~~~~~~~~~~~~~~~~~~^~
1 error generated.
```
Xcode 9 is :heart:

**Comment by fxcoudert** [comment]
🎁 https://github.com/Homebrew/formula-patches/commit/07b42975cffd862a8f3d236b129fcf85f172c479

**Comment by ilovezfs** [comment]
thanks @fxcoudert :)

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
> Xcode 9 is ❤️

Shipped stable today as well; if there are many more of these issues lingering around we're about to find 'em lol.

**Comment by ilovezfs** [comment]
patch doesn't want to apply for some reason

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
CI is ✅ so I think the patch applies. @ilovezfs what's wrong with it?

**Comment by ilovezfs** [comment]
the commit message on https://github.com/Homebrew/formula-patches/pull/187 needs to be tweaked because it's lying

**Comment by ilovezfs** [comment]
@fxcoudert also you need to review that patch as I changed it since you originally committed it.

**Comment by fxcoudert** [comment]
https://github.com/Homebrew/formula-patches/pull/187 approved, merged with edited commit message

**Comment by ilovezfs** [comment]
Then we're good to go here.

**Comment by ilovezfs** [comment]
patch url updated.

**Comment by ilovezfs** [comment]
https://jenkins.brew.sh/job/Homebrew%20High%20Sierra%20Testing/914/
