### PR TITLE
grafana-agent 0.31.1

### PR DESCRIPTION
**Pull request by grafanabot**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
> Error: An exception occurred within a child process:
(https://github.com/Homebrew/homebrew-core/actions/runs/4106732687/jobs/7085424896#step:6:38)
    NoMethodError: undefined method `rfc3339' for 2023-02-06 18:23:25 UTC:Time

**Comment by rfratto** [comment]
🤔 We didn't really change anything between 0.31.0 and 0.31.1 that would make this break, other than updating a dependency to unblock #122082.

Would re-triggering the CI help here, maybe?

**Comment by rfratto** [comment]
> That one is weird. It looks like it happens while running untar ...

Ah, unless something about the runners changed. I remember having to install BSD tar on macOS for a similar error in the past.

**Comment by chenrui333** [comment]
Introduced by https://github.com/Homebrew/brew/pull/14502.

**Comment by chenrui333** [comment]
The rfc3339 issue got resolved in #122483

**Review by chenrui333 — APPROVED** [review]
