### PR TITLE
ilmbase 2.3.0

### PR DESCRIPTION
**Pull request by DennisOSRM**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
The following need revision bump: `ctl field3d imagemagick opencv opencv@2 opencv@3 openexr openimageio openvdb pbrt rawtoaces synfig vips` (one commit per formula, with message `ctl: revision for ilmbase`).

**Comment by fxcoudert** [comment]
- `opencv` failure because the patch changed checksum (it was rebased).
- `opencv@3` failure because it needs that same patch.

**Comment by fxcoudert** [comment]
Three build failures:

- `ctl` fails with:

```
/tmp/ctl-20190416-81866-bnmw95/CTL-ctl-1.5.2/lib/IlmCtlSimd/CtlSimdInst.cpp:192:31: error: invalid operands to binary expression ('basic_ostream<char, std::__1::char_traits<char> >' and 'Iex::BaseExc')
                 inst->lineNumber() << ": " << e);
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/usr/local/include/OpenEXR/IexMacros.h:110:27: note: expanded from macro 'REPLACE_EXC'
        _iex_replace_s << text;              \
        ~~~~~~~~~~~~~~~~~~^~~~
```

- `field3d` fails with ```undefined local variable or method `scons'```
- `synfig` fails with:

```
In file included from widthpoint.cpp:34:
In file included from ./widthpoint.h:33:
./vector.h:44:13: error: 'isnan' is missing exception specification 'noexcept'
inline bool isnan(float x) { return x != x; }
            ^
                           noexcept
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:533:1: note: previous declaration is here
isnan(float __lcpp_x) _NOEXCEPT { return __libcpp_isnan(__lcpp_x); }
^
In file included from widthpoint.cpp:34:
In file included from ./widthpoint.h:33:
```

**Comment by fxcoudert** [comment]
Mojave failure for `synfig`, will be dealt with in https://github.com/Homebrew/homebrew-core/pull/38961

**Comment by fxcoudert** [comment]
Thanks @DennisOSRM for getting this started!
