### PR TITLE
tintin 2.02.11

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
data.c:1346:18: error: use of undeclared identifier 'environ'
                                                for (env = environ ; *env ; env++)
                                                           ^
data.c:1359:18: error: use of undeclared identifier 'environ'
                                                for (env = environ ; *env ; env++)
                                                           ^
2 errors generated.
```

**Comment by carlocab** [comment]
Looks like this was broken by https://github.com/scandum/tintin/commit/e8686858ef49772e540d8457e805958c760b0f0e.

Related: https://github.com/zeromq/czmq/issues/1834

**Comment by chenrui333** [comment]
relates to scandum/tintin#47

**Comment by carlocab** [comment]
Looks like there's a fix available: https://github.com/scandum/tintin/issues/47#issuecomment-828701145

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
```
scan.c:324:19: error: use of undeclared identifier 'PATH_MAX'
                if (getcwd(cwd, PATH_MAX) == NULL)
                                ^
```
Probably needs an
```c
#include <limits.h>
```
in `scan.c`.

**Review by SMillerDev — APPROVED** [review]
