### PR TITLE
glew 2.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by fxcoudert** [comment]
Rebased, retesting

**Comment by fxcoudert** [comment]
ffmpeg does not build on 10.15:

```
2020-10-05T20:12:43.8063010Z libavformat/libsrt.c:317:66: error: use of undeclared identifier 'SRTO_STRICTENC'; did you mean 'SRTO_STATE'?
2020-10-05T20:12:43.8064630Z         (s->enforced_encryption >= 0 && libsrt_setsockopt(h, fd, SRTO_STRICTENC, "SRTO_STRICTENC", &s->enforced_encryption, sizeof(s->enforced_encryption)) < 0) ||
2020-10-05T20:12:43.8065550Z                                                                  ^~~~~~~~~~~~~~
2020-10-05T20:12:43.8065990Z                                                                  SRTO_STATE
2020-10-05T20:12:43.8067340Z /usr/local/Cellar/srt/1.4.2/include/srt/srt.h:200:4: note: 'SRTO_STATE' declared here
2020-10-05T20:12:43.8068020Z    SRTO_STATE = 17,          // current socket state, see UDTSTATUS, read only
2020-10-05T20:12:43.8068430Z    ^
2020-10-05T20:12:43.8069400Z libavformat/libsrt.c:336:50: error: use of undeclared identifier 'SRTO_SMOOTHER'
2020-10-05T20:12:43.8070730Z         (s->smoother && libsrt_setsockopt(h, fd, SRTO_SMOOTHER, "SRTO_SMOOTHER", s->smoother, strlen(s->smoother)) < 0) ||
2020-10-05T20:12:43.8071310Z                                                  ^
```

`blastem` has missing resources:

```
2020-10-05T15:38:30.3662200Z blastem:
2020-10-05T15:38:30.3663290Z   * Stable resource "vasm": The URL https://server.owl.de/~frank/tags/vasm1_8f.tar.gz is not reachable
2020-10-05T15:38:30.3664440Z   * HEAD resource "vasm": The URL https://server.owl.de/~frank/tags/vasm1_8f.tar.gz is not reachable
```

**Comment by jonchang** [comment]
ffmpeg probably needs this patch cherry-picked: https://github.com/FFmpeg/FFmpeg/commit/7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315

**Comment by jonchang** [comment]
Added patch for ffmpeg and fixed the blastem build. The latter is probably not going to last too much longer in homebrew/core, but this will help it limp along for a while.

**Comment by jonchang** [comment]
Audit failure is a transient GitHub API error, gonna merge this.

**Comment by jonchang** [comment]
Scratch that, gotta rebase it again 😅

**Review by SMillerDev — DISMISSED** [review]

**Review by jonchang — DISMISSED** [review]

**Review by jonchang — DISMISSED** [review]

**Comment by jonchang** [comment]
Closed in https://github.com/Homebrew/homebrew-core/commit/6fbf6a848e36600fd5bc83bd5073b5abaf0fefda
