### PR TITLE
gpgme: migrate to `python@3.12`

### PR DESCRIPTION
**Pull request by branchv**
gpgme: migrate to `python@3.12`

### CODE REVIEW

**Comment by chenrui333** [comment]
regression test failure with alot

` Expected #<Pathname:/private/tmp/alot-test-20231009-87382-bom0w8/out.log> to be exist?.`

**Comment by chenrui333** [comment]
`constantly` need some build change
```
  ==> python3.12 -m pip --python=/opt/homebrew/Cellar/alot/0.10_3/libexec/bin/python install --verbose --no-deps --no-binary=:all: --ignore-installed --no-compile /private/tmp/alot--constantly-20231015-45973-vhnx3y/constantly-15.1.0
  Using pip 23.2.1 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)
  Processing /private/tmp/alot--constantly-20231015-45973-vhnx3y/constantly-15.1.0
    Preparing metadata (setup.py): started
    Running command python setup.py egg_info
    /private/tmp/alot--constantly-20231015-45973-vhnx3y/constantly-15.1.0/versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
      LONG_VERSION_PY['git'] = '''
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/private/tmp/alot--constantly-20231015-45973-vhnx3y/constantly-15.1.0/setup.py", line 41, in <module>
        version=versioneer.get_version(),
                ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/private/tmp/alot--constantly-20231015-45973-vhnx3y/constantly-15.1.0/versioneer.py", line 1405, in get_version
        return get_versions()["version"]
               ^^^^^^^^^^^^^^
      File "/private/tmp/alot--constantly-20231015-45973-vhnx3y/constantly-15.1.0/versioneer.py", line 1339, in get_versions
        cfg = get_config_from_root(root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/private/tmp/alot--constantly-20231015-45973-vhnx3y/constantly-15.1.0/versioneer.py", line 399, in get_config_from_root
        parser = configparser.SafeConfigParser()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

**Comment by chenrui333** [comment]
Just FYI, there is a new release with gpgme, so I created a PR separately, https://github.com/Homebrew/homebrew-core/pull/152346

**Comment by cho-m** [comment]
> `constantly` need some build change

There is an open PR now https://github.com/twisted/constantly/pull/31. Bit worried that upstream's last commit was 2018 and last release was 2015 but `constantly` is owned/used by `twisted`, which is actively maintained.

**Comment by chenrui333** [comment]
- https://github.com/twisted/constantly/pull/33

**Comment by alex** [comment]
constantly now has a released which should work on python 3.12

**Review by chenrui333 — APPROVED** [review]
