### PR TITLE
pg_cron 1.5.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>* Fixes a bug that caused crashes after upgrading binaries to 1.5, by Polina Bungina</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Undefined symbols for architecture arm64:
    "_libintl_ngettext", referenced from:
        _PgCronLauncherMain in pg_cron.o
  ld: symbol(s) not found for architecture arm64
```

**Review by chenrui333 — DISMISSED** [review]

**Review by ZhongRuoyu — DISMISSED** [review]

**Review by ZhongRuoyu — APPROVED** [review]
