### PR TITLE
pyoxidizer 0.24.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
    = note: ld: warning: object file (/private/tmp/pyoxidizerOJHyiE/build/target/aarch64-apple-darwin/debug/deps/libpyo3_ffi-b9ea064ef657ba4e.rlib(415005a29d63fbd9-config.o)) was built for newer macOS version (12.0) than being linked (11.0)
            Undefined symbols for architecture arm64:
              "_mkfifoat", referenced from:
                  _os_mkfifo_impl in libpyo3_ffi-b9ea064ef657ba4e.rlib(posixmodule.o)
              "_mknodat", referenced from:
                  _os_mknod_impl in libpyo3_ffi-b9ea064ef657ba4e.rlib(posixmodule.o)
            ld: symbol(s) not found for architecture arm64
            clang: error: linker command failed with exit code 1 (use -v to see invocation)
            
  
  error: could not compile `python-oxidized-importer` due to previous error
  warning: build failed, waiting for other jobs to finish...
  error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExecutable to FileManifest
      
      Caused by:
          0: building Python executable
          1: building executable with Rust project
          2: cargo build failed
         --> ./pyoxidizer.bzl:283:5
          |
      283 |     files.add_python_resource(".", exe)
          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PythonExecutable.to_file_manifest()
      
      
  error: adding PythonExecutable to FileManifest
  
  Caused by:
      0: building Python executable
      1: building executable with Rust project
      2: cargo build failed
  Error: pyoxidizer: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /opt/homebrew/Cellar/pyoxidizer/0.24.0/bin/pyoxidizer build --verbose
```

**Comment by chenrui333** [comment]
@messense can you also help with this upgrade? Thanks!

**Comment by messense** [comment]
I suspect it has something to do with `python-build-standalone`, this release note mentions `mkfifoat` and `mknodat` : https://github.com/indygreg/python-build-standalone/releases/tag/20221220

**Comment by messense** [comment]
Perhaps build with macOS 13.0 will fix it? https://github.com/indygreg/python-build-standalone/blob/7820a1bfdda920ed001ea47dafc9575cc39f13b5/cpython-unix/build-cpython.sh#L391-L395

**Comment by chenrui333** [comment]
@messense do you want to give that a stab? Thanks!! :)

**Comment by messense** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/121289
