### PR TITLE
llvm: various config file fixes

### LINKED ISSUE #197277: llvm: Clang doesn't use `SDKROOT` when linking
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```console
% brew gist-logs llvm@18
Error: No logs.

% brew gist-logs llvm@19
Error: No logs.

% brew config
HOMEBREW_VERSION: 4.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 824efa8836dc226aa92dbbf7404c1b4a66707cca
Last commit: 7 days ago
Core tap JSON: 10 Nov 22:51 UTC
Core cask tap JSON: 10 Nov 22:51 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit dunno
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false

% brew doctor
Your system is ready to brew.
```

Note that the system is a clean virtual machine with a newly installed homebrew. The problem has also been reproduced [here](https://github.com/Homebrew/homebrew-core/pull/196094#discussion_r1835780712).

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

It is generally expected that setting the `SDKROOT` environment variable (or the `-isysroot` flag) when compiling with Clang on macOS selects a different SDK. `xcrun`, for example, uses this to make it easy to select a different SDK when compiling.

This is somewhat supported by the Clang provided by the `llvm` package, but the SDK that `llvm` was built with is always selected when linking instead of the value set by `xcrun` / in `SDKROOT` / with `-isysroot`.

This is likely to affect cross compilation (to iOS/tvOS/watchOS/visionOS). I'm investigating this because of https://github.com/rust-lang/rust/pull/131477 and https://github.com/rust-lang/cc-rs/issues/1278, since it is unclear how downstream users such as `rustc` should pass a different SDK root.

The following contrived example program fails to link with the macOS 15.1 SDK for this reason:
```objective-c
#import <os/lock.h>

int main(int argc, char *argv[]) {
    if (@available(macos 15.0, *)) {
        // Use some API that's only available on macOS 15.0 or newer
        os_unfair_lock lock = OS_UNFAIR_LOCK_INIT;
        os_unfair_lock_lock_with_flags(&lock, OS_UNFAIR_LOCK_FLAG_ADAPTIVE_SPIN);
    }
    return 0;
}
```

### What happened (include all command output)?

Linking fails with:
```
Undefined symbols for architecture arm64:
 "_os_unfair_lock_lock_with_flags", referenced from:
      _main in foo-21aa0e.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### What did you expect to happen?

The macOS 15.1 SDK is used, also when linking, and compilation and linking succeeds.
OR
An error at compile-time because the macOS 14.0 SDK is consistently used.

### Step-by-step reproduction instructions (by running `brew` commands)

1. Install `llvm` package (any version):
    
    brew install llvm@19
    
2. Install Xcode 15.4 and Xcode 16.1 (or equivalent Command Line Tools), so that the macOS 14.0 and macOS 15.1 SDKs are available.
3. Put the example program above in `foo.m`.
4. Try to compile with the macOS 14.0 SDK (this fails as expected, because the function isn't available in the old SDK):
    ```sh
    xcrun -sdk macosx14.0 clang foo.m
    xcrun -sdk macosx14.0 /opt/homebrew/opt/llvm@19/bin/clang foo.m
    ```
5. Compile with Xcode Clang and macOS 15.1 SDK (this works):
    ```sh
    xcrun -sdk macosx15.1 clang foo.m
    ```
6. Compile with Clang provided by `llvm` package and macOS 15.1 SDK (this fails linking):
    ```sh
    xcrun -sdk macosx15.1 /opt/homebrew/opt/llvm@19/bin/clang foo.m
    ```

Use `-v` to see that Clang always passes the same value to `ld`'s `-syslibroot`.

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Let's create config files that target `aarch64` too. This is used as the
target by Python. See Homebrew/discussions#5778.

Also, use `-isysroot` instead of `--sysroot` so that our choice can be
overridden by setting `SDKROOT`. Fixes #197277.

### CODE REVIEW

**Comment by carlocab** [comment]
Cherry-picked onto #199909.

**Comment by madsmtm** [comment]
I don't think this will let users override by setting `SDKROOT`, it'll always prefer the value in `-isysroot`. But at least it also won't confusingly try to use different SDKs at compile and at link time, so definitely an improvement.

**Comment by carlocab** [comment]
Merged in https://github.com/Homebrew/homebrew-core/pull/199909.
