### PR TITLE
qemu 6.0.0

### PR DESCRIPTION
**Pull request by tylinux**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by cho-m** [comment]
I think the ARM node has some macOS 11.3 SDK-related failures (seen in other PRs) due to C++20 `#include <version>` finding the wrong file (in this case, QEMU's `version` file).
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:37:
../version:1:1: error: expected unqualified-id
6.0.0
^
```

**Comment by BrettDong** [comment]
I am on macOS 11.3 on M1 Mac. I also got this compile error when compiling QEMU 6.0.0 source code downloaded from their official website, along with another one:
```
In file included from ../disas/arm-a64.cc:25:
In file included from /Users/brett/Downloads/qemu-6.0.0/disas/libvixl/vixl/a64/disasm-a64.h:33:
In file included from /Users/brett/Downloads/qemu-6.0.0/disas/libvixl/vixl/a64/decoder-a64.h:30:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/list:185:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:672:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:206:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__debug:14:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:95:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/wchar.h:119:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wchar.h:109:6: error: unknown type name 'mbstate_t'; did you mean '__mbstate_t'?
            mbstate_t * __restrict);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/arm/_types.h:55:3: note: '__mbstate_t' declared here
} __mbstate_t;
  ^
```

I tried to link `MacOSX.sdk` to `MacOSX11.1.sdk` but to no avail.

File: Formula/qemu.rb [hunk 1]
```diff
@@ -82,6 +75,8 @@ def install
       args << "--enable-cocoa"
     end
 
+    # fix xcode search version header error
+    system "mv", "VERSION", "VERSION.txt"
```
Comment (BrettDong) [inline Formula/qemu.rb:79]:
```suggestion
    mv "VERSION", "VERSION.txt"
```

**Comment by Lunaticf** [comment]
same problem

**Comment by climann** [comment]
Can confirm that 92d23ecbb254ef54f7e4b50495fc77e9f8ce45a1 works on M1 with Big Sur 11.3 SDK.

**Comment by Lunaticf** [comment]
> Can confirm that [92d23ec](https://github.com/Homebrew/homebrew-core/commit/92d23ecbb254ef54f7e4b50495fc77e9f8ce45a1) works on M1 with Big Sur 11.3 SDK.

download the rb,

```
brew install ./qemu.rb                                                                                                            [21:58:22]
Error: Failed to load cask: ./qemu.rb
Cask 'qemu' is unreadable: wrong constant name #<Class:0x000000013d986f00>
Warning: Treating ./qemu.rb as a formula.
==> Downloading https://ghcr.io/v2/homebrew/core/qemu/manifests/6.0.0
-#O#- #   #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "qemu_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/qemu/manifests/6.0.0
FAIL
```

above error... is there anything I am wrong

**Comment by Lunaticf** [comment]
> Can confirm that [92d23ec](https://github.com/Homebrew/homebrew-core/commit/92d23ecbb254ef54f7e4b50495fc77e9f8ce45a1) works on M1 with Big Sur 11.3 SDK.

download that formula and run...  

```
$ brew install ./qemu.rb                                                                                                            [23:46:36]
Error: Failed to load cask: ./qemu.rb
Cask 'qemu' is unreadable: wrong constant name #<Class:0x000000013ac730e0>
Warning: Treating ./qemu.rb as a formula.
==> Downloading https://ghcr.io/v2/homebrew/core/qemu/manifests/6.0.0
-=O#- #  #    #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "qemu_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/qemu/manifests/6.0.0
```

**Comment by BrettDong** [comment]
> > Can confirm that [92d23ec](https://github.com/Homebrew/homebrew-core/commit/92d23ecbb254ef54f7e4b50495fc77e9f8ce45a1) works on M1 with Big Sur 11.3 SDK.
> 
> 
> 
> download that formula and run...  
> 
> 
> 
> ```
> 
> $ brew install ./qemu.rb                                                                                                            [23:46:36]
> 
> Error: Failed to load cask: ./qemu.rb
> 
> Cask 'qemu' is unreadable: wrong constant name #<Class:0x000000013ac730e0>
> 
> Warning: Treating ./qemu.rb as a formula.
> 
> ==> Downloading https://ghcr.io/v2/homebrew/core/qemu/manifests/6.0.0
> 
> -=O#- #  #    #
> 
> curl: (22) The requested URL returned error: 404
> 
> Error: Failed to download resource "qemu_bottle_manifest"
> 
> Download failed: https://ghcr.io/v2/homebrew/core/qemu/manifests/6.0.0
> 
> ```

You need to build from source.

File: Formula/qemu.rb [hunk 2]
```diff
@@ -2,23 +2,16 @@ class Qemu < Formula
...
     patch do
-      url "https://git.qemu.org/?p=qemu.git;a=patch;h=0dbce6efb5ff2e7113734d3a0cabbf87fc56feec"
-      sha256 "8ced33c7f829216544b762d8db0f143dbea04fa5a1ce41b491bbd7808f64a944"
-    end
-
-    # remove in next release
-    patch do
-      url "https://git.qemu.org/?p=qemu.git;a=patch;h=cb7abd8319d19000b57ae6c5c474c2635db054c6"
-      sha256 "818ad42f0cb25ab5df37058e27d7f879e4389489f692da4404c1f15dde5b2c4d"
+      url "https://gist.githubusercontent.com/tylinux/1e12e733728413ffa8bc7e7a1eab437c/raw/89f7efa1ec8a62d634bd6856ffc3026dd1d06447/qemu_macos_11.3.patch"
```
Comment (SMillerDev) [inline Formula/qemu.rb:13]: This will need to be upstreamed

File: Formula/qemu.rb [hunk 3]
```diff
@@ -82,6 +75,8 @@ def install
       args << "--enable-cocoa"
     end
 
+    # fix xcode search version header error
+    mv "VERSION", "VERSION.txt"
```
Comment (SMillerDev) [inline Formula/qemu.rb:79]: Is upstream aware of this bug?

File: Formula/qemu.rb (hunk 2 above)
Comment (climann) [reply Formula/qemu.rb:13]: This seems to be an issue on systems with case insensitiv filesystems and libc++ 8 and newer.
Apparently FreeBSD had similar issues in the ports tree around March 2019 (like https://github.com/freebsd/freebsd-ports/commit/65232cf5a26581b4c1e83e2e48bb93641dc050d1 and many more). 
Apple upgraded LLVM from 10.0.0 to 11.1.0. Not sure if this is a libc++ regression, a macOS specific bug or intended C++20 behaviour.

Comment (carlocab) [reply Formula/qemu.rb:13]: The issue comea from having files called `version` (or perhaps `VERSION`) in your include paths since some headers will now do `#include <version>`.

I suspect putting files that aren't headers in your include paths is just not a good idea. At the very least, if you have to, don't give them generic names that could easily be in someone's `#include` directive.

Comment (Bo98) [reply Formula/qemu.rb:13]: Apple only added the `version` C++20 header in the just-released Xcode 12.5 which is why it's appearing now.

This is a general incompatibility with the C++20 standard library and thus should be in upstream's interest to accept such a patch.

Comment (climann) [reply Formula/qemu.rb:13]: Thanks for the explanation. I reported the issue here: https://gitlab.com/qemu-project/qemu/-/issues/129.

File: Formula/qemu.rb (hunk 3 above)
Comment (BrettDong) [reply Formula/qemu.rb:79]: There is a patch in upstream pending review:

https://patchew.org/QEMU/CA+pCdY09+OQfXq3YmRNuQE59ACOq7Py2q4hqOwgq4PnepCXhTA@mail.gmail.com/

Comment (climann) [reply Formula/qemu.rb:79]: Yes, related tickets:

- Gitlab: https://gitlab.com/qemu-project/qemu/-/issues/129
- Patchew: [https://patchew.org/QEMU/...](https://patchew.org/QEMU/CA+pCdY09+OQfXq3YmRNuQE59ACOq7Py2q4hqOwgq4PnepCXhTA@mail.gmail.com/)

**Comment by rvs** [comment]
From the peanut gallery -- huge +1 to get this in -- would really help a lot of folks on M1

File: Formula/qemu.rb (hunk 3 above)
Comment (tylinux) [reply Formula/qemu.rb]: I just changed this PR to use qemu's patch.

File: Formula/qemu.rb [hunk 4]
```diff
@@ -2,23 +2,16 @@ class Qemu < Formula
...
     patch do
-      url "https://git.qemu.org/?p=qemu.git;a=patch;h=0dbce6efb5ff2e7113734d3a0cabbf87fc56feec"
-      sha256 "8ced33c7f829216544b762d8db0f143dbea04fa5a1ce41b491bbd7808f64a944"
-    end
-
-    # remove in next release
-    patch do
-      url "https://git.qemu.org/?p=qemu.git;a=patch;h=cb7abd8319d19000b57ae6c5c474c2635db054c6"
-      sha256 "818ad42f0cb25ab5df37058e27d7f879e4389489f692da4404c1f15dde5b2c4d"
+      url "https://patchwork.kernel.org/project/qemu-devel/patch/CA+pCdY09+OQfXq3YmRNuQE59ACOq7Py2q4hqOwgq4PnepCXhTA@mail.gmail.com/raw/"
```
Comment (carlocab) [inline Formula/qemu.rb:13]: Is there a patch we can use from `git.qemu.org`?

Comment (tylinux) [reply Formula/qemu.rb:13]: Not yet...

Comment (carlocab) [reply Formula/qemu.rb:13]: Hmm, ok. The patch should at the very least be preceded by a comment about what it's for. Is there an upstream issue that tracks the problem this patch addresses? We should probably link to that.

Comment (climann) [reply Formula/qemu.rb:13]: As mentioned above:

- Issue: https://gitlab.com/qemu-project/qemu/-/issues/129
- Patch in review: https://patchew.org/QEMU/CA+pCdY09+OQfXq3YmRNuQE59ACOq7Py2q4hqOwgq4PnepCXhTA@mail.gmail.com/

Comment (climann) [reply Formula/qemu.rb:13]: The patch made it to ` git.qemu.org`:
- Commit: https://git.qemu.org/?p=qemu.git;a=commit;h=75eebe0b1f15464d19a39c4186bfabf328ab601a
- Patch: https://git.qemu.org/?p=qemu.git;a=patch;h=75eebe0b1f15464d19a39c4186bfabf328ab601a

File: Formula/qemu.rb [hunk 5]
```diff
@@ -2,23 +2,16 @@ class Qemu < Formula
...
+      sha256 "a9a643c8089b004f5c5208ec9afc7630ed1b249e7911fcf19e742a7a1b58bdb4"
```
Comment (climann) [inline Formula/qemu.rb:14]:
```suggestion
      url "https://git.qemu.org/?p=qemu.git;a=patch;h=75eebe0b1f15464d19a39c4186bfabf328ab601a"
      sha256 "9f4db8c6f80f4a87baf1b778fea62bbad89db9db5fd47548c2d22e5475edd910"
```

Use patch from `git.qemu.org`.

**Review by carlocab — APPROVED** [review]
