### PR TITLE
rtags: Added plist support.

### PR DESCRIPTION
**Pull request by mpark**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

This is based on:
https://github.com/Andersbakken/rtags#integration-with-launchd-mac-os-x

### CODE REVIEW

File: Formula/rtags.rb [hunk 1]
```diff
@@ -28,6 +28,45 @@ def install
...
 
+  def caveats; <<-EOS.undent
+    The instance of rtags that run via brew services listens to
+    the socket file at #{var}/.rdm
+
+      rc --socket-file=#{var}/.rdm ...
+    EOS
+  end
+
+  plist_options :startup => false
```
Comment (DomT4) [inline Formula/rtags.rb]: `false` doesn't need stating. Usually if not `plist_options :startup` you'd set something like:
```ruby
plist_options :manual => "rdm --log-file=#{var}/log/rtags.log --socket-file=#{var}/.rdm"
```
Or such.

File: Formula/rtags.rb [hunk 2]
```diff
@@ -28,6 +28,45 @@ def install
     end
   end
 
+  def caveats; <<-EOS.undent
+    The instance of rtags that run via brew services listens to
+    the socket file at #{var}/.rdm
```
Comment (DomT4) [inline Formula/rtags.rb]: Feels a bit questionable to have it be a hidden directory. Any particular reason for that?

Comment (mpark) [inline Formula/rtags.rb]: Ah, I just kept the name from the default value:
```
--socket-file|-n [arg]                 Use this file for the server socket (default ~/.rdm).
```
Would it be better to just use `rdm` instead?

Comment (DomT4) [inline Formula/rtags.rb]: Hidden directories are preferred in `HOME` by users, but a lot less common in places like `var`. `#{var}/rdm` sounds 👍 to me.

Comment (mpark) [inline Formula/rtags.rb]: > Hidden directories are preferred in HOME by users
Using the default value of `~/.rdm` would actually improve usability I think, since the simple
invocation of `rc` will work without having to specify `rc --socket-file=#{var}/rdm`.

But I'm not sure if this is good practice. Is there a policy or a convention for home-brew
packages around this?

Comment (MikeMcQuaid) [inline Formula/rtags.rb]: Just use the default value 👍

Comment (DomT4) [inline Formula/rtags.rb]: Basically, as long as you're not relying on Homebrew being able to write to that prefix during install or test, that's fine to use the default.

Comment (mpark) [inline Formula/rtags.rb]: Great!

I need some help with filling out this part:
```
<dict>
  <key>SockPathName</key>
  <string>#{var}/.rdm</string>
</dict>
```
What can I replace `#{var}` with, to get the user's `$HOME` directory?

Comment (MikeMcQuaid) [inline Formula/rtags.rb]: `ENV["HOME"]` but what happens if you just don't specify this argument?

Comment (mpark) [inline Formula/rtags.rb]: @MikeMcQuaid: As far as I understand, if this argument is not specified, `launchd` won't be listening to this socket for activity. The `--inactivity-timeout` flag in conjunction with this argument is what makes `rtags` run on-demand.

File: Formula/rtags.rb (hunk 1 above)
Comment (mpark) [inline Formula/rtags.rb]: Ah, I see. I got `plist_options :startup => false` from the formula for `kwm`.
For this plist configuration, we can just leave it out, since `launchd` listens to the socket at `~/.rdm` for activity and launches `rdm` automatically.

File: Formula/rtags.rb (hunk 2 above)
Comment (MikeMcQuaid) [inline Formula/rtags.rb]: Cool, seems fine then.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
OK, just an audit failure:
```
        Error: 1 problem in 1 formula
rtags:
  * Please set plist_options when using a formula-defined plist.
```
Take a look at examples like [`bind.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bind.rb) and [`collectd.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/collectd.rb).

**Comment by ilovezfs** [comment]
It's also run-time failure on El Capitan.
```
==> /usr/local/Cellar/rtags/2.3/bin/rc -c
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/rtags/2.3/bin/rc
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/rtags/2.3/bin/rc
  Expected in: /usr/lib/libSystem.B.dylib

```

**Comment by ilovezfs** [comment]
@mpark run-time failure is now fixed by https://github.com/Homebrew/homebrew-core/pull/6118 so if you rebase your PR on master and fix the audit issue mentioned above it should be :green_apple:

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!
