### PR TITLE
sfcgal: build with Boost 1.75

### PR DESCRIPTION
**Pull request by fxcoudert**
One of the most-downloaded formula with no Apple Silicon bottle… let's try to fix it

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
/tmp/sfcgal-20210107-30997-1fxlso/SFCGAL-v1.3.9/src/detail/generator/building.cpp:103:46: error: no viable conversion from 'shared_ptr<Straight_skeleton_2<CGAL::Exact_predicates_inexact_constructions_kernel>>' to 'shared_ptr<Straight_skeleton_2<SFCGAL::Kernel>>'
    boost::shared_ptr< Straight_skeleton_2 > skeleton = CGAL::create_interior_straight_skeleton_2( polygon ) ;
                                             ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:352:21: note: candidate constructor not viable: no known conversion from 'boost::shared_ptr<Straight_skeleton_2<Exact_predicates_inexact_constructions_kernel> >' (aka 'shared_ptr<Straight_skeleton_2<CGAL::Epick> >') to 'boost::detail::sp_nullptr_t' (aka 'nullptr_t') for 1st argument
    BOOST_CONSTEXPR shared_ptr( boost::detail::sp_nullptr_t ) BOOST_SP_NOEXCEPT : px( 0 ), pn()
                    ^
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:416:5: note: candidate constructor not viable: no known conversion from 'boost::shared_ptr<Straight_skeleton_2<Exact_predicates_inexact_constructions_kernel> >' (aka 'shared_ptr<Straight_skeleton_2<CGAL::Epick> >') to 'const boost::shared_ptr<CGAL::Straight_skeleton_2<CGAL::Epeck, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> > > &' for 1st argument
    shared_ptr( shared_ptr const & r ) BOOST_SP_NOEXCEPT : px( r.px ), pn( r.pn )
    ^
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:628:5: note: candidate constructor not viable: no known conversion from 'boost::shared_ptr<Straight_skeleton_2<Exact_predicates_inexact_constructions_kernel> >' (aka 'shared_ptr<Straight_skeleton_2<CGAL::Epick> >') to 'boost::shared_ptr<CGAL::Straight_skeleton_2<CGAL::Epeck, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> > > &&' for 1st argument
    shared_ptr( shared_ptr && r ) BOOST_SP_NOEXCEPT : px( r.px ), pn()
    ^
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:444:5: note: candidate template ignored: substitution failure [with Y = CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> >]: no type named 'type' in 'boost::detail::sp_enable_if_convertible<CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> >, CGAL::Straight_skeleton_2<CGAL::Epeck, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> > >'
    shared_ptr( shared_ptr<Y> const & r, typename boost::detail::sp_enable_if_convertible<Y,T>::type = boost::detail::sp_empty() )
    ^                                                                                           ~~~~
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:478:5: note: candidate template ignored: could not match 'auto_ptr' against 'shared_ptr'
    shared_ptr( std::auto_ptr<Y> && r ): px(r.get()), pn()
    ^
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:510:5: note: candidate template ignored: could not match 'unique_ptr' against 'shared_ptr'
    shared_ptr( std::unique_ptr< Y, D > && r ): px( r.get() ), pn()
    ^
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:526:5: note: candidate template ignored: could not match 'unique_ptr' against 'shared_ptr'
    shared_ptr( boost::movelib::unique_ptr< Y, D > r ): px( r.get() ), pn()
    ^
/opt/homebrew/include/boost/smart_ptr/shared_ptr.hpp:637:5: note: candidate template ignored: substitution failure [with Y = CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> >]: no type named 'type' in 'boost::detail::sp_enable_if_convertible<CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> >, CGAL::Straight_skeleton_2<CGAL::Epeck, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> > >'
    shared_ptr( shared_ptr<Y> && r, typename boost::detail::sp_enable_if_convertible<Y,T>::type = boost::detail::sp_empty() )
    ^                                                                                      ~~~~
```

**Comment by fxcoudert** [comment]
Reported at https://gitlab.com/Oslandia/SFCGAL/-/issues/240
