### ISSUE TITLE
rsync failed to build on osx 10.10.5

### ISSUE THREAD

**Issue by extrinsicmedia** [Homebrew/homebrew-core#2331]
Getting this error after tapping homebrew/dupes and running `homebrew install rsync`

Error: undefined method `apply' for #<Resource:0x007fc3d424b720>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-dupes/rsync.rb:24:in `block in <class:Rsync>'
/usr/local/Library/Homebrew/resource.rb:49:in `instance_eval'
/usr/local/Library/Homebrew/resource.rb:49:in `initialize'
/usr/local/Library/Homebrew/patch.rb:115:in `new'
/usr/local/Library/Homebrew/patch.rb:115:in `initialize'
/usr/local/Library/Homebrew/patch.rb:18:in `new'
/usr/local/Library/Homebrew/patch.rb:18:in `create'
/usr/local/Library/Homebrew/software_spec.rb:168:in `patch'
/usr/local/Library/Homebrew/formula.rb:1834:in `block in patch'
/usr/local/Library/Homebrew/formula.rb:1834:in `each'
/usr/local/Library/Homebrew/formula.rb:1834:in `patch'
/usr/local/Library/Taps/homebrew/homebrew-dupes/rsync.rb:19:in `<class:Rsync>'
/usr/local/Library/Taps/homebrew/homebrew-dupes/rsync.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/formulary.rb:214:in `from_rack'
/usr/local/Library/Homebrew/extend/ARGV.rb:37:in `block in resolved_formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `resolved_formulae'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:134:in `gist_logs'
/usr/local/Library/brew.rb:146:in `<main>'

**Comment by MikeMcQuaid** [comment]
Can you rerun `brew update` (twice) and paste your `brew config` and `brew doctor` output here? Thanks!

**Comment by extrinsicmedia** [comment]
Brew config info:

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 74ac2f192e4cf7bad3b945c2966fbd9c9cca0e77
Last commit: 8 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.8.0_66, 1.8.0_60

**Comment by extrinsicmedia** [comment]
brew doctor output:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

**Comment by MikeMcQuaid** [comment]
@extrinsicmedia What happened when you ran `brew update`?

**Comment by extrinsicmedia** [comment]
The first time it updated the caskroom tap and said up-to-date.  The second time it just said up-to-date.

**Comment by MikeMcQuaid** [comment]
`brew config` shows it's definitely not up to date.

**Comment by extrinsicmedia** [comment]
Any suggestions on forcing it to update?

**Comment by MikeMcQuaid** [comment]
@extrinsicmedia `cd /usr/local; git fetch; git checkout --force master; git reset --hard origin/master; brew update; brew update`

**Comment by extrinsicmedia** [comment]
That did the trick!  Thanks very much for your time @MikeMcQuaid.
