### ISSUE TITLE
Patch for APR build

### ISSUE THREAD

**Issue by marcastel** [Homebrew/homebrew-core#74701]
### Provide a detailed description of the proposed feature

Gents. Not a brew user, so placing information here. I peeked at your formula to build APR on macOS. It fails. I provided a [patch](https://bz.apache.org/bugzilla/show_bug.cgi?id=64753#c11) that you may be interested in using. Cheers.

**Comment by alebcay** [comment]
To quote from the attached patch link:

---

I recently updated to XCode 12 on macOS 10.15.6, which comes with Apple Clang 12.0.0 (LLVM Clang 10.0.0). I am no longer able to compile APR from source. I see the following error message:

```
In file included from encoding/apr_encode.c:28:
In file included from ./include/apr_encode.h:24:
./include/apr.h:561:2: error: Can not determine the proper size for pid_t
#error Can not determine the proper size for pid_t
 ^
In file included from encoding/apr_encode.c:30:
In file included from ./include/apr_strings.h:52:
./include/apr_want.h:94:8: error: redefinition of 'iovec'
struct iovec
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_iovec_t.h:31:8: note: previous definition is here
struct iovec {
       ^
2 errors generated.
make[1]: *** [encoding/apr_encode.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from strings/apr_cpystrn.c:17:
./include/apr.h:561:2: error: Can not determine the proper size for pid_t
#error Can not determine the proper size for pid_t
 ^
In file included from passwd/apr_getpass.c:22:
In file included from /var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-apr-1.7.0-pw3odg3co73bcqzmq4nptwwyhbkdxab7/spack-src/include/arch/unix/apr_private.h:1074:
In file included from /var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-apr-1.7.0-pw3odg3co73bcqzmq4nptwwyhbkdxab7/spack-src/include/arch/unix/../apr_private_common.h:24:
In file included from ./include/apr_pools.h:43:
./include/apr.h:561:2: error: Can not determine the proper size for pid_t
#error Can not determine the proper size for pid_t
 ^
In file included from strings/apr_cpystrn.c:18:
In file included from ./include/apr_strings.h:52:
./include/apr_want.h:94:8: error: redefinition of 'iovec'
struct iovec
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_iovec_t.h:31:8: note: previous definition is here
struct iovec {
       ^
In file included from passwd/apr_getpass.c:23:
In file included from ./include/apr_strings.h:52:
./include/apr_want.h:94:8: error: redefinition of 'iovec'
struct iovec
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_iovec_t.h:31:8: note: previous definition is here
struct iovec {
       ^
2 errors generated.
make[1]: *** [strings/apr_cpystrn.lo] Error 1
2 errors generated.
make[1]: *** [passwd/apr_getpass.lo] Error 1
make: *** [all-recursive] Error 1
```

Compilation worked fine on macOS 10.15.6 with XCode 11, which comes with Apple Clang 11.0.3 (LLVM Clang 9.0.0), so I believe this is a consequence of a stricter compiler.

**Comment by carlocab** [comment]
I guess I'm just confused that we didn't see the build failure in the CI run I linked to above, which should have been a build using Xcode 12.

**Comment by fxcoudert** [comment]
> It fails.

It's working on our build machines. In the absence of an actual failure report, closing.
