### PR TITLE
mariadb 10.1.18 (stable), 10.2.2 (devel)

### PR DESCRIPTION
**Pull request by makigumo**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by makigumo** [comment]
Error is probably because of Xcode/CLT 8.0. Relevant error message seems to be `dyld: Symbol not found: _clock_gettime`. My guess would be for it to build fine using Xcode 7.3.1.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!
