### ISSUE TITLE
--universal --java subversion failed to build on macOS 10.12.2 (16C67)

### ISSUE THREAD

**Issue by asimsalam** [Homebrew/homebrew-core#8067]
### Bug reports:

I tried to run brew install --universal --java subversion.

It failed to build with linking errors. Here is the tail:

==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
==> Best Mirror http://www.gtlib.gatech.edu/pub/apache/serf/serf-1.3.9.tar.bz2
######################################################################## 100.0%
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.9.5_1/libexec/serf GSSAPI=/usr CC=/usr/bin/clang CFLAGS=-Os -w -
Last 15 lines from /Users/as186204/Library/Logs/Homebrew/subversion/01.scons:
ld: warning: ignoring file /usr/local/lib/libz.dylib, file was built for i386 which is not the architecture being linked (x86_64): /usr/local/lib/libz.dylib
Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _serf_deflate_read in deflate_buckets.os
  "_inflate", referenced from:
      _serf_deflate_read in deflate_buckets.os
  "_inflateEnd", referenced from:
      _serf_deflate_read in deflate_buckets.os
      _serf_deflate_destroy_and_data in deflate_buckets.os
  "_inflateInit2_", referenced from:
      _serf_deflate_read in deflate_buckets.os
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [libserf-1.dylib] Error 1
scons: building terminated because of errors.

READ THIS: https://git.io/brew-troubleshooting

The logs are at:
https://gist.github.com/d40dd58d6953e99f32b9eb31ba349dce

Output of brew doctor:
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcrypto.0.9.8.dylib
  /usr/local/lib/libcrypto.dylib
  /usr/local/lib/libklcskca.dylib
  /usr/local/lib/libklcsrt.dylib
  /usr/local/lib/libklcsstd.dylib
  /usr/local/lib/libklcstr.dylib
  /usr/local/lib/libklmspack.0.1.0.dylib
  /usr/local/lib/libklmspack.0.dylib
  /usr/local/lib/libklmspack.dylib
  /usr/local/lib/libssl.0.9.8.dylib
  /usr/local/lib/libssl.dylib
  /usr/local/lib/libz.1.2.5.dylib
  /usr/local/lib/libz.1.dylib
  /usr/local/lib/libz.dylib

Output of brew config:
$ brew config
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9d4b86496cb37bcd6ba97ff8961fabc99065bc81
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A

Please let me know if you need any more information.

**Comment by asimsalam** [comment]
https://gist.github.com/d40dd58d6953e99f32b9eb31ba349dce

**Comment by MikeMcQuaid** [comment]
> You can erase any parts of this template not applicable to your Issue.
> 
> Bug reports:
> 
> Please replace this section with a brief summary of your issue AND the output of brew config and brew doctor or if reporting a formula issue include the link from:
> brew gist-logs <formula>
> (where <formula> is the name of the formula that failed to build). Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

Please do this.

**Comment by asimsalam** [comment]
Updated the Bug report with information.

**Comment by ploxiln** [comment]
I would heed this warning:

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcrypto.0.9.8.dylib
  /usr/local/lib/libcrypto.dylib
...
  /usr/local/lib/libssl.0.9.8.dylib
  /usr/local/lib/libssl.dylib
  /usr/local/lib/libz.1.2.5.dylib
  /usr/local/lib/libz.1.dylib
  /usr/local/lib/libz.dylib
```

Do you know where these came from, what they were for?

So, you're building universal, both x86_64 and i386, and the linker says it skipped over `/usr/local/lib/libz.dylib` because it was looking for x86_64 and that's i386, but I'm not 100% confident that it really didn't use it.

```
/usr/bin/clang -o libserf-1.dylib -L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names \
  -arch x86_64 -arch i386 -Wl,-install_name,/private/tmp/subversion--serf-20161220-79349-qy3uu5/serf-1.3.9/libserf-1.dylib -Wl,-search_paths_first -dynamiclib context.os incoming.os \
  outgoing.os ssltunnel.os buckets/aggregate_buckets.os buckets/allocator.os buckets/barrier_buckets.os buckets/buckets.os buckets/bwtp_buckets.os buckets/chunk_buckets.os buckets/dechunk_buckets.os buckets/deflate_buckets.os \
  buckets/file_buckets.os buckets/headers_buckets.os buckets/iovec_buckets.os buckets/limit_buckets.os buckets/mmap_buckets.os buckets/request_buckets.os buckets/response_body_buckets.os buckets/response_buckets.os buckets/simple_buckets.os \
  buckets/socket_buckets.os buckets/ssl_buckets.os auth/auth.os auth/auth_basic.os auth/auth_digest.os auth/auth_spnego.os auth/auth_spnego_gss.os auth/auth_spnego_sspi.os \
  -L/usr/local/opt/apr/libexec/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/apr-util/libexec/lib -L/usr/local/opt/openssl/lib -lssl -lcrypto -lz -lapr-1 -lpthread -laprutil-1 -lexpat -liconv -lkrb5
ld: warning: ignoring file /usr/local/lib/libz.dylib, file was built for i386 which is not the architecture being linked (x86_64): /usr/local/lib/libz.dylib
Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _serf_deflate_read in deflate_buckets.os
  "_inflate", referenced from:
_serf_deflate_read in deflate_buckets.os
...
```

It's supposed to be finding and using `/usr/lib/libz.dylib`:

```
$ file /usr/lib/libz.dylib 
/usr/lib/libz.dylib: Mach-O universal binary with 2 architectures
/usr/lib/libz.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/usr/lib/libz.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by asimsalam** [comment]
libz is present. 

$ ls -alh /usr/lib/libz.dylib
lrwxr-xr-x  1 root  wheel    12B Dec  7 12:30 /usr/lib/libz.dylib -> libz.1.dylib
$ file !$
file /usr/lib/libz.dylib
/usr/lib/libz.dylib: Mach-O universal binary with 2 architectures: [x86_64: Mach-O 64-bit dynamically linked shared library x86_64] [i386: Mach-O dynamically linked shared library i386]
/usr/lib/libz.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/usr/lib/libz.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
$ 

No, I do not know where the version in /usr/local/lib came from.

**Comment by ploxiln** [comment]
You may have compiled and installed some application that needed those. Anyway, you can try moving them out of the way temporarily to see if they are the cause of this problem. Something like:

```
mkdir ~/templibs
mv /usr/local/lib/libz.*dylib /usr/local/lib/libssl.*dylib /usr/local/lib/libcrypto.*dylib ~/tmplibs/
```

Then try building subversion again. If something important to you broke, you can move the libs back.

**Comment by MikeMcQuaid** [comment]
> Warning: Unbrewed dylibs were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected dylibs:
> /usr/local/lib/libcrypto.0.9.8.dylib
> /usr/local/lib/libcrypto.dylib
> /usr/local/lib/libklcskca.dylib
> /usr/local/lib/libklcsrt.dylib
> /usr/local/lib/libklcsstd.dylib
> /usr/local/lib/libklcstr.dylib
> /usr/local/lib/libklmspack.0.1.0.dylib
> /usr/local/lib/libklmspack.0.dylib
> /usr/local/lib/libklmspack.dylib
> /usr/local/lib/libssl.0.9.8.dylib
> /usr/local/lib/libssl.dylib
> /usr/local/lib/libz.1.2.5.dylib
> /usr/local/lib/libz.1.dylib
> /usr/local/lib/libz.dylib

You need to remove all of these and, most likely, uninstall and reinstall all your Homebrew packages as many of them will have incorrectly built against these. Sorry!
