### PR TITLE
vim 9.0.1150

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  vim9class.c:450:10: error: no member named 'class_flags' in 'struct class_S'
              cl->class_flags = CLASS_INTERFACE;
              ~~  ^
  vim9class.c:450:24: error: use of undeclared identifier 'CLASS_INTERFACE'
              cl->class_flags = CLASS_INTERFACE;
                                ^
  2 errors generated.
```

**Review by p-linnane — DISMISSED** [review]

**Comment by chenrui333** [comment]
some merge conflict with #118926

**Review by p-linnane — DISMISSED** [review]

**Review by chenrui333 — APPROVED** [review]
