### PR TITLE
ctags: fix build on recent macOS 10.14 - conflict with __unused__

### PR DESCRIPTION
**Pull request by ploxiln**
The build failed on latest macOS 10.14.5 like so:

    In file included from main.c:62:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/dirent.h:80:2: error: use of undeclared identifier 'unused'
            __unused long   __padding; /* (__dd_rewind space left for bincompat) */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:161:40: note: expanded from macro '__unused'
    #define __unused        __attribute__((__unused__))
                                           ^
    ./general.h:60:37: note: expanded from macro '__unused__'
    # define __unused__  __attribute__((unused))
                                        ^
    1 error generated.
    make: *** [main.o] Error 1

As you can see, exuberant-ctags has defined `__unused__` but the
macOS toolchain also uses `__unused__` and it is confused.

The easiest fix is to pretend this is unsupported and disable/blank
`__unused__` (which should only affect compiler warnings, and the
same for the printf format string warnings which are also disabled).

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
  * not really - it tries to use my system ruby, but that doesn't have development headers, so it fails to install gems

### CODE REVIEW

**Comment by fxcoudert** [comment]
Has this been reported upstream? Please add a link to the bug report, and possibly use their patch to fix it.

**Comment by ploxiln** [comment]
Last upstream release was 2009, last upstream commit was 2014. Thus the other two mini patches this recipe already applied.

Everyone is waiting for the "universal-ctags" fork to make a release, but the maintainer there is reluctant to make an imperfect release: https://github.com/universal-ctags/ctags/issues/1038 so until there is even an alpha release tagged, there's a separate homebrew tap to always build from HEAD: https://github.com/universal-ctags/homebrew-universal-ctags

**Comment by fxcoudert** [comment]
Merged then :(
Thanks for the patch
