### PR TITLE
nmap 7.93

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Undefined symbols for architecture arm64:
    "_EVP_MD_CTX_create", referenced from:
        _make_nonce in http_digest.o
        _make_response in http_digest.o
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by carlocab** [comment]
> ```
> 
>   Undefined symbols for architecture arm64:
> 
>     "_EVP_MD_CTX_create", referenced from:
> 
>         _make_nonce in http_digest.o
> 
>         _make_response in http_digest.o
> 
>   ld: symbol(s) not found for architecture arm64
> 
>   clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ```

I think this symbol is supposed to be provided by OpenSSL.

**Comment by carlocab** [comment]
Ah, this is the problem: https://stackoverflow.com/a/46769674/10153385

`EVP_MD_CTX_create` is an old OpenSSL API that has been replaced by `EVP_MD_CTX_new`, defined in `libcrypto`.

No idea why it's trying to use an old OpenSSL API. Maybe it's picking up the system `libcrypto`?

**Comment by cho-m** [comment]
Upstream added some code to support `openssl@3` (https://github.com/nmap/nmap/commit/140dd72415f61a4bcd13966ed9c35149e7cf0173)

The `EVP_MD_CTX_create` seems to be for older OpenSSL 1.0 rather than 1.1? Not sure what `OPENSSL_API_LEVEL` is defined to (macro looks like from OpenSSL 3.0 but some headers have a copy like `ncat/ncat_ssl.h`).
```c
#if OPENSSL_API_LEVEL < 10100
#define EVP_MD_CTX_new EVP_MD_CTX_create
```

**Comment by carlocab** [comment]
Probably broken by https://github.com/nmap/nmap/commit/140dd72415f61a4bcd13966ed9c35149e7cf0173, but it doesn't cleanly revert.

This needs to be reported upstream.

**Comment by carlocab** [comment]
Reported at https://github.com/nmap/nmap/issues/2516.

**Review by carlocab — APPROVED** [review]
