### PR TITLE
isl 0.21

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
Testing failures of `nwchem` on all three nodes,

```
23:23:47 ==> ./runtests.mpi.unix procs 2 dft_he2+ prop_mep_gcube pspw tddft_h2o tce_n2
23:23:47  Mpirun is not in your current path. Please do:
23:23:47  setenv MPIRUN_PATH /home/guido/bagheria/bin/mpirun 
23:23:47  Please make sure you have the right mpirun for your system.
23:23:47  Alternatively set the number of processors to 0.
```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Actually this won't work because we just revisioned `gcc` to fix some Xcode bug.
@lembacon can you bump the gcc revision to 2 and rebase on top of master? Then it should be good to do.

**Comment by lembacon** [comment]
> Actually this won't work because we just revisioned `gcc` to fix some Xcode bug.
> @lembacon can you bump the gcc revision to 2 and rebase on top of master? Then it should be good to do.

Done.

**Comment by scpeters** [comment]
gcc@6 and gcc@7 are failing to build on mojave; should we apply the patch from #39041 to these as well?

~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83:0,
                 from ../../gcc/config/darwin-driver.c:30:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:94:2: error: '_Atomic' does not name a type
  _Atomic u_long          cr_ref;  /* reference count */
  ^~~~~~~
~~~

gcc@6 fails on high sierra with a different error:

~~~
19:24:08 In file included from ../../../../../libstdc++-v3/src/filesystem/dir.cc:29:0:
19:24:08 /private/tmp/gcc@6-20190419-33830-23bz55/gcc-6.5.0/build/x86_64-apple-darwin17.7.0/libstdc++-v3/include/experimental/filesystem:40:38: fatal error: experimental/bits/fs_dir.h: No such file or directory
19:24:08  #include <experimental/bits/fs_dir.h>
19:24:08                                       ^
19:24:08 compilation terminated.
~~~

**Comment by zbeekman** [comment]
@scpeters the first error is definitely the same bug. I'll open PRs to patch. No idea what the second error is about. I'll hunt around.

**Comment by zbeekman** [comment]
Bumped gcc@5, gcc@6, gcc@7 for the Xcode 10.2 bug. #39134 

I think the gcc@6 failure on high sierria is the APFS bug. IDK if/why that patch was removed, but from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89864 it sounds like that error is the APFS bug... I need to dig around to figure out when/why it was removed and confirm that it is in fact the same issue.

**Comment by fxcoudert** [comment]
Thanks @lembacon, merging. One test failure due to random bottle download issue.
