### PR TITLE
mosh: patch to fix mojave build

### PR DESCRIPTION
**Pull request by scpeters**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The mosh formula is failing to build on mojave in https://github.com/Homebrew/homebrew-core/pull/40438 for protobuf 3.9.1 with compilation errors like the following:

~~~
network.cc:338:57: error: invalid operands to binary expression ('__bind<int, sockaddr *, unsigned int &>' and 'int')
    if ( bind( sock(), &local_addr.sa, local_addr_len ) == 0 ) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~
~~~

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/46354/version=mojave/testReport/junit/brew-test-bot/mojave/install___build_bottle_mosh/

I was able to reproduce the mosh build failure on `master` and found an upstream commit that fixes it: https://github.com/mobile-shell/mosh/commit/e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0

### CODE REVIEW

**Comment by YujiShen** [comment]
Hi @scpeters , I try to install HEAD but failed when patching, any fix for this?
```
==> Patching
==> Applying e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0.patch
patching file src/network/network.cc
Hunk #1 FAILED at 332.
1 out of 1 hunk FAILED -- saving rejects to file src/network/network.cc.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/mosh--patch-20190821-38285-99wflk/e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0.patch` exited with 1.
```

**Comment by YujiShen** [comment]
@scpeters I comment the patch and install it without issue. But I am not sure whether this is correct... Does this mean the patch has already been merged into upstream?

**Comment by scpeters** [comment]
yes, the commit has been merged upstream, I'll look into disabling the patch for HEAD builds

**Comment by scpeters** [comment]
do you mind making a pull request that wraps the patch in a `unless build.head?` block?

* https://github.com/Homebrew/homebrew-core/blob/master/Formula/archey.rb#L12

**Comment by YujiShen** [comment]
Sure, glad to contribute. What does this mean?

**Comment by scpeters** [comment]
There is an example of using `unless build.head?` in the archer formula:

* https://github.com/Homebrew/homebrew-core/blob/master/Formula/archey.rb#L12

**Comment by YujiShen** [comment]
Thanks! I just submit the pull request: https://github.com/Homebrew/homebrew-core/pull/43349

I see how to use the block, but don't understand why use `build.head`, since we do not want to patch when do HEAD install. Sorry I am not familiar with these variables in Homebrew....

**Comment by scpeters** [comment]
The `unless` keyword mean it will only apply the patch if `build.head?` is false. It's like `if not`.

**Comment by YujiShen** [comment]
Got it. It's Ruby syntax... Thanks for explanation!
