### PR TITLE
newsboat: fix build

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This should fix the "call to undeclared function 'wget_wch'" build failure seen in #128865. Logs: https://github.com/Homebrew/homebrew-core/actions/runs/4784368511/jobs/8509780504?pr=128865#step:7:8328

We don't need to publish bottles because there's no actual change in the bottles' contents.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
  gcc -pthread -DNCURSES_WIDECHAR=1 -I. -Wall -Os -ggdb -D_GNU_SOURCE -fPIC   -c -o base.o base.c
  base.c:537:11: error: call to undeclared function 'wget_wch'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          int rc = wget_wch(stdscr, &wch);
                   ^
  base.c:537:11: note: did you mean 'wgetch'?
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ncurses.h:763:28: note: 'wgetch' declared here
  extern NCURSES_EXPORT(int) wgetch (WINDOW *);                           /* implemented */
                             ^
  base.c:736:4: error: call to undeclared function 'mvwaddnwstr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                          mvwaddnwstr(win, y, x, p, len);
                          ^
  base.c:736:4: note: did you mean 'mvwaddnstr'?
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ncurses.h:634:28: note: 'mvwaddnstr' declared here
  extern NCURSES_EXPORT(int) mvwaddnstr (WINDOW *, int, int, const char *, int);  /* generated */
                             ^
  base.c:744:4: error: call to undeclared function 'mvwaddnwstr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                          mvwaddnwstr(win, y, x, p, len);
                          ^
  3 errors generated.
```

**Review by p-linnane — APPROVED** [review]
