### PR TITLE
hapi-fhir-cli 3.2.0 (new formula)

### PR DESCRIPTION
**Pull request by johngrimes**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
```
02:37:40 INFO  ca.uhn.fhir.cli.ValidateCommand - Reading file '/tmp/hapi-fhir-cli-test-20180128-90238-1r15hwe/TestResource.json' using encoding UTF-8
02:37:40 INFO  ca.uhn.fhir.cli.ValidateCommand - Fully read - Size is 5KB
02:37:40 INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU3]
02:37:43 INFO  ca.uhn.fhir.util.XmlUtil - FHIR XML procesing will use StAX implementation 'null' version 'null'
02:37:43 WARN  c.u.fhir.parser.LenientErrorHandler - Unknown element 'comment' found while parsing
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.phloc.schematron.svrl.SVRLReader.readXML(SVRLReader.java:73)
	at com.phloc.schematron.xslt.AbstractSchematronXSLTResource.applySchematronValidationToSVRL(AbstractSchematronXSLTResource.java:171)
	at com.phloc.schematron.SchematronHelper.applySchematron(SchematronHelper.java:126)
	at ca.uhn.fhir.validation.schematron.SchematronBaseValidator.validateResource(SchematronBaseValidator.java:79)
	at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:231)
	at ca.uhn.fhir.cli.ValidateCommand.run(ValidateCommand.java:135)
	at ca.uhn.fhir.cli.App.main(App.java:189)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 7 more
Error: hapi-fhir-cli: failed
```

Seems that the test is failing, unfortunately.  When you run `brew test hapi-fhir-cli` on your local machine, does it pass?  If so, what Java version are you using?

**Comment by johngrimes** [comment]
Yes, it works on my local machine, I have Java 1.8.0_152-ea.

I have opened an issue on the source repository: jamesagnew/hapi-fhir#838

**Comment by ilovezfs** [comment]
New formulae are required to work with Java 9. Feel free to open a fresh PR when that is the case! Thanks @johngrimes
