### PR TITLE
bmake 20201010

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`brew test --retry --verbose libmaa` on 10.15

**Comment by chenrui333** [comment]
```
==> Testing libmaa
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201019-26418-14ahb2w.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmaa.rb --verbose --retry
==> /usr/bin/clang test.c -I/usr/local/Cellar/libmaa/1.4.7/include -L/usr/local/Cellar/libmaa/1.4.7/lib -lmaa -o test
test.c:35:27: error: implicitly declaring library function 'strtol' with type 'long (const char *, char **, int)' [-Werror,-Wimplicit-function-declaration]
   if (argc == 2) limit = strtol( argv[1], NULL, 0 );
                          ^
test.c:35:27: note: include the header <stdlib.h> or explicitly provide a declaration for 'strtol'
1 error generated.
==> Testing libmaa (again)
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201019-26692-ir458e.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmaa.rb --verbose --retry
==> /usr/bin/clang test.c -I/usr/local/Cellar/libmaa/1.4.7/include -L/usr/local/Cellar/libmaa/1.4.7/lib -lmaa -o test
test.c:35:27: error: implicitly declaring library function 'strtol' with type 'long (const char *, char **, int)' [-Werror,-Wimplicit-function-declaration]
   if (argc == 2) limit = strtol( argv[1], NULL, 0 );
                          ^
test.c:35:27: note: include the header <stdlib.h> or explicitly provide a declaration for 'strtol'
1 error generated.
```

**Comment by chenrui333** [comment]
```
--- install-maa ---
checking C compiler type... clang 12.0.0
bmake[1]: "/usr/local/Cellar/mk-configure/0.34.2/share/mk-configure/mk/mkc_imp.platform.sys.mk" line 112: 'Settings for clang-12.0.0 is not available, run "mkc_compiler_settings" utility'
```

**Comment by chenrui333** [comment]
works on my 10.15 machine

**Comment by chenrui333** [comment]
```
==> brew livecheck libmaa --full-name --debug
==> brew audit libmaa --online --git --skip-style
==> brew uninstall --force mk-configure pkg-config
```

**Comment by chenrui333** [comment]
close in favor of #65386
