### ISSUE TITLE
tesseract head with opencl ""_clReleaseProgram", referenced from:"

### ISSUE THREAD

**Issue by y-fedorov** [Homebrew/homebrew-core#4764]
```
$ brew install tesseract --HEAD --with-opencl
==> Using the sandbox
==> Cloning https://github.com/tesseract-ocr/tesseract.git
Updating /Users/latistaadmin/Library/Caches/Homebrew/tesseract--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/tesseract/HEAD-a75ab45_2 --enable-opencl
==> make install
Last 15 lines from /Users/latistaadmin/Library/Logs/Homebrew/tesseract/03.make:
  "_clReleaseProgram", referenced from:
      OpenclDevice::ReleaseOpenclEnv(_GPUEnv*) in libtesseract_opencl.a(openclwrapper.o)
  "_clSetKernelArg", referenced from:
      OpenclDevice::pixReadFromTiffKernel(unsigned int*, int, int, int, unsigned int*) in libtesseract_opencl.a(openclwrapper.o)
      pixDilateCL_55(int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixErodeCL_55(int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixDilateCL(int, int, int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixErodeCL(int, int, unsigned int, unsigned int) in libtesseract_opencl.a(openclwrapper.o)
      pixORCL_work(unsigned int, unsigned int, _cl_mem*, _cl_mem*, _cl_mem*) in libtesseract_opencl.a(openclwrapper.o)
      pixANDCL_work(unsigned int, unsigned int, _cl_mem*, _cl_mem*, _cl_mem*) in libtesseract_opencl.a(openclwrapper.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libtesseract.la] Error 1
make: *** [install-recursive] Error 1
```

**brew gist-logs tesseract**
https://gist.github.com/y-fedorov/0e5a302dd68ff9d8647f03ba4c15050a

**brew update**
Already up-to-date.

**$ cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update**
HEAD is now at 5a264cf Merge pull request #947 from zmwangx/fix-test-bot-desc
Updated 1 tap (homebrew/core).
==> Updated Formulae
redpen

$ brew install tesseract   - is OK
$ brew install tesseract --HEAD   - is OK

**Comment by ilovezfs** [comment]
Yup,
```
==> Installing tesseract
==> Using the sandbox
==> Cloning https://github.com/tesseract-ocr/tesseract.git
Cloning into '/Users/joe/Library/Caches/Homebrew/tesseract--git'...
remote: Counting objects: 794, done.
remote: Compressing objects: 100% (733/733), done.
remote: Total 794 (delta 125), reused 235 (delta 42), pack-reused 0
Receiving objects: 100% (794/794), 3.78 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (125/125), done.
Checking connectivity... done.
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/tesseract/HEAD-a75ab45_2 --enable-opencl
==> make install
Last 15 lines from /Users/joe/Library/Logs/Homebrew/tesseract/03.make:
  "_clReleaseProgram", referenced from:
      OpenclDevice::ReleaseOpenclEnv(_GPUEnv*) in libtesseract_opencl.a(openclwrapper.o)
  "_clSetKernelArg", referenced from:
      OpenclDevice::pixReadFromTiffKernel(unsigned int*, int, int, int, unsigned int*) in libtesseract_opencl.a(openclwrapper.o)
      pixDilateCL_55(int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixErodeCL_55(int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixDilateCL(int, int, int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixErodeCL(int, int, unsigned int, unsigned int) in libtesseract_opencl.a(openclwrapper.o)
      pixORCL_work(unsigned int, unsigned int, _cl_mem*, _cl_mem*, _cl_mem*) in libtesseract_opencl.a(openclwrapper.o)
      pixANDCL_work(unsigned int, unsigned int, _cl_mem*, _cl_mem*, _cl_mem*) in libtesseract_opencl.a(openclwrapper.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libtesseract.la] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
tesseract head with opencl ""_clReleaseProgram", referenced from:" https://github.com/Homebrew/homebrew-core/issues/4764
```

**Comment by ilovezfs** [comment]
@y-fedorov OK, I found the problem. This is a regression caused by https://github.com/tesseract-ocr/tesseract/commit/b1c921b59e6af1e68fd026cbc30540929b818552

You can fix it by changing
```
libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION) -no-undefined
```
back to
```
libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION)
```

So in the formula just after `def install` add
```
    if build.head?
      inreplace "api/Makefile.am",
        "libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION) -no-undefined",
        "libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION)"
    end
```

or apply this diff
```
diff --git a/Formula/tesseract.rb b/Formula/tesseract.rb
index 53fd868..8b3ba36 100644
--- a/Formula/tesseract.rb
+++ b/Formula/tesseract.rb
@@ -71,6 +71,12 @@ class Tesseract < Formula
   end
 
   def install
+    if build.head?
+      inreplace "api/Makefile.am",
+        "libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION) -no-undefined",
+        "libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION)"
+    end
+
     if build.with? "training-tools"
       icu4c = Formula["icu4c"]
       ENV.append "CFLAGS", "-I#{icu4c.opt_include}"
```

**Comment by y-fedorov** [comment]
I checked by changing formula, with your code. And it solved my problem.
```
if build.head?
      inreplace "api/Makefile.am",
      "libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION) -no-undefined",
      "libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION)"
end
```

Thank you!

**Comment by ilovezfs** [comment]
@y-fedorov you're welcome :)

Do you want to file the bug report upstream or shall I?

**Comment by y-fedorov** [comment]
I do not know how to do it, I'll be glad if you could help. Thank you!

**Comment by ilovezfs** [comment]
No problem, will do. Thanks for reporting this to us.

**Comment by ilovezfs** [comment]
upstream report filed here: https://github.com/tesseract-ocr/tesseract/issues/426

**Comment by ilovezfs** [comment]
@y-fedorov I merged the fix in https://github.com/Homebrew/homebrew-core/commit/239ebb27242b8691b4725bfdf94d33259f6d09aa so you can revert the local changes to the formula and just run `brew update` :)
