### PR TITLE
voltdb 8.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Current version does not build on any of macOS 10.11, 10.12 or 10.13 https://jenkins.brew.sh/job/Homebrew%20Testing/489/

```
install events in the last 30 days for voltdb
================================================================================
1 | voltdb                                                        | 11 | 100.00%
================================================================================

install_on_request events
================================================================================
1 | voltdb                                                        | 10 | 100.00%
================================================================================

BuildError events
================================================================================
1 | voltdb                                                         | 7 | 100.00%
================================================================================
```

**Comment by fxcoudert** [comment]
And voltdb 8.0 does not build either…

☠️☠️☠️

**Comment by fxcoudert** [comment]
- Java version needs to be exactly 1.8
- Further failure:

```
     [exec] /private/tmp/voltdb-20180313-94365-fqkjai/voltdb-voltdb-8.0/src/ee/voltdbjni.cpp:595:16: error: cannot initialize a variable of type 'jlong *' (aka 'long *') with an rvalue of type 'int64_t *' (aka 'long long *')
     [exec]         jlong* fragmentIdsBuffer = engine->getBatchFragmentIdsContainer();
     [exec]                ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     [exec] /private/tmp/voltdb-20180313-94365-fqkjai/voltdb-voltdb-8.0/src/ee/voltdbjni.cpp:601:26: error: assigning to 'jlong *' (aka 'long *') from incompatible type 'int64_t *' (aka 'long long *')
     [exec]             depIdsBuffer = engine->getBatchDepIdsContainer();
     [exec]                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fxcoudert** [comment]
It seems there is something wrong with every version of voltdb we try… so let's remove it for now https://github.com/Homebrew/homebrew-core/commit/0c1983166e8d8e98f5e8ce464c37090b76a8a67d

We would welcome a pull request to add it back, once it works correctly on macOS!
