### ISSUE TITLE
docker-machine-driver-xhyve fails to build on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#31740]
See #28817. Error is:

```
==> opam config exec -- make lib9p
vendor/lib9p/request.c:28:10: vendor/lib9p/pack.c:32:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
vendor/lib9p/connection.c:28:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
vendor/lib9p/log.c:28:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [vendor/build/lib9p/log.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
1 error generated.
make: *** [vendor/build/lib9p/connection.o] Error 1
make: *** [vendor/build/lib9p/request.o] Error 1
make: *** [vendor/build/lib9p/pack.o] Error 1
```

**Comment by Buzzglo** [comment]
+1

**Comment by nebrass** [comment]
I have the same problem :(

**Comment by estherh5** [comment]
I also have this problem.

**Comment by SMillerDev** [comment]
If you're on mojave there is no way not to have this problem. You'll have to wait for #32461

**Comment by fxcoudert** [comment]
Fixed
