### PR TITLE
asn1c 0.9.29

### LINKED ISSUE #131: brew cask install caskroom/cask/brew-cask does not work
I try ''brew install caskroom/cask/brew-cask'' on my OS X 11.04 system. I meet the following problem. I have tried brew update and brew doctor, no warning and no error show up. But I still get the same issue.  What is the problem?

brew cask install caskroom/cask/brew-cask
Error: No available Cask for caskroom/cask/brew-cask
Error: nothing to install

### PR DESCRIPTION
**Pull request by botantony**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## What's Changed

### FEATURES:
  * Added support for basic Information Object Sets driven code generation.
  * Added OER support.
  * Added LTE RRC example (Bi-Ruei, Chiu).
  * Added IEEE 1609.2 example.
  * Added SAE J2735 example.

### NOTABLE:
  * Converter example (included by default):
    * converter-sample.c renamed into converter-example.c
    * make converter-example.mk file for building that converter
    * asn1c -no-gen-example to stop generating converter-example.{c,mk}
  * asn1c -no-gen-example option to disable converter-example generation.
  * Added random value generation (-R option to converter-example).
  * Added LibFuzzer-based randomized tests for supported transfer syntaxes
    (DER, OER, UPER, XER) into tests/tests-randomized. See the following
    article to get the latest LibFuzzer-enabled clang on macOS:
      https://medium.com/@levwalkin/compile-llvm-clang-libfuzzer-b61e82718430
    then ensure the new clang is in the way:
      CC=clang CXX=clang++ ./configure --enable-Werror --enable-test-fuzzer
  * OBJECT IDENTIFIER and RELATIVE-OID API simplified.
  * uper_encode() API got new argument (breaks API compatibility).
  * asn1c -gen-XXX flags are deprecated. Use -no-gen-XXX to disable codecs.

### FIXES IN COMPILER-GENERATED OUTPUT:
  * Fix incomplete (failed) CHOICE XER decoding memory leak.
        (Severity: medium; Security impact: medium)
  * Fix REAL type overwrite conversion memory leak.
        (Severity: low; Security impact: medium)
  * Fix UPER string decoding constrained only by lower bound > 0
        (Severity: low; Security impact: none)
  * Fix UPER decoding of large [bit-]strings of size a multiple of 16K
        (Severity: low; Security impact: none)
  * Fix XER decoder crash on maliciously constructed ENUMERATED input.
        (Severity: medium; Security impact: medium)
  * Fix XER decoder of INTEGER, OBJECT IDENTIFIER, and RELATIVE-OID.
        In some cases an INTEGER overflow during parsing is not detected
        and incorrect value is returned to the decoder instead of an error.
        Reported by Nika Pona <npona@digamma.ai>.
        (Severity: low; Security impact: medium)
  * Fix BER CHOICE decoding infinite loop. Reported by John Bradley (Credex).
        (Severity: high; Security impact: low)

### FIXES IN TOOLING:
  * CVE-2017-12966 verified not present.
  * Fix `unber` buffer overrun. Reported by Eric Sesterhenn.
        (Severity: low; Security impact: high)

## Change Details

* Delete unnecessary checks before some function calls by @elfring in https://github.com/vlm/asn1c/pull/87
* Unify the naming of asn_OCTET_STRING_specifics_t variables by @brchiu in https://github.com/vlm/asn1c/pull/89
* Solve "make check-per" failed on Lubuntu by @brchiu in https://github.com/vlm/asn1c/pull/90
* Fix 'declaration inside parameter list' warning by @brchiu in https://github.com/vlm/asn1c/pull/96
* Windows universal build by @akire in https://github.com/vlm/asn1c/pull/128
* Use wide types to decode x509 certificate in examples, solves #47 by @daa in https://github.com/vlm/asn1c/pull/102
* Fix segmentation fault in asn1c_make_identifier  by @velichkov in https://github.com/vlm/asn1c/pull/104
* Fixed a mistype in man by @theirix in https://github.com/vlm/asn1c/pull/110
* Locate AR using standard macro by @theirix in https://github.com/vlm/asn1c/pull/109
* Refreshing reserved keywords by @gareins in https://github.com/vlm/asn1c/pull/118
* Rewrite the 64bit test. Fixes #131 by @velichkov in https://github.com/vlm/asn1c/pull/132
* Fix many memory leaks reported by valgrind by @brchiu in https://github.com/vlm/asn1c/pull/126
* Fix some memory leakage found till now by @brchiu in https://github.com/vlm/asn1c/pull/153
* Add LTE-RRC example by @brchiu in https://github.com/vlm/asn1c/pull/150
* Skip last comma when there are no extensions by @johvik in https://github.com/vlm/asn1c/pull/145
* Merge PR99 and its fixes to support parsing Information Object and Information Object Set by @brchiu in https://github.com/vlm/asn1c/pull/154
* Fix issue 144 by @brchiu in https://github.com/vlm/asn1c/pull/160
* Fix duplicate 'const' warnings by @johvik in https://github.com/vlm/asn1c/pull/158
* Missing void in _new_stack() by @johvik in https://github.com/vlm/asn1c/pull/157
* Add (void) when st is unused by @johvik in https://github.com/vlm/asn1c/pull/156
* Add const to strings in skeletons/ by @johvik in https://github.com/vlm/asn1c/pull/155
* Fix compile SAE J2735_201603DA.ASN issue by @brchiu in https://github.com/vlm/asn1c/pull/168
* Omit constraints code if -fno-constraints by @mattipee in https://github.com/vlm/asn1c/pull/173
* Fix issue 180 and 182 by @brchiu in https://github.com/vlm/asn1c/pull/184
* Move type operations to another structure by @brchiu in https://github.com/vlm/asn1c/pull/186
* suppress warning in x64 by @DanyaFilatov in https://github.com/vlm/asn1c/pull/203
* Fix some memory leakage and access violation in recent code by @brchiu in https://github.com/vlm/asn1c/pull/208
* Replace MAXFLOAT with FLT_MAX by @ringlej in https://github.com/vlm/asn1c/pull/213
* Fix issue 211 by @brchiu in https://github.com/vlm/asn1c/pull/214
* fix issue #220: implicit declaration of function ‘isatty’ by @ringlej in https://github.com/vlm/asn1c/pull/221
* Do not ignore the test errors in TravisCI by @velichkov in https://github.com/vlm/asn1c/pull/223
* Fix s1ap code generation by @brchiu in https://github.com/vlm/asn1c/pull/224
* Fix duplicate 'asn_VAL_23_ignore' generated from RANAP ASN.1 by @brchiu in https://github.com/vlm/asn1c/pull/227
* Do not build 32bit skeletons lib and check-converter by @velichkov in https://github.com/vlm/asn1c/pull/229
* Add test case for issue #178 by @ringlej in https://github.com/vlm/asn1c/pull/236
* Fix 'make check' error under sample.source.RRC by @brchiu in https://github.com/vlm/asn1c/pull/241
* Fix crash when processing S1AP by @brchiu in https://github.com/vlm/asn1c/pull/244
* Cleanup generated makefiles and make it work better with autotools by @ringlej in https://github.com/vlm/asn1c/pull/245
* Remove static qualifier from var in SET_OF__encode_sorted by @dwd in https://github.com/vlm/asn1c/pull/283
* Modify asn_time2GT_frac to accept 9 digits of fractional seconds by @rkubik in https://github.com/vlm/asn1c/pull/275
* Fix warning : function declaration isn’t a prototype by @brchiu in https://github.com/vlm/asn1c/pull/270
* Fix OCTET_STRING/BIT_STRING skeleton dependency by @jonnystorm in https://github.com/vlm/asn1c/pull/346
* Fix usage cmd in README of examples/sample.source.LDAP3 by @shadansari in https://github.com/vlm/asn1c/pull/349
* Decouple NULL and BOOLEAN by @vlm in https://github.com/vlm/asn1c/pull/386
* fix issue #379 by @robstradling in https://github.com/vlm/asn1c/pull/380
* Update asn1c-usage.tex by @fei4xu in https://github.com/vlm/asn1c/pull/340
* Fix compiler redefinition warnings for __EXTENSIONS__ by @dfranusic in https://github.com/vlm/asn1c/pull/327
* docs: fix simple typo, occured -> occurred by @timgates42 in https://github.com/vlm/asn1c/pull/413
* Improve test coverage for parser and AST testing. by @joluxer in https://github.com/vlm/asn1c/pull/382
* Update ASN1C_ENVIRONMENT_VERSION to v0.9.29 by @kellerkindt in https://github.com/vlm/asn1c/pull/421
* Add SECURITY.md by @vlm in https://github.com/vlm/asn1c/pull/514
* Fix make check by @vlm in https://github.com/vlm/asn1c/pull/517
* Fix BER CHOICE decoding infinite loop on malformed indefinite-length EOC by @vlm in https://github.com/vlm/asn1c/pull/518
* Fix ASan stack-check false positive and 32-bit PER test failure by @vlm in https://github.com/vlm/asn1c/pull/519
* Fix multiple definition of asn_debug_indent in debug builds by @vlm in https://github.com/vlm/asn1c/pull/520
* Detect AddressSanitizer under Clang via __has_feature by @vlm in https://github.com/vlm/asn1c/pull/521
* Fix PER constraint inheritance for type aliases by @vlm in https://github.com/vlm/asn1c/pull/526

## New Contributors
* @elfring made their first contribution in https://github.com/vlm/asn1c/pull/87
* @akire made their first contribution in https://github.com/vlm/asn1c/pull/128
* @daa made their first contribution in https://github.com/vlm/asn1c/pull/102
* @velichkov made their first contribution in https://github.com/vlm/asn1c/pull/104
* @theirix made their first contribution in https://github.com/vlm/asn1c/pull/110
* @gareins made their first contribution in https://github.com/vlm/asn1c/pull/118
* @johvik made their first contribution in https://github.com/vlm/asn1c/pull/145
* @mattipee made their first contribution in https://github.com/vlm/asn1c/pull/173
* @DanyaFilatov made their first contribution in https://github.com/vlm/asn1c/pull/203
* @ringlej made their first contribution in https://github.com/vlm/asn1c/pull/213
* @dwd made their first contribution in https://github.com/vlm/asn1c/pull/283
* @rkubik made their first contribution in https://github.com/vlm/asn1c/pull/275
* @jonnystorm made their first contribution in https://github.com/vlm/asn1c/pull/346
* @shadansari made their first contribution in https://github.com/vlm/asn1c/pull/349
* @vlm made their first contribution in https://github.com/vlm/asn1c/pull/386
* @robstradling made their first contribution in https://github.com/vlm/asn1c/pull/380
* @fei4xu made their first contribution in https://github.com/vlm/asn1c/pull/340
* @dfranusic made their first contribution in https://github.com/vlm/asn1c/pull/327
* @timgates42 made their first contribution in https://github.com/vlm/asn1c/pull/413
* @joluxer made their first contribution in https://github.com/vlm/asn1c/pull/382
* @kellerkindt made their first contribution in https://github.com/vlm/asn1c/pull/421

**Full Changelog**: https://github.com/vlm/asn1c/compare/v0.9.28...v0.9.29</pre>
  <p>View the full release notes at <a href="https://github.com/vlm/asn1c/releases/tag/v0.9.29">https://github.com/vlm/asn1c/releases/tag/v0.9.29</a>.</p>
</details>
<hr>

### CODE REVIEW

**Comment by botantony** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/27943621787/job/82682760589#step:6:1141

**Review by bevanjkay — APPROVED** [review]
