### ISSUE TITLE
Error in 'brew install globus-toolkit'

### ISSUE THREAD

**Issue by kdfred** [Homebrew/homebrew-core#6128]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

$ brew install globus-toolkit
==> Using the sandbox
==> Downloading http://toolkit.globus.org/ftppub/gt6/installers/src/globus_toolkit-6.0.1443479657.tar.gz
Already downloaded: /Users/kurt/Library/Caches/Homebrew/globus-toolkit-6.0.1443479657.tar.gz
==> ./configure --prefix=/usr/local/Cellar/globus-toolkit/6.0.1443479657/libexec --mandir=/usr/local/Cellar/globus-toolkit/6.0.1443479657/share/man
==> make
Last 15 lines from /Users/kurt/Library/Logs/Homebrew/globus-toolkit/02.make:
setproctitle.c:148:17: error: use of undeclared identifier 'VIS_NL'
            VIS_CSTYLE|VIS_NL|VIS_TAB|VIS_OCTAL);
                       ^
setproctitle.c:148:24: error: use of undeclared identifier 'VIS_TAB'
            VIS_CSTYLE|VIS_NL|VIS_TAB|VIS_OCTAL);
                              ^
setproctitle.c:148:32: error: use of undeclared identifier 'VIS_OCTAL'
            VIS_CSTYLE|VIS_NL|VIS_TAB|VIS_OCTAL);
                                      ^
4 errors generated.
make[4]: **\* [setproctitle.o] Error 1
make[3]: **\* [openbsd-compat/libopenbsd-compat.a] Error 2
make[2]: **\* [gsi_openssh-stamp] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

https://gist.github.com/anonymous/28d673b3cbdfe66dc81d6a99b5b9fa7b

**Comment by MikeMcQuaid** [comment]
A known issue unfortunately that this doesn't work on 10.12: https://github.com/Homebrew/homebrew-core/issues/5488

**Comment by ilovezfs** [comment]
@kdfred Should be fixed now if you `brew update`
