### PR TITLE
zig 0.8.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
```make
==> /usr/local/Cellar/zig/0.8.0/bin/zig cc hello.c -o hello
In file included from hello.c:1:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h:64:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:93:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
        unsigned char   *_base;
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may be null
        unsigned char   *_base;
                        ^
                          _Nullable 
```

**Comment by carlocab** [comment]
Looks like this can be bottled for ARM now. Not sure about the Mojave failure, though.

@kubkon is there any chance you could take a look at this? The failing part of the test is from your addition in #77890.

**Comment by kubkon** [comment]
I just wanted to point out, the actual error is the below:

```
In file included from hello.c:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h:224:5: error: 'TARGET_OS_EMBEDDED' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_EMBEDDED
```

Here's the thing: we will try fixing this and include a fix in 0.8.1. However, is it possible to still merge this as-is so that the users of other flavours of macOS and especially arm64 have access to zig 0.8.0?

**Comment by carlocab** [comment]
> However, is it possible to still merge this as-is so that the users of other flavours of macOS and especially arm64 have access to zig 0.8.0?

I'm not opposed to that. It would mean no bottles for Mojave users, though, unless we also modify the test to skip the problematic test on Mojave.

**Comment by kubkon** [comment]
> > However, is it possible to still merge this as-is so that the users of other flavours of macOS and especially arm64 have access to zig 0.8.0?
> 
> I'm not opposed to that. It would mean no bottles for Mojave users, though, unless we also modify the test to skip the problematic test on Mojave.

That sounds good to me. Could you tweak it so that the problematic test case is run on all other flavours @carlocab?

**Review by nandahkrishna — APPROVED** [review]

**Comment by carlocab** [comment]
As an aside, if we're already linking LLVM statically, perhaps it would also be possible to link LLVM's libc++ statically as well? I think that would allow us to make `llvm` a build-only dependency.

Or, if Zig also works with system libc++, that should work too.
