### PR TITLE
fb303 fbthrift fizz folly wangle watchman 2022.08.08.00

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

File: Formula/watchman.rb [hunk 1]
```diff
@@ -1,10 +1,17 @@
...
-  head "https://github.com/facebook/watchman.git", branch: "main"
+
+  stable do
+    url "https://github.com/facebook/watchman/archive/v2022.07.18.00.tar.gz"
+    sha256 "e602bcb49309adc88367d5e24aa9314819b468ec79c8b7986f413bd3ea0d67e6"
+
+    resource "edencommon" do
+      url "https://github.com/facebookexperimental/edencommon.git",
+          revision: "1da3b6542ee1b2634a6108ad84bbc25b7f5785da"
+    end
```
Comment (cho-m) [inline Formula/watchman.rb:13]: No tags/releases. I just went with commit that was close to other `v2022.07.18.00` releases. This particular commit is for file `folly-rev.txt` that matches the `folly` release in this PR.

**Comment by cho-m** [comment]
Anyone know if we can detect if `folly` was built as bottle?

As seen in `rust` PRs (e.g. #98823), if `folly` was built from bottle on Intel (i.e. with flags like `-march=nehalem`), `watchman` also needs to be built with same arch/sse/etc flags.

Not an issue if user uses bottles for both or uses source for both. However, if someone installs `folly` bottle and then tries to install `watchman` from source/head, it may hit an error.

**Comment by carlocab** [comment]
We can check the tab for that I think.

**Comment by cho-m** [comment]
Linux failed to build `folly` due to SSE4.2 code -- https://github.com/facebook/folly/issues/1823

Other formulae failed due to previous topic as `folly` was built from source due to missing bottle and then caused issues mixing with `-march=core2`.

File: Formula/watchman.rb (hunk 1 above)
Comment (carlocab) [reply Formula/watchman.rb:13]: We should ask upstream to cut tags. They're usually pretty willing to do so.

**Comment by carlocab** [comment]
On Catalina:
```
  Undefined symbols for architecture x86_64:
    "folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()", referenced from:
        folly::f14::detail::F14Table<folly::f14::detail::VectorContainerPolicy<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<apache::thrift::AsyncProcessorFactory::MethodMetadata const>, void, void, void, std::__1::integral_constant<bool, true> > >::rehashImpl(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)::'lambda'()::operator()() const in test-d8bfc8.o
  ld: symbol(s) not found for architecture x86_64
```

File: Formula/fb303.rb [hunk 2]
```diff
@@ -51,10 +51,10 @@ def install
         return 0;
       }
     EOS
-    system ENV.cxx, "-std=c++17", "-I#{include}", "-I#{Formula["openssl@1.1"].opt_include}", "test.cpp",
+    system ENV.cxx, *ENV.cxxflags.split, "-std=c++17", "-I#{include}", "-I#{Formula["openssl@1.1"].opt_include}",
```
Comment (carlocab) [inline Formula/fb303.rb:54]: This fixes the test on macOS but breaks it on Linux...

Comment (cho-m) [reply Formula/fb303.rb:54]: `test.cpp` needs to be before the linker flags.

Comment (carlocab) [reply Formula/fb303.rb:55]: Ah right

**Comment by cho-m** [comment]
Actually, based on original Intel macOS error, I think `fb303` test might need to be compiled using `-march=#{Hardware.oldest_cpu}`.

It looks like the errors we see when trying to compile with different `-march`/SSE than what `folly` was originally compiled with.

File: Formula/folly.rb [hunk 3]
```diff
@@ -48,6 +48,9 @@ class Folly < Formula
 
   fails_with gcc: "5"
 
+  # Fix undefined reference to `folly::detail::base64_detail::base64Encode_SSE4_2
+  patch :DATA
```
Comment (cho-m) [inline Formula/folly.rb:52]: Can try upstream's commit https://github.com/facebook/folly/commit/437b29dd062a40c741b2147827025a2f413b76c7 or at least add reference

File: Formula/fb303.rb (hunk 2 above)
Comment (cho-m) [reply Formula/fb303.rb]: Looks like `-march=native` does still cause issues on Linux as there are now other libraries that need to be linked.

Interesting that `ENV.cxxflags` has `-march=nehalem` on macOS. I guess difference in behavior could be from Linux shims like https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/os/linux/extend/ENV/shared.rb#L12

In theory, the more accurate compilation on Linux would be adding same build-time flags too, but excluding them doesn't cause any issues for now.

**Comment by carlocab** [comment]
Note: risk of merge conflict with #105132

File: Formula/fb303.rb (hunk 2 above)
Comment (cho-m) [reply Formula/fb303.rb]: Looks like issue isn't just `-march=native` (which does break `folly` linkage) but also `-Os` optimization.

If we want to leave that, then can try adding `-lthriftcpp2`.

**Comment by cho-m** [comment]
Noting that `folly` is not going to build in `2022.07.25.00`.

I commented on build problems in https://github.com/facebook/folly/issues/1823, which is due to some incorrect CMake logic.

File: Formula/folly.rb [hunk 4]
```diff
@@ -90,3 +95,25 @@ def install
...
++#if FOLLY_X64 && FOLLY_SSE_PREREQ(4, 2)
+ #include <folly/detail/base64_detail/Base64_SSE4_2.h>
+ #endif
+ 
+ namespace folly::detail::base64_detail {
+ 
+-#if FOLLY_X64
++#if FOLLY_X64 && FOLLY_SSE_PREREQ(4, 2)
+ Base64RuntimeImpl base64EncodeSelectImplementation() {
+   if (folly::CpuId().sse42()) {
```
Comment (cho-m) [inline Formula/folly.rb:118]: I wonder if `folly` has CPU runtime detection if we build with SSE4.2/AVX support.

Comment (cho-m) [reply Formula/folly.rb:118]: I do see similar runtime detection code in other files like 

https://github.com/facebook/folly/blob/v2022.07.25.00/folly/hash/Checksum.cpp#L67-L75
```cpp
bool crc32c_hw_supported() {
  static folly::CpuId id;
  return id.sse42();
}

bool crc32_hw_supported() {
  static folly::CpuId id;
  return id.sse42();
}
```

https://github.com/facebook/folly/blob/v2022.07.25.00/folly/experimental/crypto/LtHash.cpp#L62-L76
```cpp
// static
template <>
bool MathOperation<MathEngine::SSE2>::isAvailable() {
  static const bool kIsAvailable =
      CpuId().sse2() && MathOperation<MathEngine::SSE2>::isImplemented();
  return kIsAvailable;
}

// static
template <>
bool MathOperation<MathEngine::AVX2>::isAvailable() {
  static const bool kIsAvailable =
      CpuId().avx2() && MathOperation<MathEngine::AVX2>::isImplemented();
  return kIsAvailable;
}
```

So, the initial macros like `FOLLY_SSE_PREREQ(4, 2)`, `__SSE2__`, `__AVX2__` may be for host compilation support while SSE/AVX may be detected at runtime.

Comment (carlocab) [reply Formula/folly.rb:118]: Did folly use your patch? They may not be willing to look at patches posted in comments since they technically need a CLA to use contributed code.

Comment (cho-m) [reply Formula/folly.rb:118]: They added a more extensive fix https://github.com/facebook/folly/commit/437b29dd062a40c741b2147827025a2f413b76c7, which is available in next release, but CMake logic is currently broken as upstream reversed x86_64 vs non-x86_64 logic https://github.com/facebook/folly/commit/9d6acb35763d329d3fd6f4223ebf134f03e65d15.

We could update to `2022.07.25.00`, patch the CMake logic, and potentially add `ENV.runtime_cpu_detection`.

Not sure what is output if we try to compile with both `-march=core2` and `-msse4.2` on Linux (I think the `-mavx` code is skipped since we don't add `libsodium` dependency).

Comment (carlocab) [reply Formula/folly.rb:118]: `-march=core2` is only an alias for the lower level flags (e.g. `-mmmx`, `-msse`, etc), so the compiler should handle it fine. But adding `-msse4.2` is almost equivalent to setting `-march=nehalem`, I think.

**Comment by cho-m** [comment]
`wangle` test failed on Linux (specifically from `folly` header):
```
  /home/linuxbrew/.linuxbrew/Cellar/wangle/2022.08.08.00/share/wangle/EchoServer.cpp:20:
  /home/linuxbrew/.linuxbrew/include/folly/Random.h:374:53: error: exponent has no digits
    374 |     return (rand64(std::forward<RNG>(rng)) >> 11) * 0x1.0p-53;
        |                                                     ^~~~~~
  Error: wangle: failed
```

File: Formula/folly.rb [hunk 5]
```diff
@@ -51,7 +60,8 @@ class Folly < Formula
   def install
     ENV.llvm_clang if OS.mac? && (DevelopmentTools.clang_build_version <= 1100)
 
-    args = std_cmake_args + %w[
+    args = std_cmake_args + %W[
+      -DCMAKE_LIBRARY_ARCHITECTURE=#{Hardware::CPU.arch}
```
Comment (carlocab) [inline Formula/folly.rb:64]: What does this do, exactly? The [documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_ARCHITECTURE.html) doesn't say too much.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
I think watchman can be [switched to `pcre2`](https://github.com/facebook/watchman/commit/3ce6c9baa08c240d90937c85dae2afc6ad010bc8). But let's do it in a follow-up to save on CI time.

File: Formula/folly.rb (hunk 5 above)
Comment (cho-m) [reply Formula/folly.rb:64]: I don't think it does anything meaningful via CMake, but not entirely sure.

It gets set on OS like Debian that use `/usr/lib/x86_64-linux-gnu` directories.

The problem is `folly` automatically assumes x86_64 if `CMAKE_LIBRARY_ARCHITECTURE` is not set.

**Comment by cho-m** [comment]
> I think watchman can be [switched to `pcre2`](https://github.com/facebook/watchman/commit/3ce6c9baa08c240d90937c85dae2afc6ad010bc8). But let's do it in a follow-up to save on CI time.

Forgot to check on dependencies after re-bumping. Couple days until next weekly release (`2022.08.15.00`) so could handle there.

**Comment by carlocab** [comment]
It no longer links to `pcre` so could be broken for some users. #107971
