### ISSUE TITLE
Formulae without Sierra bottles

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew-core#5488]
Jenkins finally managed to chew through the daunting Sierra build queue. Below are the remaining ones that defied (not necessarily only) Sierra for one reason or another.

The list is generated with the script https://gist.github.com/zmwangx/89f07670c8e42f58434bd6d15653ecf6. You can also pass a blacklist to the script to get a more workable list (e.g., putting `qt` and `qt5` in the blacklist blocks the entire Qt tree). See `need-bottle -h`.

---

Formulae that made the top 5000 install events chart during September 2016, ordered by popularity:

- [x] qt5
- [x] xctool (https://github.com/facebook/xctool/issues/716)
- [ ] swiftlint (swift 2.2, https://github.com/realm/SwiftLint/issues/815)
- [x] pypy ([upstream issue](https://bitbucket.org/pypy/pypy/issues/2407/pypy-541-fails-to-build-on-macos-sierra), #5689)
- [ ] pyqt (qt, #1705)
- [x] pyqt5
- [x] qscintilla2 (https://github.com/Homebrew/homebrew-core/pull/5786)
- [ ] swiftgen (swift 2.2, https://github.com/AliSoftware/SwiftGen/issues/169)
- [x] qwt
- [x] allegro (#6017)
- [x] pyside
- [x] shiboken
- [x] gnuradio
- [x] upx (#6264, https://sourceforge.net/p/upx/bugs/248/, https://github.com/upx/upx/issues/4)
- [ ] infer (need to wait for 0.9.4 according to #5130)
- [x] jack (#5487)
- [x] qca
- [x] qwtpolar
- [x] binwalk
- [x] git-cola (#6210)
- [x] folly (#5548)
- [x] gpsbabel
- [x] qcachegrind
- [x] radare2
- [x] libewf (libyal/libewf#60, #5737)
- [x] dvm (#5587)
- [x] irrlicht (#5592)
- [x] tcptrace (#6223)
- [ ] imagesnap (project dead since 2011, but 10.11 bottle works on 10.12 unmodified)
- [x] uwsgi (https://github.com/Homebrew/homebrew-core/pull/5528)
- [x] log4cxx
- [ ] capnp (#5773, https://github.com/sandstorm-io/capnproto/issues/375)
- [ ] swift (need to upgrade to 3.0)
- [ ] fb-adb (has [newer release](https://github.com/facebook/fb-adb/releases/tag/2.0.0), which unfortunately [requires dupes/make](https://github.com/facebook/fb-adb/tree/2.0.0#building))
- [x] fpc (#5732)
- [ ] ctorrent (redefinition of `clockid_t`)
- [x] syncthing-inotify
- [ ] pgloader (has [newer release](https://github.com/dimitri/pgloader/releases/tag/v3.3.1), updating resources seems to be a royal pain though)
- [ ] volatility (Pillow problem, complexity of [homebrew/python/pillow](https://github.com/Homebrew/homebrew-python/blob/master/pillow.rb) isn't confidence-inspiring; I wonder if Pillow is really needed, not immediately obvious)
- [ ] libqglviewer (qt, #1705)
- [x] sift (https://github.com/svent/sift/pull/80)
- [x] shairport-sync
- [x] pyside-tools
- [ ] otto (go 1.7+:`-X flag requires argument of the form importpath.name`)
- [x] ace
- [ ] ircii (#6404)
- [ ] juju (#5911)
- [x] dcmtk
- [ ] io (seems good to go)
- [ ] xml2 (#6405)
- [ ] tomcat-native (`apr` problem)
- [x] moc
- [x] natalie
- [ ] open-zwave (broken dylib link in build path)
- [ ] rack (https://github.com/rackspace/rack/issues/446, go 1.7+:`-X flag requires argument of the form importpath.name`)
- [x] codequery
- [x] zurl
- [ ] libgroove (redefinition of `clockid_t` and `clock_gettime`)
- [x] opencsg
- [x] kube-aws
- [x] libmongoclient
- [ ] shibboleth-sp
- [ ] bashdb (#6407)
- [x] bokken
- [x] castxml
- [ ] vice (references `QuickTime/QuickTime.h`)
- [x] debianutils
- [ ] taylor (swift 2.2)
- [ ] distcc (migrated from Google Code to https://github.com/distcc/distcc, but no new release)
- [x] darkice
- [x] pushpin
- [x] gsoap
- [ ] dc3dd (seems good to go)
- [x] sqliteman
- [x] aurora-cli (#6006)
- [x] djview4 (https://github.com/Homebrew/homebrew-core/pull/5736)
- [ ] gecode (qt5, maybe good to go)
- [ ] libfaketime (clock issue, code assumes `CLOCK_REALTIME` undefined on macOS, masking `#include <mach/clock.h>`)
- [x] frescobaldi
- [ ] libbtbb (#6401)
- [x] qjackctl
- [ ] chuck (appear to be having trouble linking `/System/Library/PrivateFrameworks/MultitouchSupport.framework` properly)
- [ ] dshb (https://github.com/beltex/dshb/issues/36)
- [x] puddletag
- [ ] libbladerf (redefinition of `clockid_t`)
- [ ] qjson (qt, #1705)
- [x] ssdb (ideawu/ssdb#995, #5734)
- [x] dspdfviewer
- [x] st
- [ ] coin (qt, #1705)
- [x] mftrace
- [ ] darkstat (redefinition of `clockid_t`)
- [ ] makepkg (#6402)
- [ ] aws-apigateway-importer (#6403)
- [x] cfengine (https://github.com/Homebrew/homebrew-core/pull/5513)
- [ ] fstar (those ocaml resources are causing conflicts and a lot of pain, and ocaml install can choose to ignore your cached downloads anyway; should just admit resources aren't good for everything, and let the package manager do the heavylifting.)

---

Obscure formulae that didn't make the top 5000 install events chart (some of these need to be thrown into boneyard — no mercy for the weak):

- [ ] activemq-cpp
- [ ] aiccu
- [x] automoc4
- [ ] blucat
- [ ] buildapp
- [ ] bzr-explorer
- [ ] coccinelle
- [ ] compface
- [x] ctail
- [x] cuty_capt
- [x] dirt
- [ ] dsd
- [ ] exim
- [ ] ezlupdate
- [x] fastd ([upstream issue](https://projects.universe-factory.net/issues/239), #6012)
- [ ] fdroidserver
- [x] gammaray
- [ ] globus-toolkit
- [ ] intercal
- [ ] ipbt
- [ ] ironcli
- [ ] jxrlib
- [ ] libechonest
- [ ] libetonyek
- [ ] libfabric
- [ ] liblastfm
- [ ] libodfgen
- [x] ltc-tools
- [x] md
- [ ] mdds
- [ ] mighttpd2
- [ ] mimms
- [ ] mmix
- [ ] nordugrid-arc
- [ ] openvdb
- [ ] parrot
- [x] qbs
- [ ] qpm
- [ ] qtplay
- [ ] quazip
- [ ] qxmpp
- [x] rcssserver
- [ ] rdate
- [x] remctl
- [ ] saldl
- [ ] schismtracker
- [ ] sfk
- [ ] snappystream
- [ ] srclib
- [ ] swish-e
- [ ] tbox
- [ ] tevent
- [ ] tlassemble
- [ ] uberftp
- [ ] ubertooth
- [x] valkyrie
- [x] weboob
- [ ] writerperfect
- [ ] wyrd
- [ ] xar-mackyle

**Comment by zmwangx** [comment]
I've ordered the list by popularity so hopefully the priority is clearer now.

**Comment by iMichka** [comment]
Hi. Just to let you know that castxml was updated and has now Sierra bottles :)

**Comment by ilovezfs** [comment]
@iMichka thanks

**Comment by Moisan** [comment]
Folly issue is known: #5426.

**Comment by ilovezfs** [comment]
@Moisan yup, and I've got a fix :)

**Comment by Moisan** [comment]
`io` builds into a bottle with no issue on my side.

**Comment by ilovezfs** [comment]
@Moisan I see this
```
[ 41%] Linking C shared library _build/dll/libIoAppleSensors.dylib
cd /tmp/io-20161003-34714-easan8/io-2015.11.11/buildroot/addons/AppleSensors && /usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/IoAppleSensors.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang  -fobjc-exceptions  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -dynamiclib -Wl,-headerpad_max_install_names  -flat_namespace -o _build/dll/libIoAppleSensors.dylib -install_name /tmp/io-20161003-34714-easan8/io-2015.11.11/buildroot/addons/AppleSensors/_build/dll/libIoAppleSensors.dylib CMakeFiles/IoAppleSensors.dir/source/IoAppleSensors.c.o CMakeFiles/IoAppleSensors.dir/source/AppleSMC.c.o CMakeFiles/IoAppleSensors.dir/source/AppleLMU.c.o CMakeFiles/IoAppleSensors.dir/source/unimotion.c.o CMakeFiles/IoAppleSensors.dir/source/IoAppleSensorsInit.c.o ../../_build/dll/libiovmall.dylib -framework IOKit ../../_build/dll/libcoroutine.dylib ../../_build/dll/libgarbagecollector.dylib ../../_build/dll/libbasekit.dylib -ldl 
Undefined symbols for architecture x86_64:
  "_CFGetTypeID", referenced from:
      _getPrefDouble in unimotion.c.o
  "_CFNumberGetTypeID", referenced from:
      _getPrefDouble in unimotion.c.o
  "_CFNumberGetValue", referenced from:
      _getPrefDouble in unimotion.c.o
  "_CFNumberIsFloatType", referenced from:
      _getPrefDouble in unimotion.c.o
  "_CFPreferencesCopyAppValue", referenced from:
      _getPrefDouble in unimotion.c.o
  "_CFPreferencesGetAppIntegerValue", referenced from:
      _read_sms in unimotion.c.o
      _read_sms_real in unimotion.c.o
  "_CFRelease", referenced from:
      _getPrefDouble in unimotion.c.o
  "___CFConstantStringClassReference", referenced from:
      CFString in AppleLMU.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [addons/AppleSensors/_build/dll/libIoAppleSensors.dylib] Error 1
make[1]: *** [addons/AppleSensors/CMakeFiles/IoAppleSensors.dir/all] Error 2
make: *** [all] Error 2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by ilovezfs** [comment]
@Moisan same output on Jenkins as I see locally for `io`: https://bot.brew.sh/job/Homebrew%20Testing/1139/version=sierra/console

Perhaps you know what's different in your environment?

**Comment by Moisan** [comment]
My bad, I get similar issues now.

**Comment by dunn** [comment]
Replacing libewf url with Debian sources in https://github.com/Homebrew/homebrew-core/pull/5737.

**Comment by joachimmetz** [comment]
FYI I put the official package here: https://github.com/libyal/legacy/tree/master/libewf

**Comment by dunn** [comment]
Oh, thanks!  If you tag a release on GitHub you can also add those files as attachments to the release.

**Comment by joachimmetz** [comment]
I know but this is a legacy release predating a move to github.

**Comment by leee** [comment]
@zmwangx - do you intend on updating this list(s) as Formula items get updated? (c.f. #5776)

**Comment by zmwangx** [comment]
@leee Maintainers should check off items directly.

For non-maintainers: if you notice something that should be checked off but hasn't been, please leave a comment, and I (or another maintainer) will get to it. Thanks.

**Comment by thinker0** [comment]
#6006

**Comment by Eitot** [comment]
@zmwangx: `gpsbabel` #5960

**Comment by Moisan** [comment]
`sift` depend on this [PR upstream](https://github.com/svent/sift/pull/80)

**Comment by Moisan** [comment]
The issue that breaks `rack` is [known upstream](https://github.com/rackspace/rack/issues/446)

**Comment by Moisan** [comment]
`bokken` depends on `radare2` which is now fixed. It seems to build correctly now.

**Comment by Moisan** [comment]
`gsoap` and `dcmtk` are fixed.

**Comment by zmwangx** [comment]
@ilovezfs I've added a reason or potential solution for every reasonably popular formula (just can't get excited about the rest of them).

`dc3dd` and `io` seem to be compiling fine now, should try them out on Sierra Testing; `gecode` is a Qt5 revdep, maybe good to go, not sure because I don't want to install Qt.

A bunch of clock-redefinition should be easy to fix, will leave that to you so that the replaced gibberish is consistent across the code base.

There might be other low hanging fruits which I forgot to mention.

**Comment by ilovezfs** [comment]
@zmwangx #6408

**Comment by ilovezfs** [comment]
Anyone who has been following or contributing to this issue, please use #6408 from now on.
