### PR TITLE
efl 1.20.2

### PR DESCRIPTION
**Pull request by jeanguyomarch**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
Failing to build on all platforms: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/847/

**Comment by jeanguyomarch** [comment]
Hi, thanks for the notice. I can see that the `brew test` fail in at least two builds. It is likely to also fail for the third one, and this is my fault. I'll fix that.

However, I'm puzzled by the issue of the El Capitan (10.11) build (https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/847/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_efl/)

EFL 1.19.0 uses the unfair lock API (https://developer.apple.com/reference/os/1646466-os_unfair_lock_lock?language=objc) introduced in 10.12 (Sierra), which causes a link issue:

```
dyld: Symbol not found: _os_unfair_lock_lock
  Referenced from: /private/tmp/efl-20170504-10135-vwao0p/efl-1.19.0/src/lib/eina/.libs/libeina.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

We make sure however that when `__MAC_10_12` is not defined, we fallback on the previous OSSpinLock API. This works fine with the Yosemite build (10.10), so I'm not sure of why this is going wrong, as this is the first occurence of this issue. By looking at the configuration of your El Capitan build slave, I see the following:

```
MACOSX_DEPLOYMENT_TARGET: 10.11
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
```
Is this normal to mention a 10.12 sdk on the 10.11 buildbot? I'm not sure to understand what actually happens, but I have the feeling that `__MAC_10_12` is defined (because of the SDKROOT?), and this causes the symbol to be undefined.

Thanks.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/pull/6625

**Comment by fxcoudert** [comment]
Try to replace the checks on `__MAC_10_12 ` by `__MAC_OS_X_VERSION_MIN_REQUIRED >= 1012 `

**Comment by jeanguyomarch** [comment]
Hi,

sorry for the huge delay. Thanks @fxcoudert for your suggestion, it seems indeed to be the way to go. How can I be sure that this change effectively fixes the build issues on the CI? Is there a way to test that before integrating the changes upstream?

Also, since EFL 1.20 should be released in a close future, so I wonder if this PR should be abandoned (for a new one to be created) or re-cycled for the future 1.20?

**Comment by ilovezfs** [comment]
>How can I be sure that this change effectively fixes the build issues on the CI?

You can use a `patch do` block.

>Also, since EFL 1.20 should be released in a close future, so I wonder if this PR should be abandoned (for a new one to be created) or re-cycled for the future 1.20?

You can just refresh this one.

**Comment by jeanguyomarch** [comment]
Okay thanks, EFL 1.20 will have the changes as proposed by @fxcoudert. I'll then just update this PR when EFL 1.20 will be out. Hopefully, I won't need to use `patch do`.

**Comment by jeanguyomarch** [comment]
(commenting to remove the stale label) efl 1.20 has not yet been released (still in rc)

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @jeanguyomarch!
