### ISSUE TITLE
imagemagick 6.9.5-1 fails to compile on OS X 10.11.5

### ISSUE THREAD

**Issue by jonnybarnes** [Homebrew/homebrew-core#2932]
https://gist.github.com/jonnybarnes/79387baeac3da1fed59e24af79d77b49

**Comment by dunn** [comment]
It's failing to find libltdl, which is part of libtool: https://gist.github.com/jonnybarnes/79387baeac3da1fed59e24af79d77b49#file-01-configure-L1-L585

OSX ships with an older libtool, which apparently doesn't include it:
```
🔥  locate ltdl
/Applications/Oracle Calendar.app/Contents/Frameworks/libltdl.7.dylib
/Applications/Oracle Calendar.app/Contents/Frameworks/libltdl.dylib
/Applications/Paint.app/Contents/Frameworks/libltdl.7.dylib
/Applications/Paint.app/Contents/Frameworks/libltdl.dylib
/usr/local/Cellar/libtool/2.4.6/include/libltdl
/usr/local/Cellar/libtool/2.4.6/include/libltdl/lt_dlloader.h
/usr/local/Cellar/libtool/2.4.6/include/libltdl/lt_error.h
/usr/local/Cellar/libtool/2.4.6/include/libltdl/lt_system.h
/usr/local/Cellar/libtool/2.4.6/include/ltdl.h
/usr/local/Cellar/libtool/2.4.6/lib/libltdl.7.dylib
/usr/local/Cellar/libtool/2.4.6/lib/libltdl.a
/usr/local/Cellar/libtool/2.4.6/lib/libltdl.dylib
/usr/local/Cellar/libtool/2.4.6/share/aclocal/ltdl.m4
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt__alloc.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt__argz_.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt__dirent.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt__glibc.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt__private.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt__strl.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt_dlloader.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt_error.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/lt_system.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/libltdl/slist.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/ltdl.c
/usr/local/Cellar/libtool/2.4.6/share/libtool/ltdl.h
/usr/local/Cellar/libtool/2.4.6/share/libtool/ltdl.mk
/usr/local/include/libltdl
/usr/local/include/ltdl.h
/usr/local/lib/libltdl.7.dylib
/usr/local/lib/libltdl.a
/usr/local/lib/libltdl.dylib
/usr/local/share/aclocal/ltdl.m4
```
Can you try `brew install libtool` and test it again?

**Comment by jterk** [comment]
@dunn imagemagick lists `libtool` as a dependency.

**Comment by jterk** [comment]
```
$ brew info imagemagick
imagemagick: stable 6.9.5-1, HEAD
Tools and libraries to manipulate images in many formats
https://www.imagemagick.org/
/opt/boxen/homebrew/Cellar/imagemagick/6.9.5-1 (1,464 files, 22.4M) *
  Built from source on 2016-07-11 at 08:44:55
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/imagemagick.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: xz ✔, libtool ✔
Recommended: jpeg ✔, libpng ✔, libtiff ✔, freetype ✔
Optional: fontconfig ✘, little-cms ✘, little-cms2 ✘, libwmf ✘, librsvg ✘, liblqr ✘, openexr ✘, ghostscript ✘, webp ✘, fftw ✘, pango ✘
```

**Comment by dunn** [comment]
Woops, should have checked first.

Not quite sure what's going on, then.

**Comment by henderea** [comment]
I'm getting the exact same issue, and I'm also on 10.11.5.  I tried re-installing libtool and trying imagemagick again, and it still didn't work.

Is it possible that the issue is due to homebrew installing `libtool` as `glibtool`?

**Comment by romellem** [comment]
I am getting the same thing on 10.10.5.

 ```
checking for libltdl... 
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... no
checking if libltdl package is complete... no -- some components failed test
configure: error: in `/private/tmp/imagemagick-20160712-98613-1g6qujt/ImageMagick-6.9.5-1':
configure: error: libltdl is required for modules build
```

**Comment by ihgann** [comment]
Just getting this error today as well; it's breaking my brewfile unfortunately.

**Comment by jeroenooms** [comment]
Some problem on mavericks.

**Comment by DomT4** [comment]
The code for that check has been around for _years_, and we've seen very occasional similar reports in the past such as [here](https://github.com/Homebrew/legacy-homebrew/issues/47879), but I can't remember it ever persistently blowing up until now.

Looking at the upstream commits between the last release & the most current one I'm not seeing any tweaks to the `lt_dlinit` check in that time. The two obvious hacks to restore build success are `--disable-shared` & `--disable-modules`, but neither are especially desirable.

`nm` confirms that blob is in both `libtool`'s static & dynamic library:
```
~> nm -UA libltdl.a | grep lt_dlinit
libltdl.a:libltdl_libltdl_la-ltdl.o: 0000000000000017 T _lt_dlinit

~> nm -UA libltdl.7.dylib | grep lt_dlinit
libltdl.7.dylib: 0000000000001e51 T _lt_dlinit
```

**Comment by jeroenooms** [comment]
@DomT4 Actually I am seeing the same problem and I build with:

```
      --disable-shared
      --enable-static
      --without-modules
```

This was all working until yesterday.

**Comment by DomT4** [comment]
@jeroenooms I can't reproduce with either:
```ruby
    args = %W[
      --disable-osx-universal-binary
      --prefix=#{prefix}
      --disable-dependency-tracking
      --disable-silent-rules
      --disable-shared
      --enable-static
      --with-modules
    ]
```

Or:
```ruby
    args = %W[
      --disable-osx-universal-binary
      --prefix=#{prefix}
      --disable-dependency-tracking
      --disable-silent-rules
      --enable-shared
      --enable-static
      --without-modules
    ]
```

**Comment by DomT4** [comment]
This seems to perhaps be a problem with newer Clangs on OS X, IMO.

If you add `fails_with :clang` to `imagemagick` all the problems go away for me locally, and the only OS X version consistently passing CI for https://github.com/Homebrew/homebrew-core/pull/2935 is Mavericks.

```
checking for libltdl...
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... yes
checking if libltdl package is complete... yes
```

**Comment by mikestecker** [comment]
Getting the same error on 10.12 Beta (16A239j)

**Comment by jeroenooms** [comment]
I think it is related to `libjpeg`. Even when building with `--disable-shared --without-modules` the jpeg encoder is suddenly broken

**Comment by anmonteiro** [comment]
building with `without-modules` works for me in macOS 10.12 beta

**Comment by DomT4** [comment]
I think this was problem with refactoring of our environment wrapper in https://github.com/Homebrew/brew/commit/0d189fae57bad6c209b471eba9e0b254a2b40886 rather than `imagemagick` itself. I've fixed the oversight in https://github.com/Homebrew/brew/commit/bd4e24ae8.

Can people `brew update` & try again?

**Comment by zmwangx** [comment]
#2935 passes, so let's call it fixed.

**Comment by calebj0seph** [comment]
I'm still getting the following error when building with `--with-quantum-depth-32 --with-hdri`:
```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I./config -I. -I. -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=32 -I/usr/include/libxml2 -I/usr/local/Cellar/libpng/1.6.23/include/libpng16 -I/usr/local/Cellar/xz/5.2.2/include -I/usr/local/Cellar/freetype/2.6.5/include/freetype2 -g -O2 -Wall -mtune=haswell -fexceptions -D_FORTIFY_SOURCE=0 -D_THREAD_SAFE -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=32 -c coders/mpr.c -o coders/coders_mpr_la-mpr.o >/dev/null 2>&1
coders/msl.c:101:12: fatal error: 'libxml/parser.h' file not found
#  include <libxml/parser.h>
           ^
1 error generated.
make[1]: *** [coders/coders_msl_la-msl.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2
```

Is a libxml2 dependency missing?

**Comment by anomaly256** [comment]
Still seeing it on 10.12 Beta despite #2935.
I know 10.12 isn't 'supported' yet, just noting it

**Comment by zmwangx** [comment]
@calebj0seph @anomaly256 I can't reproduce (not on a clean 10.12 PB1 install with Xcode and CLT). Could you provide the output of `brew config` and `ls /usr/include/libxml2/libxml`? @calebj0seph Your `clang` invocation clearly has `-I/usr/include/libxml2` so I can't fathom how `libxml/parser.h` could be missing. Maybe `libxml2` is only available when Xcode is installed, while you only have CLT?

Anyway, this should be a separate issue, since the original issue regarding `libltdl` has already been fixed by @DomT4.

**Comment by MikeMcQuaid** [comment]
> Anyway, this should be a separate issue, since the original issue regarding libltdl has already been fixed by @DomT4.

Closing based on this, thanks folks.

**Comment by anmonteiro** [comment]
I can confirm the fix by @DomT4 works on macOS 10.12 PB1

I do have Xcode-beta installed and CLT
@anomaly256 Probaby best to make sure to run `xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer/`

**Comment by anomaly256** [comment]
Thanks @anmonteiro but I had already ran that.  I had not however re-ran xcode-select --install, which appears to have done the trick.
