### PR TITLE
fastbit 2.0.3

### PR DESCRIPTION
**Pull request by fxcoudert**
Maybe the latest version will build on 10.13? https://github.com/Homebrew/homebrew-core/issues/18493

### CODE REVIEW

**Comment by ilovezfs** [comment]
@fxcoudert did apple remove flex or something?

**Comment by ilovezfs** [comment]
```
Error: 1 problem in 1 formula
fastbit:
  * HEAD: The URL https://codeforge.lbl.gov/anonscm/fastbit/trunk is not a valid svn URL
```

```
checking if the default FlexLexer.h defines yywrap... configure: error: no, must have FlexLexer.h to continue
```

**Comment by fxcoudert** [comment]
```
$ find /usr/include -name FlexLexer.h  
$ find /Applications/Xcode.app/Contents/Developer -name FlexLexer.h 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/FlexLexer.h
```

**Comment by ilovezfs** [comment]
`config.log` has some interesting errors like
```
src/array_t.h:70:18: error: ordered comparison between pointer and zero ('unsigned long long *' and 'int')
        return (m_begin > 0 && m_end > m_begin ? m_end - m_begin : 0);
                ~~~~~~~ ^ ~
src/qExpr.h:481:52: note: in instantiation of member function 'ibis::array_t<unsigned long long>::size' requested here
    virtual uint32_t nItems() const {return values.size();}
                                                   ^
3 errors generated.
```
