### PR TITLE
uhd 4.1.0.1

### PR DESCRIPTION
**Pull request by orf**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Revision bump needed for gnuradio
```
 ==> brew linkage --test gnuradio
==> FAILED
Broken dependencies:
  /usr/local/opt/uhd/lib/libuhd.4.0.0.dylib (uhd)
```

**Comment by bayandin** [comment]
```
/tmp/gnuradio-20210804-8720-5648c0/gnuradio-3.9.2.0/gr-qtgui/lib/../include/gnuradio/qtgui/DisplayPlot.h:32:10: fatal error: 'qwt_compat.h' file not found
#include <qwt_compat.h>
         ^~~~~~~~~~~~~~
```

`gnuradio` doesn't build with `qwt` 6.2.0: https://github.com/gnuradio/gnuradio/issues/4956
