### ISSUE TITLE
pyside@2 depends upon python3.10 but its cmake config finds python3.11 when present

### ISSUE THREAD

**Issue by wrohv** [Homebrew/homebrew-core#126374]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ % brew config
HOMEBREW_VERSION: 4.0.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 584588afb4ab557bcc0536f2794b4d043c333bb9
Last commit: 2 days ago
Core tap JSON: 22 Mar 16:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 5
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 5-core 64-bit dunno
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
~ % brew doctor
Your system is ready to brew.
~ %
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to build custom PySide bindings for a c++ project.

### What happened (include all command output)?

All PySide bindings configured via cmake fail to build with error messages like:

```
/opt/homebrew/opt/pyside@2/include/shiboken2/pep384impl.h:337:3: error: Please check the buffer compatibility for this python version!
# error Please check the buffer compatibility for this python version!
```

If we look inside that file, it shows that the highest compatible python version is 3.10.x:
```
#define PYTHON_BUFFER_VERSION_COMPATIBLE    (PY_VERSION_HEX >= 0x03030000 && \
                                             PY_VERSION_HEX <  0x030AFFFF)
#if !PYTHON_BUFFER_VERSION_COMPATIBLE
# error Please check the buffer compatibility for this python version!
#endif
```

### What did you expect to happen?

I expect that PySide will link to Python@3.10 in a cmake-enabled project. The formula builds correctly with python@3.10, but then the Pyside/Shiboken cmake config finds Python@3.11 if it exists.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I have reproduced this in a clean macOS/parallels vm. My steps were:


~ % brew install pyside@2 python@3.11 cmake
~ % mkdir foo
~ % cd foo
foo % echo "cmake_minimum_required(VERSION 3.26)" > CMakeLists.txt
foo % echo "project(foo)" >> CMakeLists.txt                       
foo % echo "find_package(Shiboken2 PATHS /opt/homebrew/opt/pyside@2/)" >> CMakeLists.txt 
foo % mkdir build
foo % cd build
build % cmake ..
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shiboken2Config: Using default python: .abi3
-- Found PythonInterp: /opt/homebrew/bin/python3 (found suitable version "3.11.2", minimum required is "3") 
-- Found PythonLibs: /opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib (found suitable version "3.11.2", minimum required is "3") 
-- SHIBOKEN_PYTHON_INCLUDE_DIRS computed to value: '/opt/homebrew/Frameworks/Python.framework/Versions/3.11/include/python3.11'
-- SHIBOKEN_PYTHON_LIBRARIES computed to value: '-undefined dynamic_lookup'
-- libshiboken built for Release
-- Configuring done (2.3s)
-- Generating done (0.0s)
-- Build files have been written to: ~/foo/build
```

This gets as far as showing that CMake is configuring python@3.11. I could go further with the steps to get the compile error, but I think it's clear given the above snippet from `pep384impl.h`.

I don't know what a proper solution would look like, but I have found a workaround that solves my problem. If I modify the installed file `/opt/homebrew/Cellar/pyside@2/5.15.8/lib/cmake/Shiboken2-5.15.8/Shiboken2Config.abi3.cmake` changing this line:

```
    shiboken_find_required_python(3)
```

to this:

```
    shiboken_find_required_python(3.10)
```

then CMake correctly finds python@3.10 and my bindings compile correctly.
```

**Comment by carlocab** [comment]
This seems like an upstream issue, as we don't touch the CMake config files. As an alternative workaround, it may be enough to invoke CMake with
```
-DPYTHON_EXECUTABLE=python3.10
```

**Comment by wrohv** [comment]
That alternative workaround works for me too. Neither one is ideal, but I should be able to limp forward with these. I did some digging upstream and apparently PYSIDE-1960 resolved this issue for pyside@6 by removing the buffer constraint to python <= 3.10.x. I'm doubting there will be much enthusiasm for porting that fix back to pyside2 but we can always hope.

Anyway feel free to close this as out of scope. Thanks.

**Comment by carlocab** [comment]
Not sure there's much we ought to do here at this point, I think. We'll consider applying a fix in the formula if there are more complaints about it.
