### ISSUE TITLE
MacVim fails to build on macOS Mojave 10.14 beta 10 (18A384a) with XCode-beta 10.0 beta 6 (10L232m)

### ISSUE THREAD

**Issue by emilyst** [Homebrew/homebrew-core#31917]
I attempted to install MacVim from source using Homebrew. I am running macOS Mojave 10.14 beta 10 (18A384a) with XCode-beta 10.0 beta 6 (10L232m) installed.

I used the command `brew install macvim --with-override-system-vim`. This downloaded the source code for the latest MacVim snapshot and proceeded to attempt to build it from source. This subsequently failed.

Excerpting from the build log, `02.make`, I found the following compilation error.

```
CompileC /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/Objects-normal/x86_64/MMCoreTextView.o /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/MMCoreTextView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: MacVim)
    cd /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim
    export LANG=en_US.US-ASCII
    clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -Os -mdynamic-no-pic -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DOBJC_OLD_DISPATCH_PROTOTYPES=1 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.14 -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -iquote /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/MacVim-generated-files.hmap -I/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/MacVim-own-target-headers.hmap -I/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/MacVim-all-target-headers.hmap -iquote /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/MacVim-project-headers.hmap -I/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/Release/include -I/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/DerivedSources/x86_64 -I/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/DerivedSources -F/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/Release -F/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim -F/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim -MMD -MT dependencies -MF /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/Objects-normal/x86_64/MMCoreTextView.d --serialize-diagnostics /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/Objects-normal/x86_64/MMCoreTextView.dia -c /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/MMCoreTextView.m -o /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/build/MacVim.build/Release/MacVim.build/Objects-normal/x86_64/MMCoreTextView.o
/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/MMCoreTextView.m
:
58
:
1
:
 
error
: 
static declaration of 'CTFontDrawGlyphs' follows non-static declaration

CTFontDrawGlyphs(CTFontRef fontRef, const CGGlyph glyphs[],
^
In file included from /tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/MMCoreTextView.m:28
:
In file included from 
/tmp/macvim-20180908-56321-1nv35gi/macvim-snapshot-151/src/MacVim/Miscellaneous.h
:
12
:
In file included from 
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h
:
12
:
In file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h
:
159
:
In file included from 
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h
:
8
:
In file included from 
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h
:
39:
In file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h
:20:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFont.h:1397:
6
:
 
note
: 
previous declaration is here

void CTFontDrawGlyphs(

     ^
1 error generated.
```

This _appears_ to be a problem within Xcode's platform SDK, but I'm not certain. See below for the filled out checklist and attached complete logs.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
    - This only affects `macvim`. For example, I can build `vim` fine.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
    - `brew doctor` finds a few issues, but they appear to be unrelated and have not affected the building of other formulae.
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
    - See: https://gist.github.com/emilyst/b2447e01b59cac343beefa5260775cf9
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
    - See above: not applicable.

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by LanikSJ** [comment]
I have no problems with Public Preview 9 of Mojave:
```
○ → brew install macvim --with-override-system-vim
==> Installing dependencies for macvim: cscope
==> Installing macvim dependency: cscope
==> Downloading https://homebrew.bintray.com/bottles/cscope-15.8b.mojave.bottle.tar.gz
Already downloaded: /Users/ierenstein/Library/Caches/Homebrew/downloads/a2946820a4e5947d4e821f3865bcc8103a8c70e1b970dfeb0564b0ed9cad7e01--cscope-15.8b.mojave.bottle.tar.gz
==> Pouring cscope-15.8b.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/cscope/15.8b: 11 files, 715.3KB
==> Installing macvim --with-override-system-vim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-151.tar.gz
Already downloaded: /Users/ierenstein/Library/Caches/Homebrew/downloads/a77c5747e2df56420e5087b5fdb97882fa6d3e5fdeb6bcf5665257050312ca7b--macvim-snapshot-151.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --enable-terminal --with-tlib=ncurses --with-compiledby=Homebrew --with-local-dir=/usr/local --enable-cscope --en
==> make
🍺  /usr/local/Cellar/macvim/8.1-151: 2,178 files, 34.9MB, built in 1 minute 18 seconds
```

**Comment by DomT4** [comment]
@emilyst What does `xcodebuild -version` output for you?

**Comment by emilyst** [comment]
> @emilyst What does `xcodebuild -version` output for you?

```
$ xcodebuild -version
Xcode 10.0
Build version 10L232m
```

That build version was supplied in the title and the description of my original issue.

**Comment by DomT4** [comment]
> That build version was supplied in the title and the description of my original issue.

You're quite correct, it was, I apologise! You read enough issues a day and eventually your eyes just start automatically skimming for the vital bits we usually need, sometimes missing other useful elements 🙃.

I can reproduce this locally. There is however a Mojave bottle for `macvim`, which makes me wonder what's going on with our systems that CI isn't hitting.

**Comment by emilyst** [comment]
> I can reproduce this locally. There is however a Mojave bottle for macvim, which makes me wonder what's going on with our systems that CI isn't hitting.

I wonder if I can force the use of the bottle. I'll try that. (However, I wonder if the bottle was built using an older Xcode.)

**Comment by emilyst** [comment]
I found that I could successfully force the installation from a bottle. However, in that event, it _ignores_ the option to override the system Vim.

```
$ brew install --force-bottle macvim --with-override-system-vim
==> Downloading https://homebrew.bintray.com/bottles/macvim-8.1-151.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring macvim-8.1-151.mojave.bottle.tar.gz
🔮✨  /usr/local/Cellar/macvim/8.1-151: 2,173 files, 34.9MB
$ ls -la /usr/local/bin/vim
ls: /usr/local/bin/vim: No such file or directory
$
```

There are no other versions of Vim installed from Homebrew whose links would conflict.

**Comment by DomT4** [comment]
All three Mojave boxes return `Build version 10L232m`, as expected. The Mojave bottle was added in https://github.com/Homebrew/homebrew-core/commit/143874a05e574c6d25c3b03d8dbd1f8936cc6d97, a fortnight ago.

**Comment by DomT4** [comment]
> However, in that event, it ignores the option to override the system Vim.

Yeah, that's expected behaviour. Explicitly requesting the bottle overrides any other options passed because otherwise you're requesting both a bottle and a from-source installation, which is a logically impossible request to meet.

**Comment by DomT4** [comment]
I have a lead, but a confusing one. If I revert https://github.com/Homebrew/brew/commit/2086e3c9c493265dfa9a1c45a3b8af95f6879b0d locally the build succeeds, but I did a test run on CI _(with that commit still in place)_ and the build steps succeed:

```
==> brew fetch --retry cscope gdbm makedepend openssl pkg-config python readline sphinx-doc sqlite xz
==> brew fetch --retry macvim --build-bottle --force
==> brew install --only-dependencies --verbose --build-bottle macvim
==> brew install --verbose --build-bottle macvim
==> brew audit macvim --online
==> brew style macvim
```

**Comment by emilyst** [comment]
So far, I haven't seen evidence of this build failing elsewhere aside from my own computer. However, I don't know why it's failing on _my_ computer, so I'm not sure if it's a Homebrew problem or a my-computer problem.

Are you saying you've observed a failure elsewhere, or that you've failed to observe a failure elsewhere?

**Comment by DomT4** [comment]
I can reproduce your failure locally, unless I revert https://github.com/Homebrew/brew/commit/2086e3c9c493265dfa9a1c45a3b8af95f6879b0d, but our CI system cannot reproduce your failure, period.

**Comment by emilyst** [comment]
Which Mojave build is on CI?

**Comment by DomT4** [comment]
Ah, you may have found the issue. Our Mojave machines seem to be running `18A371a` when the latest is `18A384a`. Hurrah.

**Comment by DomT4** [comment]
Super strange that reverting https://github.com/Homebrew/brew/commit/2086e3c9c493265dfa9a1c45a3b8af95f6879b0d works on the latest beta though. Wonder what's going on there.

**Comment by DomT4** [comment]
> It's definitely unclear what motivated that change

A lot of upstream projects set `-mmacosx-version-min` to 10.4 or 10.5, which prior to Mojave works because `libgcc_s.10.4.dylib` and `libgcc_s.10.5.dylib` exist. Both have been removed with Mojave, so now projects end up trying to link against non-existent libraries when passing 10.4 or 10.5 to `-mmacosx-version-min`.

Upstreams need to move to setting at least 10.6 to avoid that issue, but the number of upstreams that pass an ancient version of macOS to `-mmacosx-version-min` is significant enough that Homebrew decided to try and handle it automagically via https://github.com/Homebrew/brew/commit/2086e3c9c493265dfa9a1c45a3b8af95f6879b0d rather than having to whack every single formula/resource/etc we discovered as problematic.

That addition, as you can see, is quite new, so if it breaks lots of things with the new version of Mojave we don't yet know 🙃. The current plan though is to keep trying to do it automagically rather than per-formula/per-resource, since that's a significantly smaller maintenance overhead, but if it proves to be rather breakage-prone we may have to reconsider.

I guess two actions from here would be 1) I need to find some time to update the Mojave boxes later, 2)  Someone/I needs/need to compare `macvim` builds side-by-side with https://github.com/Homebrew/brew/commit/2086e3c9c493265dfa9a1c45a3b8af95f6879b0d applied & with https://github.com/Homebrew/brew/commit/2086e3c9c493265dfa9a1c45a3b8af95f6879b0d reverted.

**Comment by emilyst** [comment]
Curiouser and curiouser. It's difficult to see how that would cause the bug we found! I'm definitely out of my depth, here. But thanks so much for looking into it.

**Comment by emilyst** [comment]
I'd like to add that, of course, I can use the macOS supplied Vim or the regular Vim from Homebrew in the meantime, so this isn't urgent.

**Comment by DomT4** [comment]
I think it's definitely a legitimate bug somewhere in the pipeline, whether with our change or something `macvim` need to adjust upstream, so thanks for letting us know about it!

**Comment by emilyst** [comment]
So, in case anyone else runs into this, here is a workaround which avoids the environment manipulation. This formula builds and installs successfully if you install it thus.

    brew install --env=std macvim --with-override-system-vim

* * *

I have been contrasting the run of `brew install --env=std --verbose --debug macvim --with-override-system-vim` with that of `brew install --env=superenv --verbose --debug macvim --with-override-system-vim` to see what differs in the invocation of the compile step that fails. I can find only one difference between the two invocations—the precise `clang` used.

The standard environment uses `/usr/bin/clang`. The super environment uses plain `clang` (presumably after some `$PATH` manipulation to point this at `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`, but I am only guessing).

Both invocations include an otherwise identical command line (save for the location of the temp directory), including both using `-mmacosx-version-min=10.14`. I can't seem to find out what all environment variables or shims are in effect without reading a lot of source code, and I'm not certain I'll understand things correctly if I try—Homebrew seems rather complicated.

**Comment by jhorowitz** [comment]
Unfortunately, that fix doesn't seem to work for me. I solved the issue by forcing the bottle and then aliasing vim to macvim as a holdover until there's a real fix.  
Just in case someone else is having the same issue:
```bash
alias vim="/usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/bin/vim"
```

**Comment by DomT4** [comment]
I can no longer reproduce this issue with the Xcode 10 GM (10A254a), for what it's worth. Beyond that I'm no longer involved with Homebrew so this'll need to be picked up by someone who still is, if it remains an issue (CC @fxcoudert).

@jhorowitz I'd use `$(brew --prefix macvim)/MacVim.app/Contents/bin/vim` so you don't have to manually update it every time.

**Comment by chdiza** [comment]
Is anyone else noticing that, as in the original pasted-in output of this issue, Xcode 10's warning messages have garbled formatting?  Like a whole bunch of newlines inserted where there used to be none?  Like lots of linebreaks in between individual words?

**Comment by emilyst** [comment]
> I can no longer reproduce this issue with the Xcode 10 GM (10A254a), for what it's worth.

Same. I'm going to close it, but if someone else is experiencing it, they're welcome to reopen.
