### PR TITLE
boost@1.68 1.68.0 (new formula)

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This will add Boost 1.68 as a versioned formula. It turns out that a lot of formulae will fail to build against Boost 1.68, see #30914 and #31193. By adding Boost 1.68 as a versioned formula, we can slowly move formulae that can successfully build against Boost 1.68 depend on it afterwards, and eventually remove Boost 1.67 and make Boost 1.68 the default.

The rationale that I think this approach is actually worth to consider is that, we can meanwhile bump the C++ standard to C++14, as some formulae now require C++14, e.g. Folly.

This pull request does not include `boost-mpi@1.68` as `openmpi` still compiles under C++11.

### CODE REVIEW

**Comment by scpeters** [comment]
[mojave test failure](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/31186/version=mojave_testing/testReport/junit/brew-test-bot/mojave/test_boost_python_1_68/)

~~~
01:01:26 Testing boost-python@1.68
...
01:01:26 /usr/local/include/boost/python/detail/wrap_python.hpp:50:11: fatal error: 'pyconfig.h' file not found
01:01:26 # include <pyconfig.h>
01:01:26           ^~~~~~~~~~~~
01:01:26 1 error generated.
01:01:26 Error: boost-python@1.68: failed
~~~

**Comment by scpeters** [comment]
@fxcoudert the build results were in https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=sierra/30915/display/redirect but have already been flushed from the jenkins build history

Are there email summaries of the jenkins build results? If so, someone might have this info in their inbox.

**Comment by lembacon** [comment]
> I'm not sure it's a good choice: our versioned formulas are typically reserved for old versions, while we use the main formula name for the latest version. The only exception to that is `openssl`, and god knows we don't want to repeat that situation.

In this case, I think the valuable part is that we can meanwhile bump the C++ standard to C++14.

> How many formulas fail to build with boost 1.68.0?

As of #31193, the number is 10.

**Comment by fxcoudert** [comment]
@lembacon 10 formulas failing to build is about the usually number for a boost upgrade (sadly). I don't see a fundamental reason to change our procedures for this one. We create a versioned formula for the old version, and switch those 10 formulas to the old boost. Or patch if they are easy to patch.

**Comment by lembacon** [comment]
Closing in favor of #33336. (handed over to @fxcoudert 😅)
