### PR TITLE
chezmoi 2.30.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
>   NoMethodError: undefined method `rfc3339' for 2023-02-06 08:14:47 UTC:Time

**Comment by p-linnane** [comment]
Introduced by https://github.com/Homebrew/brew/pull/14502.

**Comment by branchvincent** [comment]
Fixed in #122483

**Review by branchv — APPROVED** [review]
