### ISSUE TITLE
argyll-cms failed to build on 10.12

### ISSUE THREAD

**Issue by adpa** [Homebrew/homebrew-core#5188]
argyll-cms is currently failing on Sierra.

`brew gist-logs argyll-cms` at https://gist.github.com/anonymous/c1df5eb551452a0bb678f5e817573067

Console output:

```
$ brew install argyll-cms
==> Using the sandbox
==> Downloading http://www.argyllcms.com/Argyll_V1.8.3_src.zip
Already downloaded: /Users/adpa/Library/Caches/Homebrew/argyll-cms-1.8.3.zip
==> Patching
patching file spectro/dispwin.c
==> sh makeall.sh
Last 15 lines from /Users/adpa/Library/Logs/Homebrew/argyll-cms/01.sh:
extern void ATTRIBUTE_NORETURN error(char *fmt, ...);
                               ^
gamut/gamut.c:3185:5: warning: implicit declaration of function 'error' is invalid in C99 [-Wimplicit-function-declaration]
                                error("gamut::getssvert() vertex doesn't have a triangle");
                                ^
1 warning and 1 error generated.

	clang -c -o gamut/gamut.o -DUNIX -D_THREAD_SAFE -pipe -Wno-sign-compare -fpascal-strings -m64 -O2 -DARGYLLCMS -Igamut -Ih -Iicc -Irspl -Inumlib -Iplot -Ixicc -Icgats -Ispectro -Igamut -I/usr/local/include gamut/gamut.c

...failed Cc_ gamut/gamut.o ...
...skipped <gamut>libgamut.a for lack of <gamut>libgamut.a(gamut.o)...
Archive rspl/librspl.a
...failed updating 1 target(s)...
...skipped 1 target(s)...
...updated 50 target(s)...

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

**Comment by zmwangx** [comment]
Well this formula is among the least installed ones according to our analytics so fixing it won't be a priority (considering that we still have problems with very popular ones: #4841). Could you please try to play around with it and come up with a PR or maybe an upstream bug report? Thanks.

**Comment by adpa** [comment]
Okay, I managed to get Argyll to compile. The problem appears to be the `ATTRIBUTE_NORETURN` macro in `numlib/numsup.h`, which should expand to `__attribute__((noreturn))`, but the compiler doesn't like it for some reason.

Here's the patch.
```
diff --git a/numlib/numsup.h b/numlib/numsup.h
index 366763d..d331136 100755
--- a/numlib/numsup.h
+++ b/numlib/numsup.h
@@ -324,7 +324,7 @@ extern a1log *g_log;                /* Default log */
 #define error_program g_log->tag
 extern void set_exe_path(char *arg0);

-extern void ATTRIBUTE_NORETURN error(char *fmt, ...);
+extern void __attribute__((noreturn)) error(char *fmt, ...);
 extern void warning(char *fmt, ...);
 extern void verbose(int level, char *fmt, ...);

```

**Comment by ilovezfs** [comment]
This is fixed in 1.9.0 :)

https://github.com/Homebrew/homebrew-core/pull/5253

**Comment by ilovezfs** [comment]
@adpa 1.9.0 is now merged. You can brew update and it should be fixed.

**Comment by adpa** [comment]
Everything seems to be working after the update. Thanks!
