### ISSUE TITLE
Imagemagick --with-x11 failed to build on 10.11.5

### ISSUE THREAD

**Issue by OmriShiv** [Homebrew/homebrew-core#3138]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:
I'm trying to install imagemagick --with-x11 but keep running into the following error:
Last 15 lines from /Users/os186008/Library/Logs/Homebrew/imagemagick/02.make:
  "_gzputc", referenced from:
      _WriteBlob in magick_libMagickCore_6_Q16_la-blob.o
  "_gzread", referenced from:
      _ReadBlob in magick_libMagickCore_6_Q16_la-blob.o
  "_gzseek", referenced from:
      _SeekBlob in magick_libMagickCore_6_Q16_la-blob.o
  "_gztell", referenced from:
      _TellBlob in magick_libMagickCore_6_Q16_la-blob.o
  "_gzwrite", referenced from:
      _WriteBlob in magick_libMagickCore_6_Q16_la-blob.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [magick/libMagickCore-6.Q16.la] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

https://gist.github.com/anonymous/723aa6a195bb094ee71947c7520fcc28

**Comment by DomT4** [comment]
This seems very likely to be the problem:
```
    /usr/local/lib/libz.1.2.5.dylib
    /usr/local/lib/libz.1.dylib
    /usr/local/lib/libz.dylib
```

If you didn't put them there intentionally, I'd remove them. If you put them there intentionally, I'd move them out of the way temporarily. Non-system zlib's are notoriously problematic on OS X.

After either of those steps, retry the installation.

**Comment by OmriShiv** [comment]
That worked great, thanks!

On Wed, Jul 20, 2016 at 8:38 AM, Dominyk Tiller <notifications@github.com> wrote:
This seems very likely to be the problem:

    /usr/local/lib/libz.1.2.5.dylib
    /usr/local/lib/libz.1.dylib
    /usr/local/lib/libz.dylib


If you didn't put them there intentionally, I'd remove them. If you put them there intentionally, I'd move them out of the way temporarily. Non-system zlib's are notoriously problematic on OS X.

After either of those steps, retry the installation.

**Comment by DomT4** [comment]
Great! Let us know if you run into anything else. Glad all is working as expected now 😃
