### PR TITLE
perkeep: depend on go@1.12

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR attempts to make `perkeep` buildable from source again by downgrading to `go@1.12`. I realize that this is generally not a good thing and that [a previous attempt to downgrade to `go@1.10` was turned away due to us carrying so many versions of `go`](https://github.com/Homebrew/homebrew-core/pull/52131), but trying to get up to the current `go` version would require an unacceptable amount of patching on our end.

The last tagged version of `perkeep` (which is the current version of the formula) depends on [`gopherjs`](https://github.com/gopherjs/gopherjs), and it is vendored in the subdirectory `vendor/github.com/gopherjs/gopherjs`. Unfortunately, this version of `gopherjs` is trapped at `go` 1.10 (compile will fail on newer `go` versions due to missing compilation symbols, etc.).

Thus, this PR replaces the vendored version of `gopherjs` that is shipped with the current latest tagged version of `gopherjs` with a newer version (from the `HEAD` of the `gopherjs` repo at time of writing, because surprise, surprise - `gopherjs` has no tagged releases either 🙃). This newer version of `gopherjs` builds with any version of `go`, but will still only _run_ with `go` 1.12 (specifically, it requires access to the `GOROOT` of `go` 1.12 in order to work properly). I've tried bypassing the checks in `gopherjs` that enforce this requirement, only to have much bigger compilation errors down the line.

[There has been work on getting support in `gopherjs` for Go 1.13/1.14](https://github.com/gopherjs/gopherjs/pull/964), but the PR seems to have stalled. The PR contains some 50 commits, so including them all isn't an option (unless we want to just compile them into one mega-patch to be hosted on `formula-patches`).

Meanwhile, the current `HEAD` version of `perkeep` doesn't seem to depend on `gopherjs` at all anymore and actually builds fine with `go` 1.14. **Thus the ideal solution would be for `perkeep` to cut a release (some 1700+ commits over the course of about two years now - thanks @roopakv for [following up with their team on this](https://github.com/perkeep/perkeep/issues/1307)) and everything should just work again™.**

### CODE REVIEW

**Comment by SMillerDev** [comment]
Looks acceptable-even-though-I-dont-like-it to me.

**Comment by alebcay** [comment]
> Looks acceptable-even-though-I-dont-like-it to me.

I empathize. Very rarely have I gritted my teeth so hard while writing a PR.

**Comment by roopakv** [comment]
@SMillerDev @alebcay do we have stats on how much something is installed? I'd love to understand why it is better to support such an old version of the tool rather than either kill the formula until they cut a new release?

Im slightly on the side where if we have a formula in core the rules to maintain should be stricter. If this was not in core and was a tap then that isn't the worst issue?

**Comment by alebcay** [comment]
Sure, the stats are at the bottom of every formula page at formulae.brew.sh. [Here's the stats for `perkeep`](https://formulae.brew.sh/formula/perkeep).

**Review by chenrui333 — APPROVED** [review]
