### PR TITLE
freeradius-server 3.2.1

### PR DESCRIPTION
**Pull request by sayomaki**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Bump formula version `3.2.0 -> 3.2.1`
Add `python@3.10` as build dependency to fix build error
<details>
  <summary>Build error</summary>

  ```
  ==> make
  Last 15 lines from /Users/willi123yao/Library/Logs/Homebrew/freeradius-server/02.make:
  LINK build/lib/rlm_pap.la
  CC src/modules/rlm_passwd/rlm_passwd.c
  LINK build/lib/rlm_passwd.la
  CC src/modules/rlm_perl/rlm_perl.c
  LINK build/lib/rlm_perl.la
  CC src/modules/rlm_preprocess/rlm_preprocess.c
  LINK build/lib/rlm_preprocess.la
  CC src/modules/rlm_python/rlm_python.c
  LINK build/lib/rlm_python.la
  CC src/modules/rlm_python3/rlm_python3.c
  src/modules/rlm_python3/rlm_python3.c:37:10: fatal error: 'Python.h' file not found
  #include <Python.h>
           ^~~~~~~~~~
  1 error generated.
  make: *** [build/objs/src/modules/rlm_python3/rlm_python3.lo] Error 1
  
  Do not report this issue to Homebrew/brew or Homebrew/core!
  ```
</details>

### CODE REVIEW

**Comment by willi123yao** [comment]
```
  CC src/modules/rlm_python/rlm_python.c
  ld: cannot link directly with dylib/framework, your binary is not an allowed client of /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libpython2.7.tbd for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [build/lib/local/rlm_python.la] Error 1
```

Seems that the `rlm_python` module depends on python2 which is not supported anymore and causing build issues when linking to the system python2 framework. This issue interestingly did not surface on my local machine as it is running 10.15 and the way how Apple deprecates linking against internal libraries in Big Sur and above.

Build and tests seem to be working on linux (tested on ubuntu 22.04), therefore we will disable the python2 `rlm_python` module when building for macOS. The python3 `rlm_python3` module remains unaffected.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @willi123yao!
