### PR TITLE
swiftlint 0.56.1

### PR DESCRIPTION
**Pull request by SimplyDanny**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /private/tmp/swiftlint-20240806-7938-9p76mj/.build/checkouts/swift-syntax/Sources/SwiftSyntax/generated/SyntaxRewriter.swift:3917:35: error: incorrect argument label in call (have 'fromContentsOf:', expected 'from:')
            _ = newLayout.initialize(fromContentsOf: node.raw.layoutView!.children)
                                    ^~~~~~~~~~~~~~~
                                     from
  /private/tmp/swiftlint-20240806-7938-9p76mj/.build/checkouts/swift-syntax/Sources/SwiftSyntax/generated/SyntaxRewriter.swift:3935:17: error: value of type 'UnsafeMutableBufferPointer<RawSyntax?>' has no member 'deinitialize'
        newLayout.deinitialize()
        ~~~~~~~~~ ^~~~~~~~~~~~
  error: fatalError
```

**Comment by SimplyDanny** [comment]
I don't really understand what's going on here.

The API calls that err in the macOS 12 build require Swift 5.8. At least that's when they were added. However, Apply [claims](https://developer.apple.com/documentation/swift/unsafemutablebufferpointer/deinitialize()) macOS 10.10+. This builds with Swift 5.10 but the Homebrew provided Swift package doesn't contain a Swift standard library? What I see in [another build](https://dev.azure.com/jpsim/21a52e07-282a-4de5-94ee-80b88c9ffa64/_apis/build/builds/9109/logs/22) is that it links against the SDK that comes with Xcode 14.2 and certainly contains an older standard library.

**Comment by SimplyDanny** [comment]
@chenrui333: Is it intended that Homebrew's Swift toolchain doesn't come with a stdlib?

**Comment by carlocab** [comment]
> @chenrui333: Is it intended that Homebrew's Swift toolchain doesn't come with a stdlib?

It should come with a stdlib IIUC, but @Bo98 should be able to answer more questions here.

**Comment by Bo98** [comment]
It is somewhat intentional yeah. Purpose of the Swift toolchain in Homebrew was more so you can use newer Swift dev toolchains on older macOS (given the quick dropping of support of older macOS in Xcode) rather than being a replacement for libswift that ships with the OS. We currently treat libswift similar to libc: if you need features only available in newer runtime libraries, it probably doesn't really run outside of Homebrew on that macOS anyway.

On Linux it's a bit different where the full standard library is shipped because there is no OS support there obviously.

**Comment by SimplyDanny** [comment]
> It is somewhat intentional yeah. Purpose of the Swift toolchain in Homebrew was more so you can use newer Swift dev toolchains on older macOS (given the quick dropping of support of older macOS in Xcode) rather than being a replacement for libswift that ships with the OS. We currently treat libswift similar to libc: if you need features only available in newer runtime libraries, it probably doesn't really run outside of Homebrew on that macOS anyway. So the Homebrew Swift toolchain on macOS is always a buildtime-only dependency and never a runtime dependency.

Homebrew's Swift as a buildtime dependency would be sufficient for SwiftLint to build. There is no runtime dependency.

What I understood (and that can be wrong) is that the Swift standard library for newer Swift versions can provide new APIs that internally call to implementations still provided by the OS. The APIs that break the build for macOS 12 at the moment should work down to macOS 10.10, but Swift <5.8 just doesn't have an interface to it. And since macOS 12 doesn't include the newer Swift standard library either, any Swift compiler >5.7 just cannot locate the symbols. So including the standard library into Homebrew's toolchain would still be of benefit.

Please let me know if my understanding is correct.

> Do note that Apple is dropping macOS 12 support in a matter of weeks and we won't have macOS 12 CI anymore, so don't feel like you have to spend a disproportionate amount of time on this if you do want to make SwiftLint 0.56.0 require Ventura or later.

This is a very valuable note and most likely the way to go in this case. I've actually spent too much time on this problem already.

**Review by carlocab — APPROVED** [review]
