### PR TITLE
boost 1.69.0

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lembacon** [comment]
Well, starting Boost 1.69, the `tagged` layout will include `<arch-and-model>`. 🙃

https://github.com/boostorg/boost/blob/boost-1.69.0/boostcpp.jam#L156-L157

The library name will look like `libboost_regex-mt-x64.dylib`, including a `-x64` suffix in this case.

**Comment by lembacon** [comment]
> Well, starting Boost 1.69, the `tagged` layout will include `<arch-and-model>`. 🙃
> 
> https://github.com/boostorg/boost/blob/boost-1.69.0/boostcpp.jam#L156-L157
> 
> The library name will look like `libboost_regex-mt-x64.dylib`, including a `-x64` suffix in this case.

I think we should keep the layout as-is for now, so I've changed `--layout=tagged` to `--layout=tagged-1.66`.

**Comment by fxcoudert** [comment]
Rev-bumping needed for `azure-storage-cpp bitcoin btfs cpprestsdk cucumber-cpp folly gnuradio gr-osmosdr graph-tool i2pd ledger lgogdownloader libbitcoin libbitcoin-blockchain libbitcoin-client libbitcoin-database libbitcoin-explorer libbitcoin-network libbitcoin-node libbitcoin-protocol libbitcoin-server libswiften libtorrent-rasterbar metaproxy mkvtoolnix monero ncmpcpp openimageio osquery osrm-backend pcl pdftoedn pgrouting source-highlight uhd upscaledb wesnoth widelands`

**Comment by scpeters** [comment]
osquery is missing some boost headers, so it's failing before the no-weak-import issue. I submitted a patch upstream in https://github.com/facebook/osquery/pull/5325, but I don't think it will apply to 3.3.0, and the build is failing anyway.

**Comment by scpeters** [comment]
The boost signals library is removed in 1.69:

* https://www.boost.org/users/history/version_1_69_0.html

I maintain one package that uses that; I need to see if we can easily switch to signals2 or if we'll need `boost@1.68` in our tap.

**Comment by scpeters** [comment]
Turns out we aren't even using boost signals in the code; it was just searching for the component. I think it will be an easy fix for us; no `boost@1.68` needed.

**Comment by scpeters** [comment]
I tried resolving conflicts through the gui, which created a merge commit and broke CI, so I rebased instead.

**Comment by scpeters** [comment]
A patch for osquery has been accepted: https://github.com/facebook/osquery/commit/41b785b86cf585dfab04903247f779e0728e7bfc

A patch for uhd is in the works: https://github.com/EttusResearch/uhd/pull/241#issuecomment-453184446

**Comment by scpeters** [comment]
The [libbitcoin](https://github.com/libbitcoin/libbitcoin) repository was renamed at some point to [libbitcoin-system](https://github.com/libbitcoin/libbitcoin-system), so the tarball sha256 has changed. Perhaps it should just point to the new repo name with the new sha256.

~~~
23:04:59 ==> Downloading from https://codeload.github.com/libbitcoin/libbitcoin-system/tar.gz/v3.5.0
23:04:59 Warning: Formula reports different SHA256: 214d9cd6581330b0e1f6fd8f0c634c46b75ae5515806ecac189f21c0291ae2d9
23:04:59 Downloaded to: /Users/brew/Library/Caches/Homebrew/downloads/d41fab214748b9d248e4047f456139bb9ff328c03f19df07d856ebd51ce75587--libbitcoin-system-3.5.0.tar.gz
23:04:59 SHA256: 44ecd8b0de0dff2296f03e9c7f42a0afb9ac4f916aeaf6de2bffd0ccc05790b5
~~~

**Comment by scpeters** [comment]
I've rebased and pushed two fixes:

* uhd has an upstream patch for boost 1.69 support
* changed url and sha256 for lib bitcoin

**Comment by scpeters** [comment]
that last build took 12 hours; here's a discussion of some (not all) of the failures

* libbitcoin-protocol fails to find zeromq during its build, which should be fixed by https://github.com/Homebrew/brew/pull/5539
* metaproxy had a [compilation failure](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/36348/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_metaproxy/); I've [posted a patch to their mailing list](http://lists.indexdata.dk/pipermail/yazlist/2019-January/004296.html) as I couldn't find a repository in which to submit pull request
* osquery has an [upstream patch](https://github.com/facebook/osquery/commit/41b785b86cf585dfab04903247f779e0728e7bfc) that can fix its compilation error
* pgrouting needs a revision bump

**Comment by scpeters** [comment]
Ok, oddly, the `pgrouting` test failure that inspired its revision bump is actually caused by `sfcgal`. So we should revision bump `sfcgal` and revert the bump to `pgrouting`:

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/36348/version=mojave/testReport/junit/brew-test-bot/mojave/test_pgrouting/

~~~
2019-01-15 09:23:53.402 GMT [3726] ERROR:  could not load library "/usr/local/lib/postgresql/postgis-2.5.so": dlopen(/usr/local/lib/postgresql/postgis-2.5.so, 10): Symbol not found: __ZN5boost6system6detail20generic_category_ncxEv
	  Referenced from: /usr/local/opt/sfcgal/lib/libSFCGAL.1.dylib
	  Expected in: /usr/local/opt/boost/lib/libboost_system-mt.dylib
	 in /usr/local/opt/sfcgal/lib/libSFCGAL.1.dylib
~~~

**Comment by scpeters** [comment]
I've added a few commits to my fork while we wait for 
https://github.com/Homebrew/brew/pull/5539

* https://github.com/scpeters/homebrew-core/commits/boost-1.69.0

**Comment by scpeters** [comment]
trying again with more patches...

**Comment by scpeters** [comment]
the build took 11 hours this time; it looks like two of my patches (690046f for graph-tool on 10.13 and 8c74c5a for osquery) didn't work. The other failures are:

* folly (pre-existing build failure related to zstd)
* libswiften (beware the 280 MB console log that eventually just says `scons: building terminated because of errors.`)

**Comment by scpeters** [comment]
the osquery patch should apply after osquery 3.3.2 https://github.com/Homebrew/homebrew-core/pull/35941

**Comment by SMillerDev** [comment]
`Formula/i2pd.rb` is conflicting, needs a rebase.

**Comment by scpeters** [comment]
I still expect the following failures, so maybe we can wait to update this branch until someone has an idea about how to fix one of these:

* folly (see also #35982)
* graph-tool (on high sierra #35703)
* libswiften (I just noticed [two](https://swift.im/git/swift/commit/?id=a2dc74cd0e4891037b97b6a782de80458675e4f0) new upstream [commits](https://swift.im/git/swift/commit/?id=3666cbbe30e4d4e25401a5902ae359bc2c24248b) related to boost 1.69, so I'll test those out)
* osquery (see also #35941)

**Comment by scpeters** [comment]
I think libswiften will be fixed by upstream patches in https://github.com/scpeters/homebrew-core/commit/a9bf4bf23d49da7e31e568813819634ee46670fe

**Comment by scpeters** [comment]
I built again on Friday with patches for libswiften in https://github.com/Homebrew/homebrew-core/pull/35030/commits/f51d68dd8d34a8e6632d15fbde95c75c2ac9f934, so now the only failures are:

* audit failure for libbitcoin due to 
https://github.com/Homebrew/homebrew-core/pull/35030/commits/56cbeb7cd5e39addf06d54d526836f36c47dca4b, which could be submitted as a separate pull request I suppose
* build failure for folly (see also https://github.com/Homebrew/homebrew-core/pull/35982)
* build failure for osquery (see also https://github.com/Homebrew/homebrew-core/pull/35941)
* build failure for graph-tool on high sierra (fix previously attempted in https://github.com/Homebrew/homebrew-core/pull/35703)

**Comment by scpeters** [comment]
I've resolved conflicts on my fork; waiting for a good time to update this and start a long CI job

**Comment by scpeters** [comment]
jenkins was idle, so I just pushed

**Comment by scpeters** [comment]
there's a new build failure of `libbi`

**Comment by scpeters** [comment]
I wasn't able to reproduce the `libbi` failure, but it failed on all 3 platforms

**Comment by fxcoudert** [comment]
I fixed the `libbi` test in another PR, so this should now be okay.

**Comment by scpeters** [comment]
I've resolved conflicts again on my fork and am again waiting for a quiet time for CI to push. I haven't seen any action on 
https://github.com/Homebrew/brew/issues/5702, so I'm guessing pcl will still fail for that reason.

**Comment by fxcoudert** [comment]
@scpeters you can push, we need to merge this at some point :) CI will take the time it takes

**Comment by scpeters** [comment]
I just pushed, but I want to add the osquery patch too; I'll push again shortly and make sure the CI responds

**Comment by scpeters** [comment]
If I had to guess, I would expect the following failures from the build that just started:

* folly (see also #35982)
* graph-tool on 10.13 (fix previously attempted in #35703)
* pcl (see https://github.com/Homebrew/brew/issues/5702#issuecomment-463123237)

**Comment by scpeters** [comment]
Well my osquery patch didn't apply because it was made to the development branch. I just made another pull request to the stable branch in https://github.com/facebook/osquery/pull/5496/ and added that patch to my fork in https://github.com/scpeters/homebrew-core/commit/2b7f9a433d901feda81747097f03dce58ac91e2c.

The pcl 10.13 failure is gone, but we still have:

* folly
* graph-tool on 10.13
* monero on 10.13
* osquery (new patch on my fork)

**Comment by scpeters** [comment]
resolved conflicts again, we'll see if the osquery patch is working

**Comment by scpeters** [comment]
resolved conflicts and pushed

**Comment by scpeters** [comment]
removed monero patch

**Comment by scpeters** [comment]
Ok, I think we are getting close. It's now down to the following two failures:

* folly fails on everything (see also #35982)
* graph-tool fails on 10.13 (fix previously attempted in #35703 and discussion of pre-existing issues in https://github.com/Homebrew/homebrew-core/pull/36244#issuecomment-456381444)

I made a few attempts at building graph-tool on my 10.13 machine, but it's failing while trying to build the vendored matplotlib, and I don't have enough experience with python to know how to convince it to not use the 10.14 SDK. But we have a precedent for merging without a high-sierra bottle, so that's an option.

I don't know what to say about folly. The last pull request to try to update it was closed as stale. It's a leaf package, so nothing depends on it.

**Comment by scpeters** [comment]
ok I just resolved conflicts again, and this might be the one; folly was fixed for 10.12 and 10.13 in #37862, so I think the only expected failures will be folly on 10.14 and graph-tool on 10.13, and I expect that we will live with those since users can use bottles from older platforms

**Comment by scpeters** [comment]
Well, even after removing zstd from folly's dependency list in #37862, it still finds it opportunistically during the boost build, I think because `apache-arrow` happened to install it. I looked in the following two places but didn't see an easy cmake variable to set to make it fail to find zstd:

* https://github.com/facebook/folly/blob/a0e3a7454c233bf97e07b657006b8b857f3bb0ea/CMake/folly-deps.cmake#L105-L110
* https://github.com/facebook/folly/blob/master/CMake/FindZstd.cmake

I've reported the folly failure upstream

* https://github.com/facebook/folly/issues/1057

**Comment by scpeters** [comment]
I've submitted a fix for folly 10.13 / 10.14 in https://github.com/Homebrew/homebrew-core/pull/38043, with 10.12 disabled. After that is merged, I would expect graph-tool on 10.13 to be the only failure

**Comment by scpeters** [comment]
I'm testing the folly build locally and then I will push if it's ok

**Comment by fxcoudert** [comment]
> After that is merged, I would expect graph-tool on 10.13 to be the only failure

Then we should proceed.

**Comment by scpeters** [comment]
I just pushed 🤞

**Comment by scpeters** [comment]
latest build:

* expected 10.13 graph-tool failure
* https://osquery.io website is down
* 10.13 failure of `brew test cucumber-cpp`

seems close enough to me

**Comment by fxcoudert** [comment]
Given that a `cpprestsdk` was introduced by another merge (sorry), I have merged everything except that. I'll handle it separately in #38115

**Comment by fxcoudert** [comment]
Congrats @scpeters @lembacon on great work!

**Comment by henryiii** [comment]
How hard will Boost 1.70 be to add? Really looking forward to Boost:::Histogram!
