### ISSUE TITLE
gcc failed to build on 10.10.5

### ISSUE THREAD

**Issue by ppwbecker** [Homebrew/homebrew-core#1871]
gcc (6.1.0) build failed with compilation errors.

https://gist.github.com/0e589b81d5f8411a4eb5ea3792f00f53

**Comment by ppwbecker** [comment]
Ran "brew install gcc --without-multilib", and gcc installed successfully.
