### ISSUE TITLE
ctorrent failed to build on 10.12 (16A323 GM)

### ISSUE THREAD

**Issue by preston** [Homebrew/homebrew-core#5129]
Fails to compile every time on Sierra.

`brew gist-logs ctorrent` at https://gist.github.com/preston/3535c71130344bc138ea435457ea9972

Console output:

```
$ brew install ctorrent
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/dtorrent/dtorrent/3.3.2/ctorrent-dnh3.3.2.tar.gz
Already downloaded: /Users/preston/Library/Caches/Homebrew/ctorrent-3.3.2.tar.gz
==> Downloading https://raw.githubusercontent.com/achikin/ctorrent-patch/master/ctorrent-3.3.2-negative-ints.patch
Already downloaded: /Users/preston/Library/Caches/Homebrew/ctorrent--patch-d24d04760a3480e921c54ea1af39e7bb094a8b774ee09bb8849f9c1f76731193.patch
==> Patching
==> Applying ctorrent-3.3.2-negative-ints.patch
patching file bencode.cpp
==> ./configure --prefix=/usr/local/Cellar/ctorrent/3.3.2_2
==> make install
Last 15 lines from /Users/preston/Library/Logs/Homebrew/ctorrent/02.make:
clang++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c -o btfiles.o btfiles.cpp
clang++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c -o btrequest.o btrequest.cpp
clang++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c -o btstream.o btstream.cpp
clang++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c -o bufio.o bufio.cpp
clang -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c compat.c
In file included from compat.c:11:
./compat.h:23:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
make: *** [compat.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

pro:bittorious preston$ brew gist-logs ctorrent
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes it has: []
Create a new personal access token: https://github.com/settings/tokens
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

**Comment by dunn** [comment]
Could you report this upstream?  Sierra changed how some time/clock functions work, which looks like the cause of this.

**Comment by preston** [comment]
I just emailed the author (from http://www.rahul.net/dholmes/ctorrent/) with a link to this issue. Hopefully he's able to take a look soon.

**Comment by mmalchuk** [comment]
@preston @dunn ctorrent didn't updated since 2008-06-14, IMO we need to solve the issue ourselves.

**Comment by dunn** [comment]
If it's effectively abandoned, and no longer building on macOS, I think we'll have to remove it.

**Comment by ilovezfs** [comment]
:+1: to :skull:

**Comment by mmalchuk** [comment]
@dunn @ilovezfs ctorrent is still used on the Mavericks, Yosemite and El Capitan.

**Comment by dunn** [comment]
Yes, but if there's no expectation of it working on Sierra then we're going to have to remove it eventually.  We could set a maximum macOS requirement if there's still a large demand for it, I suppose.

**Comment by preston** [comment]
+1 for removing ctorrent from Sierra, especially since the `mktorrent` package does essentially the same thing and compiles and works fine on both El Capitan and Sierra..

**Comment by kmarty** [comment]
I don't see 'ctorrent -x foo.torrent' alternative in mktorrent.

**Comment by mmalchuk** [comment]
**mktorrent** doesn't provide torrent file information used for example to view torrent files in the midnight-commander

**Comment by MikeMcQuaid** [comment]
@mmalchuk Regardless: we can't continue to support unmaintained software.

**Comment by fxcoudert** [comment]
Closed by migrating to boneyard https://github.com/Homebrew/homebrew-core/commit/604a8d64ae9b10033784ba5130a0397f4322ad43
