### ISSUE TITLE
Sphinx failed to build using --with-mysql and the mysql@5.5 package

### ISSUE THREAD

**Issue by pgrippi** [Homebrew/homebrew-core#8528]
Gist: https://gist.github.com/pgrippi/8bad2908c12b51b3058bf70198a03911

I have the `mysql@5.5` package installed and when I run `brew install sphinx --with-mysql` the build fails. This used to work with the `homebrew/versions/mysql55` package but that was recently removed and added into homebrew core.

I've verified that mysql.h exists in `/usr/local/include/mysql/` but I don't believe the build is looking there for the mysql header files. If I symlink the .h files manually into `/usr/local/include` the build works.

**Comment by ilovezfs** [comment]
you might want to try `brew reinstall --build-from-source python` and then try the install again

**Comment by pgrippi** [comment]
Sadly no luck, python was able to compile from source just fine but when I try the sphinx install command again it fails with the same error:

```
==> make install
Last 15 lines from /Users/petergrippi/Library/Logs/Homebrew/sphinx/04.make:
In file included from sphinxsoundex.cpp:16:
./sphinx.h:66:10: fatal error: 'mysql.h' file not found
#include <mysql.h>
         ^
1 error generated.
make[2]: *** [sphinxsoundex.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [sphinxquery.o] Error 1
1 error generated.
make[2]: *** [sphinxexcerpt.o] Error 1
1 error generated.
make[2]: *** [sphinx.o] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

Gist logs here: https://gist.github.com/257d1fbd0f2ff34acf1f3784865c2388

**Comment by ilovezfs** [comment]
`brew install --env=std --with-mysql sphinx` should work.

**Comment by pgrippi** [comment]
Yup that worked, thanks!

**Comment by nijikon** [comment]
@ilovezfs if it worked we can close?

**Comment by ilovezfs** [comment]
@nijikon no.

**Comment by ilovezfs** [comment]
Something in superenv argument refurbishing is filtering out the include path even when added explicitly.

**Comment by ilovezfs** [comment]
@mistydemeo @MikeMcQuaid the build failure is a consequence of https://github.com/Homebrew/brew/commit/4fd5c5c159c0f8d2f848524e98d4cc938e2207e8 which throws out `/usr/local/Cellar/mysql@5.5/5.5.49/include/mysql` since mysql@5.5 is fulfilling the `:mysql` requirement and not in the set of formula dependencies.

**Comment by Fil** [comment]
It still doesn't work for me. Can someone sum up how to brew install sphinx?

**Comment by MikeMcQuaid** [comment]
1.1.7 has been tagged. `brew update` for the fix for this issue.
