### ISSUE TITLE
gd fails to build on 10.11.5

### ISSUE THREAD

**Issue by copmill** [Homebrew/homebrew-core#2274]
gd fails to build with the following error:

gdxpm.c:29:10: fatal error: 'X11/xpm.h' file not found

`brew gist-logs gd` output:

https://gist.github.com/6452f68ba9833f3ce8b1261f716486b0

**Comment by tdsmith** [comment]
I can't reproduce; configure is finding lXpm on your system and isn't on mine. What's the output of `mdfind -name libXpm` for you?

**Comment by copmill** [comment]
mdfind -name libXpm output:

/opt/X11/lib/libXpm.4.dylib

**Comment by tdsmith** [comment]
Aha, this should help: can you add this to the top of the `install` method, try to reinstall gd, and post the gist-logs again?

`ENV.append_to_cflags "-Wl,-t"`

**Comment by copmill** [comment]
New brew gist-logs gd output:

https://gist.github.com/158faa6355d1b5bc6eae722bacd1d35e

**Comment by tdsmith** [comment]
You have a /usr/local/lib/libXpm.dylib that configure is finding, and once it finds that it's assuming that you need the X11 headers to build against it. https://gist.github.com/anonymous/158faa6355d1b5bc6eae722bacd1d35e#file-config-log-L2398

We should probably just pass `--without-xpm` to gd's `configure` but (re)moving that file might save you from future grief.

**Comment by copmill** [comment]
It's a symlink to /opt/X11/lib/libXpm.4.dylib. I don't know where it came from but I just removed it. gd builds fine now.

**Comment by tdsmith** [comment]
:+1: Great! I'll close this in favor of the PR. Let us know if we can help with anything else.
