### PR TITLE
libstfl: Depend on ruby to fix linker error

### PR DESCRIPTION
**Pull request by muellermartin**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] ~~Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?~~ There seems to be an issue with a line which my patch does not touch: `` `Use :optional` or `:recommended` instead of `depends_on "swig" => :build if build.with?("python")` ``

-----

When `libstfl` is built from source, currently the build fails with the following linker error:

```
Undefined symbols for architecture x86_64:
  "_rb_cFixnum", referenced from:
      _Init_stfl in stfl_wrap.o
  "_rb_data_object_alloc", referenced from:
      _Init_stfl in stfl_wrap.o
      __wrap_stfl_form_allocate in stfl_wrap.o
      _SWIG_Ruby_NewPointerObj in stfl_wrap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [stfl.bundle] Error 1
make: *** [ruby/build_ok] Error 2
```

See full log (with marked error) here: https://gist.github.com/muellermartin/b6f4ce3e123055ba772b29e5406192a4#file-01-make-L62

This issue was adressed in a very old PR #250 but seems to have been reintroduced by commit 3375486.

My patch simply also pulls `ruby` as recommended dependency (not just on Mac OS X as old as or older than Mountain Lion) which fixes the error for me.

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks @muellermartin!

**Comment by muellermartin** [comment]
I'm glad, that I can help ;) Thanks for merging!
