### ISSUE TITLE
aws-sam-cli v1.97.0 packaging refers to wrong dependancy

### ISSUE THREAD

**Issue by kristofwillen** [Homebrew/homebrew-core#141576]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0985dabec8517ab5afda7cfee7d59f1da4ed6ce
Last commit: 21 hours ago
Core tap JSON: 06 Sep 13:03 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

After upgrading aws-sam-cli via 'brew upgrade' from v1.96.0 to 1.97.0, I receive the following error:
```bash
$ sam build

Error: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/watchdog/events.py)
...
````

cfr full stack trace below

### What happened (include all command output)?

```bash
$ sam build

Error: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/watchdog/events.py)

Traceback:
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/lib/telemetry/metric.py", line 184, in wrapped
    raise exception  # pylint: disable=raising-bad-type
    ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/lib/telemetry/metric.py", line 149, in wrapped
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/cli/main.py", line 95, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/commands/build/command.py", line 169, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/commands/build/command.py", line 223, in do_cli
    from samcli.commands.build.build_context import BuildContext
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/commands/build/build_context.py", line 21, in <module>
    from samcli.lib.bootstrap.nested_stack.nested_stack_manager import NestedStackManager
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/lib/bootstrap/nested_stack/nested_stack_manager.py", line 17, in <module>
    from samcli.lib.providers.sam_function_provider import SamFunctionProvider
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/lib/providers/sam_function_provider.py", line 13, in <module>
    from samcli.lib.utils.file_observer import FileObserver
  File "/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/samcli/lib/utils/file_observer.py", line 17, in <module>
    from watchdog.events import (

An unexpected error was encountered while executing "sam build".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20build%20-%20ImportError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20build%20-%20ImportError
````

### What did you expect to happen?

I expect 'sam build' to work without Python stacktrace.

After some investigation, it seems that EVENT_TYPE_OPEN has been added in watchdog v2.3.0, while the aws-sam-cli.rb still seems to refer to v2.1.2.

IMO this should refer to watchdog 3.0.0, as stated in the changelog on aws-sam-cli for version 1.97.0.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew upgrade aws-sam-cli
...

$ sam --version
SAM CLI, version 1.97.0

$ sam build
Error: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/usr/local/Cellar/aws-sam-cli/1.97.0/libexec/lib/python3.11/site-packages/watchdog/events.py)
...

$ brew uninstall aws-sam-cli
...

$ python3.11 -m pip install aws-sam-cli
...

$ sam build
** works! **
```

**Comment by ZhongRuoyu** [comment]
Thanks for the report; this is fixed by #141577. Please do `brew update`, then `brew reinstall aws-sam-cli`.

**Comment by kristofwillen** [comment]
Can confirm all is A-Ok again.  Thanks!
