### PR TITLE
rust 1.52.1

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Heads-up that the [SDKROOT block](https://github.com/Homebrew/homebrew-core/pull/76780/files#diff-09429fb8865f112660b94594e989aae2b9aa9e2550f096566f03bb7ec45d795dL72-L78) can be removed. Its absence allows the current version to build on 10.12 and doesn't appear to affect later versions.

**Comment by carlocab** [comment]
1.52.1 has been released.

**Comment by disrupted** [comment]
> 1.52.1 has been released.

I have opened https://github.com/Homebrew/homebrew-core/pull/76990

**Comment by Bo98** [comment]
Well you still have to fix the breakages caused by 1.52, if you're happy to do that go ahead. I won't be able to look into it until tomorrow.

**Comment by disrupted** [comment]
> Well you still have to fix the breakages caused by 1.52, if you're happy to do that go ahead. I won't be able to look into it until tomorrow.

I see what you mean now. Was hoping for a quick fix to get the update for rust-analyzer through. But in that case I am going to close my PR as I think it will make more sense to make the necessary changes directly here if you can bump to v1.52.1

**Comment by carlocab** [comment]
> Was hoping for a quick fix to get the update for rust-analyzer through.

Rust takes two days to run in CI, so the version bump was never going to be quick, unfortunately.

**Comment by cho-m** [comment]
Starting some initial failure analysis for Intel nodes.

#### Rust failures or pending triage:
- `angle-grinder` - actual Rust compilation failure. probably need to analyze further:
    ```make
       Compiling ag v0.16.0 (/private/tmp/angle-grinder-20210506-90401-nbddyx/angle-grinder-0.16)
    error: proc-macro derive panicked
      --> src/alias.rs:13:26
       |
    13 | const ALIASES_DIR: Dir = include_dir!("aliases");
       |                          ^^^^^^^^^^^^^^^^^^^^^^^
       |
       = help: message: assertion failed: source.starts_with(prefix)
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
    ```
- `freeswitch` - need triage... last 150 lines of cmake logs doesn't seem to help.

#### Probably unrelated failures:
- `asuka`, `vice`, `gifski`, `ktmpl`, `wasm-pack` failures look identical to previous update `rust 1.51.0` #73924, so probably can ignore
- `chronograf` - issue I mentioned for `go 1.16.4` PR related to building with `node 16`
- `pdfpc` - same upstream issue with Vala 0.52 (I opened pdfpc/pdfpc#594)
- `mlpack` - fixed in #76835
- `ppsspp` - issue due to newer `ffmpeg`. Probably will fail until a newer version is added to Homebrew with hrydgard/ppsspp#14176 
- `cargo-watch` - reoccurring test failure over multiple Formula.
- `caffe` - test had another intermittent failure. Really need to find a way to fix this test case as it logs way too much.

**Comment by carlocab** [comment]
`vice` is a `test-bot` bug. `asuka` is only on Big Sur and doesn't have a Big Sur bottle, so we can ignore that one.

**Comment by cho-m** [comment]
@carlocab probably worth a try in PR as I was able to `git apply ...` on top of `git checkout v1.11.3`

**Comment by carlocab** [comment]
This is the freeswitch error:
```
In file included from locks/unix/thread_mutex.c:17:
In file included from /private/tmp/freeswitch-20210507-44211-eeq084/libs/apr/include/arch/unix/apr_arch_thread_mutex.h:27:
In file included from /private/tmp/freeswitch-20210507-44211-eeq084/libs/apr/include/arch/unix/apr_private.h:881:
In file included from /private/tmp/freeswitch-20210507-44211-eeq084/libs/apr/include/arch/unix/../apr_private_common.h:24:
In file included from ./include/apr_pools.h:39:
In file included from ./include/apr_general.h:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:69:42: error: use of undeclared identifier 'NSIG'
extern __const char *__const sys_signame[NSIG];
                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:70:42: error: use of undeclared identifier 'NSIG'
extern __const char *__const sys_siglist[NSIG];
                                         ^
```
Logs: [freeswitch.tar.gz](https://github.com/Homebrew/homebrew-core/files/6455578/freeswitch.tar.gz)

**Comment by cho-m** [comment]
Then the `freeswitch` failure may be the same issue discussed in closed attempt to bump to 1.10.6 (#75728) relating to upstream failure from signalwire/freeswitch#1145.

**Comment by carlocab** [comment]
Is `freeswitch` building its own `apr`? Maybe we can persuade it to use the brewed one, if it is?

**Comment by cho-m** [comment]
Not too sure, but configure.ac `apr` related section appears to be:
https://github.com/signalwire/freeswitch/blob/v1.10.5/configure.ac#L835-L838
```autoconf
AC_CHECK_LIB(apr-1, apr_pool_mutex_set, use_system_apr=yes, use_system_apr=no)
AM_CONDITIONAL([SYSTEM_APR],[test "${use_system_apr}" = "yes"])
AC_CHECK_LIB(aprutil-1, apr_queue_pop_timeout, use_system_aprutil=yes, use_system_aprutil=no)
AM_CONDITIONAL([SYSTEM_APRUTIL],[test "${use_system_aprutil}" = "yes"])
```
Probably need to check Homebrew's `apr` has `apr_pool_mutex_set`.

**Comment by SMillerDev** [comment]
> For chronograf (and similar Node 16 failures from #76791 (comment)) is it better to

I'd say downgrade node

**Comment by carlocab** [comment]
Let's give this another go.

**Comment by cho-m** [comment]
`angle-grinder` is going to still fail to compile with Rust 1.52 since the lock file hasn't changed.

I guess there is an option to ignore failure for now and deal with it afterward.

**Comment by carlocab** [comment]
ARM failures with bottles:

- `angle-grinder`
- `cargo-audit`
- `cargo-watch`
- `gifski`
- `gnumeric`
- `graph-tool`
- `mpv`
- `pc6001vx`

**Comment by carlocab** [comment]
Ok, the `mpv` build is just haunted

**Comment by carlocab** [comment]
Mojave

```
Error: 13 failed steps!
brew install --build-from-source angle-grinder
brew test --retry --verbose buku
brew install --build-from-source cargo-audit
brew test --retry --verbose cargo-watch
brew test --retry --verbose cargo-watch
brew install --build-from-source gifski
brew install --build-from-source graph-tool
brew test --retry --verbose ktmpl
brew install --build-from-source openimageio
brew install --build-from-source pdfpc
brew install --build-from-source vice
brew test --retry --verbose wasm-pack
brew test --retry --verbose wasm-pack
```

**Comment by cho-m** [comment]
Ignoring some standard failures, the remaining ones for Intel are:
- `openimageio` (All, build)
- `buku` (Mojave, test)
- `deno` (Big Sur, build) - `LLVM ERROR: IO failure on output stream: No space left on device`

**Comment by carlocab** [comment]
Can't reproduce the `openimageio` from current `master`.

**Comment by cho-m** [comment]
Not sure why `openimageio` started failing. It didn't fail in the previous run, but it did fail in the Linux-specific PR #78107, which didn't touch the Rust version.

It's possibly due to something else changing in build environment (e.g. other formulae or CI settings).

There is a Homebrew error on possible token expiration, though I haven't checked if this is cause of failure:
```
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:290:in `raise_error': GitHub API Error: Bad credentials (GitHub::API::AuthenticationFailedError)
HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
  https://github.com/settings/tokens
	from /usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:234:in `open_rest'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:166:in `search'
```

**Comment by carlocab** [comment]
Yea, seems like a network error. Probs didn't get to do `git clone` properly or something.

We could try re-running to see if it was just a fluke. That's pretty costly, though. And I doubt any change in `rust` can actually break `openimageio` without also breaking the intermediate formulae that connect `openimageio` to `rust` in the dependency graph.

**Comment by cho-m** [comment]
I also didn't see an issue building both `rust 1.52.1` and `openimageio` locally.

I will go with my previous comment that `angle-grinder` is probably the only formula affected by this update.
As `rust` is its only dependency, I don't expect us needing to rebuild the bottles.
If we need to fix, we can try modifying the problematic dependency that @Bo98 was looking into.

As more Rust projects are starting to use 1.52+ features, I think it is better to get this merged.

**Comment by carlocab** [comment]
Yes, let's merge this. It's blocking a few other PRs.
