### PR TITLE
imgproxy 2.16.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Fails on Apple Silicon:

```
# github.com/bugsnag/panicwrap
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bugsnag/panicwrap@v1.2.2/monitor.go:56:8: undefined: dup2
```

**Comment by chenrui333** [comment]
rebase after go1.16 merge.

**Comment by carlocab** [comment]
Same ARM failure in #72439.
