### ISSUE TITLE
kibana fails to build on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#31741]
See #28817. Error is:

```
  clang++ '-D_DARWIN_USE_64_BIT_INODE=1' '-DV8_TARGET_ARCH_X64' '-DENABLE_DISASSEMBLER' '-DV8_I18N_SUPPORT' -I../deps/v8  -O3 -gdwarf-2 -fstrict-aliasing -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/kibana--node-20180903-48917-1q8rkt4/out/Release/.deps//private/tmp/kibana--node-20180903-48917-1q8rkt4/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/task-queue.o.d.raw   -c -o /private/tmp/kibana--node-20180903-48917-1q8rkt4/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/task-queue.o ../deps/v8/src/libplatform/task-queue.cc
In file included from ../deps/v8/src/libplatform/default-platform.cc:5:
../deps/v8/src/libplatform/default-platform.h:8:10: fatal error: 'functional' file not found
#include <functional>
         ^~~~~~~~~~~~
1 error generated.
make[1]: *** [/private/tmp/kibana--node-20180903-48917-1q8rkt4/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-platform.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../deps/v8/src/libplatform/task-queue.cc:5:
../deps/v8/src/libplatform/task-queue.h:8:10: fatal error: 'queue' file not found
#include <queue>
         ^~~~~~~
1 error generated.
make[1]: *** [/private/tmp/kibana--node-20180903-48917-1q8rkt4/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/task-queue.o] Error 1
make: *** [node] Error 2
```

**Comment by chrmoritz** [comment]
This would be fixed in `kibana@6.3+` with the upgrade to `node@8.x`, which is unfortunately blocked on resolving their licencing issue (#28995).

**Comment by chrmoritz** [comment]
This would be fixed in #31926.

**Comment by commitay** [comment]
Closed via b4e7f4a4fd100975e6869a9ba6a6e248577672db
