### PR TITLE
fastfetch 1.10.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
On Intel Big Sur:

```
  /tmp/fastfetch-20230222-15563-13poxds/fastfetch-1.10.1/src/detection/sound/sound_apple.c:13:9: error: use of undeclared identifier 'kAudioObjectPropertyElementMain'; did you mean 'kAudioObjectPropertyElementName'?
          kAudioObjectPropertyElementMain
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          kAudioObjectPropertyElementName
```

This was added in 1.10.0 (https://github.com/LinusDierheimer/fastfetch/commit/d83232430635da16d5d91584762f51f4454f5edf). From https://developer.apple.com/documentation/coreaudio/kaudioobjectpropertyelementmain, `kAudioObjectPropertyElementMain` requires at least Ventura.

**Comment by nandahkrishna** [comment]
@ZhongRuoyu I just wanted to test a patch to see if this builds on < 12.0, it's just that this property was renamed from `kAudioObjectPropertyElementMaster` to `kAudioObjectPropertyElementMain` in newer macOSes. I will send a PR to upstream if this ends up working.

**Comment by ZhongRuoyu** [comment]
> @ZhongRuoyu I just wanted to test a patch to see if this builds on < 12.0, it's just that this property was renamed from `kAudioObjectPropertyElementMaster` to `kAudioObjectPropertyElementMain` in newer macOSes. I will send a PR to upstream if this ends up working.

Makes sense; I didn't notice that. Thanks @nandahkrishna.

> PS: If it doesn't work, should require Monterey (12.0) and not Ventura (13.0) as stated in the docs.

Yeah, sorry, my typo.

**Review by ZhongRuoyu — APPROVED** [review]
Thanks @nandahkrishna!

**Comment by CarterLi** [comment]
I will release a patch version later. However can we use the latest xcode (macOS SDK) in old macOS version too? [Similar issue](https://github.com/LinusDierheimer/fastfetch/commit/7a5d88270edd9b0aa07acf291fe15cdd6b9fb6c0) happened before and I'm tired applying hacks for old xcode versions.

**Comment by ZhongRuoyu** [comment]
> I will release a patch version later.

Thanks.

> However can we use the latest xcode (macOS SDK) in old macOS version too?

Unfortunately, the newest SDK is not available to Big Sur (11.x): https://en.wikipedia.org/wiki/Xcode#Xcode_11.0_-_14.x_(since_SwiftUI_framework).

**Comment by CarterLi** [comment]
* [Homebrew supports and recommends the latest Xcode and/or Command Line Tools available for your platform](https://docs.brew.sh/Xcode): false
* Homebrew enforce supporting the ancient Xcode version that Homebrew requires: true

**Comment by ZhongRuoyu** [comment]
> [Homebrew supports and recommends the latest Xcode and/or Command Line Tools available for your platform](https://docs.brew.sh/Xcode): false

The latest Xcode and/or Command Line Tools \*\*available for your platform\*\*. See: https://github.com/Homebrew/brew/blob/a3207a03900d7b012c999fad911a701baed82be5/Library/Homebrew/os/mac/xcode.rb#L19.

> Homebrew enforce supporting the ancient Xcode version that Homebrew requires: true

The latest Xcode available on Big Sur is 13.2.1, which was released on December 17, 2021.

Call it ancient or not, Apple does provide support for Big Sur (the latest Big Sur was released [6 days ago](https://support.apple.com/en-sg/HT211896)), and so do us. And we do require the latest Xcode on whichever major macOS version we support.
