### PR TITLE
badtouch: add --locked flag to cargo install

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Relates to #46025

### CODE REVIEW

**Comment by samford** [comment]
The CI build is failing here because the lock file in badtouch v0.7.0 (latest) uses an old version of kuchiki, which in turn uses an old version of cssparser that has a build error.

Dependency versions were bumped in the [latest commit to badtouch](https://github.com/kpcyrd/badtouch/commit/2eeb9962d3c91e8d982ca74ee3b31dc8c47c481f) (2019-08-13), which updates the kuchiki version and fixes the cssparser error.  However, the changes to `src/ulimit.rs` in that commit lead to a mismatched type error with Rust 1.38.0 on my machine (macOS Catalina 10.15.1) but this error didn't appear in the upstream Travis CI builds using 1.38.0.

```
error[E0308]: mismatched types
  --> src/ulimit.rs:13:21
   |
13 |     RLIMIT_NOFILE = libc::RLIMIT_NOFILE,
   |                     ^^^^^^^^^^^^^^^^^^^ expected u32, found i32
help: you can convert an `i32` to `u32` and panic if the converted value wouldn't fit
   |
13 |     RLIMIT_NOFILE = libc::RLIMIT_NOFILE.try_into().unwrap(),
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

Simply running `cargo update` with the v0.7.0 files leads to a successful build locally (albeit with more warnings), since the changes to `src/ulimit.rs` aren't included.  This is something that will need to be addressed upstream and it may be good to have them bump the dependency versions again and create a new release at the same time, if it's not too much trouble.

They may also want to fix the clippy warnings, since they're using a function ([std::mem::uninitialized](https://doc.rust-lang.org/std/mem/fn.uninitialized.html)) in an unsafe block in `src/ulimit.rs` that will be deprecated in 1.39.0.

**Comment by chenrui333** [comment]
I have the same exact error on my catalina machine as well.

**Comment by chenrui333** [comment]
Based the PR build () results, I think it just did not quite work on their end.

image

**Comment by samford** [comment]
Those macOS builds fail with the same error (`error[E0308]: mismatched types`), which is expected since your PR only updates the dependencies and doesn't address the source of the error on macOS (`src/ulimit.rs`), as described above.  The owner will need to decide how to fix the `ulimit` error on macOS but it would be good if you mentioned the error and provided the full error text so they're aware of the problem.

**Comment by samford** [comment]
The build error we were encountering related to `src/ulimit.rs` has been fixed upstream (kpcyrd/badtouch#73) and is in their master branch.  It looks like we'll have to wait until the next release after 0.7.0 to add the `--locked` flag.

Besides that, the author of badtouch was looking for your input on their PR to add macOS to their Travis setup (kpcyrd/badtouch#74), based on your PR (kpcyrd/badtouch#72).

**Comment by kpcyrd** [comment]
I've tagged 0.7.1 that should resolve this, please let me know if you need anything else. Thanks for your work!

**Comment by chenrui333** [comment]
@kpcyrd, cool, let me check on the new release. 

Sorry for the late reply on the PR (this week was crazy for me).

**Comment by chenrui333** [comment]
It works good now. Thanks @kpcyrd @samford !!
