### ISSUE TITLE
calculix-ccx failed to build on 10.12.2

### ISSUE THREAD

**Issue by sallind** [Homebrew/homebrew-core#8247]
### Bug reports:
Error for command :
brew install calculix-ccx
==> Installing calculix-ccx from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://www.dhondt.de/ccx_2.11.src.tar.bz2
Already downloaded: /Users/Daniel-STP/Library/Caches/Homebrew/calculix-ccx-2.11.tar.bz2
==> Patching
patching file ccx_2.11/src/CalculiX.h
patching file ccx_2.11/src/Makefile
patching file ccx_2.11/src/u_free.c
==> Downloading http://www.netlib.org/linalg/spooles/spooles.2.2.tgz
Already downloaded: /Users/Daniel-STP/Library/Caches/Homebrew/calculix-ccx--spooles-2.2.tgz
==> make -C spooles lib
==> make -C spooles/MT/src makeLib
==> make -C ccx_2.11/src ccx_2.11 CC=clang FC=/usr/local/bin/gfortran CFLAGS=-O2 -I../../spooles -DARCH=Linux -DSPOOLES -DARPACK -DMATRIXSTORAGE FFLAGS=-O2 DIR=../../spooles LIBS=$(
Last 15 lines from /Users/Daniel-STP/Library/Logs/Homebrew/calculix-ccx/03.make:
      _dtrsm_ in ccx_2.11.a(dgesv.o)
      _dgetrs_ in ccx_2.11.a(dgesv.o)
      _dgemm_ in ccx_2.11.a(dgesv.o)
  "_xerbla_", referenced from:
      _dtrsm_ in ccx_2.11.a(dgesv.o)
      _dgetrs_ in ccx_2.11.a(dgesv.o)
      _dgemm_ in ccx_2.11.a(dgesv.o)
      _dger_ in ccx_2.11.a(dgesv.o)
      _dgetf2_ in ccx_2.11.a(dgesv.o)
      _dgetrf_ in ccx_2.11.a(dgesv.o)
      _dgesv_ in ccx_2.11.a(dgesv.o)
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [ccx_2.11] Error 1

*******************************************
`brew gist-logs calculix-ccx`
https://gist.github.com/sallind/f1f6fc4333ea9c4acc375511a75be102

*******************************************
Result of ..$ brew config
HOMEBREW_VERSION: 1.1.5-44-gaaf70eb
ORIGIN: https://github.com/Homebrew/brew
HEAD: aaf70eb69656ab9f64a70c8daea4581c270766a6
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c6577cddb1c954c30100e0f7470e953174b3de7a
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 1.8.3.2 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

*******************************************
Result of ..$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Thanks for your help

**Comment by MikeMcQuaid** [comment]
> ==> Installing calculix-ccx from homebrew/science

Please report this there (as the error message should have told you; if it did not please let us know so we can fix this bug).
