### ISSUE TITLE
webp fails to build on OS X 10.11.5

### ISSUE THREAD

**Issue by aarestad** [Homebrew/homebrew-core#1736]
Looks like it's failing with a linking error:

```
Undefined symbols for architecture x86_64:
  "_glutLeaveMainLoop", referenced from:
      _HandleKey in vwebp-vwebp.o
  "_glutSetOption", referenced from:
      _main in vwebp-vwebp.o
ld: symbol(s) not found for architecture x86_64

```
Gist: https://gist.github.com/0566a0aa5a18ff15bc6a0b07378f31b4

**Comment by aarestad** [comment]
Realized that maybe the slightly out-of-date XQuartz may have been the issue - it wasn't. Here's an updated gist: https://gist.github.com/849139a3c2595a893b5bc8818ac29f45

**Comment by MatzFan** [comment]
Same issue here on 10.11.5 while trying to upgrade gd formula:

```
==> Upgrading gd
==> Installing dependencies for gd: webp
==> Installing gd dependency: webp
==> Downloading http://downloads.webmproject.org/releases/webp/libwebp-0.5.0.tar
Already downloaded: /Users/me/Library/Caches/Homebrew/webp-0.5.0.tar.gz
==> ./configure --enable-libwebpmux --enable-libwebpdemux --enable-libwebpdecode
==> make install
Last 15 lines from /Users/me/Library/Logs/Homebrew/webp/02.make:
  CCLD     libexampleutil.la
  CCLD     dwebp
  CCLD     cwebp
  CCLD     vwebp
  CCLD     webpmux
Undefined symbols for architecture x86_64:
  "_glutLeaveMainLoop", referenced from:
      _HandleKey in vwebp-vwebp.o
  "_glutSetOption", referenced from:
      _main in vwebp-vwebp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [vwebp] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1
```

**Comment by aleksandrs-ledovskis** [comment]
Works fine for me

```
» sw_vers -productVersion
10.11.5
```

```
==> Upgrading gd
==> Installing dependencies for gd: webp
==> Installing gd dependency: webp
==> Downloading http://downloads.webmproject.org/releases/webp/libwebp-0.5.0.tar.gz
######################################################################## 100.0%
==> ./configure --enable-libwebpmux --enable-libwebpdemux --enable-libwebpdecoder --prefix=/usr/local/Cellar/webp/0.5.0
==> make install
🍺  /usr/local/Cellar/webp/0.5.0: 36 files, 3.2M, built in 47 seconds
==> Installing gd
==> Downloading https://github.com/libgd/libgd/archive/gd-2.2.1.tar.gz
==> Downloading from https://codeload.github.com/libgd/libgd/tar.gz/gd-2.2.1
######################################################################## 100.0%
==> Downloading https://github.com/libgd/libgd/commit/0bc8586e.patch
######################################################################## 100.0%
==> Downloading https://github.com/libgd/libgd/commit/502e4cd8.patch
######################################################################## 100.0%
==> Patching
==> Applying 0bc8586e.patch
patching file .travis.yml
patching file Makefile.am
patching file bootstrap.sh
patching file thumbs.bat
patching file thumbs.sh
patching file travis/main.sh
==> Applying 502e4cd8.patch
patching file configure.ac
==> ./bootstrap.sh
==> ./configure --prefix=/usr/local/Cellar/gd/2.2.1_1 --without-x --with-png=/usr/local/opt/libpng --with-fontconfig=/usr/local/opt/fontconfig --with-freetype=/usr/local/opt/freetype --with-jpeg=/usr/local/opt/jpeg --with-tiff=/usr/local/opt/libtiff --with-webp=/usr/local/opt/webp
==> make install
🍺  /usr/local/Cellar/gd/2.2.1_1: 35 files, 2.1M, built in 46 seconds
```

**Comment by UniqMartin** [comment]
Do any of you happen to have the `freeglut` formula installed? If so, can you try temporarily unlinking it via `brew unlink freeglut` and then try again? If not, what is the output of the following commands?

```
ls -AlFd /usr/local/include/GL
ls -AlFd /usr/local/include/GL/glut.h
```

**Comment by Sembei** [comment]
That did the trick on 10.10.5

**Comment by MatzFan** [comment]
Ditto 10.11.5, thanks

**Comment by ilovezfs** [comment]
@UniqMartin is conflicts_with the solution here or something else?

**Comment by UniqMartin** [comment]
@ilovezfs To be honest, I don't know what solution is best. `conflicts_with` seems like a sledgehammer. Making `freeglut` a keg-only formula should also fix the issue, but I'm not familiar with `freeglut` and whether this will cause any issues on its own. Maybe there's a way to prevent `webp` from picking up this header, but I haven't investigated yet …

**Comment by UniqMartin** [comment]
A proper solution is still pending, but for posteriority and for anyone wanting to reproduce the failure (assuming a pristine Homebrew installation):

```
brew install homebrew/x11/freeglut
brew install webp --universal
```

The failure happens because one of the `webp` binaries tries to link to `libglut` provided by the `freeglut` formula, but fails because `libglut` (unlike `webp`) hasn't been built with both the `i386` and `x86_64` architectures. The lack of architecture support isn't detected by `./configure` thus it uses the library found there despite the missing support for `i386`. (Unlinking `freeglut` causes `webp` to find the `GLUT` system framework instead. That one provides both architectures, so the link during the build succeeds.)

**Comment by UniqMartin** [comment]
For those affected by the problem: After a `brew update` you can link `freeglut` again via `brew link freeglut`. It should no longer negatively affect the build of the `webp` formula.
