### PR TITLE
pkg-config: fix build with Xcode 15.3

### PR DESCRIPTION
**Pull request by fxcoudert**
Fixes https://github.com/orgs/Homebrew/discussions/5194

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]
I'm confused about the issue. If it was fixed in glib, why are we affected still?

**Comment by ran-isenberg** [comment]
when is this expected to get merged?
I get the same error when trying to install pyenv and pkg-config is a dependancy


Last 15 lines from /Users/ran.isenberg/Library/Logs/Homebrew/pkg-config/02.make:
gatomic.c:464:10: error: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]
  return g_atomic_pointer_xor ((volatile gpointer *) atomic, val);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gatomic.h:191:45: note: expanded from macro 'g_atomic_pointer_xor'
    (gsize) __sync_fetch_and_xor ((atomic), (val));                          \
                                            ^~~~~
