### PR TITLE
glib-networking 2.50.0 and libsoup 2.56.0

### PR DESCRIPTION
**Pull request by tschoonj**
Enabled `p11-kit support`, which also required a modification to the `gnutls` formula.
`libsoup` depends on `glib-networking`, so I added that one too

### CODE REVIEW

**Comment by tschoonj** [comment]
Looks like Jenkins is having a bad moment

File: Formula/gnutls.rb [hunk 1]
```diff
@@ -20,6 +21,7 @@ class Gnutls < Formula
   depends_on "nettle"
   depends_on "guile" => :optional
   depends_on "unbound" => :optional
+  depends_on "p11-kit"
```
Comment (DomT4) [inline Formula/gnutls.rb]: Given we've only _just_ restored this from the boneyard, we might want to make this `:optional` for now.

Comment (tschoonj) [inline Formula/gnutls.rb]: In both `glib-networking` and `gnutls`?

Comment (DomT4) [inline Formula/gnutls.rb]: Aye, for now. We can review the situation later but if we introduce this by default and then end up removing `p11-kit` down the line because we discover further issues we'll have to force a rebuild of a wider group of formulae, which is a pain.

Comment (tschoonj) [inline Formula/gnutls.rb]: ok, fair enough

**Comment by ilovezfs** [comment]
looks like there are some xcode 8 + gnutls issues to sort out

**Comment by tschoonj** [comment]
Well I had to downgrade to Xcode 7.3 on my El Cap to get this working (`undefined reference to _getentropy`).

How do I fix this exactly, since it looks like you guys are using Xcode 8 on the El Cap bot?

**Comment by DomT4** [comment]
Blocked on resolution of https://github.com/Homebrew/homebrew-core/pull/5434 and/or https://github.com/Homebrew/homebrew-core/commit/46be01e503df1e30dba395bffd87d2619e117748.

**Comment by tschoonj** [comment]
@ilovezfs What are your thoughts on merging this one in?

**Comment by ilovezfs** [comment]
Assuming the option works the PR looks benign.

**Comment by RandomDSdevel** [comment]
@ilovezfs, @tschoonj:  The formulas edited by this PR might need an/another `revision` bump after I finally get around to filing another PR to resolve my comments regarding [commit `46be01e`](https://github.com/Homebrew/homebrew-core/commit/46be01e503df1e30dba395bffd87d2619e117748), though.  In the meantime, you guys will have to make this PR relative to the changes I committed in PR #5434.

**Comment by ilovezfs** [comment]
@RandomDSdevel handled https://github.com/Homebrew/homebrew-core/pull/6174.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Thanks for taking care of that for me!  I would have gotten around to it eventually, but I usually like to wait to make contributions until after I have everything managed by Homebrew on my system up to date so that I have a clean in-`brew` state to work with and have been held back from doing this by my current dependency on [[qt5] Qt v5.7.0 Fails to Build on OS X/macOS v10.11.6 'El Capitan'](https://github.com/Homebrew/homebrew-core/issues/6032).  I don't know if that should really be a concern of mine, but I thought it might be best if I made a conservative decision in that department.

**Comment by ilovezfs** [comment]
@RandomDSdevel no worries. FYI: https://github.com/Homebrew/homebrew-core/pull/6175

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Thanks for the pointer!  I'll keep track of that, too, then.  Didn't remember that being an issue, but, as you might have guessed, I've been a bit frazzled lately, so who _knows_ whether, given my scatterbrained state, I might have recognized it as one or not?  😵😆.

**Comment by tschoonj** [comment]
I removed all p11-kit related stuff from these commits this morning 😢 

didn't realize 0.23.2 would become stable 😄

**Comment by tschoonj** [comment]
will merge this one in as is, feel free to add p11-kit support later
