### ISSUE TITLE
cmocka failed to build on 10.12

### ISSUE THREAD

**Issue by apexskier** [Homebrew/homebrew-core#5090]
`gist-logs` output at https://gist.github.com/apexskier/a9720aceda93dba99ce04f9df5eb8010

I was able to install manually from cmocka's git source without trouble, but compiling fails, so I decided to try brew.

(this was a manual install's issue)
```
cc -Wall -Wall -Werror -Wswitch-default -Wfatal-errors -I/usr/local/include test.c
Undefined symbols for architecture x86_64:
  "__cmocka_run_group_tests", referenced from:
      _main in test-d2ff02.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test] Error 1 
```

**Comment by mistydemeo** [comment]
This is fixed in the 1.1.0 release; I'll get a PR up.

**Comment by apexskier** [comment]
Sweet, thanks!
