### PR TITLE
webp: avoid build issue with freeglut installed

### LINKED ISSUE #1736: webp fails to build on OS X 10.11.5
Looks like it's failing with a linking error:

```
Undefined symbols for architecture x86_64:
  "_glutLeaveMainLoop", referenced from:
      _HandleKey in vwebp-vwebp.o
  "_glutSetOption", referenced from:
      _main in vwebp-vwebp.o
ld: symbol(s) not found for architecture x86_64

```
Gist: https://gist.github.com/0566a0aa5a18ff15bc6a0b07378f31b4

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

This disables checking for OpenGL/GLUT and effectively results in the `vwebp` binary (a simple WebP viewer) not being built.

The problem being worked around by this is: If `freeglut` (from the `homebrew/x11` tap) is installed and was built without the `--universal` option but then `webp` is built with the `--universal` option (either directly or as a dependency of another formula), then it will find the GLUT headers and libraries provided by `freeglut` (instead of the `GLUT` framework in `/System/Library`) which appears to be fine during the
`./configure` run, but then causes failure during the build due to lacking architecture support.

Closes #1736.

cc @mistydemeo

### CODE REVIEW

**Comment by ilovezfs** [comment]
Don't we usually allow inheritance to handle this as wine and all its deps do? Or is that not possible with these two formulae?

Also, since this results in a component not being built, shouldn't that at least be made optional if there's no way to handle this via the regular inheritance mechanism?

**Comment by DomT4** [comment]
Could perhaps do:

```ruby
args << "--disable-gl" if build.universal?
```
But no objections to the current pure disable here. I can't imagine people banging down our doors to demand its return, so.

**Comment by UniqMartin** [comment]
> Don't we usually allow inheritance to handle this as wine and all its deps do? Or is that not possible with these two formulae?

This only works when there's a dependency relationship between the formulae in question. As it stands, `freeglut` files are picked up unintentionally by `webp` and `webp` neither can nor should depend on `freeglut`.

> Could perhaps do: […]

This quickly crossed my mind, but I consciously decided not to do this, as this will give users a different set of binaries depending on whether they have a universal build or not, and that is likely to cause more irritation than taking away this binary from everyone.

> Also, since this results in a component not being built, shouldn't that at least be made optional if there's no way to handle this via the regular inheritance mechanism?

My thinking here is that the binary is obscure enough to not be missed by 99.9% of our user base. We can still reconsider and try to find a more elegant solution once users come banging at our door.
