### ISSUE TITLE
Python 3.8 doesn't build on 11.0

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/homebrew-core#56791]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`python@3.8` was in the dependency tree of software I was installing, but failed to build from source on Big Sur.

## What happened (include command output)

Installation fails; logs here: https://gist.github.com/mistydemeo/658ea7401c00b2b8dccee9f067ac2c0e

Specifically, the error is here:

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.16.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.16.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.16.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration  -I./Include/internal  -I. -I./Include    -DPy_BUILD_CORE_BUILTIN  -DPy_BUILD_CORE_BUILTIN -I./Include/internal -c ./Modules/posixmodule.c -o Modules/posixmodule.o
./Modules/posixmodule.c:9141:20: error: variable has incomplete type 'struct sf_hdtr'
    struct sf_hdtr sf;
                   ^
./Modules/posixmodule.c:9141:12: note: forward declaration of 'struct sf_hdtr'
    struct sf_hdtr sf;
           ^
1 error generated.
```

This happened on macOS 11.0 beta 1 for Intel using the CLT.

## What you expected to happen

Build succeeds.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install python@3.8`

**Comment by soheil** [comment]
This is also causing `brew install node` to fail since `python 3.8` is a dependency.

**Comment by soheil** [comment]
PR to remove `python 3.8` dependency for `node` https://github.com/Homebrew/homebrew-core/pull/56795

**Comment by claui** [comment]
A little info about `struct sf_hdtr`: [man sendfile](https://www.freebsd.org/cgi/man.cgi?query=sendfile)

**Comment by pcr910303** [comment]
In fact, this applies to usual python as well.

**Comment by Bo98** [comment]
This is being handled upstream. It's still early days of the beta.

**Comment by claui** [comment]
> This is being handled upstream.

@Bo98 Are you referring to https://github.com/python/cpython/pull/21113?

**Comment by Bo98** [comment]
Ah yes. I wasn't aware that the pull request had already been created so I didn't have anything to link.

That indeed should fix the issue.

**Comment by yuyaebean** [comment]
Is there any way to fix this problem temporary?

**Comment by claui** [comment]
> Is there any way to fix this problem temporary?

Nothing that Homebrew would be able to support.
I’m afraid you’re on your own here. But as @Bo98 said: please remember that macOS BS is in a very early beta.
Issues like the one at hand are to be expected.

**Comment by Bo98** [comment]
If you have Homebrew installed to /usr/local, then the existing Catalina bottles can be used and thus not need to worry about the build issues.

We may apply upstream's patch to the formula once it is merged.

But please try to get used to there being issues in the Big Sur betas. Python is _not_ the only thing broken (CMake is another, for example) and we already know that there will be further breakages as the betas progress (such as 10.16 becoming 11.0).

**Comment by mistydemeo** [comment]
Can confirm that PR will fix it; I'll backport that to us once it's merged upstream, but we can hold out until then.

**Comment by Bo98** [comment]
It's worth noting that it looks like the fix will _not_ be backported to 3.7. I think it missed the cut by a few days and they are now only accepting security fixes.

**Comment by Bo98** [comment]
The patch managed to just sneak in to 3.7.8 which will be released in the next few days.

We can apply https://github.com/python/cpython/pull/21153 for 3.8 until 3.8.4 releases in mid-July.
