### PR TITLE
snappy 1.2.2

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>* We fixed a very old issue of data corruption when compressed size
    exceeds 4GB. This can happen when you compress data close to 4GB
    and it's incompressible, for example, random data.

* Started to use minimum CMake 3.10 because older ones are not
    planned to be supported.

* Various other small fixes</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
folly failed to build with snappy 1.2.2

```
  "typeinfo for snappy::Source", referenced from:
      typeinfo for folly::compression::(anonymous namespace)::IOBufSnappySource in Compression.cpp.o
ld: symbol(s) not found for architecture arm64
```

**Comment by cho-m** [comment]
On Snappy side, following related issue:
- https://github.com/google/snappy/issues/184
- https://github.com/google/snappy/issues/189 (mainly on discussion of removing `-fno-rtti` which would implicitly fix build, but there is potential ABI impact so not something we should touch unless upstream agrees with change).

Though perhaps Folly side needs to handle this. In which case we may be blocked until they decide to start testing Snappy 1.2.x - https://github.com/facebook/folly/blob/main/build/fbcode_builder/manifests/snappy#L16-L18

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/222288
