### PR TITLE
LLVM@3*: import from homebrew/versions

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Homebrew/versions PR: https://github.com/Homebrew/homebrew-versions/pull/1475

Also, remove various unused options from analytics.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by equal-l2** [comment]
llvm@3.4 and llvm@3.5 should depend on isl newer than 0.12 because they need `isl/val.h`, which is introduced at isl 0.12

**Comment by MikeMcQuaid** [comment]
Thanks @equal-l2. The issue is cloog@0.18 is depending on isl@0.11 so that'll need handled too.

**Comment by equal-l2** [comment]
@MikeMcQuaid 
The version difference between `cloog` and `cloog@0.18` is on the patch version.
Maybe are they interchangeable?

**Comment by MikeMcQuaid** [comment]
> The version difference between cloog(0.18.4) and cloog@0.18(0.18.0) is on the patch version.
> Maybe are they interchangeable?

@equal-l2 Good idea, will try that out. Thanks a lot for the help!

**Comment by MikeMcQuaid** [comment]
@equal-l2 We have a tricky problem here due to the new version handling. cloog(0.18.4) and cloog@0.18(0.18.0) use different ISLs and GMPs. We'll need them to use the same as the GCC that uses them. Thoughts on how to resolve this? CC @ilovezfs for an example of something we could easily shoot ourselves in the foot on without https://github.com/Homebrew/brew/pull/1681.

**Comment by ilovezfs** [comment]
>We'll need them to use the same as the GCC that uses them.

Is that just an aesthetic preference or something that we know actually compromises the functionality of the compiler?

**Comment by MikeMcQuaid** [comment]
> Is that just an aesthetic preference or something that we know actually compromises the functionality of the compiler?

Partly it's to avoid descending into madness of having a single piece of software depend on two versions of the same thing. It may or may not compromise the functionality of the compiler but actually detecting that may prove difficult.

**Comment by ilovezfs** [comment]
>Partly it's to avoid descending into madness of having a single piece of software depend on two versions of the same thing.

That's circular reasoning if it's supposed to be a demonstration of "something we could easily shoot ourselves in the foot" with.

**Comment by MikeMcQuaid** [comment]
@ilovezfs It would be if I didn't make the second argument: it could break things in ways that would be very subtle (i.e. at runtime). We saw similarly with mixed C++ standard libraries: things fail infrequently and extremely weirdly.

**Comment by ilovezfs** [comment]
>It would be if I didn't make the second argument: it could break things in ways that would be very subtle (i.e. at runtime).

That sounds plausible though if the given releases are ABI compatible it's not clear to me what form that breakage would take.

>We saw similarly with mixed C++ standard libraries: things fail infrequently and extremely weirdly.

The C++ situation is actually still very broken despite the C++ standards warnings because we have no way to require the use of the same compiler for dependencies and reverse dependencies, and the mixed and matched compilers are rarely actually fully ABI compatible. I recently had an upstream quite unhappy about how we don't enforce the use of the same compiler because it's causing our users to file bogus support issues with them.

**Comment by equal-l2** [comment]
Is it impossible to replace all isl@0.11 dependency with isl 0.12?

At least, cloog@0.18 builds on isl 0.12.

**Comment by MikeMcQuaid** [comment]
I'll try, thanks @equal-l2.

**Comment by equal-l2** [comment]
Well, it found that LLVM 3.5 needs isl 0.13 or newer, unfortunately.

```
Analysis/Dependences.cpp:237:20: error: use of undeclared identifier 'isl_ctx_get_max_operations'
  long MaxOpsOld = isl_ctx_get_max_operations(S.getIslCtx());
                   ^
Analysis/Dependences.cpp:238:3: error: use of undeclared identifier 'isl_ctx_set_max_operations'
  isl_ctx_set_max_operations(S.getIslCtx(), OptComputeOut);
  ^
Analysis/Dependences.cpp:292:44: error: use of undeclared identifier 'isl_error_quota'
  if (isl_ctx_last_error(S.getIslCtx()) == isl_error_quota) {
                                           ^
Analysis/Dependences.cpp:300:3: error: use of undeclared identifier 'isl_ctx_reset_operations'; did you mean 'isl_ctx_reset_error'?
  isl_ctx_reset_operations(S.getIslCtx());
  ^~~~~~~~~~~~~~~~~~~~~~~~
  isl_ctx_reset_error
/usr/local/opt/isl@0.12/include/isl/ctx.h:236:6: note: 'isl_ctx_reset_error' declared here
void isl_ctx_reset_error(isl_ctx *ctx);
     ^
Analysis/Dependences.cpp:301:3: error: use of undeclared identifier 'isl_ctx_set_max_operations'
  isl_ctx_set_max_operations(S.getIslCtx(), MaxOpsOld);
  ^
5 errors generated.
```

`isl_ctx_get_max_operations` and etc. are introduced on isl 0.13.

Maybe isl 0.14 will work.

**Comment by equal-l2** [comment]
Now I feel like it is reasonable to drop LLVM 3.4 & 3.5 support...

**Comment by MikeMcQuaid** [comment]
Pulled just 3.7 and 3.8 for now.

**Comment by tmcdonell** [comment]
llvm@3.8 and llvm@3.7 are now hard-coded at `--enable-targets=host`, and the option `--with-all-targets` is gone. Was there a reason for this, or is that a regression?

**Comment by MikeMcQuaid** [comment]
@tmcdonell We are cutting down on options because they aren't tested by CI. We may be open to changing the defaults instead.
