### PR TITLE
libvncserver 0.9.14

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
it has some installation conflict (which is expected as they are installing the same artifact, will deprecate libvnc in another PR)

**Comment by chenrui333** [comment]
```
  rm /opt/homebrew/include/rfb
  ln -s ../../Cellar/libvnc/0.9.14/include/rfb/keysym.h keysym.h
  ln -s ../../Cellar/libvnc/0.9.14/include/rfb/rfb.h rfb.h
  ln -s ../../Cellar/libvnc/0.9.14/include/rfb/rfbclient.h rfbclient.h
  ln -s ../../Cellar/libvnc/0.9.14/include/rfb/rfbconfig.h rfbconfig.h
  ln -s ../../Cellar/libvnc/0.9.14/include/rfb/rfbproto.h rfbproto.h
  ln -s ../../Cellar/libvnc/0.9.14/include/rfb/rfbregion.h rfbregion.h
  ln -s ../../Cellar/libvnc/0.9.14/include/rfb/threading.h threading.h
  The formula built, but is not symlinked into /opt/homebrew
  Error: The `brew link` step did not complete successfully
  Could not symlink include/rfb/keysym.h
  Target /opt/homebrew/include/rfb/keysym.h
  is a symlink belonging to libvnc. You can unlink it:
    brew unlink libvnc
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite libvncserver
  
  To list all files that would be deleted:
    brew link --overwrite --dry-run libvncserver
```

**Comment by SMillerDev** [comment]
```
  /usr/bin/ld: x11vnc-xwrappers.o:(.bss+0x440): multiple definition of `pointerMutex'; x11vnc-8to24.o:(.bss+0x40020): first defined here
  /usr/bin/ld: x11vnc-xwrappers.o:(.bss+0x480): multiple definition of `inputMutex'; x11vnc-8to24.o:(.bss+0x40060): first defined here
  /usr/bin/ld: x11vnc-xwrappers.o:(.bss+0x4c0): multiple definition of `clientMutex'; x11vnc-8to24.o:(.bss+0x400a0): first defined here
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:552: x11vnc] Error 1
  make[1]: Leaving directory '/tmp/x11vnc-20221229-12829-1fmeg65/x11vnc-0.9.16/src'
  make: *** [Makefile:503: install-recursive] Error 1
```

**Comment by chenrui333** [comment]
Will need to debug the linux build separately.

**Comment by cho-m** [comment]
That's a GCC 10+ `-fno-common` error message.

Maybe related upstream commit: https://github.com/LibVNC/x11vnc/commit/a48b0b1cd887d7f3ae67f525d7d334bd2feffe60

**Comment by chenrui333** [comment]
still the same issue on the linux build

**Comment by cho-m** [comment]
> still the same issue on the linux build

You need to fix `x11vnc`. Looks like changes were done on `libvncserver`.

**Review by p-linnane — DISMISSED** [review]

**Review by p-linnane — APPROVED** [review]
