### PR TITLE
purescript 0.9.2

### PR DESCRIPTION
**Pull request by ilovezfs**
needed to patch ambiguous occurrence errors

### CODE REVIEW

**Comment by schrepfler** [comment]
Any idea why this broke on the CI server, commit seems OK as I would have thought to commit it (sha matches).

**Comment by ilovezfs** [comment]
```
[115 of 137] Compiling Language.PureScript.Ide.Pursuit ( src/Language/PureScript/Ide/Pursuit.hs, dist/dist-sandbox-175d3357/build/Language/PureScript/Ide/Pursuit.o )

src/Language/PureScript/Ide/Pursuit.hs:56:32: error:
    Ambiguous occurrence ‘fromStrict’
    It could refer to either ‘Protolude.fromStrict’,
                             imported from ‘Protolude’ at src/Language/PureScript/Ide/Pursuit.hs:22:1-26
                             (and originally defined in ‘Data.Text.Lazy’)
                          or ‘Data.ByteString.Lazy.fromStrict’,
                             imported from ‘Data.ByteString.Lazy’ at src/Language/PureScript/Ide/Pursuit.hs:26:49-58

src/Language/PureScript/Ide/Pursuit.hs:68:30: error:
    Ambiguous occurrence ‘fromStrict’
    It could refer to either ‘Protolude.fromStrict’,
                             imported from ‘Protolude’ at src/Language/PureScript/Ide/Pursuit.hs:22:1-26
                             (and originally defined in ‘Data.Text.Lazy’)
                          or ‘Data.ByteString.Lazy.fromStrict’,
                             imported from ‘Data.ByteString.Lazy’ at src/Language/PureScript/Ide/Pursuit.hs:26:49-58
```


Probably due to a new version of one of deps.

**Comment by ilovezfs** [comment]
@schrepfler It's a regression introduced by https://github.com/purescript/purescript/commit/8063c4d0498c9bdca74ffe165edcdd1ea1a4f15b

This fixes it:
```
diff --git a/src/Language/PureScript/Ide/Pursuit.hs b/src/Language/PureScript/Ide/Pursuit.hs
index 9032a34..d7164fa 100644
--- a/src/Language/PureScript/Ide/Pursuit.hs
+++ b/src/Language/PureScript/Ide/Pursuit.hs
@@ -19,7 +19,7 @@ module Language.PureScript.Ide.Pursuit
   , findPackagesForModuleIdent
   ) where
 
-import           Protolude
+import           Protolude hiding (fromStrict)
 
 import qualified Control.Exception             as E
 import           Data.Aeson
diff --git a/src/Language/PureScript/Ide/Util.hs b/src/Language/PureScript/Ide/Util.hs
index 4e4c235..7ccf217 100644
--- a/src/Language/PureScript/Ide/Util.hs
+++ b/src/Language/PureScript/Ide/Util.hs
@@ -27,7 +27,7 @@ module Language.PureScript.Ide.Util
   , module Language.PureScript.Ide.Conversions
   ) where
 
-import           Protolude
+import           Protolude (hiding decodeUtf8, encodeUtf8)
 import           Data.Aeson
 import qualified Data.Text                     as T
 import           Data.Text.Lazy.Encoding       (decodeUtf8, encodeUtf8)
```

**Comment by schrepfler** [comment]
So what's the plan, commit upstream and wait for new tag?

**Comment by ilovezfs** [comment]
@schrepfler no, I've opened an upstream PR and will apply it as a patch to this PR in the next few minutes: https://github.com/purescript/purescript/pull/2225

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

@schrepfler you can try it locally if you do `brew pull 2905`

**Comment by DomT4** [comment]
@ilovezfs 👍 when you're happy. LGTM. Thanks for filing a PR upstream as well!

**Comment by schrepfler** [comment]
Are we merging it then?

**Comment by ilovezfs** [comment]
@schrepfler sure. The issues being discussed with upstream regarding the PR are about bumping their Stack requirements which has no effect over here so I'll just refresh this once that's set in stone, hopefully with a new tag too.

**Comment by ilovezfs** [comment]
@schrepfler :ship:'d

**Comment by ilovezfs** [comment]
Woo hoo upstream PR just merged! https://github.com/purescript/purescript/commit/15c466f19df3bde8c617adc0502e8fa6d8a6bd2f
