### ISSUE TITLE
root compilation fails after update to Xcode 9 (High Sierra)

### ISSUE THREAD

**Issue by soleti** [Homebrew/homebrew-core#18567]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I am trying to install root6 using the latest available version from github (master branch). It includes some patches not available in 6.10/06 which allow to compile on XCode 9 (https://github.com/root-project/root/commit/9339de9e644b06d5f77607f83aea118969cab7b6, https://github.com/root-project/root/commit/e16c3fd309e375e8aa781a6495a74a3f89b0cb25, https://github.com/root-project/root/commit/263508429dec26449513914e71f0f71c9ce9485f).

It's the same problem described here https://github.com/Homebrew/homebrew-core/issues/14418#issuecomment-324257556

Gist logs available at https://gist.github.com/soleti/fb9f29b969fdc047c9ef7e026ccae276

When I try to compile I get several errors like these:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
```

**Comment by soleti** [comment]
Reported here https://sft.its.cern.ch/jira/browse/ROOT-9026

**Comment by ilovezfs** [comment]
thx!

**Comment by matthewkenzie** [comment]
I pulled the master from root which has these patches in I think. And try the install myself (using the same cmake commands as brew). I get some error with free type instead:

[ 68%] Performing download step (verify and extract) for 'FREETYPE'
cd /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src && /usr/local/Cellar/cmake/3.9.3_1/bin/cmake -P /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-download-Release.cmake
-- FREETYPE download command succeeded.  See also /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-download-*.log
cd /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src && /usr/local/Cellar/cmake/3.9.3_1/bin/cmake -E touch /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/./FREETYPE-download
[ 69%] No patch step for 'FREETYPE'
/usr/local/Cellar/cmake/3.9.3_1/bin/cmake -E echo_append
/usr/local/Cellar/cmake/3.9.3_1/bin/cmake -E touch /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/./FREETYPE-patch
[ 69%] No update step for 'FREETYPE'
/usr/local/Cellar/cmake/3.9.3_1/bin/cmake -E echo_append
/usr/local/Cellar/cmake/3.9.3_1/bin/cmake -E touch /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/./FREETYPE-update
[ 69%] Performing configure step for 'FREETYPE'
cd /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE && /usr/local/Cellar/cmake/3.9.3_1/bin/cmake -P /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-Release.cmake
CMake Error at /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-Release.cmake:16 (message):
  Command failed: 2

   './configure' '--prefix' '/Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix' '--with-pic' '--disable-shared' '--with-png=no' '--with-bzip2=no' '--with-harfbuzz=no' 'CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc' 'CFLAGS=-O'

  See also

    /Users/matt/Library/Caches/Homebrew/root--git/build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-configure-*.log

**Comment by soleti** [comment]
Compiling the same .tar.gz standalone (cmake && make, without brew install) works fine. I think it's a problem related to Homebrew

**Comment by ilovezfs** [comment]
Sort of by definition not, since pre Xcode 9 it was fine ;)

**Comment by soleti** [comment]
I think it can be caused by `/usr/local/Homebrew/Library/Homebrew/shims/super/clang++`, while when I compile standalone I use `/usr/bin/clang++`. But I might be wrong of course...

**Comment by ilovezfs** [comment]
In any case, closing this out since it's an upstream issue.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`

**Comment by wickles** [comment]
FYI I found that I was not able to compile my projects against ROOT after upgrading to 6.10.06 without upgrading Xcode, due to missing/moved standard headers.
```
> % make
g++ -O3 -Wall -fPIC -pthread -stdlib=libc++ -std=c++11 -m64 -I/usr/local/Cellar/root/6.10.06/include/root -c DataStruct.cxx
In file included from DataStruct.cxx:2:
In file included from ./DataStruct.h:7:
In file included from /usr/local/Cellar/root/6.10.06/include/root/TROOT.h:28:
In file included from /usr/local/Cellar/root/6.10.06/include/root/TDirectory.h:25:
In file included from /usr/local/Cellar/root/6.10.06/include/root/TNamed.h:26:
In file included from /usr/local/Cellar/root/6.10.06/include/root/TString.h:28:
/usr/local/Cellar/root/6.10.06/include/root/RStringView.h:19:10: fatal error: 'string_view' file not found
#include <string_view>
         ^
1 error generated.
make: *** [DataStruct.o] Error 1
```
This error went away after updating to Xcode 9.0.
