### PR TITLE
libquvi 0.9.4, quvi 0.9.5 and cclive 0.9.3

### PR DESCRIPTION
**Pull request by ilovezfs**
libquvi:
- depend on glib, libgcrypt and libproxy

cclive:
- depend on glibmm
- depend on libquvi instead of quvi
- patches for Boost >=1.56, C++11 and glibc's strerror_r
- vendor luasocket

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 not sure about shipping this because libquvi now has some luarocks dependencies (see https://github.com/macports/macports-ports/blob/28bbe4a6ac928ec718fcb820c624f869abf63436/net/libquvi-scripts/Portfile#L21) and cclive in the PR. Thoughts?

File: Formula/cclive.rb [hunk 1]
```diff
@@ -14,16 +13,58 @@ class Cclive < Formula
...
+
+  # Fix build errors due to assumption of glibc's strerror_r and due to C++11
+  # requirement that there be a space between literal and identifier.
+  patch do
+    url "https://raw.githubusercontent.com/Homebrew/formula-patches/1266537/cclive/cxx11-and-strerror_r.diff"
+    sha256 "38ce495646de295e8cb2d6712d82f2d995db0601649197bc17ab01c5027e7845"
+  end
+
+  resource "luasocket" do
+    url "https://luarocks.org/luasocket-3.0rc1-2.src.rock"
```
Comment (DomT4) [inline Formula/cclive.rb]: Someone really needs to have a word with Luarocks about redirects someday:
```
x-object-url: http://commondatastorage.googleapis.com/moonrocks/54/luasocket-3.0rc1-2.src.rock?1
```
That URL supports `https://` but sure, whatever 😓.

**Comment by DomT4** [comment]
> libquvi now has some luarocks dependencies

Quite a few. That could be fun. I can take a look, if you like? I don't have a major objection to including more `luarocks` stuff in core now we have a default layout/system in place for it, but not completely ideal this is leaning on `lua@5.1` rather than simply `lua`. More we add now the longer we commit to keeping `lua@5.1` alive if anything breaks it 🙈.

**Comment by ilovezfs** [comment]
Note that libquvi already depends on lua@5.1. It's the luarocks deps that are new.

For the sake of argument, let's say we manage to fix libquvi so that it works with lua 5.3. It's not clear to me how we bundle luarocks into the libquvi scripts here without actually installing them globally linked into /usr/local.

**Comment by ilovezfs** [comment]
i.e. it feels like cclive should be able to consume libquvi without itself becoming responsible for bolting on the needed luarock

**Comment by ilovezfs** [comment]
Here's what happens with 5.3 btw
```
bash-3.2$  /usr/local/Cellar/cclive/0.9.3/bin/cclive --no-download https://youtu.be/VaVZL7F6vqU
dyld: lazy symbol binding failed: Symbol not found: _luaL_openlib
  Referenced from: /usr/local/opt/libquvi/lib/libquvi-0.9-0.9.4.dylib
  Expected in: flat namespace

dyld: Symbol not found: _luaL_openlib
  Referenced from: /usr/local/opt/libquvi/lib/libquvi-0.9-0.9.4.dylib
  Expected in: flat namespace

/usr/local/Cellar/cclive/0.9.3/bin/cclive: line 4: 81269 Trace/BPT trap: 5       "/usr/local/Cellar/cclive/0.9.3/libexec/bin/cclive" "$@"
bash-3.2$ 
```

**Comment by ilovezfs** [comment]
This is one of the cases where building lua 5.3 with `-DLUA_COMPAT_5_1` would fix it. :roll_eyes:

**Comment by DomT4** [comment]
> It's not clear to me how we bundle luarocks into the libquvi scripts here

A mass `inreplace` to prepend the desired path into each script? 🙈. I've done that sort of thing locally before, it's fun.

>  it feels like cclive should be able to consume libquvi without itself becoming responsible for bolting on the needed luarock

Yeah, I don't disagree here. It feels like a bit of a dance.

**Comment by ilovezfs** [comment]
>A mass inreplace to prepend the desired path into each script?

:sob:

**Comment by ilovezfs** [comment]
That is tempting though since libquvi is likely never to upgraded again …

**Comment by ilovezfs** [comment]
This is all too upsetting so I'm just closing this.

**Comment by DomT4** [comment]
I'll think about it a bit.
