### PR TITLE
opencascade 7.8.1

### PR DESCRIPTION
**Pull request by joe-warren**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> cmake --build build
  [ 50%] Building CXX object CMakeFiles/test.dir/main.cpp.o
  In file included from /tmp/opencascade-test-20240628-36405-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:19:
  In file included from /opt/homebrew/include/opencascade/Standard.hxx:21:
  /opt/homebrew/include/opencascade/Standard_Integer.hxx:82:1: error: unknown type name 'constexpr'
  constexpr Standard_Integer  IntegerFirst()
  ^
  /opt/homebrew/include/opencascade/Standard_Integer.hxx:82:27: error: expected ';' after top level declarator
  constexpr Standard_Integer  IntegerFirst()
                            ^
  In file included from /tmp/opencascade-test-20240628-36405-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:21:
  In file included from /opt/homebrew/include/opencascade/Standard_Handle.hxx:19:
  In file included from /opt/homebrew/include/opencascade/Standard_Transient.hxx:20:
  In file included from /opt/homebrew/include/opencascade/Standard_PrimitiveTypes.hxx:25:
  /opt/homebrew/include/opencascade/Standard_Real.hxx:60:1: error: unknown type name 'constexpr'
  constexpr Standard_Real     RealSmall()
  ^
  /opt/homebrew/include/opencascade/Standard_Real.hxx:60:24: error: expected ';' after top level declarator
  constexpr Standard_Real     RealSmall()
                         ^
  In file included from /tmp/opencascade-test-20240628-36405-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:21:
  In file included from /opt/homebrew/include/opencascade/Standard_Handle.hxx:19:
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:59:10: error: unknown type name 'constexpr'
    static constexpr const char* get_type_name () { return "Standard_Transient"; }
           ^
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:62:52: error: use of undeclared identifier 'Standard_Type'
    Standard_EXPORT static const opencascade::handle<Standard_Type>& get_type_descriptor ();
                                                     ^
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:65:53: error: use of undeclared identifier 'Standard_Type'
    Standard_EXPORT virtual const opencascade::handle<Standard_Type>& DynamicType() const;
                                                      ^
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:68:73: error: use of undeclared identifier 'Standard_Type'
    Standard_EXPORT Standard_Boolean IsInstance(const opencascade::handle<Standard_Type>& theType) const;  
                                                                          ^
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:76:69: error: use of undeclared identifier 'Standard_Type'
    Standard_EXPORT Standard_Boolean IsKind(const opencascade::handle<Standard_Type>& theType) const;
                                                                      ^
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:93:46: error: expected ';' at end of declaration list
    inline Standard_Integer GetRefCount() const noexcept { return myRefCount_; }
                                               ^
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:38:3: error: use of undeclared identifier 'Standard'
    DEFINE_STANDARD_ALLOC
    ^
  /opt/homebrew/include/opencascade/Standard_DefineAlloc.hxx:59:12: note: expanded from macro 'DEFINE_STANDARD_ALLOC'
      return Standard::Allocate (theSize);                               \
             ^
  In file included from /tmp/opencascade-test-20240628-36405-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:21:
  In file included from /opt/homebrew/include/opencascade/Standard_Handle.hxx:19:
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:38:3: error: use of undeclared identifier 'Standard'
  /opt/homebrew/include/opencascade/Standard_DefineAlloc.hxx:[63](https://github.com/Homebrew/homebrew-core/actions/runs/9715750892/job/26817956325?pr=175902#step:3:64):5: note: expanded from macro 'DEFINE_STANDARD_ALLOC'
      Standard::Free (theAddress);                                       \
      ^
  In file included from /tmp/opencascade-test-20240628-3[64](https://github.com/Homebrew/homebrew-core/actions/runs/9715750892/job/26817956325?pr=175902#step:3:65)05-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:21:
  In file included from /opt/homebrew/include/opencascade/Standard_Handle.hxx:19:
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:38:3: error: use of undeclared identifier 'Standard'
  /opt/homebrew/include/opencascade/Standard_DefineAlloc.hxx:[65](https://github.com/Homebrew/homebrew-core/actions/runs/9715750892/job/26817956325?pr=175902#step:3:66):3: note: expanded from macro 'DEFINE_STANDARD_ALLOC'
    DEFINE_STANDARD_ALLOC_ARRAY                                          \
    ^
  /opt/homebrew/include/opencascade/Standard_DefineAlloc.hxx:27:13: note: expanded from macro 'DEFINE_STANDARD_ALLOC_ARRAY'
       return Standard::Allocate (theSize);                              \
              ^
  In file included from /tmp/opencascade-test-20240628-36405-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:21:
  In file included from /opt/homebrew/include/opencascade/Standard_Handle.hxx:19:
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:38:3: error: use of undeclared identifier 'Standard'
  /opt/homebrew/include/opencascade/Standard_DefineAlloc.hxx:65:3: note: expanded from macro 'DEFINE_STANDARD_ALLOC'
    DEFINE_STANDARD_ALLOC_ARRAY                                          \
    ^
  /opt/homebrew/include/opencascade/Standard_DefineAlloc.hxx:31:6: note: expanded from macro 'DEFINE_STANDARD_ALLOC_ARRAY'
       Standard::Free (theAddress);                                      \
       ^
  In file included from /tmp/opencascade-test-20240628-36405-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:21:
  In file included from /opt/homebrew/include/opencascade/Standard_Handle.hxx:19:
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:43:26: error: member initializer 'myRefCount_' does not name a non-static data member or base class
    Standard_Transient() : myRefCount_(0) {}
                           ^~~~~~~~~~~~~~
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:46:52: error: member initializer 'myRefCount_' does not name a non-static data member or base class
    Standard_Transient (const Standard_Transient&) : myRefCount_(0) {}
                                                     ^~~~~~~~~~~~~~
  /opt/homebrew/include/opencascade/Standard_Transient.hxx:59:58: error: cannot initialize return object of type 'const int *' with an lvalue of type 'const char[19]'
    static constexpr const char* get_type_name () { return "Standard_Transient"; }
                                                           ^~~~~~~~~~~~~~~~~~~~
  In file included from /tmp/opencascade-test-20240628-36405-3ft450/main.cpp:1:
  In file included from /opt/homebrew/include/opencascade/Quantity_Color.hxx:21:
  /opt/homebrew/include/opencascade/Standard_Handle.hxx:3[79](https://github.com/Homebrew/homebrew-core/actions/runs/9715750892/job/26817956325?pr=175902#step:3:80):17: error: no member named 'IncrementRefCounter' in 'Standard_Transient'
          entity->IncrementRefCounter();
          ~~~~~~  ^
  /opt/homebrew/include/opencascade/Standard_Handle.hxx:385:34: error: no member named 'DecrementRefCounter' in 'Standard_Transient'
        if (entity != 0 && entity->DecrementRefCounter() == 0)
                           ~~~~~~  ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by joe-warren** [comment]
I've also modifed the opencascade test to use C++ 11, as this is (or more recent) is required by recent versions of opencascade.

**Comment by joe-warren** [comment]
I _think_ f3d just needs rebuilding, which I think can be done by bumping the revision?

**Comment by joe-warren** [comment]
I'm not totally sure what to do about this; I'm 90% sure that `gmsh` and `f3d` should work with `opencascade 7.8.1`, but they need rebuilding
I've incremened the revision of those packages to reflect this (although I'm not sure that this is correct?).
However, it looks like CI is now timing out now it's trying to build 3 packages.

Any help or advice would be appreciated?

**Comment by joe-warren** [comment]
Opened a discussion [here](https://github.com/orgs/Homebrew/discussions/5465) for visibility

**Review by ZhongRuoyu — APPROVED** [review]
Thank you for your first contribution to Homebrew, @joe-warren!
