### ISSUE TITLE
Formulae without Sierra bottles

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#6408]
Initially copied verbatim from https://github.com/Homebrew/homebrew-core/issues/5488. --ilovezfs (29 Oct 2016)

Jenkins finally managed to chew through the daunting Sierra build queue. Below are the remaining ones that defied (not necessarily only) Sierra for one reason or another.

The list is generated with the script https://gist.github.com/zmwangx/89f07670c8e42f58434bd6d15653ecf6. You can also pass a blacklist to the script to get a more workable list (e.g., putting `qt` and `qt5` in the blacklist blocks the entire Qt tree). See `need-bottle -h`.

---
\* means the formula now has an `:el_capitan_or_later` bottle but not a `:sierra` bottle yet.

Formulae that made the top 5000 install events chart during September 2016, ordered by popularity:
- [x] fb-adb (removed in https://github.com/Homebrew/homebrew-core/commit/9a4a8e63a667152196de72dbf4f3b97fe630b3f0)
- [x] ctorrent (redefinition of `clockid_t`)
- [x] open-zwave (https://github.com/Homebrew/brew/pull/1801)
- [x] libgroove (redefinition of `clockid_t` and `clock_gettime`; also fails on El Capitan)
- [x] vice (#8621)
- [x] libfaketime (https://github.com/Homebrew/homebrew-core/pull/18249)
- [ ] dshb (https://github.com/beltex/dshb/issues/36)
- [ ] libbladerf (redefinition of `clockid_t`)
- [ ] darkstat (redefinition of `clockid_t`)
- [x] valgrind (https://github.com/Homebrew/homebrew-core/pull/14653)

---
Obscure formulae that didn't make the top 5000 install events chart (some of these need to be thrown into boneyard — no mercy for the weak):
- [x] aiccu
- [x] blucat
- [x] buildapp
- [x] compface
- [x] dsd (#8590)
- [x] intercal (#8591)
- [x] jxrlib (#8608)
- [x] libodfgen
- [x] mimms (#8594)
- [x] nordugrid-arc
- [x] parrot (https://github.com/Homebrew/brew/pull/1801)
- [x] qpm (#8593)
- [x] qtplay (#8614)
- [x] rdate (#8611)
- [x] saldl (10.12: error: pointer is missing a nullability type specifier; 10.11: error: implicit declaration of function 'clock_gettime' is invalid in C99 and error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW')

---
- [x] qt5
- [x] xctool (https://github.com/facebook/xctool/issues/716)
- [x] swiftlint (swift 2.2, https://github.com/realm/SwiftLint/issues/815)
- [x] pypy ([upstream issue](https://bitbucket.org/pypy/pypy/issues/2407/pypy-541-fails-to-build-on-macos-sierra), #5689)
- [x] pyqt (qt, #1705)
- [x] pyqt5
- [x] qscintilla2 (https://github.com/Homebrew/homebrew-core/pull/5786)
- [x] swiftgen (https://github.com/Homebrew/homebrew-core/pull/6663)
- [x] qwt
- [x] allegro (#6017)
- [x] pyside
- [x] shiboken
- [x] gnuradio
- [x] upx (https://github.com/Homebrew/homebrew-core/pull/7956)
- [x] infer (#7057)
- [x] jack (#5487)
- [x] qca
- [x] qwtpolar
- [x] binwalk
- [x] git-cola (#6210)
- [x] folly (#5548)
- [x] gpsbabel
- [x] qcachegrind
- [x] radare2
- [x] libewf (libyal/libewf#60, #5737)
- [x] dvm (#5587)
- [x] irrlicht (#5592)
- [x] tcptrace (#6223)
- [x] *imagesnap (project dead since 2011, but 10.11 bottle works on 10.12 unmodified)
- [x] uwsgi (https://github.com/Homebrew/homebrew-core/pull/5528)
- [x] log4cxx
- [x] capnp (#5773, https://github.com/sandstorm-io/capnproto/issues/375)
- [x] swift (https://github.com/Homebrew/homebrew-core/pull/6645)
- [x] fpc (#5732)
- [x] syncthing-inotify
- [x] pgloader (#6698)
- [x] volatility (#8324)
- [x] libqglviewer (qt, #1705)
- [x] sift (https://github.com/svent/sift/pull/80)
- [x] shairport-sync
- [x] pyside-tools
- [x] otto (#7924)
- [x] ace
- [x] ircii (#6404)
- [x] juju (0edadae312832a3c8e4c993a1922109cb6f0259b)
- [x] dcmtk
- [x] io (#6109)
- [x] xml2 (#6405)
- [x] tomcat-native (#7448)
- [x] moc
- [x] natalie
- [x] rack (#7924)
- [x] codequery
- [x] zurl
- [x] opencsg
- [x] kube-aws
- [x] libmongoclient
- [x] shibboleth-sp (#5546)
- [x] bashdb (#6407)
- [x] bokken
- [x] castxml
- [x] debianutils
- [x] taylor (##7216)
- [x] distcc (migrated from Google Code to https://github.com/distcc/distcc, but no new release)
- [x] darkice
- [x] pushpin
- [x] gsoap
- [x] dc3dd (seems good to go)
- [x] sqliteman
- [x] aurora-cli (#6006)
- [x] djview4 (https://github.com/Homebrew/homebrew-core/pull/5736)
- [x] gecode (https://github.com/Homebrew/homebrew-core/pull/4439)
- [x] frescobaldi
- [x] libbtbb (#6401)
- [x] qjackctl
- [x] chuck (#5855)
- [x] puddletag
- [x] qjson (qt, #1705)
- [x] ssdb (ideawu/ssdb#995, #5734)
- [x] dspdfviewer
- [x] st
- [x] coin (qt, #1705)
- [x] mftrace
- [x] makepkg (#6402)
- [x] aws-apigateway-importer (#6403)
- [x] cfengine (https://github.com/Homebrew/homebrew-core/pull/5513)
- [x] fstar (https://github.com/Homebrew/homebrew-core/pull/6635)

---

- [x] activemq-cpp
- [x] automoc4
- [x] bzr-explorer (#6738)
- [x] coccinelle (#6318)
- [x] ctail
- [x] cuty_capt
- [x] dirt
- [x] exim (#6089)
- [x] ezlupdate (#5722)
- [x] fastd ([upstream issue](https://projects.universe-factory.net/issues/239), #6012)
- [x] fdroidserver (https://github.com/Homebrew/homebrew-core/pull/6440)
- [x] gammaray
- [x] globus-toolkit (#6587)
- [x] ipbt (#6637)
- [x] ironcli
- [x] libechonest (#6819)
- [x] libetonyek (#6583)
- [x] libfabric (#6551)
- [x] liblastfm (#6740)
- [x] ltc-tools
- [x] md
- [x] mdds (#6580)
- [x] mighttpd2
- [x] mmix (#6384)
- [x] openvdb (#7007)
- [x] qbs
- [x] quazip (#6821)
- [x] qxmpp (#6822)
- [x] rcssserver
- [x] remctl
- [x] schismtracker (#6692)
- [x] sfk https://github.com/Homebrew/homebrew-core/pull/6064
- [x] snappystream (#7232)
- [x] srclib (#7259)
- [x] swish-e
- [x] tbox (#6392)
- [x] tevent
- [x] tlassemble
- [x] uberftp
- [x] ubertooth
- [x] valkyrie
- [x] weboob
- [x] writerperfect
- [x] wyrd
- [x] xar-mackyle

**Comment by Eitot** [comment]
`imagesnap` seems to have reached a dead end with Xcode 8, due to the removal of QTKit in SDK 10.12. Xcode 8 bundles only this SDK, so it affects El Capitan as well.

ref. Homebrew/homebrew-science#4303.

**Comment by zmwangx** [comment]
Could you please try to build `dc3dd` and `io`, and possibly also `gecode` on Sierra Testing?

**Comment by ilovezfs** [comment]
lol.

**Comment by ilovezfs** [comment]
@zmwangx 
https://bot.brew.sh/job/Homebrew%20Sierra%20Testing/1137/
https://bot.brew.sh/job/Homebrew%20Sierra%20Testing/1138/
https://bot.brew.sh/job/Homebrew%20Sierra%20Testing/1139/

**Comment by zmwangx** [comment]
Thanks. Apparently `io` has already been bottled which I didn't notice... `gecode` succeeded. And CI bugged out again on `dc3dd`.

**Comment by leaveye** [comment]
how about add `valgrind` to the list

**Comment by ilovezfs** [comment]
@leaveye added.

**Comment by tyteen4a03** [comment]
Valgrind [3.12.0](http://valgrind.org/docs/manual/dist.news.html) introduced preliminary Sierra support.

**Comment by zmwangx** [comment]
@tyteen4a03 Not good enough. See https://github.com/Homebrew/homebrew-core/pull/6231.

**Comment by Moisan** [comment]
[`libfabric` has a PR for a new version.](https://github.com/Homebrew/homebrew-core/pull/6551)

**Comment by ilovezfs** [comment]
@Moisan yes, that's my PR :laughing:

**Comment by zmwangx** [comment]
swiftgen done (#6663).

**Comment by tsparber** [comment]
fdroidserver done (https://github.com/Homebrew/homebrew-core/pull/6440)

**Comment by Moisan** [comment]
I think PR #6064 got lost during the transition from issue #5488.

**Comment by Moisan** [comment]
- `libechonest`has been moved to boneyard #6819 
- `ezlupdate` has been moved to boneyard too #5722
- `blucat` builds fine on my end.

**Comment by Moisan** [comment]
`coccinelle` has been updated #6318 and now has a bottle.

**Comment by zmwangx** [comment]
Also resolved: pyqt, imagesnap, libqglviewer.

**Comment by Moisan** [comment]
`exim` has been resolved.

**Comment by ilovezfs** [comment]
I have refreshed the lists here and moved the incomplete ones to the top. Great work so far everyone who has contributed to making progress on Sierra support.

Quick status update. From the original lists the following still need to be bottled for Sierra:

Popular list:
fb-adb, ctorrent, open-zwave, libgroove, vice, libfaketime, dshb, libbladerf, darkstat, valgrind

Less popular list:
aiccu, blucat, buildapp, compface, dsd, intercal, jxrlib, libodfgen, mimms, nordugrid-arc, parrot, qpm, qtplay, rdate, saldl

**Comment by zmwangx** [comment]
Great, we might have a chance of being able to close this by the time the 10.13 warning is added to brew.

**Comment by Moisan** [comment]
`libodfgen` builds fine on my side and the test passes.

**Comment by ilovezfs** [comment]
@Moisan yup, built fine. Bottle added.

**Comment by ilovezfs** [comment]
This is superseded by [the equivalent for High Sierra](https://github.com/Homebrew/homebrew-core/issues/18493).

Thanks to everyone who helped here :heart: and especially to @zmwangx, who created the original one https://github.com/Homebrew/homebrew-core/issues/5488.
