### PR TITLE
glew 2.3.0

### PR DESCRIPTION
**Pull request by botantony**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by Niram7777** [comment]
> > There are missing extensions with 2.3.0 and I can't install glew@2.2.0 because it doesn't exist.
> > ```
> > /Users/runner/work/rpcs3/rpcs3/rpcs3/Emu/RSX/GL/glutils/buffer_object.cpp:47:4: error: use of undeclared identifier 'glNamedBufferStorageEXT'; did you mean '__glewBufferStorageEXT'?
> >    47 |                         DSA_CALL2(NamedBufferStorage, m_id, size, data_, flags);
> >       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > /Users/runner/work/rpcs3/rpcs3/rpcs3/Emu/RSX/GL/glutils/common.h:39:3: note: expanded from macro 'DSA_CALL2'
> >    39 |                 gl##func##EXT(__VA_ARGS__);
> >       |                 ^~~~~~~~~~~~~
> > <scratch space>:70:1: note: expanded from here
> >    70 | glNamedBufferStorageEXT
> >       | ^~~~~~~~~~~~~~~~~~~~~~~
> > /usr/local/include/GL/glew.h:24223:43: note: '__glewBufferStorageEXT' declared here
> >  24223 | GLEW_FUN_EXPORT PFNGLBUFFERSTORAGEEXTPROC __glewBufferStorageEXT;
> >        |                                           ^
> > 1 error generated.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you keep 2.2.0 available ?
> 
> It will be fixed with [nigels-com/glew#455](https://github.com/nigels-com/glew/pull/455)

I still believe Homebrew should keep both versions as a temporary solution

**Comment by p-linnane** [comment]
@Niram7777 That's not how Homebrew works. We only add versioned formulae for very popular software that has multiple supported versions like PostgreSQL and GCC.

I'll open a PR adding that upstream patch and we'll see if it helps. If you have any ideas for updating the `glew` formula test to catch this kind of issue in the future it would be appreciated.

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/259963

**Comment by p-linnane** [comment]
Homebrew ships the latest upstream releases. When a downstream project breaks against a new upstream version, fixing that incompatibility is the upstream project’s responsibility; Homebrew simply distributes the result.

`stable` is the latest tagged release and `HEAD` tracks upstream development. Neither implies downstream compatibility guarantees. The patch PR I opened addresses the issue you're experiencing.

**Comment by Alexbal52** [comment]
> @Niram7777 That's not how Homebrew works. We only add versioned formulae for very popular software that has multiple supported versions like PostgreSQL and GCC.
> 
> I'll open a PR adding that upstream patch and we'll see if it helps. If you have any ideas for updating the `glew` formula test to catch this kind of issue in the future it would be appreciated.

The mac intel build still fail to compile with https://github.com/Homebrew/homebrew-core/pull/259963 merged 
IMG_0111

**Comment by Alexbal52** [comment]
> There are missing extensions with 2.3.0 and I can't install glew@2.2.0 because it doesn't exist.
> 
> ```
> /Users/runner/work/rpcs3/rpcs3/rpcs3/Emu/RSX/GL/glutils/buffer_object.cpp:47:4: error: use of undeclared identifier 'glNamedBufferStorageEXT'; did you mean '__glewBufferStorageEXT'?
>    47 |                         DSA_CALL2(NamedBufferStorage, m_id, size, data_, flags);
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/runner/work/rpcs3/rpcs3/rpcs3/Emu/RSX/GL/glutils/common.h:39:3: note: expanded from macro 'DSA_CALL2'
>    39 |                 gl##func##EXT(__VA_ARGS__);
>       |                 ^~~~~~~~~~~~~
> <scratch space>:70:1: note: expanded from here
>    70 | glNamedBufferStorageEXT
>       | ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/local/include/GL/glew.h:24223:43: note: '__glewBufferStorageEXT' declared here
>  24223 | GLEW_FUN_EXPORT PFNGLBUFFERSTORAGEEXTPROC __glewBufferStorageEXT;
>        |                                           ^
> 1 error generated.
> ```
> 
> Could you keep 2.2.0 available ?

The mac intel build is fixed on PR https://github.com/RPCS3/rpcs3/pull/17920
