### ISSUE TITLE
mkvtoolnix failed to build on 10.14.2

### ISSUE THREAD

**Issue by naos** [Homebrew/homebrew-core#35256]
```
==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/29.0.0_1 --with-boost=/usr/local/opt/boost --with-docbook-xsl-root=/usr/local/opt/docbook-xsl/docbook-xsl 
==> rake -j8
Last 15 lines from /Volumes/Users/nikola/Library/Logs/Homebrew/mkvtoolnix/02.rake:
         CXX src/mkvtoolnix-gui/util/waiting_spinner_widget.cpp
         CXX src/mkvtoolnix-gui/util/widget.cpp
         CXX src/mkvtoolnix-gui/watch_jobs/tab.cpp
         CXX src/mkvtoolnix-gui/watch_jobs/tool.cpp
         RCC src/mkvtoolnix-gui/qt_resources.qrc
         CXX src/mkvtoolnix-gui/qt_resources.cpp
        LINK src/mkvtoolnix-gui/mkvtoolnix-gui
ld: warning: object file (/usr/local/lib/libfmt.a(format.cc.o)) was built for newer OSX version (10.14) than being linked (10.9)
ld: warning: object file (/usr/local/Cellar/pugixml/1.9/lib/pugixml-1.9/libpugixml.a(pugixml.cpp.o)) was built for newer OSX version (10.13) than being linked (10.9)
Undefined symbols for architecture x86_64:
  "___CFConstantStringClassReference", referenced from:
      CFString in macos.o
      CFString in macos.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
[https://gist.github.com/c740aacaa0439d0ab926c398589c629c](https://gist.github.com/c740aacaa0439d0ab926c398589c629c)

**Comment by BenjaminDigeon** [comment]
Exactly the same error when i try to upgrade from version 28.2.0 to 29.0.0_1 with qt.

**Comment by Jumacbook** [comment]
+1

**Comment by leetoburrito** [comment]
I'm seeing this as well.

**Comment by retokromer** [comment]
Exactly the same error here on macOS 10.13.6 as well.

**Comment by SMillerDev** [comment]
Does it work without QT?

**Comment by retokromer** [comment]
>Does it work without QT?

Yes, without the Qt GUI it works.

**Comment by sjml** [comment]
Hi @MikeMcQuaid! I know there's currently an overall effort to remove options, and I totally understand the move in that direction. I'd implore, in the case, to not move too quickly on pulling this one. The Qt interface for mkvtoolnix is a very hard thing to get building independently of Homebrew, and this formula was working very reliably before the most recent update. 

I'm happy to take a look and dig in to see what broke and how best to fix it if you'd like, but it would great to have some time to investigate before we just reflexively yank the option.

**Comment by sjml** [comment]
Before I investigate further, though, @AlexaraWu, since you made the last few commits and it looks like there was some question about including fmt as a dependency, do you have some insight here? (Since the error message is coming from a build mismatch with libfmt...)

**Comment by BorisDr** [comment]
Fmt and pugixml prevents from building --with-qt enabled option

**Comment by MikeMcQuaid** [comment]
> The Qt interface for mkvtoolnix is a very hard thing to get building independently of Homebrew, and this formula was working very reliably before the most recent update.

The option is going to eventually either be made default or removed.

**Comment by sjml** [comment]
> The option is going to eventually either be made default or removed.

Right, I know that's the overall goal. I just know the easier option is to quickly remove it, and wanted to put in my two cents that it not be done too quickly, especially before the most recent contributor to the formula has a chance to weigh in. My guess would be that the Qt option is more likely to go away than become default since it's a big GUI dependency, so at least wanted to make sure that the process for making that decision wasn't over-hasty.

**Comment by Arkensaw** [comment]
I think there is still a need for the UI but it actually would be better to create a cask for this. The problem is, that the project does not release MacOS binaries.

**Comment by hagabla** [comment]
The GUI is needed, at least by me.

**Comment by reatlat** [comment]
@hagabla 
Why not use compiled version? 
https://www.fosshub.com/MKVToolNix.html
https://mkvtoolnix.download/macos/MKVToolNix-29.0.0.dmg

**Comment by reatlat** [comment]
@retokromer haha, yes, I know, just wandering @hagabla needs the last version right now,
BTW I test build version... and the color scheme works wrong :/ I can't read any text in app :(
switched to Linux machine =) on Linux works perfect :)

**Comment by sjml** [comment]
> @hagabla
> Why not use compiled version?
> https://www.fosshub.com/MKVToolNix.html
> https://mkvtoolnix.download/macos/MKVToolNix-29.0.0.dmg

Huh! I didn’t know they did compiled releases. Could we make a cask out of this and then leave the brew formula as the command line version?

**Comment by MikeMcQuaid** [comment]
@sjml this seems like the best idea so far 👍🏻

**Comment by Arkensaw** [comment]
I just did a quick test. A simple cask made from the second URL works ok. The first URL from Fosshub will not work though as Fosshub does not allow scripted or automated downloads.

**Comment by naos** [comment]
> @retokromer haha, yes, I know, just wandering @hagabla needs the last version right now,
> BTW I test build version... and the color scheme works wrong :/ I can't read any text in app :(
> switched to Linux machine =) on Linux works perfect :)

Which version have you tested? Color scheme was problem with mojave dark mode in earlier versions. They fixed it, there are no visibility problems in version 28.2.0, it works perfectly.

**Comment by fxcoudert** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/35383

**Comment by danieljl** [comment]
> > @retokromer haha, yes, I know, just wandering @hagabla needs the last version right now,
> > BTW I test build version... and the color scheme works wrong :/ I can't read any text in app :(
> > switched to Linux machine =) on Linux works perfect :)
> 
> Which version have you tested? Color scheme was problem with mojave dark mode in earlier versions. They fixed it, there are no visibility problems in version 28.2.0, it works perfectly.

@naos I'm not the one you were asking, but I too have the same problem with the latest version (29.0.0):

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1947204/50534467-a3ddac80-0b6f-11e9-9dc1-75b38225631c.png">

I installed the latest version via `brew cask install mkvtoolnix-app` since `mkvtoolnix` in homebrew-core cannot be built with `--with-qt` option anymore. So, maybe the problem comes from the prebuilt binary.

Can we put `--with-qt` option back and apply #35364 (some have confirmed this fixed the build issue) instead? We can still remove it from the default options.

**Comment by danieljl** [comment]
@MikeMcQuaid If the option is not default, it doesn't hurt, I guess?

**Comment by MikeMcQuaid** [comment]
@danieljl https://github.com/Homebrew/homebrew-core/issues/31510

**Comment by retokromer** [comment]
Then I would suggest to hard-enable Qt. 
cc @mbunkus

**Comment by danieljl** [comment]
@MikeMcQuaid I still don't understand why optional options are discouraged. Surely there should be some sane defaults if users install the package without any options. But, we can still provide optional options for users who wants more customizability. And it won't hurt users who install it without any options.

**Comment by mbunkus** [comment]
> and the color scheme works wrong :/ I can't read any text in app :(

This is a bug in Qt wrt. the dark color scheme in Mojave that was fixed in Qt 5.12.0. See [here](https://gitlab.com/mbunkus/mkvtoolnix/issues/2407) for details and links to a v29 DMG linked against Qt 5.12.0.

**Comment by mbunkus** [comment]
I don't know what "cask" means in this context. If I understand this issue correctly, the Homebrew version of MKVToolNix now comes without the GUI; is that correct? In that case I'll probably remove the link from the MKVToolNix home page as I don't want to recommend incomplete packages.

**Comment by MikeMcQuaid** [comment]
> See [here](https://gitlab.com/mbunkus/mkvtoolnix/issues/2407) for details and links to a v29 DMG linked against Qt 5.12.0.

@mbunkus Nice work thanks 🎉 

> If I understand this issue correctly, the Homebrew version of MKVToolNix now comes without the GUI; is that correct?

`brew install mkvtoolnix` installs the CLI rather than the GUI, yes.

> In that case I'll probably remove the link from the MKVToolNix home page as I don't want to recommend incomplete packages.

Instead please consider changing the installation instructions to `brew cask install mkvtoolnix-app` which will install your DMG and no longer requires building from source.

**Comment by MikeMcQuaid** [comment]
> This is a bug in Qt wrt. the dark color scheme in Mojave that was fixed in Qt 5.12.0. See [here](https://gitlab.com/mbunkus/mkvtoolnix/issues/2407) for details and links to a v29 DMG linked against Qt 5.12.0.

Also to others in this thread: once this is an "official" release the changes here will be applied to the Cask once it's updated (same process as a formula).
