### PR TITLE
cjdns: fix build to find python executable

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Failure seen in `rust` PR #98823

### CODE REVIEW

File: Formula/cjdns.rb [hunk 1]
```diff
@@ -18,7 +18,17 @@ class Cjdns < Formula
...
+  on_macos do
+    # Fails to build with python@3.10.
+    # AttributeError: module 'collections' has no attribute 'MutableSet'
+    # Related PR: https://github.com/cjdelisle/cjdns/pull/1246
+    depends_on "python@3.9" => :build
+  end
+
   def install
+    # Libuv build fails on macOS with: env: python: No such file or directory
+    ENV.prepend_path "PATH", Formula["python@3.9"].opt_libexec/"bin" if OS.mac?
```
Comment (cho-m) [inline Formula/cjdns.rb:30]: Checking macOS-only first as not sure if `python` executable was ever on PATH in Linux CI.

**Review by SMillerDev — APPROVED** [review]
