### ISSUE TITLE
Tcl-tk does not build on 10.9 with gcc@7

### ISSUE THREAD

**Issue by cbertelli** [Homebrew/homebrew-core#28850]
This is the error:

Last 15 lines from /Users/carlo/Library/Logs/Homebrew/tcl-tk/06.make:
/private/tmp/tcl-tk--tk-20180610-83460-8gssds/tk8.6.8/unix/../macosx/tkMacOSXXStubs.c:183:2: error: use of undeclared identifier 'NSOperatingSystemVersion'
        NSOperatingSystemVersion systemVersion = [[NSProcessInfo processInfo] operatingSystemVersion];
        ^
/private/tmp/tcl-tk--tk-20180610-83460-8gssds/tk8.6.8/unix/../macosx/tkMacOSXXStubs.c:184:10: error: use of undeclared identifier 'systemVersion'
        major = systemVersion.majorVersion;
                ^
/private/tmp/tcl-tk--tk-20180610-83460-8gssds/tk8.6.8/unix/../macosx/tkMacOSXXStubs.c:185:10: error: use of undeclared identifier 'systemVersion'
        minor = systemVersion.minorVersion;
                ^
/private/tmp/tcl-tk--tk-20180610-83460-8gssds/tk8.6.8/unix/../macosx/tkMacOSXXStubs.c:186:10: error: use of undeclared identifier 'systemVersion'
        patch = systemVersion.patchVersion;
                ^
4 errors generated.
make: *** [tkMacOSXXStubs.o] Error 1
make: *** Waiting for unfinished jobs....

And this is the  gist from brew gist-logs tcl-tk:
https://gist.github.com/e93ff6b8b25ed024c5ef3d3887d16891

**Comment by cbertelli** [comment]
Eventually, even using gcc@7, tcl-tk did not build with:

Last 15 lines from /Users/carlo/Library/Logs/Homebrew/tcl-tk/06.make:
                           ^
/private/tmp/tcl-tk--tk-20180610-42357-jjl0ha/tk8.6.8/unix/../macosx/tkMacOSXDialog.c: In function 'Tk_GetSaveFileObjCmd':
/private/tmp/tcl-tk--tk-20180610-42357-jjl0ha/tk8.6.8/unix/../macosx/tkMacOSXDialog.c:996:27: error: expected expression before '^' token
         completionHandler:^(NSInteger returnCode)
                           ^
/private/tmp/tcl-tk--tk-20180610-42357-jjl0ha/tk8.6.8/unix/../macosx/tkMacOSXDialog.c: In function 'Tk_ChooseDirectoryObjCmd':
/private/tmp/tcl-tk--tk-20180610-42357-jjl0ha/tk8.6.8/unix/../macosx/tkMacOSXDialog.c:1146:27: error: expected expression before '^' token
         completionHandler:^(NSInteger returnCode)
                           ^
/private/tmp/tcl-tk--tk-20180610-42357-jjl0ha/tk8.6.8/unix/../macosx/tkMacOSXDialog.c: In function 'Tk_MessageBoxObjCmd':
/private/tmp/tcl-tk--tk-20180610-42357-jjl0ha/tk8.6.8/unix/../macosx/tkMacOSXDialog.c:1429:27: error: expected expression before '^' token
         completionHandler:^(NSModalResponse returnCode)
                           ^
make: *** [tkMacOSXDialog.o] Error 1
make: *** Waiting for unfinished jobs....

This is the new gist from brew gist-logs tcl-tk:
https://gist.github.com/69568c63953482f1f35502cf0c94a4cc

**Comment by ilovezfs** [comment]
This is
https://trac.macports.org/ticket/55649
https://core.tcl.tk/tcl/tktview/95a8293a2936e34cc8d0658c21e5214f1ca9b435

The needed patch is https://github.com/macports/macports-ports/commit/0a883ad388b2cbecf14f5ed674bfc9b6d2ce6f23

**Comment by ilovezfs** [comment]
I've fixed it in https://github.com/Homebrew/homebrew-core/pull/28857 so it should work if you `brew update`.

**Comment by cbertelli** [comment]
Yes! It did and I could build grass7 and QGIS too! Many thanks.

**Comment by cbertelli** [comment]
I was too quick saying I could build QGIS. It crashed saying it was built, but it wasn't.
I kept trying, but it consistently freezed after a while (40 minutes) for three times. This is not to bother you, but to ask to keep this open. I saved a gist to be able to trace the error, but let me try another time.
This is the gist, anyway.
https://gist.github.com/9959a447c9a90d31c480cefc328c230f

**Comment by cbertelli** [comment]
I tried again with the same outcome. This is the gist. If it stopped or crashed it could be the fault of the formula, freezing seems another thing and maybe you could suggest something. Here is the gist:
https://gist.github.com/40ff46b0c76b00feb9a2a0c6058d77aa
