### PR TITLE
fb303: add fbthrift test dep

### PR DESCRIPTION
**Pull request by chenrui333**
```
/usr/local/Cellar/fb303/2023.10.23.00/include/fb303/thrift/gen-cpp2/BaseService.h:9:10: fatal error: 'thrift/lib/cpp2/gen/service_h.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

found in #152259
regression test, https://github.com/chenrui333/github-action-test/actions/runs/6659200739/job/18097771742

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

followup of #152259

----

I can confirm the file is indeed missing in the bottle

```
==> Downloading https://ghcr.io/v2/homebrew/core/fb303/blobs/sha256:681a105e906d42e7b85e9ddb5ad5c2655e634985d8cc8e8c5f36bb2a63fcdd39
Already downloaded: /Users/rui/Library/Caches/Homebrew/downloads/a805257a89043e38efecf18c4a43ea207bbc08998bc76842e9bb36536d283af9--fb303--2023.10.23.00.arm64_ventura.bottle.tar.gz

$ fd service_h.h /Users/rui/Library/Caches/Homebrew/downloads/fb303/2023.10.23.00/include/fb303
$
```

### CODE REVIEW

**Comment by chenrui333** [comment]
weird, it still does not have the service_h.h file
```
  /opt/homebrew/Cellar/fb303/2023.10.23.00_1/include/fb303/thrift/gen-cpp2/BaseService.h:9:10: fatal error: 'thrift/lib/cpp2/gen/service_h.h' file not found
  #include <thrift/lib/cpp2/gen/service_h.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```

**Comment by Bo98** [comment]
Looks to me that `fbthrift` is should not be build-only as it's needed to use `fb303` headers.

It likely broke after it changed in https://github.com/Homebrew/homebrew-core/commit/9b89968c88a098ce61641e55e2b1779c48b7151e

**Comment by carlocab** [comment]
Could probably be `:build` and `:test`, since you likely won't need the `fbthrift` headers at runtime if you just link to an `fb303` library.

**Comment by chenrui333** [comment]
cool, let me update the build.

**Review by p-linnane — APPROVED** [review]
