### ISSUE TITLE
openssh from bottle doesn't work on 10.12.0

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#9077]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:
```
ssh -T git@github.com
dyld: lazy symbol binding failed: Symbol not found: _timingsafe_bcmp
  Referenced from: /usr/local/bin/ssh
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _timingsafe_bcmp
  Referenced from: /usr/local/bin/ssh
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

**Comment by sds** [comment]
Could you share how you fixed this problem, @yurikoles?

**Comment by yurikoles** [comment]
I have reported it to dupes https://github.com/Homebrew/homebrew-dupes/issues/716
And a workaround is very simple: just upgrade to new release of macOS :)
