### PR TITLE
include-what-you-use: revision bump (llvm 21)

### LINKED ISSUE #1825: `fatal error: 'stdarg.h' file not found` when bumping llvm to 21.1.2
👋 seeing the following regression test failure when bumping llvm to 21.1.2

```
  ==> /opt/homebrew/Cellar/include-what-you-use/0.25/bin/include-what-you-use main.cc -Xiwyu --mapping_file=/opt/homebrew/opt/llvm/include/c++/v1/libcxx.imp 2>&1
  In file included from main.cc:1:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/iostream:45:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/ios:228:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale:17:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale_dir/locale_base_api.h:115:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale_dir/support/apple.h:18:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale_dir/support/bsd_like.h:23:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/wchar.h:116:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX26.sdk/usr/include/wchar.h:67:
  /Library/Developer/CommandLineTools/SDKs/MacOSX26.sdk/usr/include/_wchar.h:90:10: fatal error: 'stdarg.h' file not found
     90 | #include <stdarg.h>
        |          ^~~~~~~~~~
```

relates to https://github.com/Homebrew/homebrew-core/pull/245468

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

Test failure seen with llvm 21.1.2 in #245468

```
$ include-what-you-use --print-resource-dir
/opt/homebrew/Cellar/llvm/21.1.1/lib/clang/21
```

Fixes https://github.com/include-what-you-use/include-what-you-use/issues/1825

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by cho-m** [comment]
We likely want to tune `IWYU_RESOURCE_RELATIVE_TO` and `IWYU_RESOURCE_DIR` to avoid recording the Cellar path to LLVM.

Haven't tested but something like:
```rb
resource_dir = Pathname(Utils.safe_popen_read(llvm.opt_bin/"clang", "-print-resource-dir").chomp)
resource_dir = resource_dir.sub(llvm.prefix.realpath, llvm.opt_prefix)
...
%W[
  -DIWYU_RESOURCE_RELATIVE_TO=iwyu
  -DIWYU_RESOURCE_DIR=#{resource_dir.relative_path_from(bin)}
]
```

The problem with default `IWYU_RESOURCE_RELATIVE_TO=clang` is it uses the realpath to Clang in `IWYU_RESOURCE_BINARY_PATH` which breaks on every revision/version bump.

`IWYU_RESOURCE_RELATIVE_TO=iwyu` calculates the path at runtime via `IWYU_RESOURCE_DIR`
