### PR TITLE
Migrate some formulas to openssl 1.1 (A)

### PR DESCRIPTION
**Pull request by fxcoudert**
Formula beginning with `a` that depend on `openssl` and are not part of more complex dependency chains. Let's see how many build with openssl 1.1

### CODE REVIEW

**Comment by fxcoudert** [comment]
Only one failure! 🎈

`apib` fails to build with:
```
In file included from apib_lines.c:17:
./apib_common.h:23:10: fatal error: 'apr_file_io.h' file not found
#include <apr_file_io.h>
```
