### PR TITLE
glib 2.84.0

### PR DESCRIPTION
**Pull request by botantony**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to #210308

### CODE REVIEW

**Comment by botantony** [comment]
```
  --- stderr ---
  Traceback (most recent call last):
    File "/tmp/glib--gobject-introspection-20250309-6056-vrxdk1/gobject-introspection-1.83.4/build/tools/g-ir-scanner", line 104, in <module>
      sys.exit(scanner_main(sys.argv))
               ~~~~~~~~~~~~^^^^^^^^^^
    File "/tmp/glib--gobject-introspection-20250309-6056-vrxdk1/gobject-introspection-1.83.4/build/giscanner/scannermain.py", line 615, in scanner_main
      ss, filenames = create_source_scanner(options, args)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
    File "/tmp/glib--gobject-introspection-20250309-6056-vrxdk1/gobject-introspection-1.83.4/build/giscanner/scannermain.py", line 473, in create_source_scanner
      ss.parse_files(filenames)
      ~~~~~~~~~~~~~~^^^^^^^^^^^
    File "/tmp/glib--gobject-introspection-20250309-6056-vrxdk1/gobject-introspection-1.83.4/build/giscanner/sourcescanner.py", line 266, in parse_files
      self._parse(headers)
      ~~~~~~~~~~~^^^^^^^^^
    File "/tmp/glib--gobject-introspection-20250309-6056-vrxdk1/gobject-introspection-1.83.4/build/giscanner/sourcescanner.py", line 298, in _parse
      cc = CCompiler(compiler_name=self._compiler)
    File "/tmp/glib--gobject-introspection-20250309-6056-vrxdk1/gobject-introspection-1.83.4/build/giscanner/ccompiler.py", line 176, in __init__
      compiler_name = distutils.ccompiler.get_default_compiler()
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'distutils' has no attribute 'ccompiler'. Did you mean: 'compilers'?
  ```

**Comment by botantony** [comment]
New version of `gobject-introspection` uses deprecated Python methods (doesn't work with Python 3.12+). I do not have GNOME GitLab account (and for some reason it doesn't allow me to use my regular GitLab), it'd be nice if someone could create a new issue 🙏 https://gitlab.gnome.org/GNOME/gobject-introspection

**Comment by botantony** [comment]
hmm... maybe i was wrong and it requires [`setuptools`](https://pypi.org/project/setuptools/) python module now

**Comment by botantony** [comment]
pypa/setuptools/issues/3583

File: Formula/g/glib.rb [hunk 1]
```diff
@@ -51,14 +51,8 @@ class Glib < Formula
...
   resource "gobject-introspection" do
-    url "https://download.gnome.org/sources/gobject-introspection/1.82/gobject-introspection-1.82.0.tar.xz"
-    sha256 "0f5a4c1908424bf26bc41e9361168c363685080fbdb87a196c891c8401ca2f09"
-  end
-
-  # Backport PATH python shebang rather than manually rewriting
-  patch do
-    url "https://gitlab.gnome.org/GNOME/glib/-/commit/160e55575e2183464dbf5aa733d6c2df3c674c4c.diff"
-    sha256 "29b178b53a9a636ca9538ee97e20838b9942d24018d6679d3cc29e59b3b6c0c1"
+    url "https://download.gnome.org/sources/gobject-introspection/1.83/gobject-introspection-1.83.4.tar.xz"
```
[the remark this answers is not in the document]
Comment (botantony) [reply Formula/g/glib.rb:54]: Changing gobject-introspection back to the old version didn't help, it still fails

**Review by fxcoudert — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Thanks!
