### PR TITLE
dromeaudio: fix test

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR has been revised to only rework the test so it won't fail on CI. This is necessary because `DromeAudioPlayer` will fail with an error when executed it's executed with an audio file on CI. `DromeAudioPlayer` _does_ work with some audio devices (like the speakers/headphone output of a MacBook Pro) but apparently not the audio device in our CI environment.

-----

**The original content of this PR has been preserved below for posterity:**

Building `dromeaudio` from source was failing with the following error:

```
/tmp/dromeaudio-20200525-6573-1r4rest/DromeAudio-0.3.0/src/DromeAudio/VorbisSound.cpp:30:10: fatal error: 'vorbisfile.h' file not found
#include <vorbisfile.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/DromeAudio/CMakeFiles/DromeAudio.dir/VorbisSound.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/DromeAudio/CMakeFiles/DromeAudio.dir/all] Error 2
make: *** [all] Error 2
```

Adding `libvorbis` as a dependency resolves the issue.

The other goal of this PR is to see how the `dromeaudio` test does on CI, since it failed in #55191. Depending on what audio devices I have connected to my computer, the test can reliably fail or pass for me locally. It may be that this test will always fail on CI due to the environment.

### CODE REVIEW

**Comment by samford** [comment]
Apparently `dromeaudio` only fails to build from source in this manner when you have `libvorbis` installed, so it's not necessary to add it to the formula.

I'm not sure what to make of the test, since it passed with no changes to this formula but fails with a revision bump. I'm not sure that we can rely on it but the alternative would seemingly be to execute `DroneAudioPlayer` and to check for the usage text output.

**Comment by SMillerDev** [comment]
Did you try running the command manually after installing with revision?

**Comment by samford** [comment]
Ignoring the vorbis issue, the main issue is that `DromeAudioPlayer` doesn't work properly with some audio devices. On my MacBook Pro, the test works fine with no modifications to the formula and using the current bottled version if I have the audio output set to the internal speakers/headphone output.

I tested this with five other audio outputs: HDMI audio, 3.5mm out on a Thunderbolt 3 dock, a virtual audio output, an external USB audio device (A), and another external USB audio device (B). The test only worked for one of the external USB audio devices (B) and failed for everything else in this manner:

```
/usr/local/Cellar/dromeaudio/0.3.0/bin/DromeAudioPlayer
/usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.mp3

DromeAudio Exception: AudioDriverOSX::AudioDriverOSX(): AudioUnitSetProperty (for StreamFormat) failed
Audio driver initialization failed
Error: dromeaudio: failed
```

This is the same error that appears on CI (as seen in the sqlite PR), so apparently the audio device in that context isn't one that works with `DromeAudioPlayer`.

It seems like our options are either neutering the test (e.g., executing `DromeAudioPlayer` without a file and checking for the usage output) or disabling/removing the formula. The analytics are as follows:

```
install: 2 (30 days), 5 (90 days), 23 (365 days)
install-on-request: 2 (30 days), 5 (90 days), 23 (365 days)
build-error: 0 (30 days)
```

The 30d installs are probably just me.  It's not a very popular formula and hasn't seen an update since 2015, so take from that what you will.

**Comment by SMillerDev** [comment]
If you can verify that it works and it's just the test failing I'm inclined to leave it and neuter the test with a comment explaining the situation.

**Comment by samford** [comment]
If it's compatible with the audio output device you're using, then `DromeAudioPlayer` works as expected. I ran it on an m4a file [using the current bottle] and it played the audio through the current audio device.

It fails, as described above, when you use an audio device that it's apparently not compatible with. Seeing as it hasn't been updated since 2015, this situation isn't likely to improve.

This formula also provides the `DromeAudio` library/headers, so this is for more than just `DromeAudioPlayer`. If all this is enough to keep the formula around, I can rework this PR to update the test. What do you think about something like this?

```ruby
test do
  assert_predicate include/"DromeAudio", :exist?
  assert_predicate lib/"libDromeAudio.a", :exist?

  assert_match /Usage: .*?DromeAudioPlayer <filename>/i,
               shell_output(bin/"DromeAudioPlayer 2>&1", 1)
end
```

**Comment by SMillerDev** [comment]
Yeah, test looks acceptable. Maybe add a line in there that real tests don't work with a link to this PR.

**Comment by SMillerDev** [comment]
No, just a comment in the block. No need to show users anything

**Comment by samford** [comment]
I reworked this to only include the test fix and made sure to include an explanatory comment in the test. The CI test workflow was seemingly cancelled, so I imagine there was a reason for it and I'll hold off on restarting the workflow for a bit.
