### PR TITLE
gdal: Fixing install path and workaround for gdal not building against poppler 0.73+

### PR DESCRIPTION
**Pull request by cmarquardt**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This pull request fixes two issues:

1. `gdal` doesn't build for non-standard prefixes; the reason is that for some dependencies used a hardcoded installation path (`/usr/local`).
2. `gdal` v2.4.0 doesn't build against `poppler` 0.73 and later (see [this upstream issue](https://github.com/OSGeo/gdal/issues/1208)). I understand this will be fixed in `gdal` v2.4.1, but that isn't yet released. As the patches seem to be quite large and scattered over various files, I've reactivated building against `podofo` for the time being.

Thanks for considering...

### CODE REVIEW

File: Formula/gdal.rb [hunk 1]
```diff
@@ -83,16 +82,17 @@ def install
...
-      "--with-hdf5=/usr/local",
-      "--with-netcdf=/usr/local",
-      "--with-jasper=/usr/local",
-      "--with-xerces=/usr/local",
-      "--with-odbc=/usr/local",
-      "--with-dods-root=/usr/local",
-      "--with-epsilon=/usr/local",
-      "--with-webp=/usr/local",
-      "--with-podofo=/usr/local",
+      "--with-cfitsio=#{Formula["proj"].opt_prefix}",
```
Comment (fxcoudert) [inline Formula/gdal.rb]: Why is this `proj` and not `cfitsio`?

File: Formula/gdal.rb [hunk 2]
```diff
@@ -83,16 +82,17 @@ def install
...
+      "--with-hdf5=#{Formula["hdf5"].opt_prefix}",
+      "--with-netcdf=#{Formula["netcdf"].opt_prefix}",
+      "--with-jasper=#{Formula["jasper"].opt_prefix}",
+      "--with-xerces=#{Formula["xerces-c"].opt_prefix}",
+      "--with-odbc=#{Formula["unixodbc"].opt_prefix}",
+      "--with-dods-root=#{Formula["libdap"].opt_prefix}",
+      "--with-epsilon=#{Formula["epsilon"].opt_prefix}",
+      "--with-webp=#{Formula["webp"].opt_prefix}",
+      # "--with-poppler=#{Formula["poppler"].opt_prefix}", # Commented out as poppler 0.73+ doesn't work with gdal 2.4.0
```
Comment (fxcoudert) [inline Formula/gdal.rb]: Instead of disabling `poppler`, can the upstream patches be used? https://github.com/OSGeo/gdal/issues/1208

**Review by fxcoudert — CHANGES_REQUESTED** [review]

File: Formula/gdal.rb (hunk 1 above)
Comment (cmarquardt) [reply Formula/gdal.rb]: Oops - thanks for spotting this. It's a typo; fixed in the next commit.

File: Formula/gdal.rb (hunk 2 above)
Comment (cmarquardt) [reply Formula/gdal.rb]: I tried to extract the main parts of the relevant patches, but after I got them to apply cleanly the compilation failed in other parts of the code - there were lots of side effects on other parts of the source code. My guess is that these commits were based on so many other ones since the v2.4.0 release that at least I am not capable to extract a small subset that fixes this particular issue.

Given that v2.4.1 will come out at some point (there's actually a release candidate since a few days) which will fix the problem, I decided at some point that trying to backport these fixes isn't worth the effort, especially as the formula still carried the dependency on podofo for some reason.

**Comment by cmarquardt** [comment]
Obsoleted by #38273.
