### PR TITLE
inspectrum: fix build for Linux and add head branch

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/runs/3447558515?check_suite_focus=true
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5 -O2 -std=gnu++11 -O3 -DNDEBUG -rdynamic CMakeFiles/inspectrum.dir/inspectrum_autogen/mocs_compilation.cpp.o CMakeFiles/inspectrum.dir/abstractsamplesource.cpp.o CMakeFiles/inspectrum.dir/amplitudedemod.cpp.o CMakeFiles/inspectrum.dir/cursor.cpp.o CMakeFiles/inspectrum.dir/cursors.cpp.o CMakeFiles/inspectrum.dir/main.cpp.o CMakeFiles/inspectrum.dir/fft.cpp.o CMakeFiles/inspectrum.dir/frequencydemod.cpp.o CMakeFiles/inspectrum.dir/mainwindow.cpp.o CMakeFiles/inspectrum.dir/inputsource.cpp.o CMakeFiles/inspectrum.dir/phasedemod.cpp.o CMakeFiles/inspectrum.dir/plot.cpp.o CMakeFiles/inspectrum.dir/plots.cpp.o CMakeFiles/inspectrum.dir/plotview.cpp.o CMakeFiles/inspectrum.dir/samplebuffer.cpp.o CMakeFiles/inspectrum.dir/samplesource.cpp.o CMakeFiles/inspectrum.dir/spectrogramcontrols.cpp.o CMakeFiles/inspectrum.dir/spectrogramplot.cpp.o CMakeFiles/inspectrum.dir/threshold.cpp.o CMakeFiles/inspectrum.dir/traceplot.cpp.o CMakeFiles/inspectrum.dir/tuner.cpp.o CMakeFiles/inspectrum.dir/tunertransform.cpp.o CMakeFiles/inspectrum.dir/util.cpp.o -o inspectrum  /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Widgets.so.5.15.2 /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Concurrent.so.5.15.2 -lfftw3f -lliquid /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Gui.so.5.15.2 /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Core.so.5.15.2 
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Widgets.so.5.15.2: undefined reference to `std::pmr::monotonic_buffer_resource::~monotonic_buffer_resource()@GLIBCXX_3.4.28'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Core.so.5.15.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Widgets.so.5.15.2: undefined reference to `vtable for std::pmr::monotonic_buffer_resource@GLIBCXX_3.4.28'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5Widgets.so.5.15.2: undefined reference to `std::pmr::get_default_resource()@GLIBCXX_3.4.26'
```

Also build in separate directory based on upstream instructions in https://github.com/miek/inspectrum/wiki/Build

### CODE REVIEW

File: Formula/inspectrum.rb [hunk 1]
```diff
@@ -20,9 +20,17 @@ class Inspectrum < Formula
   depends_on "liquid-dsp"
   depends_on "qt@5"
 
+  on_linux do
+    depends_on "gcc"
+  end
+
+  fails_with gcc: "5"
```
Comment (branchvincent) [inline Formula/inspectrum.rb:27]: for my own knowledge, what does `fails_with` convey that `depends_on "gcc"` doesn't?

**Review by branchv — APPROVED** [review]

File: Formula/inspectrum.rb (hunk 1 above)
Comment (SMillerDev) [reply Formula/inspectrum.rb:27]: I think it's an indication that Linux can't use the system GCC if it's GCC 5.

Comment (branchvincent) [reply Formula/inspectrum.rb:27]: gotcha, but doesn't `depends_on "gcc"` mean we know exactly what version we will use and therefore no longer care about the system's `gcc`?

for comparison, when we `depends_on "python@3.9"` we don't need to say `fails_with python: "2"` etc. granted i'm not very familiar with c-based languages so i am probably just missing something small here

Comment (cho-m) [reply Formula/inspectrum.rb:27]: That is my understanding too. For our bottling:
- On Linux, we build on Ubuntu 16.04 which has `gcc-5`. In future, we will move to Ubuntu 18.04 which has `gcc-7`.
- On macOS, we build with Apple `clang`.

Unless you add `fails_with`, Homebrew Linux CI will pick the defaults during compiler selection.

Once you add `fails_with`, Homebrew will exclude it, which means another compiler needs to be added (e.g. `depend_on "gcc"`) or build will fail.

When Linux CI is moved to Ubuntu 18.04, we will be able to drop `gcc` dependency on a lot of formulae.

---

The situation of adding `gcc` without `fails_with` is usually for something else, like `gfortran`.

Comment (branchvincent) [reply Formula/inspectrum.rb:27]: ah i see now, thanks for explaining!

**Comment by cho-m** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/1177780034
