### PR TITLE
gh 0.11.1

### PR DESCRIPTION
**Pull request by mislav**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Review by dawidd6 — DISMISSED** [review]

**Review by dawidd6 — DISMISSED** [review]

**Comment by mislav** [comment]
@dawidd6 Is this format new?

```rb
url "https://github.com/cli/cli.git",
  tag:      "v0.11.1",
  revision: "58bd549de5db008e9dd92cb6673b9ed85449d778"
```

If so, should future updates to this formula follow this format? I will have to fix automation for that.

Furthermore, why have you removed environment variables I've added here?

```rb
env = {
  "GH_VERSION" => version,
  "GO_LDFLAGS" => "-s -w",
}
system env, "make", "bin/gh", "manpages"
```

**Comment by mislav** [comment]
> Is this format new?
> 
> ```ruby
> url "https://github.com/cli/cli.git",
>   tag:      "v0.11.1",
>   revision: "58bd549de5db008e9dd92cb6673b9ed85449d778"
> ```
> 
> If so, should future updates to this formula follow this format?

Sorry, what I meant to ask is: does Homebrew prefer git-style URLs like those? Previously, this formula used archive tarball URLs to download the package:

```rb
url "https://github.com/cli/cli/archive/v0.11.1.tar.gz"
```

**Comment by dawidd6** [comment]
I saw in your `Makefile` that the version is set based on output from git. So I've changed the download strategy from tarball to git and simplified the install method. Tested it locally and version was correct in `gh`. I think there is no preference for download strategy actually, but it is suitable in this case. `brew bump-formula-pr` handles both strategies btw. Shameless plug (you might find it useful): https://github.com/dawidd6/action-homebrew-bump-formula

**Comment by zavan** [comment]
I was getting an error when upgrading from 0.9.0 to 0.11.1:

```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

Removing 0.9.0 and installing 0.11.1 worked.

**Comment by Bo98** [comment]
> I think there is no preference for download strategy actually

The preference is typically tarball unless there is benefits for a git clone.
