### PR TITLE
uhd 4.1.0.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/tmp/uhd-20210630-5599-1f60lyg/host/lib/usrp/cores/rx_dsp_core_3000.cpp:86:32: error: no member named 'math' in namespace 'boost'; did you mean simply 'math'?
            int if_freq_sign = boost::math::sign(fe_conn.get_if_freq());
                               ^~~~~~~~~~~
                               math
/tmp/uhd-20210630-5599-1f60lyg/host/include/uhd/utils/fp_compare_epsilon.ipp:15:27: note: 'math' declared here
namespace uhd { namespace math { namespace fp_compare {
                          ^
/tmp/uhd-20210630-5599-1f60lyg/host/lib/usrp/cores/rx_dsp_core_3000.cpp:86:39: error: no member named 'sign' in namespace 'uhd::math'; did you mean 'sinf'?
            int if_freq_sign = boost::math::sign(fe_conn.get_if_freq());
                                      ^~~~~~~~~~
                                      sinf
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:328:14: note: 'sinf' declared here
extern float sinf(float);
             ^
2 errors generated.
```

**Comment by chenrui333** [comment]
Close for now, will revisit it later.

**Comment by cho-m** [comment]
```
In file included from /tmp/gnuradio-20210817-4229-tocoi6/gnuradio-3.9.2.0/gr-qtgui/lib/DisplayPlot.cc:11:
/tmp/gnuradio-20210817-4229-tocoi6/gnuradio-3.9.2.0/gr-qtgui/lib/../include/gnuradio/qtgui/DisplayPlot.h:32:10: fatal error: 'qwt_compat.h' file not found
#include <qwt_compat.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [gr-qtgui/lib/CMakeFiles/gnuradio-qtgui.dir/DisplayPlot.cc.o] Error 1
```

**Comment by bayandin** [comment]
> ```
> In file included from /tmp/gnuradio-20210817-4229-tocoi6/gnuradio-3.9.2.0/gr-qtgui/lib/DisplayPlot.cc:11:
> /tmp/gnuradio-20210817-4229-tocoi6/gnuradio-3.9.2.0/gr-qtgui/lib/../include/gnuradio/qtgui/DisplayPlot.h:32:10: fatal error: 'qwt_compat.h' file not found
> #include <qwt_compat.h>
>          ^~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [gr-qtgui/lib/CMakeFiles/gnuradio-qtgui.dir/DisplayPlot.cc.o] Error 1
> ```

`gnuradio` doesn't support with `qwt` 6.2 https://github.com/gnuradio/gnuradio/issues/4956

**Comment by cho-m** [comment]
Do we want to block update until `gnuradio` fix or build a copy of Qwt 6.1 for `gnuradio`.

Maybe something like following (along with patch, etc.). Haven't tried yet:
```rb
  # GNU Radio currently fails to build with Qwt 6.2+, so build a local Qwt 6.1.
  # Upstream ref: https://github.com/gnuradio/gnuradio/issues/4956
  # TODO: Replace with `depends_on "qwt"` when fixed.
  resource "qwt" do
    url "https://downloads.sourceforge.net/project/qwt/qwt/6.1.6/qwt-6.1.6.tar.bz2"
    sha256 "99460d31c115ee4117b0175d885f47c2c590d784206f09815dc058fbe5ede1f6"

    # Update designer plugin linking back to qwt framework/lib after install
    # See: https://sourceforge.net/p/qwt/patches/45/
    patch :DATA
  end

  def install
    # Build local copy of Qwt 6.1. Remove when Qwt 6.2+ is supported.
    resource("qwt").stage do
      inreplace "qwtconfig.pri" do |s|
        s.gsub!(/^\s*QWT_INSTALL_PREFIX\s*=(.*)$/, "QWT_INSTALL_PREFIX=#{libexec}/qwt")
        # Install Qt plugin in `lib/qt/plugins/designer`, not `plugins/designer`.
        s.sub! %r{(= \$\$\{QWT_INSTALL_PREFIX\})/(plugins/designer)$}, "\\1/lib/qt/\\2"
      end

      args = ["-config", "release", "-spec"]
      spec = (ENV.compiler == :clang) ? "macx-clang" : "macx-g++"
      on_linux { spec = "linux-g++" }
      spec << "-arm64" if Hardware::CPU.arm?
      args << spec

      system Formula["qt@5"].opt_bin/"qmake", *args
      system "make"
      system "make", "install"
    end

    ...

    args = std_cmake_args + %W[
      ...
      -DQWT_LIBRARIES=#{libexec}/qwt/lib/qwt.framework/qwt
      -DQWT_INCLUDE_DIRS=#{libexec}/qwt/lib/qwt.framework/Headers

```

**Comment by cho-m** [comment]
Can either wait for #86315, which tries to use pending upstream `gnuradio` fix for Qwt, or can combine this PR with the `gnuradio` bump to avoid extra revision.

**Comment by carlocab** [comment]
Cherry-picked onto #86315.
