### PR TITLE
rust 1.46.0

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
10.14 10.15

```
brew install --build-from-source komposition
brew test --retry --verbose minidlna
brew install --build-from-source visp
```

10.13

```
brew install --build-from-source komposition
brew test --retry --verbose minidlna
brew install --build-from-source opencv@3
brew install --build-from-source visp
```

**Comment by dtrodrigues** [comment]
`visp` is related to `pcl` being out of date and not working with `boost 1.73`, which is being worked on - https://github.com/Homebrew/homebrew-core/pull/59146

**Comment by bayandin** [comment]
- `brew install --build-from-source komposition`: looks similar to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968729, if so it requires to update `gi-pango` in upstream (I suppose)
```
GI/Pango/Objects/Font.hs:670:9: error:
    parse error on input ‘HarfBuzz.FeatureT.feature_t’
    |
670 |     Ptr HarfBuzz.FeatureT.feature_t ->      -- features : TCArray False (-1) 2 (TInterface (Name {namespace = "HarfBuzz", name = "feature_t"}))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build gi-pango-1.0.22 (which is required by exe:komposition
from komposition-0.2.0 and exe:komposition-split from komposition-0.2.0). See
the build log above for details.
```
- `brew install --build-from-source visp`: one of the dependencies (`pcl`) doesn't support the latest `boost` (could be fixed with `pcl` update https://github.com/Homebrew/homebrew-core/pull/59146)
- `brew test --retry --verbose minidlna` test will be fixed in https://github.com/Homebrew/homebrew-core/pull/60401
- `brew install --build-from-source opencv@3` (on 10.13 only): can't reproduce it locally yet, but the error already happen with previous rust updates https://github.com/Homebrew/homebrew-core/issues/57305#issue-650058492

**Comment by bayandin** [comment]
The only remaining thing is to update `cargo` resource to `0.47.0` (the tag was created after I created this PR).

**Comment by bayandin** [comment]
Ok, there are no extra failures, so I believe we're good to roll out the new version of rust.

All the failures noted in https://github.com/Homebrew/homebrew-core/issues/57305#issuecomment-684773734

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
Nice work @bayandin !
