### ISSUE TITLE
qtkeychain failed to build on 10.11.4

### ISSUE THREAD

**Issue by kramer65** [Homebrew/homebrew-core#513]
To start off: I ran `brew update` twice and fixed as many issues in brew doctor as possible. I'm still left with two issues reported by brew doctor, which are shown in [this paste](http://pastebin.com/mkz8qauL).

I'm trying to install `qtkeychain` using the command `brew install qtkeychain`, which results in the following error:

```
$ brew install qtkeychain
==> Installing qtkeychain from owncloud/owncloud
==> Downloading https://github.com/frankosterfeld/qtkeychain/archive/0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/qtkeychain-0.3.tar.gz
Warning: SHA1 support is deprecated and will be removed in a future version.
Please switch this formula to SHA256.
==> cmake . -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qtkeychain/0.3 -DCMAKE_BUILD_TYPE=Release -
==> make install
Last 15 lines from /Users/kramer65/Library/Logs/Homebrew/qtkeychain/02.make:
/usr/local/opt/qt5/lib/QtCore.framework/Headers/qtypetraits.h:492:1: error: C++ requires a type specifier for all declarations
Q_STATIC_ASSERT((!is_unsigned<qint16>::value));
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/qt5keychain.dir/moc_keychain.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
20 errors generated.
make[2]: *** [CMakeFiles/qt5keychain.dir/moc_keychain_p.cpp.o] Error 1
20 errors generated.
make[2]: *** [CMakeFiles/qt5keychain.dir/keychain.cpp.o] Error 1
20 errors generated.
make[2]: *** [CMakeFiles/qt5keychain.dir/keychain_mac.cpp.o] Error 1
make[1]: *** [CMakeFiles/qt5keychain.dir/all] Error 2
make: *** [all] Error 2
```

The result of `brew gist-logs qtkeychain` can be found here: https://gist.github.com/anonymous/5ac41a004aad238adb8a388d0134fd31

Does anybody know whats wrong and what I can do to fix this?

**Comment by mikemcquaid** [comment]
> owncloud/owncloud

You'll need to report this to https://github.com/owncloud/homebrew-owncloud.
