### ISSUE TITLE
Pango 1.40.5 fails to compile on macOS Sierra 10.12.4

### ISSUE THREAD

**Issue by jorgenarntzen** [Homebrew/homebrew-core#12405]
Pango fails to compile on macOS Sierra 10.12.4. I have reinstalled the dependencies without problems, but Pango still fails to compile. Below I've linked the gist-output:

https://gist.github.com/977b5684f2d955e1f22e7cdecf031c33

The output of the compilation yields the following:

Jrgens-MacBook-Pro:~ jorgenarntzen$ brew reinstall pango --with-x11
==> Reinstalling pango --with-x11
==> Using the sandbox
==> Downloading https://download.gnome.org/sources/pango/1.40/pango-1.40.5.tar.xz
Already downloaded: /Users/jorgenarntzen/Library/Caches/Homebrew/pango-1.40.5.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/pango/1.40.5 --ena
==> make
Last 15 lines from /Users/jorgenarntzen/Library/Logs/Homebrew/pango/02.make:
        XGenericEventCookie *in,
        ^
/opt/X11/include/X11/Xlibint.h:1429:9: error: unknown type name 'XGenericEventCookie'
        XGenericEventCookie *out);
        ^
18 errors generated.
make[4]: *** [pangoxft-fontmap.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"Pango\" -DPANGO_ENABLE_BACKEND -DPANGO_ENABLE_ENGINE -DSYSCONFDIR=\"/usr/local/Cellar/pango/1.40.5/etc\" -DLIBDIR=\"/usr/local/Cellar/pango/1.40.5/lib\" -I.. -I.. -DG_DISABLE_CAST_CHECKS -D_REENTRANT -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.29/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.8/include/cairo -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/graphite2/1.3.9/include -I/usr/local/Cellar/harfbuzz/1.4.5/include/harfbuzz -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -fvisibility=hidden -g -O2 -Wall -c pangoxft-render.c -o pangoxft-render.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"Pango\" -DPANGO_ENABLE_BACKEND -DPANGO_ENABLE_ENGINE -DSYSCONFDIR=\"/usr/local/Cellar/pango/1.40.5/etc\" -DLIBDIR=\"/usr/local/Cellar/pango/1.40.5/lib\" -I.. -I.. -DG_DISABLE_CAST_CHECKS -D_REENTRANT -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.29/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.8/include/cairo -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/graphite2/1.3.9/include -I/usr/local/Cellar/harfbuzz/1.4.5/include/harfbuzz -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -fvisibility=hidden -g -O2 -Wall -c pangocairo-context.c  -fno-common -DPIC -o .libs/pangocairo-context.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"Pango\" -DPANGO_ENABLE_BACKEND -DPANGO_ENABLE_ENGINE -DSYSCONFDIR=\"/usr/local/Cellar/pango/1.40.5/etc\" -DLIBDIR=\"/usr/local/Cellar/pango/1.40.5/lib\" -I.. -I.. -DG_DISABLE_CAST_CHECKS -D_REENTRANT -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.29/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.8/include/cairo -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/graphite2/1.3.9/include -I/usr/local/Cellar/harfbuzz/1.4.5/include/harfbuzz -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -fvisibility=hidden -g -O2 -Wall -c pangocairo-context.c -o pangocairo-context.o >/dev/null 2>&1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by fxcoudert** [comment]
On my system, where `cairo` is installed with default options (no `--with-x11`), `brew reinstall pango --with-x11` fails with:

```
viewer-cairo.c:35:10: fatal error: 'cairo-xlib.h' file not found
#include <cairo-xlib.h>
```

**Comment by fxcoudert** [comment]
On the other hand, once I have installed `cairo --with-x11`, `brew reinstall pango --with-x11` works fine (and I have the same macOS, XQuartz, Xcode version as the OP).

**Comment by ilovezfs** [comment]
Yes, it's going to fail due to the superenv filtering when the build system tries to use x11 opportunistically.

**Comment by jorgenarntzen** [comment]
Was able to install pango without the --with-x11 flag. Something wrong with X11, same problem with installation of R. However, this issue can be closed.

**Comment by ilovezfs** [comment]
Actually it can't since the superenv issue remains.

**Comment by daveio** [comment]
This issue is still ongoing, but for the sake of anyone looking for ideas for a fix,
`brew reinstall pango --env=std`
worked for me. Superenv still needs unbreaking of course, but it's a working stopgap.
