### ISSUE TITLE
libre fails to build on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#31491]
`libre` fails to build on macOS 10.14 Mojave (#28817) https://jenkins.brew.sh/job/Homebrew%20Mojave%20Testing/493/version=mojave_testing/testReport/junit/brew-test-bot/mojave/install_libre/ with:

```
  AR      libre.a
Undefined symbols for architecture x86_64:
  "__mod_close", referenced from:
      _mod_destructor in mod.o
  "__mod_open", referenced from:
      _mod_load in mod.o
  "__mod_sym", referenced from:
      _mod_load in mod.o
  "_lock_alloc", referenced from:
      _rtcp_sess_alloc in sess.o
  "_lock_read_get", referenced from:
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
  "_lock_rel", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
      _timeout in sess.o
  "_lock_write_get", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _timeout in sess.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by SConaway** [comment]
Works with headers
