### PR TITLE
grin-wallet: fix build on Rust 1.53.0+

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/runs/3216720440?check_suite_focus=true
```
error[E0308]: mismatched types
  --> /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.7.4/src/atof/algorithm/bhcomp.rs:62:24
   |
62 |     let bytes = bits / Limb::BITS;
   |                        ^^^^^^^^^^ expected `usize`, found `u32`
```

### CODE REVIEW

**Comment by danielnachun** [comment]
Let's add this patch to https://github.com/Homebrew/formula-patches instead of the formula itself because it is quite long.

File: Formula/grin-wallet.rb [hunk 1]
```diff
@@ -14,6 +14,15 @@ class GrinWallet < Formula
...
   depends_on "rust" => :build
 
+  on_linux do
+    depends_on "pkg-config" => :build
+    depends_on "openssl@1.1"
+  end
+
+  # Fix build on Rust 1.53.0+. Remove in the next release.
+  # Backport of https://github.com/mimblewimble/grin-wallet/pull/621
+  patch :DATA
```
Comment (carlocab) [inline Formula/grin-wallet.rb:24]: Can we just download the `Cargo.lock` off the latest commit and replace the one in the tarball?

Comment (cho-m) [reply Formula/grin-wallet.rb:24]: Maybe. I wasn't sure if some dependency changes would pull in incompatible APIs since most of the other Cargo.lock/toml changes were updated along with other Rust code changes.

Might as well give it a try.

File: Formula/grin-wallet.rb [hunk 2]
```diff
@@ -14,9 +14,24 @@ class GrinWallet < Formula
   depends_on "llvm" => :build # for libclang
```
Comment (carlocab) [inline Formula/grin-wallet.rb:14]: macOS provides `libclang` (on Big Sur, at least). I wonder if we can do without this dependency. Doesn't have to be done in this PR, though.

**Comment by cho-m** [comment]
It looks like there are some incompatible changes with newer Cargo.lock.

I'll go back to patching the Cargo.lock. This patch should only exist for a short time (until the next `grin-wallet` release). Is it still preferred to add to `formula-patches` repo?

**Comment by SMillerDev** [comment]
No, local patch should be fine. But can you make an issue upstream indicating that this doesn't build right now?

**Comment by cho-m** [comment]
> No, local patch should be fine. But can you make an issue upstream indicating that this doesn't build right now?

The patch would be a backport of existing fix.

I think latest HEAD should build okay. Trying to only update Cargo.lock without updating other parts of code is causing issue.

The patch itself is large due to needing 2 versions of a dependency `cfg-if`.
It can be seen here: https://github.com/Homebrew/homebrew-core/commit/ce597a3ed7f73a3ecef820385db8b79bd3448bdd (~250 lines).

It multiplies the size of formula, which may not be ideal.
Though, it allows easily removing once next bump occurs.

**Comment by SMillerDev** [comment]
> The patch would be a backport of existing fix.

Yeah, I realized I wasn't being very clear when I saw your response. I meant it as a "tell upstream to release soon" kinda issue.

File: Formula/grin-wallet.rb (hunk 2 above)
Comment (cho-m) [reply Formula/grin-wallet.rb]: Updated to `uses_from_macos "llvm" => :build`. Mojave just passed, so hopefully will be fine with newer Clang too.

**Comment by cho-m** [comment]
CI all good with re-added patch. Added ready-to-merge, but still open to discussion on relocating patch to file.

**Review by carlocab — APPROVED** [review]
