### PR TITLE
docfx 2.72.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>

## New experimental API page output format

[API Page](https://github.com/dotnet/docfx/blob/main/schemas/v1.0/ApiPage.d.ts) is a new YAML output format designed to represent API documentations for a wide variety of programming languages. This release enables `docfx build` command to render API pages and `docfx metadata` command to produce API Page YAML files through the `{ "outputFormat": "ApiPage" }` option.

### 🎉 New Features
* feat: basic API page output for .NET by @yufeih in https://github.com/dotnet/docfx/pull/9309
* feat: api page view source by @yufeih in https://github.com/dotnet/docfx/pull/9318
* feat: render h2/h3 for in this article section by @yufeih in https://github.com/dotnet/docfx/pull/9320
* feat: render obsolete APIs as deprecated by @yufeih in https://github.com/dotnet/docfx/pull/9319
* feat: render enum field remarks and obsolete attribute by @yufeih in https://github.com/dotnet/docfx/pull/9327
* feat: support multiple search languages by @yufeih in https://github.com/dotnet/docfx/pull/9313
* Adds expander class to modern theme TOC <li> elements with children by @cjbotelho in https://github.com/dotnet/docfx/pull/9328
### 🐞 Bug Fixes
* fix: scroll failed when both toc and article needs scroll by @yufeih in https://github.com/dotnet/docfx/pull/9321
### 🚀 Performance Improvements
* perf: git.exe -> GitReader by @yufeih in https://github.com/dotnet/docfx/pull/9314
### 🔧 Engineering
* test: capture crash dump on CI failure by @yufeih in https://github.com/dotnet/docfx/pull/9317
### 📄 Documentation
* Update .NET Core SDK to .NET SDK by @WeihanLi in https://github.com/dotnet/docfx/pull/9308

## New Contributors
* @cjbotelho made their first contribution in https://github.com/dotnet/docfx/pull/9328

**Full Changelog**: https://github.com/dotnet/docfx/compare/v2.71.1...v2.72.0</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/ApiPage/ApiPageProcessor.cs(14,31): error CS1514: { expected [/private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/Docfx.Build.csproj::TargetFramework=net7.0]
  /private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/ApiPage/ApiPageProcessor.cs(14,31): error CS1513: } expected [/private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/Docfx.Build.csproj::TargetFramework=net7.0]
  /private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/ApiPage/ApiPageProcessor.cs(14,64): error CS8124: Tuple must contain at least two elements. [/private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/Docfx.Build.csproj::TargetFramework=net7.0]
  /private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/ApiPage/ApiPageProcessor.cs(14,66): error CS1022: Type or namespace definition, or end-of-file expected [/private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/Docfx.Build.csproj::TargetFramework=net7.0]
  /private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/ApiPage/ApiPageProcessor.cs(14,68): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [/private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/Docfx.Build.csproj::TargetFramework=net7.0]
  /private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/ApiPage/ApiPageProcessor.cs(15,1): error CS1022: Type or namespace definition, or end-of-file expected [/private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/Docfx.Build.csproj::TargetFramework=net7.0]
  /private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/ApiPage/ApiPageProcessor.cs(71,1): error CS1022: Type or namespace definition, or end-of-file expected [/private/tmp/docfx-20231023-4900-1llpotz/docfx-2.72.0/src/Docfx.Build/Docfx.Build.csproj::TargetFramework=net7.0]
```

**Comment by p-linnane** [comment]
Closing as we are deprecating this.
