### ISSUE TITLE
ffmpeg failed to build on 10.11.5

### ISSUE THREAD

**Issue by hughbiquitous** [Homebrew/homebrew-core#2946]
ffmpeg build failed during `make install` when installing ffmpeg with options:

```
  --with-faac
  --with-fdk-aac
  --with-ffplay
  --with-fontconfig
  --with-freetype
  --with-libass
  --with-libbluray
  --with-libvorbis
  --with-libvpx
  --with-openh264
  --with-openjpeg
  --with-openssl
  --with-opus
  --with-rtmpdump
  --with-tools
  --with-webp
  --with-x265
  --with-xz
```

Console output during `brew install`:

```
==> make install
Last 15 lines from /Users/hugh/Library/Logs/Homebrew/ffmpeg/02.make:
libavcodec/libopenh264enc.c:198:29: error: no member named 'sSliceCfg' in 'SSpatialLayerConfig'
    param.sSpatialLayers[0].sSliceCfg.uiSliceMode               = s->slice_mode;
    ~~~~~~~~~~~~~~~~~~~~~~~ ^
libavcodec/libopenh264enc.c:199:29: error: no member named 'sSliceCfg' in 'SSpatialLayerConfig'
    param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceNum = avctx->slices;
    ~~~~~~~~~~~~~~~~~~~~~~~ ^
libavcodec/libopenh264enc.c:201:26: error: use of undeclared identifier 'SM_DYN_SLICE'
    if (s->slice_mode == SM_DYN_SLICE) {
                         ^
libavcodec/libopenh264enc.c:204:37: error: no member named 'sSliceCfg' in 'SSpatialLayerConfig'
            param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = s->max_nal_size;
            ~~~~~~~~~~~~~~~~~~~~~~~ ^
9 errors generated.
```

See https://gist.github.com/hughbiquitous/55ec160b5e739686f0256ef777bed594.

**Comment by MikeMcQuaid** [comment]
Could you `brew update` and try again? We may have fixed this. Thanks!

**Comment by hughbiquitous** [comment]
Thanks Mike, but sadly, the same result. Did `brew update` x2 and `brew doctor` before attempting. New gist: https://gist.github.com/096fbdb8faf9f93a17690c05ceb40a09

**Comment by henryborchers** [comment]
I also had the same problem so it's not just you.

**Comment by JCount** [comment]
I may have found something: https://github.com/cisco/openh264/issues/2505

It is possible I am reading too much into this, but the implications seem to be that the ffmpeg 3.1.1 release tarball may never be compatible with OpenH264 1.6.0, unless the patches to ffmpeg to fix the API/ABI compatibility issues are backported, because ffmpeg will only apply them to the git master.

Hence, for Homebrew, at least until the next stable ffmpeg release is cut, OpenH264 1.6.0 may only be compatible with the ffmpeg git master _(whenever these patches, which I cannot confirm to even truly exist at this point, are applied)_

**Comment by brennebeck** [comment]
I can confirm reproducing the issue. I tried `--HEAD` as well and got the same result. 

https://gist.github.com/brennebeck/8c2b2229aecec1e65ea17781146f186b

**Comment by yurrriq** [comment]
Same here.

**Comment by yurrriq** [comment]
If anyone else, like me, really needs `ffmpeg` while this gets sorted, [this snapshot](http://evermeet.cx/ffmpeg/ffmpeg-81180-g5939878.7z) worked for me.

**Comment by Dedalus27** [comment]
Exactly the same here on 10.9.5 ...

Strange, I had not changed or updated anything but yesterday morning suddenly ffmpeg stopped working with this message:

     dyld: Library not loaded: /usr/local/opt/openh264/lib/libopenh264.1.dylib
       Referenced from: /usr/local/bin/ffmpeg
       Reason: image not found
     Trace/BPT trap: 5

So I tried to uninstall and install again ffmpeg getting cmake failing as reported above.

**Comment by ilovezfs** [comment]
This patch works: http://ffmpeg.org/pipermail/ffmpeg-devel/2016-May/194492.html though I'd prefer to see upstream bless it before throwing it into the formula.

**Comment by ilovezfs** [comment]
@hughbiquitous @henryborchers @JCount @brennebeck @yurrriq @Dedalus27 

This will resolve the issue until ffmpeg decides which of the proposed 1.6.0 fixes to go with, or writes their own: https://github.com/Homebrew/homebrew-core/pull/3070

**Comment by ilovezfs** [comment]
@hughbiquitous @henryborchers @JCount @brennebeck @yurrriq @Dedalus27 Fixed now if you brew update and then try the upgrade again.

**Comment by yurrriq** [comment]
Will try tomorrow. Thanks!

**Comment by rob** [comment]
@ilovezfs I can confirm that your patch works.

**Comment by ilovezfs** [comment]
You're welcome. Sorry I'd broken it!

**Comment by yurrriq** [comment]
Confirmed here too. Cheers!

**Comment by Dedalus27** [comment]
Yes, it works. Cheers.
