### PR TITLE
nut 2.8.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  dummy-ups.c:238:24: error: no member named 'st_mtim' in 'struct stat'
                                          if (datafile_stat.st_mtim.tv_sec != fs.st_mtim.tv_sec) {
                                              ~~~~~~~~~~~~~ ^
  dummy-ups.c:238:45: error: no member named 'st_mtim' in 'struct stat'
                                          if (datafile_stat.st_mtim.tv_sec != fs.st_mtim.tv_sec) {
                                                                              ~~ ^
  2 errors generated.
```

**Comment by chenrui333** [comment]
/usr/bin/install: cannot create regular file '/usr/lib/tmpfiles.d/nut-common.tmpfiles': Permission denied
  Makefile:621: recipe for target 'install-systemdtmpfilesDATA' failed

**Comment by chenrui333** [comment]
cc @Homebrew/linux

**Comment by danielnachun** [comment]
There is a probably a flag that needs to be set to tell this where to install the `tmpfiles`.

**Comment by chenrui333** [comment]
time to have a new try after updating ubuntu runtime from v16 to v22

**Comment by fxcoudert** [comment]
Still failing, reported it upstream: https://github.com/networkupstools/nut/issues/1668

At this point, I'd suggest closing the PR.

**Comment by danielnachun** [comment]
I think I have a possible solution to this - we need to use the `--with-systemdtmpfilesdir` argument to tell `nut` to put those files elsewhere.  I'm not sure what the right directory for that is.

**Comment by fxcoudert** [comment]
I'd say `pkgshare`

**Comment by danielnachun** [comment]
The fix I pushed worked on Linux.  We're still seeing a livecheck failure - @chenrui333 perhaps we should switch to using the upstream GitHub repo?

**Comment by cho-m** [comment]
Also looks like this was using the value from our `systemd` where one of files has `prefix=/usr`:
```console
$ pkg-config --variable=tmpfilesdir systemd
/usr/lib/tmpfiles.d

$ grep prefix .linuxbrew/opt/systemd/share/pkgconfig/systemd.pc
# Names with prefixes are preferred, and the run-together names should be
prefix=/usr
root_prefix=/home/linuxbrew/.linuxbrew/Cellar/systemd/251_1
rootprefix=${root_prefix}
systemd_util_dir=${root_prefix}/lib/systemd
systemd_system_unit_dir=${rootprefix}/lib/systemd/system
systemd_system_preset_dir=${rootprefix}/lib/systemd/system-preset
systemd_user_unit_dir=${prefix}/lib/systemd/user
systemd_user_preset_dir=${prefix}/lib/systemd/user-preset
systemd_system_generator_dir=${root_prefix}/lib/systemd/system-generators
systemd_user_generator_dir=${prefix}/lib/systemd/user-generators
systemd_sleep_dir=${root_prefix}/lib/systemd/system-sleep
systemd_shutdown_dir=${root_prefix}/lib/systemd/system-shutdown
tmpfiles_dir=${prefix}/lib/tmpfiles.d
sysusers_dir=${rootprefix}/lib/sysusers.d
sysctl_dir=${rootprefix}/lib/sysctl.d
binfmt_dir=${rootprefix}/lib/binfmt.d
modules_load_dir=${rootprefix}/lib/modules-load.d
catalog_dir=${prefix}/lib/systemd/catalog
```

**Comment by chenrui333** [comment]
> The fix I pushed worked on Linux. We're still seeing a livecheck failure - @chenrui333 perhaps we should switch to using the upstream GitHub repo?

yeah, I think so. The homepage only sort of showing the latest release as NEWS, but maybe we can do a followup PR on this, cc @samford

**Comment by chenrui333** [comment]
I think we are good to go?

**Review by danielnachun — APPROVED** [review]
I think we can merge this and address the livecheck in a followup.

**Comment by samford** [comment]
> > The fix I pushed worked on Linux. We're still seeing a livecheck failure - @chenrui333 perhaps we should switch to using the upstream GitHub repo?
> 
> yeah, I think so. The homepage only sort of showing the latest release as NEWS, but maybe we can do a followup PR on this

The tarball from the stable releases on GitHub are the same as the one from the first-party website (i.e., same SHA256), so I agree that there's something to be said for switching the `stable` source. Identifying stable versions from the first-party website requires digging through the [source directories](https://networkupstools.org/source/), whereas we can simply use `GithubLatest` if we switch to the GitHub tarball.
