### ISSUE TITLE
spandsp include module noise.h: error: invalid UTF-8 in comment

### ISSUE THREAD

**Issue by MarioG-X** [Homebrew/homebrew-core#157409]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
mario@Marios-Mac-mini ~ % brew config
HOMEBREW_VERSION: 4.1.25
ORIGIN: https://github.com/Homebrew/brew
HEAD: c32bd1c7cc0c3b1b914845bddfeda53f4d877a3f
Last commit: 7 days ago
Core tap JSON: 14 Dec 17:13 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
mario@Marios-Mac-mini ~ % 

mario@Marios-Mac-mini ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Building freeswitch from scratch. I maintained the Freeswitch macOS wiki 12+years. Build on Sonoma 14.2 Command Line Tools 15.1.

The offending line is in spandsp include module noise.h: (just find "tolerance")

The tolerance for each 1/3rd octave band is °”3dB.    <– This has an invalid character
I changed to:
The tolerance for each 1/3rd octave band is 3dB.    <– This worked

I dod a brew remove and install of spandsp just to make sure it was not a transmission error, but the line contains the same comment error.

### What happened (include all command output)?

Make failed and stopped due to:
  CC       src/libfreeswitch_la-switch_spandsp.lo
In file included from src/switch_spandsp.c:36:
In file included from /usr/local/include/spandsp.h:81:
/usr/local/include/spandsp/noise.h:72:45: error: invalid UTF-8 in comment [-Werror,-Winvalid-utf8]
The tolerance for each 1/3rd octave band is <A1><D3>3dB.
                                            ^
1 error generated.
make[1]: *** [src/libfreeswitch_la-switch_spandsp.lo] Error 1
make: *** [all] Error 2

### What did you expect to happen?

The this make at this point would build normal as it had done for over 12 years.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I think it could be reproduced using make for anything that uses noise.h. However, what I did (after loading all prerequisites) was: 

Probably no need t test since it is two characters in a comment on a single line in a single module. But here are steps I did:

git clone https://github.com/signalwire/freeswitch.git
./bootstrap.sh
./configure
make

Complete instructions here: https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/macOS/macOS-Installation/macOS-Manual-Installation_13174557/#download-master-development
```

**Comment by cho-m** [comment]
The header is the same as it has always been. It may be that newer Clang is more strict or there are more errors enabled in build.

This is an upstream issue, but `spandsp` upstream looks unmaintained (last release 2014). It may be better to just deprecate that formula.

In Homebrew, we build `freeswitch` with their maintained copy of `spandsp` (which they do not tag so we cannot create a formula for):
https://github.com/Homebrew/homebrew-core/blob/b9e7f6a27e6121e5bb88350f27e8d22c247421cf/Formula/f/freeswitch.rb#L112-L115

They did fix the header there (https://github.com/freeswitch/spandsp/commit/728b60abdd1a71e254b8e831e9156521d788b2b9). I would recommend using that repo for your build given they probably have more fixes.

**Comment by MarioG-X** [comment]
Thanks for the information. I see it was fixed May 23 in FS master for spandsp but never moved to FS master/GA. Will ask if it can be handled by FS team.

**Comment by MarioG-X** [comment]
I contacted the freeswitch developers and they said homebrew needs to put in the fix. They are not doing anything. This is a real delima, can anyone help?

**Comment by MarioG-X** [comment]
Comment from them (which I don't know how to handle):
didn’t we already fix it in our tree and they just are pointing at older ?  that’s how i read the issue you opened

**Comment by MarioG-X** [comment]
It was fixed today by the Freeswitch Devs
