### PR TITLE
snappy 1.2.0

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>* Level API was added with level 2 support. Compresses 5-10% denser and decompresses 5-10% faster. The compression speed drop is about 20-30%
* Minor fixes</pre>
</details>

### CODE REVIEW

**Comment by cho-m** [comment]
We probably shouldn't https://github.com/Homebrew/homebrew-core/labels/CI-skip-recursive-dependents here given there is some breakage.

Usually should use that label when we can confirm API/ABI stability. Or at least after a full run is done on all OS (particularly needs one on Linux due to different dependency trees).

**Comment by chenrui333** [comment]
> We probably shouldn't [ CI-skip-recursive-dependents](https://github.com/Homebrew/homebrew-core/labels/CI-skip-recursive-dependents) here given there is some breakage.

I just removed the skip label and see how it goes.

**Comment by ZhongRuoyu** [comment]
`pyqt`:

```
ImportError: /home/linuxbrew/.linuxbrew/opt/qt/lib/libQt6WebEngineCore.so.6: undefined symbol: _ZN6snappy11RawCompressEPKcmPcPm
```

`pyqt@5`:

```
ImportError: /home/linuxbrew/.linuxbrew/opt/qt@5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZN6snappy11RawCompressEPKcmPcPm
```

`qt` and `qt@5` should need a rebuild.

**Comment by ZhongRuoyu** [comment]
`qt@5` failed with:

```
In file included from src/mbgl/annotation/annotation_manager.cpp:1:
In file included from src/mbgl/annotation/annotation_manager.hpp:4:
In file included from src/mbgl/annotation/symbol_annotation_impl.hpp:24:
In file included from deps/boost/1.65.1/include/boost/geometry.hpp:17:
In file included from deps/boost/1.65.1/include/boost/geometry/geometry.hpp:43:
In file included from deps/boost/1.65.1/include/boost/geometry/core/radian_access.hpp:26:
In file included from deps/boost/1.65.1/include/boost/numeric/conversion/cast.hpp:33:
In file included from deps/boost/1.65.1/include/boost/numeric/conversion/converter.hpp:13:
In file included from deps/boost/1.65.1/include/boost/numeric/conversion/conversion_traits.hpp:13:
In file included from deps/boost/1.65.1/include/boost/numeric/conversion/detail/conversion_traits.hpp:18:
In file included from deps/boost/1.65.1/include/boost/numeric/conversion/detail/int_float_mixture.hpp:19:
In file included from deps/boost/1.65.1/include/boost/mpl/integral_c.hpp:32:
deps/boost/1.65.1/include/boost/mpl/aux_/integral_wrapper.hpp:73:31: error: integer value -1 is outside the valid range of values [0, 3] for this enumeration type [-Wenum-constexpr-conversion]
    typedef AUX_WRAPPER_INST( BOOST_MPL_AUX_STATIC_CAST(AUX_WRAPPER_VALUE_TYPE, (value - 1)) ) prior;
                              ^
deps/boost/1.65.1/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
#   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
                                              ^
```

This is an issue with Boost: boostorg/mpl#69. Can probably work around with `-Wno-enum-constexpr-conversion`.

**Comment by ZhongRuoyu** [comment]
@chenrui333, I cancelled CI because this PR has conflicts with #168136 (via `qt`). That PR should be ready after this CI run so this will need to be rebased.

**Comment by chenrui333** [comment]
sounds good 👍

**Comment by SMillerDev** [comment]
```console
  ==> /usr/bin/g++-11 test.cxx -o test -L/home/linuxbrew/.linuxbrew/opt/snappy/lib -lsnappy -L/home/linuxbrew/.linuxbrew/Cellar/snappystream/1.0.0_1/lib -lsnappystream
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/snappystream/1.0.0_1/lib/libsnappystream.a(osnappystream.cpp.o): in function `snappy::oSnappyStreambuf::sync()':
  osnappystream.cpp:(.text+0x3ba): undefined reference to `snappy::MaxCompressedLength(unsigned long)'
  /usr/bin/ld: osnappystream.cpp:(.text+0x3df): undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*, snappy::CompressionOptions)'
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/snappystream/1.0.0_1/lib/libsnappystream.a(isnappystream.cpp.o): in function `snappy::iSnappyStreambuf::underflow()':
  isnappystream.cpp:(.text+0x4ff): undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
  /usr/bin/ld: isnappystream.cpp:(.text+0x54a): undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
  collect2: error: ld returned 1 exit status
```

**Review by fxcoudert — APPROVED** [review]

**Comment by miccal** [comment]
Thank you to everyone who helped out with this :)
