### PR TITLE
node@0.12: fix build with Xcode 8.3

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://github.com/Homebrew/homebrew-core/pull/14171.

Fixes build failure with >= Apple LLVM version 8.1.0 (clang-802.0.42).

The error is
```
../deps/v8/include/v8.h:5800:54: error: 'CreateHandle' is a protected member of 'v8::HandleScope'
```

Fix suggested by Thomas Rosenstein in https://github.com/nodejs/node-gyp/issues/1160.

CC @DomT4 @chrmoritz

### CODE REVIEW

**Comment by DomT4** [comment]
Thanks for sorting this out. Guess the ancient `node`s can live to fight another day 😸

**Comment by ilovezfs** [comment]
>Thanks for sorting this out.

You're welcome!

>Guess the ancient nodes can live to fight another day :smile_cat:

until `CVE Judgement Day` comes.

**Comment by DomT4** [comment]
> until CVE Judgement Day comes.

To be honest they should probably really be using our `openssl` by this point but 🤷‍♂️.
