### ISSUE TITLE
swftools --with-jpeg --with-lame failed to build on 10.13.4

### ISSUE THREAD

**Issue by jvalteren** [Homebrew/homebrew-core#28559]
Here goes...

I ran brew update and doctor, no issues there. See gist logs here, anchored to offending error: https://gist.github.com/jvalteren/646fe6e6b576a5900dcccb456c4395ce#file-02-make-L66

I wanted to add jpeg support to swftools, so I can properly use infoqscraper (see https://github.com/cykl/infoqscraper/wiki/Setting-up), which needs it otherwise it returns the error 'No JPEG library compiled in'. 

Based on issue https://github.com/Homebrew/homebrew-core/issues/15910, I already deducted that I had to unlink freetype (to prevent error `'ft2build.h' file not found`). Also, I had to provide the option --with-lame, otherwise it returns an error about missing lame (`'lame.h' file not found`). All of freetype, jpeg and lame were already installed.

So, what I ended up doing was this:
```
brew unlink freetype
brew install swftools --with-jpeg --with-lame
```
This results in the following output:
```
==> Downloading http://www.swftools.org/swftools-0.9.2.tar.gz
Already downloaded: /Users/jvalteren/Library/Caches/Homebrew/swftools-0.9.2.tar.gz
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/swftools/0.9.2_1
==> make
Last 15 lines from /Users/jvalteren/Library/Logs/Homebrew/swftools/02.make:
    jpeg_start_compress(&cinfo, FALSE);
                                ^
jpeg.c:331:30: error: use of undeclared identifier 'TRUE'
    jpeg_read_header(&cinfo, TRUE);
                             ^
jpeg.c:380:30: error: use of undeclared identifier 'TRUE'
    jpeg_read_header(&cinfo, TRUE);
                             ^
jpeg.c:462:30: error: use of undeclared identifier 'TRUE'
    jpeg_read_header(&cinfo, TRUE);
                             ^
11 errors generated.
make[1]: *** [jpeg.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```

This goes beyond my skills with homebrew and make etc to fix.  

I'm guessing here because I don't have a clean system to try this on, but these might be step-by-step reproduction instructions:
```
brew install jpeg lame freetype
brew unlink freetype
brew install swftools --with-jpeg --with-lame
```

**Comment by DomT4** [comment]
It'll be this issue: https://github.com/matthiaskramm/swftools/issues/37. Reported upstream almost a year ago and not yet fixed.

**Comment by fxcoudert** [comment]
On macOS 10.13, I see the following:

- `--with-jpeg` fails to build with the above error
- `--with-xpdf` also fails to build: `xpdf/GlobalParams.cc:925:12: error: ordered comparison between pointer and zero`
- building from source without option fails with: `modules/swffont.c:42:10: fatal error: 'ft2build.h' file not found`
