### ISSUE TITLE
docker-machine-driver-xhyve failed to build on 10.10.5

### ISSUE THREAD

**Issue by mtpereira** [Homebrew/homebrew-core#6678]
### Bug reports:

New version of `docker-machine-driver-xhyve`, `0.3.0`, fails to build with the following message:

```
==> make build
Last 15 lines from /Users/rag/Library/Logs/Homebrew/docker-machine-driver-xhyve/04.make:
  "_ev_loop_destroy", referenced from:
      _lwt_libev_stop in liblwt-unix_stubs.a(lwt_libev_stubs.o)
  "_ev_loop_new", referenced from:
      _lwt_libev_init in liblwt-unix_stubs.a(lwt_libev_stubs.o)
  "_ev_run", referenced from:
      _lwt_libev_loop in liblwt-unix_stubs.a(lwt_libev_stubs.o)
  "_ev_set_invoke_pending_cb", referenced from:
      _lwt_libev_init in liblwt-unix_stubs.a(lwt_libev_stubs.o)
  "_ev_timer_start", referenced from:
      _lwt_libev_timer_init in liblwt-unix_stubs.a(lwt_libev_stubs.o)
  "_ev_timer_stop", referenced from:
      _lwt_libev_timer_stop in liblwt-unix_stubs.a(lwt_libev_stubs.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/docker-machine-driver-xhyve] Error 2
```

https://gist.github.com/mtpereira/488d34625ae4639812d0c21aa41bd1cc

**Comment by OlliM** [comment]
On 10.12.2 Beta (16C32f) it's also not building:

==> opam install -y uri qcow-format conf-libev
Last 15 lines from /Users/olli/Library/Logs/Homebrew/docker-machine-driver-xhyve/02.opam:
  ∗  install ocamlmod      0.0.8         
  ∗  install ocplib-endian 1.0           
  ∗  install ppx_core      113.33.01+4.03
  ∗  install ppx_deriving  4.1           
  ∗  install ppx_driver    113.33.01+4.03
  ∗  install ppx_optcomp   113.33.00+4.03
  ∗  install ppx_tools     5.0+4.03.0    
  ∗  install ppx_type_conv 113.33.02+4.03
  ∗  install re            1.7.1         
  ∗  install result        1.2           
  ∗  install stringext     1.4.3         
  ∗  install topkg         0.8.1

**Comment by MikeMcQuaid** [comment]
CC @zchee

**Comment by zchee** [comment]
@MikeMcQuaid Sorry for the delay.
OK, I'll fix

**Comment by RSully** [comment]
Any updates on this? Seeing this issue on 10.12.2 installing 0.3.1

**Comment by cdelacroix** [comment]
Same here. I looked into the build and there is a hardcoded path to `/usr/local/lib/libev.a`. I have homebrew installed in a non-default location (`/opt/homebrew`) so I have no file here.

I added a temporary symlink to the file above
`sudo ln -s "$(brew --prefix)/lib/libev.a" /usr/local/lib/libev.a`

That fixed the build for me.

**Comment by cdelacroix** [comment]
Created pr #9532 with a clean fix (I hope)
