### PR TITLE
freeswitch: fix build error for undeclared identifier 'NSIG'

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Try to fix the `freeswitch` error seen in PR #76780.

I confirmed error on local `--build-from-source`:
```make
In file included from ./include/apr_general.h:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:69:42: error: use of undeclared identifier 'NSIG'
extern __const char *__const sys_signame[NSIG];
                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:70:42: error: use of undeclared identifier 'NSIG'
extern __const char *__const sys_siglist[NSIG];
                                         ^
2 errors generated.

```

The condition to define `NSIG` is:
```c
#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
#define NSIG	__DARWIN_NSIG
#endif
```

### CODE REVIEW

**Comment by cho-m** [comment]
May need someone to take a deeper look into why the existing Formula ends up failing in #76780 (and #75728, which is for next version, but is probably due to same reason).

The condition that is causing the failure is also the same condition that is used to define `NSIG`, which should have been processed due to `#include <sys/signal.h>`.

This PR essentially forcefully set the value `_DARWIN_C_SOURCE` to guarantee `NSIG` is defined, but it would be a good idea to see if there is a nicer alternative (and perhaps check if the failures are due to Apple or Homebrew given that the Formula hasn't changed since originally bottled).

---

Related headers...

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h
```h
...
#include <sys/signal.h>

#include <sys/_pthread/_pthread_types.h>
#include <sys/_pthread/_pthread_t.h>

#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
extern __const char *__const sys_signame[NSIG];
extern __const char *__const sys_siglist[NSIG];
#endif
```

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/signal.h
```h
...
#define __DARWIN_NSIG   32      /* counting 0; could be 33 (mask is 1-32) */

#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
#define NSIG    __DARWIN_NSIG
#endif
```

File: Formula/freeswitch.rb [hunk 1]
```diff
@@ -151,6 +151,10 @@ class Freeswitch < Formula
   end
 
   def install
+    on_macos do
```
Comment (carlocab) [inline Formula/freeswitch.rb:154]: Could we have a comment here explaining what this is for?

Comment (cho-m) [reply Formula/freeswitch.rb:154]: Would something like the headline message along with related upstream issue (https://github.com/signalwire/freeswitch/issues/1145) be sufficient?

---

I'm actually not sure of exact reason why this is required yet.

If I had to guess, I think it is due to `_XOPEN_SOURCE` being set by `freeswitch` in certain places, which changes value of `_POSIX_C_SOURCE`.

Perhaps due to order of `include`s, we hit the odd behavior where the same condition to set `NSIG` and access `NSIG` are not equal.

Comment (carlocab) [reply Formula/freeswitch.rb:154]: Ah, macro voodoo. very nice. I guess at minimum a comment should give some indication of when a workaround can be removed, so a link to the upstream issue would help.

Comment (cho-m) [reply Formula/freeswitch.rb:154]: Okay for the comment.

For actual fix, another alternative may be to set `_XOPEN_SOURCE`, which would do the opposite of `_DARWIN_C_SOURCE`, i.e. darwin macro would probably allow platform-specific behavior while open-source macro would use portable functions instead.

**Review by carlocab — APPROVED** [review]
