### PR TITLE
baresip 0.6.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
```
05:36:27 ==> /usr/local/Cellar/baresip/0.6.1/bin/baresip -f /private/tmp/baresip-test-20190224-94265-1h91lo6/.baresip -t
05:36:27 baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
05:36:27 config: creating config template /Users/brew/.baresip/config
05:36:27 [31mconfig: writing /Users/brew/.baresip/config: No such file or directory
05:36:27 [;m[31mmain: configure failed: No such file or directory
05:36:27 [;mua: stop all (forced=1)
05:36:27 Error: baresip: failed
05:36:27 Failed executing:
```
The test seems to work on Sierra for some reason.

**Comment by alebcay** [comment]
Just as an FYI, the current version (0.5.10) is also failing test for me on Mojave right now. I'll see if I can figure something out.

**Comment by gonhidi** [comment]
The test seems to be failing because option parsing is disabled. The `HAVE_GETOPT` flag controls that behaviour.

Asides from that, I have also noticed that `USE_UUID` is no longer used in the code. Furthermore, as the program evolved, its author seems to have been suggesting a number of other flags changes over at Macports (up to version 0.6.0). I don't know how desirable they might be here, but taking note of them — minus an `EXTRA_CFLAGS=-I${prefix}/include/rem` — as well as the above, that would leave the formula something like the following:

```diff
--- a/Formula/baresip.rb
+++ b/Formula/baresip.rb
@@ -1,8 +1,8 @@
 class Baresip < Formula
   desc "Modular SIP useragent"
   homepage "http://www.creytiv.com/baresip.html"
-  url "http://www.creytiv.com/pub/baresip-0.5.10.tar.gz"
-  sha256 "393fb010410d3fc6a4879cfda235f0ec98439be5d1dca02c15f3416f7110a7fb"
+  url "http://www.creytiv.com/pub/baresip-0.6.1.tar.gz"
+  sha256 "b559c5ca75bd066fb6f51b2e371641392b9464309b4ed44429af406b2d6cd8d9"

   bottle do
     sha256 "a7d010f0c6ea77cfe38e34a26d163fda8994c2e903988b70d8771e685eeb3c5e" => :mojave
@@ -13,6 +13,7 @@ class Baresip < Formula

   depends_on "libre"
   depends_on "librem"
+  depends_on "sdl2"

   def install
     # baresip doesn't like the 10.11 SDK when on Yosemite
@@ -26,13 +27,17 @@ class Baresip < Formula
                               "LIBRE_MK=#{libre.opt_share}/re/re.mk",
                               "LIBRE_INC=#{libre.opt_include}/re",
                               "LIBRE_SO=#{libre.opt_lib}",
+                              "HAVE_GETOPT=1",
                               "MOD_AUTODETECT=",
                               "USE_AVCAPTURE=1",
+                              "USE_AVCODEC=1",
+                              "USE_CONS=1",
                               "USE_COREAUDIO=1",
                               "USE_G711=1",
+                              "USE_G712=1",
                               "USE_OPENGL=1",
-                              "USE_STDIO=1",
-                              "USE_UUID=1"
+                              "USE_SDL2=1",
+                              "USE_STDIO=1"
   end

   test do
```

Note that I am not a user of this formula nor of the program, so I don't know if that much novelty at once might be too much. With those changes `baresip` compiles and passes the test on my Mojave 10.14.3 system, but simply adding the `HAVE_GETOPT=1` would do the same (which would also be good enough to help PR #37353 along a little).

**Comment by fxcoudert** [comment]
Let's try it again, sticking to the existing dependencies.

**Comment by gonhidi** [comment]
I didn't realize that an unspecified dependency was being satisfied because I already had `ffmpeg` installed (which should fix the `#include <libavcodec/avcodec.h>` errors that the CI came across). I am afraid that I also mistyped the `USE_G712=1`, which at least should not affect the build results; however, the intended `USE_G722=1` would have required a `spandsp` dependency in the formula.

**Comment by alebcay** [comment]
It appears that the remaining High Sierra failure may be related to Xcode/CLT header conflict; see [an earlier issue where this error popped up with the `subversion` formula](https://github.com/Homebrew/homebrew-core/issues/34883).

**Comment by Niek** [comment]
I recommend to build with ``USE_TLS=1 USE_OPENSSL=1`` to make it more useful. Many SIP accounts require or at least offer TLS connection nowadays.

**Comment by Niek** [comment]
Doesn't build on my 10.14.4 (Mojave beta):
```bash
In file included from modules/coreaudio/coreaudio.c:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:18:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AUGraph.h:101:57: error: expected a version of the form 'major[.minor[.subminor]]'
NewAUGraph(                     AUGraph __nullable * __nonnull outGraph)                AUGRAPH_DEPRECATED(10.0);

---snip---

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AUGraph.h:110:42: error: expected a version of the form 'major[.minor[.subminor]]'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AUGraph.h:47:194: note: expanded from macro 'AUGRAPH_DEPRECATED'
#define AUGRAPH_DEPRECATED(macos_intro) API_DEPRECATED("AUGraph is deprecated in favor of AVAudioEngine", macos(macos_intro, API_TO_BE_DEPRECATED), ios(2.0, API_TO_BE_DEPRECATED), watchos(2.0, API_TO_BE_DEPRECATED), tvos(9.0, API_TO_BE_DEPRECATED))
                                                                                                                                                                                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [build-x86_64/modules/avcapture/avcapture.o] Error 1
```

**Comment by Niek** [comment]
Doesn't this require an updated libre and librem as well?
```diff
diff --git a/Formula/libre.rb b/Formula/libre.rb
index 18d60c813..8063ef3f6 100644
--- a/Formula/libre.rb
+++ b/Formula/libre.rb
@@ -1,8 +1,8 @@
 class Libre < Formula
   desc "Toolkit library for asynchronous network I/O with protocol stacks"
   homepage "http://www.creytiv.com"
-  url "http://www.creytiv.com/pub/re-0.5.9.tar.gz"
-  sha256 "882ba05cae77e07099add1d24195863d08fcddfef62d1586d8d07f1721b59612"
+  url "http://www.creytiv.com/pub/re-0.6.0.tar.gz"
+  sha256 "0e97bcb5cc8f84d6920aa78de24c7d4bf271c5ddefbb650848e0db50afe98131"

   bottle do
     cellar :any
```

```diff
diff --git a/Formula/librem.rb b/Formula/librem.rb
index 0d9ca7a4f..9232fe287 100644
--- a/Formula/librem.rb
+++ b/Formula/librem.rb
@@ -1,8 +1,8 @@
 class Librem < Formula
   desc "Toolkit library for real-time audio and video processing"
   homepage "http://www.creytiv.com"
-  url "http://www.creytiv.com/pub/rem-0.5.3.tar.gz"
-  sha256 "9f98a79947d4709282a5791ac30f0eda03d5d34086f36df74bff4f8aac0e8050"
+  url "http://www.creytiv.com/pub/rem-0.6.0.tar.gz"
+  sha256 "417620da3986461598aef327c782db87ec3dd02c534701e68f4c255e54e5272c"

   bottle do
     cellar :any
```

**Comment by gonhidi** [comment]
Adding `USE_OPENSSL=1` to the baresip formula causes my local build to fail due to a missing symbol or two (the following is for source-built baresip 0.5.10 and the libre 0.5.9 bottle; the problem repeats itself in a similar fashion if the versions are respectively 0.6.1 and 0.6.0):

```
Undefined symbols for architecture x86_64:
  "_tls_alloc", referenced from:
      _add_transp_af in ua.o
```

The libre headers have USE_OPENSSL includes. To test if a mismatch was the issue I edited its formula to blindly set it; that done, both packages built without a problem. That doesn't seem to be a proper solution, since there seems to be makefile code to set the flag in the libre source (unlike baresip). Perhaps it should be looked into before giving a simple version bump to the libre and librem formulas (which, as noted above, need to be at 0.6.0 or later since baresip 0.6.0, according to its changelog; thanks for spotting it).

**Comment by Niek** [comment]
@gonhidi In that case I would suggest to update the libre{m} packages to depend on openssl as well, and change the baresip package to require the minimum version of 0.6.0 for those packages.
