### PR TITLE
boost boost-python3 boost-mpi 1.77.0

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
We'll need to update `boost-mpi` and `boost-python3` here too. But we should wait to see how many `revision` bumps we'll need first.

**Comment by carlocab** [comment]
ARM

```
Error: 21 failed steps!
brew test --retry --verbose boost-mpi
brew test --retry --verbose fuego
brew test --retry --verbose ledger
brew test --retry --verbose libbitcoin
brew test --retry --verbose libbitcoin-blockchain
brew test --retry --verbose libbitcoin-client
brew test --retry --verbose libbitcoin-database
brew test --retry --verbose libbitcoin-explorer
brew test --retry --verbose libbitcoin-network
brew test --retry --verbose libbitcoin-node
brew test --retry --verbose libbitcoin-protocol
brew test --retry --verbose libbitcoin-server
brew test --retry --verbose monero
brew test --retry --verbose ncmpcpp
brew test --retry --verbose openimageio
brew test --retry --verbose osrm-backend
brew test --retry --verbose pdnsrec
brew test --retry --verbose standardese
brew test --retry --verbose supertux
brew test --retry --verbose uhd
brew test --retry --verbose wownero
```

Big Sur (Intel)

```
Error: 22 failed steps!
brew test --retry --verbose bitcoin
brew test --retry --verbose boost-mpi
brew test --retry --verbose fuego
brew test --retry --verbose gnuradio
brew test --retry --verbose ledger
brew test --retry --verbose libbitcoin
brew test --retry --verbose libbitcoin-blockchain
brew test --retry --verbose libbitcoin-client
brew test --retry --verbose libbitcoin-database
brew test --retry --verbose libbitcoin-network
brew test --retry --verbose libbitcoin-node
brew test --retry --verbose libbitcoin-protocol
brew test --retry --verbose libbitcoin-server
brew test --retry --verbose libswiften
brew test --retry --verbose monero
brew test --retry --verbose ncmpcpp
brew test --retry --verbose openimageio
brew test --retry --verbose osrm-backend
brew test --retry --verbose pdnsrec
brew test --retry --verbose standardese
brew test --retry --verbose uhd
brew test --retry --verbose wownero
```

Catalina

```
Error: 22 failed steps!
brew test --retry --verbose bitcoin
brew test --retry --verbose boost-mpi
brew test --retry --verbose fuego
brew test --retry --verbose gnuradio
brew test --retry --verbose ledger
brew test --retry --verbose libbitcoin
brew test --retry --verbose libbitcoin-blockchain
brew test --retry --verbose libbitcoin-client
brew test --retry --verbose libbitcoin-database
brew test --retry --verbose libbitcoin-network
brew test --retry --verbose libbitcoin-node
brew test --retry --verbose libbitcoin-protocol
brew test --retry --verbose libbitcoin-server
brew test --retry --verbose libswiften
brew test --retry --verbose monero
brew test --retry --verbose ncmpcpp
brew test --retry --verbose openimageio
brew test --retry --verbose osrm-backend
brew test --retry --verbose pdnsrec
brew test --retry --verbose standardese
brew test --retry --verbose uhd
brew test --retry --verbose wownero
```

Mojave

```
Error: 23 failed steps!
brew test --retry --verbose bitcoin
brew test --retry --verbose boost-mpi
brew test --retry --verbose fuego
brew test --retry --verbose gnuradio
brew test --retry --verbose ledger
brew test --retry --verbose libbitcoin
brew test --retry --verbose libbitcoin-blockchain
brew test --retry --verbose libbitcoin-client
brew test --retry --verbose libbitcoin-database
brew test --retry --verbose libbitcoin-network
brew test --retry --verbose libbitcoin-node
brew test --retry --verbose libbitcoin-protocol
brew test --retry --verbose libbitcoin-server
brew test --retry --verbose libswiften
brew test --retry --verbose monero
brew test --retry --verbose ncmpcpp
brew test --retry --verbose openimageio
brew test --retry --verbose osrm-backend
brew test --retry --verbose pdnsrec
brew test --retry --verbose standardese
brew test --retry --verbose uhd
brew test --retry --verbose volk
brew test --retry --verbose wownero
```

Linux

```
Error: 53 failed steps!
brew linkage --test bastet
brew linkage --test bitcoin
brew test --retry --verbose bitcoin
brew linkage --test boost-mpi
brew test --retry --verbose boost-mpi
brew linkage --test cryptominisat
brew test --retry --verbose cryptominisat
brew linkage --test fizz
brew test --retry --verbose fizz
brew linkage --test folly
brew test --retry --verbose folly
brew linkage --test innoextract
brew test --retry --verbose innoextract
brew linkage --test ledger
brew test --retry --verbose ledger
brew linkage --test libbitcoin
brew test --retry --verbose libbitcoin
brew linkage --test libbitcoin-protocol
brew test --retry --verbose libbitcoin-protocol
brew linkage --test libphonenumber
brew test --retry --verbose libphonenumber
brew linkage --test mlpack
brew test --retry --verbose mlpack
brew linkage --test monero
brew test --retry --verbose monero
brew linkage --test ncmpcpp
brew test --retry --verbose ncmpcpp
brew linkage --test ompl
brew test --retry --verbose ompl
brew linkage --test openvdb
brew test --retry --verbose openvdb
brew linkage --test osm2pgsql
brew test --retry --verbose osm2pgsql
brew linkage --test pdns
brew linkage --test pdnsrec
brew test --retry --verbose pdnsrec
brew linkage --test povray
brew test --retry --verbose povray
brew linkage --test quantlib
brew linkage --test rdkit
brew test --retry --verbose rdkit
brew linkage --test simgrid
brew test --retry --verbose simgrid
brew linkage --test simple-amqp-client
brew test --retry --verbose simple-amqp-client
brew linkage --test vowpal-wabbit
brew test --retry --verbose vowpal-wabbit
brew linkage --test wangle
brew test --retry --verbose wangle
brew linkage --test watchman
brew test --retry --verbose watchman
brew linkage --test wownero
brew test --retry --verbose wownero
```

**Comment by carlocab** [comment]
Linux linkage failures:
```
bastet
bitcoin
boost-mpi
cryptominisat
fizz
folly
innoextract
ledger
libbitcoin
libbitcoin-protocol
libphonenumber
mlpack
monero
ncmpcpp
ompl
openvdb
osm2pgsql
pdns
pdnsrec
povray
quantlib
rdkit
simgrid
simple-amqp-client
vowpal-wabbit
wangle
watchman
wownero
```

**Comment by carlocab** [comment]
We can probably start with a rev bump of the Linux linkage failures plus a version bump for `boost-python3` and `boost-mpi`. Let's merge #83239 first, though, as I think that one shouldn't take any work.

**Comment by danielnachun** [comment]
The only remaining failures specific to Linux now are `boost-mpi` and `monero`.  `boost-mpi` is failing because the self-hosted runner only appears to have 1 core available, which causes the test to fail.  `monero` probably needs to be built with brewed GCC.  

The remaining failures all fail with the same errors across the different OSes, and are probably upstream issues.  An issue was already opened for the `bitcoin` formulae.  I'm not sure what's going on with `povray` - we may need to report that upstream as well.

**Comment by selsta** [comment]
> The only remaining failures specific to Linux now are boost-mpi and monero.

Can I find logs anywhere for monero build issue?

**Comment by carlocab** [comment]
> Can I find logs anywhere for monero build issue?

https://github.com/Homebrew/homebrew-core/actions/runs/1130651018

Click on any of the red ❌s on the left.

**Comment by selsta** [comment]
@carlocab https://github.com/monero-project/monero/pull/7902 should resolve the issue.

**Comment by selsta** [comment]
> Edit: Oops, you were asking specifically about monero. See https://github.com/Homebrew/homebrew-core/pull/83243/checks?check_run_id=3329581878#step:7:2847

#84411 contains `boost 1.77` compatibility fix.

**Comment by carlocab** [comment]
Thanks @selsta. Let's try to get CI going again to see where we are with this.

**Comment by cho-m** [comment]
`povray` failure is an issue in Boost. Upstream issue https://github.com/boostorg/math/issues/675, Fix commit https://github.com/boostorg/math/commit/720536a08e4e33639869e1b7a99d9ec923409c0b
```
clang++ -DHAVE_CONFIG_H -I. -I../unix  -I../source/backend -I../source/base -I../source/frontend -I../unix -I../vfe -I../vfe/unix -pthread -I/usr/local/opt/boost/include  -pipe -Wno-multichar -Wno-write-strings -O3 -ffast-math -march=native -D_THREAD_SAFE -c -o backend/control/messagefactory.o backend/control/messagefactory.cpp
In file included from backend/scene/view.cpp:34:
In file included from /usr/local/opt/boost/include/boost/math/common_factor.hpp:14:
/usr/local/opt/boost/include/boost/math/common_factor_ct.hpp:17:1: error: _Pragma takes a parenthesized string literal
BOOST_MATH_HEADER_DEPRECATED("<boost/integer/common_factor_ct.hpp>");
^
```

---

`bitcoin` failure has upstream merged PR fix in https://github.com/bitcoin/bitcoin/pull/22713 and was backported to branch 0.21 in https://github.com/bitcoin/bitcoin/pull/22808, but might not be directly usable given other commits have gone into branch.

v0.21.2 has been in testing phase using rc2, but I don't expect a release too soon given rc3 is planned beforehand.

---

`libbitcoin` is fixed in head, but has undergone a refactor while current release is from 2019. So, may require a bit of effort to backport.

**Comment by SMillerDev** [comment]
Replaced by https://github.com/Homebrew/homebrew-core/pull/91224
