### ISSUE TITLE
Big Sur Intel mass bottling tracking issue

### ISSUE THREAD

**Issue by jonchang** [Homebrew/homebrew-core#64785]
**If you are a Homebrew user on macOS Big Sur:**

> We do not provide support for this released but not yet supported version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or any other official channels. You are responsible for
> resolving any issues you experience while you are running this
> released but not yet supported version.

Maintainers, our self-hosted runners for macOS 11.0 Big Sur on Intel are now up and running. To build a bottle on Big Sur, run:

```
brew dispatch-build-bottle --macos 11.0 --upload --issue=64785 FORMULA
```

This will:

1. Run `brew test-bot` on that formula for a single macOS version (11.0)
2. Upload and commit the bottle hash (e.g. https://github.com/Homebrew/homebrew-core/commit/a1e2f9abc36d7d738e6fd20c1c50ad6cd5720294)
3. Post in this issue if there are any build failures.

**Ensure that all dependencies of the formula you are requesting a bottle for already have bottles of their own.** This will help avoid frankenbottles (where bottles are built using dependencies bottled for earlier versions of macOS). Consider using FX's script: https://github.com/Homebrew/homebrew-core/issues/64785#issuecomment-727192929

Note that the Big Sur runners do not have cask osxfuse, adoptopenjdk8, or xquartz installed. If any formulae had undeclared dependencies on these Requirements, they'll need to be updated or deprecated/disabled/removed, as appropriate.

I've also been running a script that automatically dispatches new bottling jobs if it sees we have idle runners. Think of it as a background job that will ensure that we are always at 100% utilization of the Big Sur runners. Any pull request or dispatch job will make it stop filling the queue, so that way you won't have wait to test something that you want to work on.

I've restricted this issue to repository collaborators as it is likely to attract many requests for support. Once we get the most popular formulae migrated this should be unlocked.

**Comment by jonchang** [comment]
openssl@1.1 manually published in 548542b987c67f961539b1952d2f23fbe441d4dc

**Comment by fxcoudert** [comment]
A shell script (run without argument) that tells you what formulas are ready to be bottled, in order of the analytics list:

```
#!/bin/bash

cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula

top=`brew info --analytics | cut -c 9-60 | grep -v '[(\/\-]'`

# List of formulas that are bottled (or bottle unneeded)
bottled=`egrep -l '(sha256.* => :big_sur|bottle :unneeded)' *.rb | sed 's/\.rb$//' | xargs`
bottled=" $bottled "

# One argument: the formula to check
function check_deps() {
  test -e $1.rb || return
  if [[ "$bottled" == *" $1 "* ]]; then
    return
  fi

  deps=`grep '^ *depends_on "' $1.rb | sed -e 's/^ *depends_on "//' -e 's/".*//'`
  for dep in $deps ; do
    if [[ "$bottled" == *" $dep "* ]]; then
      true
    else
      return
    fi
  done
  echo "$1"
}

for i in $top ; do
  check_deps $i
done
```

It's ugly shell, but it works

**Comment by jonchang** [comment]
Any luck getting cmake to build?

**Comment by jonchang** [comment]
Ok, the fully qualified name didn't work either.

**Comment by jonchang** [comment]
Cmake build: https://github.com/Homebrew/homebrew-core/actions/runs/363147364

**Comment by fxcoudert** [comment]
> bottle request for faad2 failed

Hum, audit failures about homepage being unreachable block bottling… gonna be annoying, that

**Comment by jonchang** [comment]
I'm not sure why we're seeing this error, it was already fixed last month: https://github.com/Homebrew/ruby-macho/pull/264

```
==> brew audit cocoapods --online --git --skip-style
==> FAILED
Error: Failed to read Mach-O binary: /usr/local/Cellar/cocoapods/1.10.0/libexec/extensions/universal-darwin-20/2.6.0/ffi-1.13.1/ffi_c.bundle
Error: Unrecognized Mach-O load command: 0x80000034
```

**Comment by jonchang** [comment]
https://github.com/Homebrew/brew/pull/9115 for cocoapods

**Comment by jonchang** [comment]
Qt bottle: https://github.com/Homebrew/homebrew-core/runs/1399724540?check_suite_focus=true

```
2020-11-14T13:37:04.4534680Z ERROR at //build/config/mac/mac_sdk.gni:80:5: Script returned non-zero exit code.
2020-11-14T13:37:04.4535370Z     exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
2020-11-14T13:37:04.4536250Z     ^----------
2020-11-14T13:37:04.4537470Z Current dir: /private/tmp/qt-20201114-71251-zayscx/qt-everywhere-src-5.15.1/qtwebengine/src/core/release/
2020-11-14T13:37:04.4539390Z Command: /usr/bin/python2 /private/tmp/qt-20201114-71251-zayscx/qt-everywhere-src-5.15.1/qtwebengine/src/3rdparty/chromium/build/mac/find_sdk.py --p
rint_sdk_path --print_bin_path 11.0
2020-11-14T13:37:04.4540350Z Returned 1.
2020-11-14T13:37:04.4540630Z stderr:
2020-11-14T13:37:04.4540810Z 
2020-11-14T13:37:04.4541130Z Traceback (most recent call last):
2020-11-14T13:37:04.4542590Z   File "/private/tmp/qt-20201114-71251-zayscx/qt-everywhere-src-5.15.1/qtwebengine/src/3rdparty/chromium/build/mac/find_sdk.py", line 127, in <modul
e>
2020-11-14T13:37:04.4543540Z     print(main())
2020-11-14T13:37:04.4544940Z   File "/private/tmp/qt-20201114-71251-zayscx/qt-everywhere-src-5.15.1/qtwebengine/src/3rdparty/chromium/build/mac/find_sdk.py", line 96, in main
2020-11-14T13:37:04.4546330Z     raise Exception('No %s+ SDK found' % min_sdk_version)
2020-11-14T13:37:04.4546830Z Exception: No 11.0+ SDK found
2020-11-14T13:37:04.4547070Z 
2020-11-14T13:37:04.4547480Z See //build/config/sysroot.gni:65:3: whence it was imported.
2020-11-14T13:37:04.4548010Z   import("//build/config/mac/mac_sdk.gni")
2020-11-14T13:37:04.4548860Z   ^--------------------------------------
2020-11-14T13:37:04.4549300Z See //BUILD.gn:76:5: which caused the file to be included.
2020-11-14T13:37:04.4549750Z     "//net:net_unittests",
2020-11-14T13:37:04.4550500Z     ^--------------------
2020-11-14T13:37:04.4550850Z Project ERROR: GN run error!
2020-11-14T13:37:04.4551770Z make[3]: *** [sub-gn_run-pro-make_first] Error 3
2020-11-14T13:37:04.4552750Z make[2]: *** [sub-core-make_first] Error 2
2020-11-14T13:37:04.4553860Z make[1]: *** [sub-src-make_first] Error 2
2020-11-14T13:37:04.4554900Z make: *** [module-qtwebengine-make_first] Error 2
```

**Comment by fxcoudert** [comment]
Erlang failure:

```
  You are natively building Erlang/OTP for a later version of MacOSX
  than current version (11.0.1). You either need to
  cross-build Erlang/OTP, or set the environment variable
  MACOSX_DEPLOYMENT_TARGET to 11.0.1 (or a lower version).
```

**Comment by fxcoudert** [comment]
```
xmlto:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      bin/xmlto
```

**Comment by jonchang** [comment]
Rust is in!

**Comment by jonchang** [comment]
xmlto PR: https://github.com/Homebrew/homebrew-core/pull/64800

**Comment by fxcoudert** [comment]
```
gstreamer:
  * HEAD: The URL https://anongit.freedesktop.org/git/gstreamer/gstreamer.git is not a valid git URL
```

**Comment by jonchang** [comment]
We should just change all the freedesktop URLs since they migrated to a hosted gitlab instance.

**Comment by fxcoudert** [comment]
```
vde:
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/vde/lib/python2.7/site-packages/vdeplug_python.so
```

**Comment by fxcoudert** [comment]
`screenresolution` has:

```
==> FAILED
Error: unknown or unsupported macOS version: :snow_leopard
```

I have no idea where it's coming from

**Comment by fxcoudert** [comment]
`rclone`:

```
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host_cgo.go:116:10: fatal error: 'fuse.h' file not found
#include <fuse.h>
         ^~~~~~~~
1 error generated.
```

**Comment by jonchang** [comment]
> `screenresolution` has:
> 
> ```
> ==> FAILED
> Error: unknown or unsupported macOS version: :snow_leopard
> ```
> 
> I have no idea where it's coming from

This is the git audit stepping too far back into pre-history to find an earlier version of screenresolution. I'll add it manually.

**Comment by jonchang** [comment]
> `rclone`:
> 
> ```
> /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host_cgo.go:116:10: fatal error: 'fuse.h' file not found
> #include <fuse.h>
>          ^~~~~~~~
> 1 error generated.
> ```

Looks like this had an implicit dependency on osxfuse, which I didn't install on the Big Sur runners.

**Comment by jonchang** [comment]
encoding error: https://github.com/Homebrew/homebrew-core/actions/runs/363238554?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEzMjAzNjQ0Mzk6MjEzNDg0
upstream retagged: https://github.com/Homebrew/homebrew-core/actions/runs/363238648?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEzMjAzOTE4MzU6MjEzNDg0

**Comment by fxcoudert** [comment]
`cabal-install` fails, and it's probably not specific to Big Sur:

```
Setup: Encountered missing or private dependencies:
base >=4.5 && <4.14
```

**Comment by jonchang** [comment]
Looks like four of our Big Sur runners are offline. I'll take a look at the boxes to see what's going on.

**Comment by jonchang** [comment]
Back at full strength.

**Comment by jonchang** [comment]
openjdk@8 will build with 11.0 bottles (hopefully) https://github.com/Homebrew/homebrew-core/pull/64845

**Comment by jonchang** [comment]
Maintainers, I've been running a script that automatically dispatches new bottling jobs if it sees we have idle runners. Think of it as a background job that will ensure that we are always at 100% utilization of the Big Sur runners. Any pull request or dispatch job will make it stop filling the queue, so that way you won't have wait to test something that you want to work on.
