### PR TITLE
fizz 2021.03.15.00

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
```
/tmp/fizz-20210321-68896-1fmfttb/fizz/tool/FizzServerBenchmarkCommand.cpp:138:58: error: non-virtual member function marked 'override' hides virtual member function
  void acceptError(folly::exception_wrapper ex) noexcept override {
                                                         ^
/usr/local/include/folly/io/async/AsyncServerSocket.h:172:18: note: hidden overloaded virtual function 'folly::AsyncServerSocket::AcceptCallback::acceptError' declared here: type mismatch at 1st parameter ('const std::exception &' vs 'folly::exception_wrapper')
    virtual void acceptError(const std::exception& ex) noexcept = 0;
                 ^
/tmp/fizz-20210321-68896-1fmfttb/fizz/tool/FizzServerBenchmarkCommand.cpp:266:22: error: variable type 'fizz::tool::(anonymous namespace)::FizzServerAcceptor' is an abstract class
  FizzServerAcceptor acceptor(port, backlog, &evb, serverContext, threadExe);
                     ^
/usr/local/include/folly/io/async/AsyncServerSocket.h:172:18: note: unimplemented pure virtual method 'acceptError' in 'FizzServerAcceptor'
    virtual void acceptError(const std::exception& ex) noexcept = 0;
                 ^
/tmp/fizz-20210321-68896-1fmfttb/fizz/tool/FizzServerCommand.cpp:113:58: error: non-virtual member function marked 'override' hides virtual member function
  void acceptError(folly::exception_wrapper ex) noexcept override;
                                                         ^
/usr/local/include/folly/io/async/AsyncServerSocket.h:172:18: note: hidden overloaded virtual function 'folly::AsyncServerSocket::AcceptCallback::acceptError' declared here: type mismatch at 1st parameter ('const std::exception &' vs 'folly::exception_wrapper')
    virtual void acceptError(const std::exception& ex) noexcept = 0;
                 ^
/tmp/fizz-20210321-68896-1fmfttb/fizz/tool/FizzServerCommand.cpp:1018:22: error: variable type 'fizz::tool::(anonymous namespace)::FizzServerAcceptor' is an abstract class
  FizzServerAcceptor acceptor(
                     ^
/usr/local/include/folly/io/async/AsyncServerSocket.h:172:18: note: unimplemented pure virtual method 'acceptError' in 'FizzServerAcceptor'
    virtual void acceptError(const std::exception& ex) noexcept = 0;
                 ^
```

**Comment by dtrodrigues** [comment]
Needs a newer folly built but recent versions do not build on 10.14
