### ISSUE TITLE
graphviz failed to build on 10.11.6

### ISSUE THREAD

**Issue by bwagner** [Homebrew/homebrew-core#8202]
### Bug reports:
==> Downloading http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.40.20161221.0239.tar.gz
Already downloaded: /Users/bwagner/Library/Caches/Homebrew/graphviz-2.40.20161221.0239.tar.gz
==> ./configure --prefix=/usr/local/Cellar/graphviz/2.40.20161221.0239 --without-qt --with-quartz --with-gts --disable-swig --without-pangocairo --without-fr
==> make install
Last 15 lines from /Users/bwagner/Library/Logs/Homebrew/graphviz/02.make:
  CCLD     libgdtclft.la
Undefined symbols for architecture x86_64:
  "_GdPtrTypeSet", referenced from:
      _gdCmd in gdtclft.o
      _tclGdTextCmd in gdtclft.o
      _GdPtrType in gdtclft.o
  "_GdPtrTypeUpdate", referenced from:
      _GdPtrType in gdtclft.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libgdtclft.la] Error 1
make[3]: *** [install-recursive] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

https://gist.github.com/549e1c788fcfe0bb0394db289a3235a6

**Comment by ilovezfs** [comment]
if you add `depends_on "gd"` to the formula it will work.

**Comment by nijikon** [comment]
#8210

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/8210.

**Comment by ilovezfs** [comment]
@bwagner if you brew update and brew upgrade it should now be fixed.

**Comment by bwagner** [comment]
Terrific, it works. Thank you.
