### ISSUE TITLE
gdal-2.4.4 does not build with Poppler v0.85+

### ISSUE THREAD

**Issue by cmarquardt** [Homebrew/homebrew-core#54085]
## Formalities

- [x] ran `brew update` and can still reproduce the problem? *Yes*
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? *Yes, although I'm using a non-standard prefix.*
- [N/A] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? *No, but the relevant output is included below.*
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? *N/A*

## What you were trying to do (and why)

Upgrade `gdal` from v2.4.4_2 to v2.4.4_4. Because there was an update available.

## What happened (include command output)

`brew upgrade gdal` results in a failed compilation (note that brew doesn't pour the bottle, but instead chooses to build from source; maybe because I prefer to use a non-standard prefix).

See below for the command output.

## What you expected to happen

That `gdal` compiles cleanly.

## Output

The error message causing the compilation to fail is:

````
pdfdataset.cpp:4072:5: error: no matching function for call to 'setErrorCallback'
    setErrorCallback(PDFDatasetErrorFunction, nullptr);
    ^~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/poppler/0.88.0/include/poppler/Error.h:53:13: note: candidate function not viable: requires single argument 'cbk', but 2 arguments were provided
extern void setErrorCallback(ErrorCallback cbk);
            ^
[...]
1 error generated.
make[2]: *** [../o/pdfdataset.lo] Error 1
````
The above happens for both `poppler` v0.87.0 and v0.88.0, and probably for all versions since v0.85.0

## Why it fails

The reason for the failure is that `poppler` changed the call signature of `setErrorCallback()` by adding a second argument, apparently in v0.85. According to the [Release Notes of `gdal` v2.4.4](https://github.com/OSGeo/gdal/blob/v2.4.4/gdal/NEWS), this release of `gdal` does however only support v0.82 and v0.83 of `poppler`.

`gdal` v2.4.4 was released on 8 January 2020; on the same day, a [patch supporting the development version of `poppler` 0.85]() was committed to the `gdal` repository, fixing the above problem. However, it doesn't seem to have made it into the v2.4.4 release.

## What can be done about it

I see two alternatives:
1. Update the `gdal` formula to build against `podofo` (another pdf library supported by `gdal`) instead of of `poppler`;
2. Update the `gdal` formula to include the patch mentioned above.

For me, both approaches seem to work. I'm happy to provide a merge request for either - but which approach would the homebrew maintainers prefer?

Thanks.

**Comment by Bo98** [comment]
Upstream prefer poppler over podofo, so we should do the same. I'd go with the patch option.

Eventually, we should be switching to gdal 3.x - but there's some outstanding compatibility issues with dependents at the moment.

**Comment by cmarquardt** [comment]
Thanks for the suggestion - there's a pull request now. 

I agree switching to v3.x would be best; until then, keeping 2.4.4 working would be nice.
