### PR TITLE
sc-im 0.6.0 (new formula)

### PR DESCRIPTION
**Pull request by claui**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

___

This PR is the sequel to the orphaned [PR #12260](https://github.com/Homebrew/homebrew-core/pull/12260).

On top of @jez’s three commits, I have added a simple functional test and upgraded the version to 0.6.0.

Discussions and reviews should be resumed here if needed.

While the formula does pass the strict audit (`brew audit --strict --online sc-im`), it [still doesn’t pass](https://github.com/Homebrew/homebrew-core/pull/12260#issue-220496205) the stricter, `--new-formula` audit.

### CODE REVIEW

File: Formula/sc-im.rb [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+  homepage "https://github.com/andmarti1424/sc-im"
+  url "https://github.com/andmarti1424/sc-im/archive/v0.6.0.tar.gz"
+  sha256 "5da644d380ab3752de283b83cce18c3ba12b068d0762c44193c34367a0dcbc38"
+  head "https://github.com/andmarti1424/sc-im.git", :branch => "freeze"
+
+  depends_on "ncurses"
+
+  def install
+    cd "src" do
+      system "make", "prefix=#{prefix}", "LDFLAGS=-L#{Formula["ncurses"].lib}"
```
Comment (JCount) [inline Formula/sc-im.rb]: This should probably be changed to `"LDFLAGS=-L#{Formula["ncurses"].opt_lib}"`. This may effectively be a no-op in this instance because `ncurses` is keg-only, but it is good to maintain consistency.

Comment (dunn) [inline Formula/sc-im.rb]: I think it's also more common to use `ENV.prepend` to modify build flags; see e.g. [`burp.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/burp.rb)

**Comment by JCount** [comment]
@claui Any movement here?

**Comment by claui** [comment]
@JCount I have incorporated the changes; however, a new issue has come up since.

When I `brew test Formula/sc-im.rb`, I get:

```
Error: sc-im: failed
undefined method `assertions' for #<Formulary::FormulaNamespacec6e2b55e001f42eaabcfc33c1547d72b::ScIm:0x007fe6188cf180>
/Library/Ruby/Gems/2.0.0/gems/minitest-5.4.1/lib/minitest/assertions.rb:126:in `assert'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/assertions.rb:38:in `assert'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/assertions.rb:187:in `assert_equal'
[…]
```

`git bisect` suggests that commit https://github.com/Homebrew/brew/commit/c45cca8 seems to have introduced this behavior on my machine.

In fact, `brew test` now breaks on my machine with any formula that uses `assert_match`, e. g. `brew test unison`. This even happens outside my dev environment, i. e. on my normal, untouched Homebrew.

Paging @MikeMcQuaid as the author of c45cca8 – any suggestions/pointers?

**Comment by MikeMcQuaid** [comment]
@claui `sudo gem uninstall minitest`

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/sc-im/0.6.0/bin/scim --nocurses --quit_afterload
Device not configured
Error: sc-im: failed
<0> expected but was
<255>.
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@claui what is this status here?

**Comment by claui** [comment]
@MikeMcQuaid Just to make sure we’re on the same page: isn’t the `brew test` subcommand supposed to work for _any Homebrew user_ (as opposed to _primarily formula authors_)?

As we have no control over whether a given Homebrew user has the `minitest` gem installed or not, how about I leave `minitest` installed deliberately on my system, and start looking into making the test work _either way?_

I wouldn’t feel comfortable if in the long run, `brew test sc-im` were responsible for extra issue reports trickling in. 😉

@ilovezfs @MikeMcQuaid Would that approach make sense?

**Comment by MikeMcQuaid** [comment]
> As we have no control over whether a given Homebrew user has the minitest gem installed or not, how about I leave minitest installed deliberately on my system, and start looking into making the test work either way?

Sounds good to me :+1:

**Comment by fxcoudert** [comment]
@brewtestbot test this please

**Comment by fxcoudert** [comment]
On the CI, test still fails with

```
==> /usr/local/Cellar/sc-im/0.6.0/bin/scim --nocurses --quit_afterload
Device not configured
Error: sc-im: failed <0> expected but was <255>.
```

**Comment by claui** [comment]
For the record, I’m still looking into a solution for `brew test` as described above.
This will probably take me another week until I can move on with this PR.

**Comment by ilovezfs** [comment]
@claui any updates here?

**Comment by claui** [comment]
@ilovezfs Will give feedback when I’m on my Mac later today.

**Comment by ilovezfs** [comment]
@claui thanks!

**Comment by claui** [comment]
With Homebrew’s recent change to Ruby 2.3.3, I have found `brew test` to work reliably again, regardless of whether I have `minitest` installed. 😄 

Which brings us back to the one remaining issue.
The formula depends on the GNU `ncurses` library in a recent version, just like the one Homebrew provides as a separate formula. Because macOS ships with a version of ncurses on its own, the Homebrew formula is tagged `keg_only :provided_by_macos`. This in turn causes `brew audit --strict --new-formula` to fail. which I feel is unjustified in this case.

As long as this PR has existed, several people (including myself) have been unable to build `sc-im` with the macOS-provided ncurses. Even if there was some hack that could make it work somehow, there’s no point in doing that because It Just Works™ with the `ncurses` formula. ☺️

**The solution is to whitelist** `ncurses` in the context of `audit.rb`. **We need a one-line PR to the core for that.**

**Comment by claui** [comment]
@ilovezfs Just for clarification: may I ask what you mean by »This is a --new-formula only audit and one we'd prefer to keep?«

I’m curious because PR #3290 does no such thing as remove the audit.

**Comment by ilovezfs** [comment]
It means that it causes CI failure for a new formula that has not yet been merged, but does not cause CI failure for any formula already in Homebrew. So once we've decided that a given use of the ncurses formula is acceptable and merge the formula, the audit failure goes away for that particular formula.

This is an endless source of confusion since people understandably think that PRs must be green in order to be merged, but new-formula-only audits mean some new formula PRs must be merged while red.

**Comment by claui** [comment]
Thanks for the explanation @ilovezfs!

Regarding the `sc-im` formula, what course of action would you suggest?

**Comment by ilovezfs** [comment]
We'll need to get upstream to fix it so it works with system ncurses.

`inreplace "Makefile", "-lncursesw", "-lncurses"` causes it to build successfully.

The Makefile has
```
ifeq ($(shell uname -s),Darwin)
  NCURSES_CFLAGS ?=
  NCURSES_LIBS   ?= -lncursesw
```
which means they're hard coding the assumption that Darwin -> MacPorts, which uses ncursesw.

**Comment by ilovezfs** [comment]
Hmm … I see it segfaults with system ncurses. That's not good.

File: Formula/sc-im.rb [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+  desc "Spreadsheet program for the terminal, using ncurses"
+  homepage "https://github.com/andmarti1424/sc-im"
+  url "https://github.com/andmarti1424/sc-im/archive/v0.6.0.tar.gz"
+  sha256 "5da644d380ab3752de283b83cce18c3ba12b068d0762c44193c34367a0dcbc38"
+  head "https://github.com/andmarti1424/sc-im.git", :branch => "freeze"
+
+  depends_on "ncurses"
+
+  def install
+    ENV.prepend "LDFLAGS", "-L#{Formula["ncurses"].opt_lib}"
```
Comment (ilovezfs) [inline Formula/sc-im.rb]: doesn't look like this is actually needed

File: Formula/sc-im.rb [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+
+    cd "src" do
+      system "make", "prefix=#{prefix}"
+      system "make", "prefix=#{prefix}", "install"
+    end
+  end
+
+  test do
+    assert_match /\s2$/, pipe_output(
```
Comment (ilovezfs) [inline Formula/sc-im.rb]:
```
  test do
    input = <<-EOS.undent
      let A1=1+1
      getnum A1
    EOS
    output = pipe_output("#{bin}/scim --nocurses --quit_afterload", input, 0)
    assert_equal "nowide 2", output.lines.last.chomp
  end
```

**Comment by ilovezfs** [comment]
@claui Given it segfaults with system ncurses, I'm fine with using the ncurses formula. I requested a couple tweaks above.

File: Formula/sc-im.rb (hunk 2 above)
Comment (claui) [reply Formula/sc-im.rb]: Good point, thanks!

I just checked it; it indeed works for me without that line.

File: Formula/sc-im.rb (hunk 3 above)
Comment (claui) [reply Formula/sc-im.rb]: A lot more readable that way. Thanks!

**Comment by claui** [comment]
@ilovezfs I have implemented your suggested changes, and squashed the commits too.

**Comment by dunn** [comment]
Getting a non-audit test failure:
```
==> /usr/local/Cellar/sc-im/0.6.0/bin/scim --nocurses --quit_afterload
Device not configured
Error: sc-im: failed
<0> expected but was
<255>.

**Comment by claui** [comment]
Oh right. When the shell session is not interactive, sc-im quits with a status code of 255 instead of 0. Before it exits, it prints the correct result no matter what. We can safely ignore the exit status in this case.

**Comment by claui** [comment]
The test now ignores the exit status, and also mutes stderr for good measure.

**Comment by dunn** [comment]
OK.  Then we can either change `0` to `255` in the `#pipe_output`, or try to trick the shell with `popen` or [`script`](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/aalib.rb).

**Comment by dunn** [comment]
Oh sorry, missed your last comment.

File: Formula/sc-im.rb [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+    end
+  end
+
+  test do
+    input = <<-EOS.undent
+      let A1=1+1
+      getnum A1
+    EOS
+    output = pipe_output(
+      "#{bin}/scim --nocurses --quit_afterload 2>/dev/null", input
```
Comment (ilovezfs) [inline Formula/sc-im.rb]: I think the need for 2>/dev/null may be a bug in brew and/or CI. This just showed up on https://github.com/Homebrew/homebrew-core/pull/19321

Comment (claui) [reply Formula/sc-im.rb]: It’s only a CI issue as far as the CI runs in a non-interactive shell, and sc-im doesn’t seem to support that. I’ve been able to reproduce the issue in any non-interactive shell, e. g. when I run the following script in my text editor:

```
/usr/local/Cellar/sc-im/0.6.0/bin/scim \
  --nocurses --quit_afterload \
    <<< $'let A1=1+1\ngetnum A1'
```

image

Comment (ilovezfs) [reply Formula/sc-im.rb]: Yeah, it's looking like the issue with https://github.com/Homebrew/homebrew-core/pull/19321 is a regression.

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @claui! Shipped :ship: :tada:
