### ISSUE TITLE
List of formula missing Linux bottles

### ISSUE THREAD

**Issue by danielnachun** [Homebrew/homebrew-core#86422]
This should now be a complete list of all remaining formulae missing Linux bottles which are not deprecated, disabled or macOS-only.  Please feel free to ask for clarifications about the my explanations I have given.

~~These formulae currently have a bottle in linuxbrew-core, but not one here.  There are no differences between the formulae in the two cores, so these likely need some additional fix to work on Linux that wasn't needed the last time they were bottled in linuxbrew-core.~~
# Existing/previous PR

- [ ] libetpan - https://github.com/Homebrew/homebrew-core/pull/96869
- [ ] musepack- https://github.com/Homebrew/homebrew-core/pull/92041, https://github.com/Homebrew/homebrew-core/pull/93871, https://github.com/Homebrew/homebrew-core/pull/96781
- [ ] opentsdb - https://github.com/Homebrew/homebrew-core/pull/100699
- [ ] strongswan - seems to break because of how we patch RPATHs: https://github.com/Homebrew/homebrew-core/pull/87998
# Needs PR
## Build Failure
- [ ] cubeb - needs to make a release: https://github.com/mozilla/cubeb/issues/666
- [x] getmail - `Error: Too many redirects (max = 25)` - will be disabled because it depends on Python 2
- [ ] libgr - fails to link `qhull` because it tries to use static `qhull` but is itelf dynamically linked  - uses static `qhull` because it depends on a deprecated API not available in the shared library
- [ ] libpointing - downloads a macOS-specific source archive; when building on Linux it requires `qmake` from `qt@5` and `make install` produces an empty installation - may also need a Python 2 script to generate proper Makefile
- [x] mono - `msbuild` fails to build
- [ ] nxengine - The formula copies a system font on macOS into the cellar - a substitute font will be needed on Linux.
- [ ] openj9 - `EOFError: End of file reached` - this appears to append while calling the `patchelf` gem during keg relocation - needs a closer look.
- [ ] rancid - `error: can't figure out how to pass count == 1 to ping`
- [ ] shtools - `libtool` invocation for linking does not work on Linux
- [ ] syck - .y files seem to be too old for `bison` - `error: conflicting types for ‘syckparse’`
- [ ] txr - `txr` binary segfaults during build
### Vendored dependencies
- [ ] aacgain - fails because it tries to build old, vendored versions of `mp4v2`, `faad`, and `mp3gain`.
- [ ] code-server - fails linkage audit because of a musl-linked binary; also needs to build `node-argon2` from source because the pre-built binary needs a newer `glibc`, but the build fails.
- [ ] falcon - `error: conflicting declaration ‘typedef long long int int64_t’` - contains an old vendered copy of `mongo-c-driver`
- [ ] montage - ~~probably missing an `#include <string.h>` in `ccalc.c`: `ccalc.c:28:7: error: expected identifier or ‘(’ before ‘__extension__’ char *strdup(const char *s1);`~~ - this problem is fixed in montage 6.0, but it now fails on macOS because it installs vendored dependencies - these only work on Linux because we use RPATH instead of install names.
- [ ] openmodelica - tries to install vendored copy of `zeromq` it later fails to find: `file INSTALL cannot find /tmp/openmodelica-20220411-17127-197f2n5/OMCompiler/3rdParty/libzmq/build/lib/libzmq.so.4.2.3: No such file or directory.`
## Test failure
- [ ] argus - `vm_stat: not found`
- [ ] bazel - test fails because patchelf.rb bug that breaks binary
- [ ] buildapp - `Can't find sbcl.core`
- [ ] cafeobj - `Can't find sbcl.core`
- [ ] clfft - test binary segfaults, possibly because it cannot find OpenCL device
- [ ] dynare - test seems to indicate Linux bottle is broken - will need to follow up with upstream.
- [x] fanyi - `Minitest::Assertion: Expected: 0, Actual: 1` - might be due to missing Chinese language locale (i.e. `zh_cn`)
- [ ] gel - test times out
- [ ] git-url-sub - test fails because of BSD-specific code
- [ ] gopass - `Minitest::Assertion: Expected: 0, Actual: nil` - only fails in CI, probably because of a patchelf.rb bug.
- [ ] ios-webkit-debug-proxy - upstream says Linux is supported - test fails due to network error: `url: (7) Failed to connect to localhost port 35707: Connection refused`
- [ ] libbi - test hangs indefinitely
- [ ] libbpg - `bpgenc` binary segfaults
- [ ] libdrawtext - uses a macOS system font which needs a substitute on Linux
- [ ] nq - `Minitest::Assertion: Expected /exited\ with\ status\ 0/ to match "==> ,18103a44a7b.4542\nexec /home/linuxbrew/.linuxbrew/Cellar/nq/0.5/bin/nq touch TEST\n\n".` - only fails in CI
- [ ] nrpe -  `TypeError: no implicit conversion from nil to integer`
- [ ] oil - test fails because patchelf.rb bug that breaks binary
- [ ] pbc - `pbc` binary segfaults
- [x] pla - upstream URL doesn't work anymore
- [ ] py-spy - wants to run test as root
- [x] safe-rm - `/bin/rm: missing operand`
- [x] showkey - test hangs indefinitely
- [ ] snapcast - might be failing because `avahi` needs root to work
- [ ] snappystream - test seems to fail because output is blank
- [ ] sync_gateway - needs to be updated to 3.0.0, but test fails: `2022/05/29 13:10:48 Couldn't start Sync Gateway: 2 errors: a server must be provided in the Bootstrap configuration Must use secure scheme in Couchbase Server URL, or opt out by setting bootstrap.use_tls_server to false. Current URL:`
- [ ] vgrep - `Minitest::Assertion: Expected: 0  Actual: nil`
## Unbottled dependency
- [ ] bsdiff - neesd `bsdmake`, but can be patched to work without it: https://github.com/archlinux/svntogit-community/blob/packages/bsdiff/trunk/Makefile.patch
- [ ] cfv - `python2`
- [ ] claws-mail - `libetpan`
- [ ] gopass-jsonapi - `gopass`
- [ ] wiiuse - `bluez` - `bluez` seems to need `glibc` >= 2.25
- [ ] pbc-sig - `pbc`
- [ ] pgloader - `buildapp`
- [ ] scriptcs - `mono`
- [x] viewvc - `python2`
## Possibly macOS-only
- [ ] iblinter - `error: unable to load standard library for target 'x86_64-unknown-linux-gnu'` - Swift formula
- [ ] plank - `<unknown>:0: error: unable to load standard library for target 'x86_64-unknown-linux-gnu'` - Swift formula
- [ ] xcprojectlint - seems to be incompatible with Swift 5.5+: `error: value of type '(@escaping (Result<T, ErrorType>) -> Void) -> Void' has no member 'dematerialize'`
- [ ] sourcedocs - `SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed` - Swift formula
- [ ] weaver - `error: cannot find 'fputs' in scope` - Swift formula
- [ ] ospray - `embree` must be build with SSE4.1 support, but Linux is set to `core2`.
- [ ] bsdmake - would require patching to build because it is a BSD program.
- [ ] icbirc - requires `bsdmake`, appears to be a BSD program
- [ ] proctools - requires `bsdmake`, appears to be a BSD program
- [ ] wait_on - requires `bsdmake`, appears to be a BSD program
# Temporarily debottled
- [x] qt-postgresql - affected by a larger problem with Qt plugins
- [x] qt - broken relocation
- [x] qmmp - needs `qt`
- [x] mkvtoolnix - needs `qt`
- [ ] wxmaxima - can't find `wxwidgets` because it now needs to `webview` support in `wxwidgets`.  This can be fixed by making `wxwidgets` depend on `webkitgtk` on Linux.
- [x] supermodel - ` Src/Sound/MPEG/audio.cpp:193:16: error: reference to ‘data’ is ambiguous`
# Fixed
- [x] `aida-header` - upstream FTP URL times out - the web interface to the CVS repository also returns a 404.  This should probably be deprecated. #98174
- [x] antlr@2 - https://github.com/Homebrew/homebrew-core/pull/102007
- [x] app-engine-python
- [x] archivemount
- [x] aterm - upstream URL times out: `The requested URL returned error: 500`.  This should probably be deprecated if no working URL exists. - #88732
- [x] ats2-postiats - sha256 error - #88856
- [x] avfs -- #102445
- [x] balena-cli - build failure: ` No rule to make target '/home/linuxbrew/.linuxbrew/Cellar/balena-cli/12.25.0/libexec/lib/node_modules/balena-cli/node_modules/@ronomon/direct-io/build/Release/binding.node', needed by '/home/linuxbrew/.linuxbrew/Cellar/balena-cli/12.25.0/libexec/lib/node_modules/balena-cli/node_modules/@ronomon/direct-io/binding.node'` - #97811
- [x] bareos-client - https://github.com/Homebrew/homebrew-core/pull/98016
- [x] beecrypt - `Expected /ZF8D/ to match "oSCb\n\n".`
- [x] bit - node package which install native binaries because of a dependency on https://github.com/Level/leveldown.  That package provides instructions on building natively from source.  It should be probably be downloaded as a resources and built from source. - #98443
- [x] bitchx - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitchx-git
- [x] bmon - `libnl`
- [x] btfs -- #102446
- [x] braid - test failure: `Braid: Error: local changes are present` - #96309
- [x] cdb - missing `#<include errno.h` in `buffer_put.c` and `strerr_sys.h`
- [x] cedille - build failure: `Warning: 'hs-source-dirs: src/MAlonzo/Code' directory does not exist.
Warning: Directory listed in cedille.cabal file does not exist: src/MAlonzo/Code
cedille> build (exe)
make: *** [cedille-stack] Error 42` - I can't reproduce this locally in Docker. - #98572
- [x] cf4ocl
- [x] clblas
- [x] clblast
- [x] clinfo
- [x] coin3d - `pyside@2`
- [x] cp2k - hardcodes paths to dependencies in build file - should be fixed with next release
- [x] cryfs
- [x] curlftpfs
- [x] daemontools
- [x] dafny - `mono`
- [x] dbxml - build failure - The initial failure was it could not find a valid BerkeleyDB tree even though we specify the path to the `berkeley-db` optdir.  It uses the static library names to figure out the version of BerkeleyDB and I broke this when I removed the static libraries for `berkeleydb` to reduce size.  This was easy to fix as we already had an `inreplace` to change the `.la` extension to `.a`, which changed so that it looks for `.so` instead.  Fixing that revealed a **second**, unrelated problem.  The configure script will fail if it thinks there is more than one version of BerkeleyDB installed, and in our current get we have `libdb-18.1.so` and a symlink to it called `libdb-18.so`.  Unfortunately `dbxml` interprets this as meaning multiple versions of the BerkeleyDB are installed when in reality it is just one.  This is easy enough for us to fix with `inreplace`, but should probably be upstreamed. -- #100471
- [x] delta - test failure: `	**************** FAIL: The initial input does not pass the test.` -- #100475
- [x] devtodo - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/stdlib.patch?h=devtodo
- [x] dieharder - SSL cert failure: `curl: (60) SSL certificate problem: unable to get local issuer certificate`.  The link works correctly in a web browser. (Disabled in https://github.com/Homebrew/homebrew-core/commit/73ae0827dac053fed999afdc828eea316834cdef)
- [x] djbdns - `daemontools`
- [x] djview4 - missing dependency `djvulibre` #98175
- [x] djvulibre - SSL cert failure - #88190
- [x] dnsdist - `cdb`
- [x] doublecpp - missing `#include <cstdlib>` in `sourcemodifier.cpp`
- [x] drake - `java: command not found`
- [x] dvd+rw-tools - needs patch to build: https://www.linuxfromscratch.org/blfs/view/svn/multimedia/dvd-rw-tools.html
- [x] eiffelstudio - `pax`
- [x] embree - https://github.com/Homebrew/homebrew-core/pull/74332
- [x] ext2fuse
- [x] f3d - has a build failure that due to `vtk` needing to be rebuilt on Ubuntu 22.04
- [x] fragroute - configure fails while looking for `libpcap` even when it is included as dependency
- [x] fuse-zip -- #102448
- [x] fwknop - `iptables` or other firewall
- [x] get-flash-videos - can't find `XML::Simple` even though it is a resource on Linux and we use and `env_script`
- [x] gibbslda - missing include `#include <stdio.h> in lda.cpp`
- [x] gobo - `eiffelstudio`
- [x] gource - build failure
- [x] grok - needs patch to work with gperf 3.1: https://github.com/jordansissel/grok/issues/29#issuecomment-1062846423
- [x] harbour - https://github.com/Homebrew/homebrew-core/pull/102321
- [x] hashcat
- [x] healpix - build failure: `In file included from cxxsupport/fitshandle.cc:36:0:
/home/linuxbrew/.linuxbrew/Cellar/cfitsio/4.0.0/include/fitsio.h:37:25: error: too many decimal points in number
 #define CFITSIO_VERSION 4.0.0` - this should be fixable, though I'm not sure why it's a problem now.  - #95615
- [x] hexgui - `java: command not found` - #102360
- [x] hping - needs `COMPILE_TIME=-D__LITTLE_ENDIAN__` and to replace `net/bpf.h` with `pcap/pbf.h` in `libpcap_stuff.c`
- [x] i2pd - `make: Nothing to be done for 'install'`
- [x] ibex - test failure (linker flags) - #100476
- [x] idutils - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=idutils
- [x] imgproxy
- [x] iozone - sha256 error - #89504
- [x] jigdo - missing `#include <stdlib.h>` in `md5sum.hh`
- [x] juise - `libslax`
- [x] launch_socket_server - ~~`socket.cgo2.c:(.text+0x2b): undefined reference to 'launch_activate_socket'`~~ this is a macOS-only formula.
- [x] ledit - audit failure
- [x] leela-zero
- [x] libgsm - https://github.com/Homebrew/homebrew-core/pull/82415
- [x] liblinear - https://github.com/Homebrew/homebrew-core/pull/97095
- [x] liblockfile - build failure: `install: cannot change ownership of '/home/linuxbrew/.linuxbrew/Cellar/liblockfile/1.17/bin/dotlockfile': Operation not permitted` - this error only happens in CI, not in local Docker. - #98132
- [x] liblunar - The project has been split into two different tools with different names: https://github.com/yetist/lunar-date and https://github.com/yetist/lunar-calendar 
- [x] libmpd - missing `#include <"string.h">` in `libmpd-internal.h`
- [x] liboil - build failure - needs `gtkdocize` to build docs.  Add this dependency or disable document generation. - https://github.com/Homebrew/homebrew-core/pull/97181
- [x] libslax - https://github.com/Homebrew/homebrew-core/pull/104241. Previously: fails to detect `libxml2` even when it is a dependency - `checking for libxml libraries >= 2.7.7... configure: error: Could not find libxml2 anywhere, check ftp://xmlsoft.org/.`
- [x] libtensorflow - requires a shim bypass to build because it uses `bazel`, which resets the build env
- [x] ltl2ba - download fails: `curl: (60) SSL certificate problem: unable to get local issuer certificate`
- [x] mariadb-connector-odbc - linkage failure, test failure -- #100474
- [x] mdxmini - requires patching because it hardcodes `-liconv`, missing `-lm`, needs `-fPIC` CFLAG
- [x] minuit2 - upstream URL error - #97810
- [x] mlkit - `mlton`
- [x] mlton - bootstrap binary needs a newer version of `glibc`
- [x] mp3val - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/mp3val-0.1.8.diff?h=mp3val
- [x] mpack - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/gcc4-fixes.patch?h=mpack
- [x] mruby-cli - build failure - this is fails because it cannot find the `mruby-io` gem.  This is only for very old versions of `mruby`.  This tool is locked into `mruby` 1.2.0, which was released in 2015.  By all appearances this tool is unmaintained and it may be time to deprecate it. #100364
- [x] nco - `antlr@2`
- [x] networkit - needs to use GCC 11 but rebuilds the CMake cache and does not pass some arguments to CMake on rebuild
- [x] nu - `gnustep-base` (and possible other GNUStep packages)
- [x] oclgrind -- #106202
- [x] onscripter - `libavifile`
- [x] opencbm - build failure - `install: cannot change permissions of ‘/etc/opencbm.conf.d’: No such file or directory` - this only fails in CI because it is trying to write to `/etc`.  We probably need to set some additional variables, possibly `DESTDIR`. - #98180
- [x] openclonk - must be built with GCC 11, but fails because of missing `#include <limits>` in `src/script/C4AulParse.cpp` - https://github.com/Homebrew/homebrew-core/pull/103535
- [x] oscats - either missing an include or needs to use `#ifdef` in `algorithms/pick_rand.c` to avoid clash with std library error: `algorithms/pick_rand.c:38:13: conflicting types for ‘select’`
- [x] paperkey - upstream URL error - #98178
- [x] planck - ~~`/tmp/planck-20210314-10603-1qjgbqj/planck-2.25.0/planck-cljs/src/planck/bundle/gcl.cljs [line 4, col 1] Unexpected EOF while reading item 1 of list, starting at line 3 and column 3.`~~ previous issue was easy to fix - needs `webkitgtk`.
- [x] psc-package - https://github.com/Homebrew/homebrew-core/pull/86521
- [x] pyside - needs to add some extra directories to `shiboken` - https://github.com/Homebrew/homebrew-core/pull/103665
- [x] pyside@2 - cannot find OpenGL header, possibly because of issues with `qt@5` - part of https://github.com/Homebrew/homebrew-core/pull/103229
- [x] qthreads - sha256 mismatch
- [x] redstore -  probably missing `#include <netdb.h> in server.c` - `error: storage size of ‘hints’ isn’t known`
- [x] rex - https://github.com/Homebrew/homebrew-core/pull/86420
- [x] rig - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rig
- [x] rofs-filtered
- [x] runit
- [x] s3-backer
- [x] s3fs
- [x] sdl_mixer - deprecated, test failure (EDIT: Fixed in #86842)
- [x] securefs -- #102450
- [x] seexpr - ASCII test graphic doesn't match expected
- [x] sfcgal - missing dependency `cgal` (EDIT: Bottled since https://github.com/Homebrew/homebrew-core/commit/8596d837e8a3e40b92bc6be858a783f3d6f44781)
- [x] shivavg - needs patching to build: https://github.com/Ecognize/ShivaVG/pull/14/files
- [x] simple-mtpfs
- [x] smlpkg - `mlton`
- [x] standardese - needs to disable building test binaries
- [x] solidity - has a build failure that is due to `boost` needing to be rebuilt on Ubuntu 22.04
- [x] swftools - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/swftools-0.9.2.patch?h=swftools
- [x] tarsnap-gui - needs to make a new tagged release with build fixes
- [x] tracker - `tracker` binary segfaults
- [x] trafshow - needs patch to build: https://aur.archlinux.org/cgit/aur.git/tree/trafshow.patch?h=trafshow
- [x] ucspi-tcp - build failure - `Oops. Your getgroups() returned 0, and setgroups() failed; this means
that I can't reliably do my shsgr test. Please either ``make'' as root
or ``make'' while you're in one or more supplementary groups.`.  This probably stopped working when we switched to building as the `linuxbrew` user instead of `root`. -- #100875
- [x] unar - `gnustep-base`
- [x] unnethack - needs patch to build: https://github.com/UnNetHack/UnNetHack/commit/04f0a3a850a94eb8837ddcef31303968240d1c31.patch
- [x] urweb - `mlton`
- [x] viennacl
- [x] ~~voldemort - `java: command not found`~~ deprecated
- [x] vsts-cli - deprecated, test failure
- [x] waon - https://github.com/Homebrew/homebrew-core/pull/104630. Previously: uses `say` to generate AIFF for test - needs an alternative test fixture (our AIFF test fixture is empty and does not work with this)
- [x] wdfs
- [x] winexe - `./configure: line 4695: syntax error near unexpected token 'fi'`
- [x] wxpython - uses a vendored copy of `wxwidgets` that conflicts with the `wxwidget` formula if linked to `lib`.  It is possible to use the brewed `wxwidgets` instead of the vendored one, but the latest tagged release is not compatible with `wxwidgets` 3.1.6.  Upstream commits have already been made for 3.1.6 support but do not apply cleanly to the source for the stable release
- [x] yamcha - missing `#include <string.h>` or `<cstring>` in `param.cpp` - `error: 'strlen' was not declared in this scope`

**Comment by chenrui333** [comment]
Per PR discussions, we should include another two formulae in here:
- oil
- bazel

**Comment by MikeMcQuaid** [comment]
This issue seems to be stale at this point.
