### PR TITLE
cmocka 1.1.0

### LINKED ISSUE #5090: cmocka failed to build on 10.12
`gist-logs` output at https://gist.github.com/apexskier/a9720aceda93dba99ce04f9df5eb8010

I was able to install manually from cmocka's git source without trouble, but compiling fails, so I decided to try brew.

(this was a manual install's issue)
```
cc -Wall -Wall -Werror -Wswitch-default -Wfatal-errors -I/usr/local/include test.c
Undefined symbols for architecture x86_64:
  "__cmocka_run_group_tests", referenced from:
      _main in test-d2ff02.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test] Error 1 
```

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Fixes #5090.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Broken on 10.11 because of `clock_gettime`:

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/cmocka/lib/libcmocka.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/cmocka/lib/libcmocka.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by ilovezfs** [comment]
@mistydemeo https://gist.github.com/ilovezfs/81577f08244b6e1812e38b12cd7ebae2
