### ISSUE TITLE
openssl@1.1 fails to build on 10.12.4

### ISSUE THREAD

**Issue by fspreiss** [Homebrew/homebrew-core#13551]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)
I wanted to install ansible, which has openssl@1.1 as dependency.
- What happened (include command output)
While installing ansible, installing the openssl@1.1 dependency caused an error. The installation of ansible was interrupted.
    ```
    $ brew install ansible
    [output omitted]
    ==> Installing ansible dependency: openssl@1.1
    ==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.0e.sierra.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring openssl@1.1-1.1.0e.sierra.bottle.tar.gz
    Error: undefined method `strip' for :versioned_formula:Symbol
    Please report this bug:
      https://git.io/brew-troubleshooting
    /usr/local/Homebrew/Library/Homebrew/formula_support.rb:55:in `to_s'
    /usr/local/Homebrew/Library/Homebrew/caveats.rb:49:in `keg_only_text'
    /usr/local/Homebrew/Library/Homebrew/caveats.rb:18:in `caveats'
    /usr/local/Homebrew/Library/Homebrew/caveats.rb:30:in `empty?'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:490:in `caveats'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:518:in `finish'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:472:in `install_dependency'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:434:in `block in install_dependencies'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:434:in `each'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:434:in `install_dependencies'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:202:in `install'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:268:in `install_formula'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `block in install'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `each'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `install'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
    ```

- What you expected to happen
I expected that ansible and all its dependencies, such as openssl@1.1, install successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)
    ```
    $ brew install openssl@1.1
    ==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.0e.sierra.bottle.tar.gz
    Already downloaded: /Users/franzstefan/Library/Caches/Homebrew/openssl@1.1-1.1.0e.sierra.bottle.tar.gz
    ==> Pouring openssl@1.1-1.1.0e.sierra.bottle.tar.gz
    ==> Using the sandbox
    Error: undefined method `strip' for :versioned_formula:Symbol
    Please report this bug:
      https://git.io/brew-troubleshooting
    /usr/local/Homebrew/Library/Homebrew/formula_support.rb:55:in `to_s'
    /usr/local/Homebrew/Library/Homebrew/caveats.rb:49:in `keg_only_text'
    /usr/local/Homebrew/Library/Homebrew/caveats.rb:18:in `caveats'
    /usr/local/Homebrew/Library/Homebrew/caveats.rb:30:in `empty?'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:490:in `caveats'
    /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:518:in `finish'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:269:in `install_formula'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `block in install'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `each'
    /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `install'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

- Debug info
    ```
    $ brew gist-logs ansible
    Error: No logs.
    ```

    ```
    $ brew doctor
    Your system is ready to brew.
    ```

    ```
    $ brew config
    HOMEBREW_VERSION: 1.1.1
    ORIGIN: https://github.com/Homebrew/brew.git
    HEAD: edf042ee97f80955b077724119e717a51eb25e29
    Last commit: 6 months ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 2392b8448e228884511c571c243bbd9dd72a8424
    Core tap last commit: 35 minutes ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: quad-core 64-bit ivybridge
    Homebrew Ruby: 2.0.0-p648
    Clang: 8.1 build 802
    Git: 2.4.0 => /usr/local/git/bin/git
    Perl: /usr/bin/perl
    Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: 1.8.0_25
    macOS: 10.12.4-x86_64
    Xcode: N/A
    CLT: 8.3.2.0.1.1492020469
    X11: 2.7.11 => /opt/X11

**Comment by JCount** [comment]
@fspreiss Your installation of `brew` is extremely out of date, and very likely is the cause. What is the output of `git -C /usr/local/Homebrew status -v`?

**Comment by fspreiss** [comment]
```
$ git -C /usr/local/Homebrew status -v
On branch stable
nothing to commit, working tree clean
```
@JCount, thanks for your input. Could the problem be that I'm on the _stable_ branch? In any case, I ran the following command, which I found in the [README.md](https://github.com/Homebrew/homebrew-core/blob/master/README.md):
```
$ cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
remote: Counting objects: 101, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 101 (delta 75), reused 95 (delta 69), pack-reused 0
Receiving objects: 100% (101/101), 14.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (75/75), completed with 31 local objects.
From https://github.com/Homebrew/brew
   459fef3b0..e0ab162f8  master     -> origin/master
HEAD is now at e0ab162f8 Merge pull request #2632 from MikeMcQuaid/sass
Updated 2 taps (caskroom/cask, homebrew/core).
```
After this, installing openssl@1.1 worked flawlessly. Am I supposed to be/stay on the _stable_ branch? Here the new status:
```
$ brew config
HOMEBREW_VERSION: 1.2.0-84-ge0ab162f8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e0ab162f82921077cfb899637fdd39e426adfc9b
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fc2890b604e032ca29eb589f2044918f15aded4b
Core tap last commit: 79 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.4.0 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by JCount** [comment]
To get your repo to track the stable tags, try running `git -C $(brew --repo) reset --hard origin/master^ && HOMEBREW_UPDATE_TO_TAG=1 brew update`. Then run `git -C $(brew --repo) status && git -C $(brew --repo) rev-parse @`. 

Finally, could you post the output of those commands here, along with the results of `brew --version`? Thanks.

**Comment by fspreiss** [comment]
Thank you, @JCount. There you go:
```
$ git -C $(brew --repo) reset --hard origin/master^ && HOMEBREW_UPDATE_TO_TAG=1 brew update
HEAD is now at 75d230318 Merge pull request #2627 from MikeMcQuaid/audit-fix-option-detection
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
aalib                               freeimage                           gnu-typist                          ibex                                s3fs
```
```
$ git -C $(brew --repo) status && git -C $(brew --repo) rev-parse @
On branch stable
nothing to commit, working tree clean
8cba0352e0be94263e2ed96c98bf93d8f2fce8ef
```
```
$ brew --version
Homebrew 1.2.0
Homebrew/homebrew-core (git revision b71e8; last commit 2017-05-14)
```

**Comment by JCount** [comment]
@fspreiss Ok, you should be all set. 🎊

Feel free to reopen this if you end up still experiencing issues. 🙂
