### PR TITLE
ffmpeg@2.8 & ffmbc: drop faac

### PR DESCRIPTION
**Pull request by zmwangx**
I just took a look at #20317 myself. As expected, both won't build with faac 1.29.9, with the same error:

    libavcodec/libfaac.c:87:15: error: no member named 'allowMidside' in 'struct faacEncConfiguration'
        faac_cfg->allowMidside = 1;
        ~~~~~~~~  ^
    1 error generated.

FFmpeg has dropped faac support in 3.2 (a year ago), so I doubt this will be fixed in the 2.8 line — there won't be anything to backport.

FFmbc is so outdated I consider it stale or dead. After dropping faac, there's still the native AAC encoder:

```console
$ ffmbc -codecs | grep aac
FFmbc version 0.7.2
Copyright (c) 2008-2014 Baptiste Coudurier and the FFmpeg developers
 DEA    aac             Advanced Audio Coding
 D A    aac_latm        AAC LATM (Advanced Audio Codec LATM syntax)
```

which I believe was still experimental when FFmbc was last synced with FFmpeg upstream, so it probably doesn't perform as well as libfaac. I checked FFmbc's `configure` and unfortunately it doesn't seem to support libvo-aacenc or libfdk_aac. If you (one the two remaining FFmbc users) absolutely need faac, you need to urge FFmbc upstream to patch and release, or wisely use `brew switch` / `brew pin`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm not sure faac upstream intended to break their API so it would be good to confirm that with them before assuming it's the case.

**Comment by zmwangx** [comment]
Good point, https://github.com/knik0/faac/issues/9.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/20626 in 69eb8e07d642c6cb5cce46eb0e58aa3f9787d4e3.
