### ISSUE TITLE
APR doesn't compile on 11.0

### ISSUE THREAD

**Issue by jordanbonaldi** [Homebrew/homebrew-core#56818]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing PHP 7.4.7, with Apr and Apr-util as dependencies

## What happened (include command output)

```
==> make install
Last 15 lines from /Users/neferett/Library/Logs/Homebrew/apr/02.make:
In file included from encoding/apr_encode.c:28:
In file included from ./include/apr_encode.h:24:
./include/apr.h:561:2: error: Can not determine the proper size for pid_t
#error Can not determine the proper size for pid_t
 ^
In file included from encoding/apr_encode.c:30:
In file included from ./include/apr_strings.h:52:
./include/apr_want.h:94:8: error: redefinition of 'iovec'
struct iovec
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.16.sdk/usr/include/sys/_types/_iovec_t.h:31:8: note: previous definition is here
struct iovec {
       ^
2 errors generated.
make: *** [encoding/apr_encode.lo] Error 1
```

## What you expected to happen

Build succeeds

## Step-by-step reproduction instructions (by running `brew install` commands)

```brew install php```

**Comment by SMillerDev** [comment]
Please read the output of `brew doctor`. You're not allowed to file issues for pre-release software.

**Comment by namhokim** [comment]
Because macOS library has iovec structure, too.
But they are difference of ifndef guard name. So struct define will be duplicated.
<img width="938" alt="ScreenCapture 2020-11-13 12 31 48" src="https://user-images.githubusercontent.com/1442538/99026742-04810180-25af-11eb-995b-3503542805e5.png">

**Comment by iMichka** [comment]
We would accept a PR to fix this. Of course the patch needs to be submitted upstream (to APR) first.

**Comment by tawmoto** [comment]
It's a bug in APR: https://bz.apache.org/bugzilla/show_bug.cgi?id=64753
