### PR TITLE
swift 5.9.2

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by Bo98** [comment]
Will have more time to look into issues here unlike last time now that Ruby 3 is basically done.

**Comment by razvanazamfirei** [comment]
```2023-12-24T16:55:37.9717208Z [68/538] Compiling llbuildNinja ManifestLoader.cpp
2023-12-24T16:55:37.9717810Z /tmp/swift-20231224-11721-bkt1we/llbuild/lib/Core/SQLiteBuildDB.cpp:28:10: fatal error: 'sqlite3.h' file not found
2023-12-24T16:55:37.9717913Z #include <sqlite3.h>
2023-12-24T16:55:37.9717995Z          ^~~~~~~~~~~
2023-12-24T16:55:37.9718084Z 1 error generated.
2023-12-24T16:55:37.9718235Z [69/538] Compiling llbuildCore SQLiteBuildDB.cpp
2023-12-24T16:55:37.9718409Z [69/538] Compiling llbuildCore DependencyInfoParser.cpp
2023-12-24T16:55:37.9718578Z [69/538] Compiling llbuildCore MakefileDepsParser.cpp
2023-12-24T16:55:37.9718728Z [69/538] Compiling llvmDemangle ItaniumDemangle.cpp
2023-12-24T16:55:37.9728525Z env SWIFTCI_USE_LOCAL_DEPS=1 SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15 LD_LIBRARY_PATH=/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/lib:/tmp/swift-20231224-11721-bkt1we/build/llbuild-linux-x86_64/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/yams/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-argument-parser/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-crypto/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-driver/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-system/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-collections/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-asn1/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-certificates/lib:/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/lib/swift/linux SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/bin/swiftc SWIFT_DRIVER_SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/bin/swiftc CC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/bin/clang SWIFTPM_CUSTOM_LIBS_DIR=/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/pm /tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/bin/swift-bootstrap --build-path /tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64 --configuration release -Xswiftc -module-cache-path -Xswiftc /tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/module-cache -Xmanifest -module-cache-path -Xmanifest /tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/module-cache
2023-12-24T16:55:37.9738799Z --- bootstrap: error: Command '['env', 'SWIFTCI_USE_LOCAL_DEPS=1', 'SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15', 'LD_LIBRARY_PATH=/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/lib:/tmp/swift-20231224-11721-bkt1we/build/llbuild-linux-x86_64/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/yams/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-argument-parser/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-crypto/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-driver/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-system/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-collections/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-asn1/lib:/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-certificates/lib:/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/lib/swift/linux', 'SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/bin/swiftc', 'SWIFT_DRIVER_SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/bin/swiftc', 'CC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9.2/libexec/bin/clang', 'SWIFTPM_CUSTOM_LIBS_DIR=/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/pm', '/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/bin/swift-bootstrap', '--build-path', '/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64', '--configuration', 'release', '-Xswiftc', '-module-cache-path', '-Xswiftc', '/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/module-cache', '-Xmanifest', '-module-cache-path', '-Xmanifest', '/tmp/swift-20231224-11721-bkt1we/build/swiftpm-linux-x86_64/module-cache']' returned non-zero exit status 1.
2023-12-24T16:55:37.9738835Z 
```

**Comment by SMillerDev** [comment]
Reported the bug upstream, maybe they can give a hand.

**Comment by Bo98** [comment]
Yeah it seems like the llbuild SwiftPM build assumes SQLite3 is always available in system include land, which likely explains the horrible hacks like this OpenBSD block: https://github.com/apple/swift-llbuild/blob/bc3ffd54c2bfa8ce2214d1342860f07ae44922d1/Package.swift#L276-L287. Haven't had a chance to ask due to the holiday shutdown.

**Comment by finagolfin** [comment]
Do you use `pkg-config` on Homebrew to supply such header paths? SwiftPM recently added the `--pkg-config-path` flag to pass the paths to such `.pc` files for library dependencies like SQLite3, I use it to [cross-compile SwiftPM itself with the host SwiftPM from linux to Android](https://github.com/termux/termux-packages/blob/6f442f6476e8b56415212a5ac0a5f818fb0ad1f3/packages/swift/swiftpm-sqlite-dependency.patch). You can probably do the same for Homebrew if the pkg-config files are there.

**Comment by Bo98** [comment]
We already set the `PKG_CONFIG_PATH` env which I think should work with SwiftPM: https://github.com/apple/swift-package-manager/blob/8817ad5adcb541890cbf71535ba52494fd48efbd/Sources/PackageLoading/PkgConfig.swift#L36-L39

The problem is `llbuild` doesn't seem to use pkg-config at all from what I see: https://github.com/apple/swift-llbuild/blob/swift-5.9.2-RELEASE/Package.swift

**Comment by finagolfin** [comment]
> We already set the PKG_CONFIG_PATH env which I think should work

Yes, that has been around for awhile and still works.

> The problem is llbuild doesn't seem to use pkg-config at all

No, that's not the issue, as llbuild is only built as a dependency of SwiftPM, and [the systemLibrary dependency is listed there and should be applied to llbuild too](https://github.com/apple/swift-package-manager/blob/release/5.9/Package.swift#L184). In fact, I don't understand why this is failing for you now, as this dependency was moved over with 5.8 last year from TSC, apple/swift-package-manager@239f3178b.

Since nothing has changed after that on the Swift end, I'm guessing something changed on your end to break this. Try building Swift 5.8.1 with the latest version of Homebrew. If that works, build 5.9.2 and compare the verbose output of each: that should give you an idea of what's going wrong, as nothing appears to have changed with this dependency since Swift 5.8.

**Comment by Bo98** [comment]
It worked semi-recently but LLVM parts broke recently due it greedily finding 3.12 (which is fixed fully in 5.11). I look into trying the SPM part specifically however.

You're right though that it's historically always been broken, but did fix in 5.8. Interesting to know though that `systemLibrary` is supposed to apply to sibling dependencies and recursively up those trees.

**Comment by finagolfin** [comment]
> Interesting to know though that systemLibrary is supposed to apply to sibling dependencies and recursively backwards up those trees - I didn't realise that was a thing.

I believe it does, but I'm not sure.

> If it's working properly the OpenBSD workaround should be able to be removed so perhaps worth cleaning that up.

His problem is likely that he's not setting the `pkg-config-path` like we are: if he did, I bet he could remove that on OpenBSD.

**Comment by Bo98** [comment]
No matter what, it seems `pkg-config` is not respected. It might happen to work if the default sysroot of the compiler matched the install location, but Homebrew for Linux is a little different in that it would technically need two sysroots as it's not a system-level package manager.

For now, I've hacked the OpenBSD code to apply to us as it seems something is going weird for two completely different setups to require it. It might have worked in 5.8 by erroneously including a system-level sqlite3 header in the Docker image - we've had that happen before so wouldn't be surprising.

**Comment by SMillerDev** [comment]
We'll need to try this again later I guess.
```console
The self-hosted runner: 12-arm64-7978145460-2 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

**Comment by finagolfin** [comment]
> No matter what, it seems pkg-config is not respected.

I doubt that, since it worked with 5.8, though as you say we cannot account for spuriously installed headers. You can try running the failing SwiftPM command manually with the `--vv` flag, to make sure it is invoking `pkg-config` correctly.

**Comment by Bo98** [comment]
You can reproduce the same issue in the official Docker image. That makes me pretty confident it's not a Homebrew-specific problem:

```console
$ docker run --rm -it swift:5.9.2

**Comment by Bo98** [comment]
You can reproduce the same issue in the official Docker image. That makes me pretty confident it's not a Homebrew-specific problem:

```console
$ docker run --rm -it swift:5.9.2
# apt update
# apt install g++ make cmake curl
# cd /root
# curl -LO https://www.sqlite.org/2024/sqlite-autoconf-3450100.tar.gz
# tar xf sqlite-autoconf-3450100.tar.gz
# cd sqlite-autoconf-3450100
# ./configure --prefix=/opt/prefix
# make install
# cd ..
# export PKG_CONFIG_PATH=/opt/prefix/lib/pkgconfig
# pkg-config --cflags sqlite3
# git clone https://github.com/apple/swift-package-manager
# cd swift-package-manager
# git checkout swift-5.9.2-RELEASE
# swift build
/root/swift-package-manager/.build/checkouts/swift-llbuild/lib/Core/SQLiteBuildDB.cpp:28:10: fatal error: 'sqlite3.h' file not found
#include <sqlite3.h>
         ^~~~~~~~~~~
1 error generated.
```

`--vv` does not show and `pkg-config` line.

**Comment by finagolfin** [comment]
Oh, just thought of it and looked it up, maybe you need to [add Homebrew as a linux packager in SwiftPM](https://github.com/apple/swift-package-manager/blob/058574d8aa40dbc7d9208b44164d8cff622b9b72/Sources/PackageLoading/Target%2BPkgConfig.swift#L165)?

**Comment by Bo98** [comment]
That's a fair point that Homebrew for Linux should probably be added to that (though not entirely sure how to implement a combined Homebrew + system package manager setup given pkg-config only respects the first provider: https://github.com/apple/swift-package-manager/blob/058574d8aa40dbc7d9208b44164d8cff622b9b72/Sources/PackageLoading/Target%2BPkgConfig.swift#L76)

Though the result of that is always merged with `PKG_CONFIG_PATH`, so ultimately the result is the same for the `llbuild` case: https://github.com/apple/swift-package-manager/blob/98747d519cab0a5e0a1610ccf8d558cbd4099454/Sources/PackageLoading/PkgConfig.swift#L82

**Comment by finagolfin** [comment]
> --vv does not show any pkg-config line.

Stick a `swift package clean` in right before checking the verbose output, or at some point SwiftPM stops running `pkg-config` and just uses the cached build config. I had no problem seeing the `pkg-config` invocation on Fedora linux just now with the system Swift 5.8.1, except after a couple `swift build` invocations without cleaning in between.

> Though the result of that is always merged with PKG_CONFIG_PATH, so ultimately the result is the same to what we're already doing here for llbuild

Obviously not, as something is going wrong: you'll probably need to step through with a debugger or build a SwiftPM that prints some output to figure this out.

**Comment by Bo98** [comment]
> Stick a `swift package clean` in right before checking the verbose output, or at some point SwiftPM stops running `pkg-config` and just uses the cached build config. I had no problem seeing the `pkg-config` invocation on Fedora linux just now with the system Swift 5.8.1, except after a couple `swift build` invocations without cleaning in between.

I see

```
debug: pkg-config --variable pc_path pkg-config
```

but that's about it.

And just to confirm pkg-config works, I ran:

```swift
// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "libTest",
    targets: [
        .systemLibrary(name: "testsqlite3", pkgConfig: "sqlite3"),
        .target(name: "libTest", dependencies: ["testsqlite3"]),
    ]
)
```

And it works fine (note the `-I/opt/prefix/include`):

```console
debug: pkg-config --variable pc_path pkg-config
Building for debugging...
/usr/bin/clang -target aarch64-unknown-linux-gnu -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -fmodules -fmodule-name=libTest -I /tmp/swifttest/Sources/libTest/include -fmodule-map-file=/tmp/swifttest/Sources/testsqlite3/module.modulemap -I/opt/prefix/include -fmodules-cache-path=/tmp/swifttest/.build/aarch64-unknown-linux-gnu/debug/ModuleCache -fPIC -fno-omit-frame-pointer -MD -MT dependencies -MF /tmp/swifttest/.build/aarch64-unknown-linux-gnu/debug/libTest.build/main.c.d -c /tmp/swifttest/Sources/libTest/main.c -o /tmp/swifttest/.build/aarch64-unknown-linux-gnu/debug/libTest.build/main.c.o
```

It _only_ doesn't work with llbuild's system that doesn't use `.systemLibrary`.

**Comment by finagolfin** [comment]
OK, so `pkg-config` is run and the pkg-config-path is being set fine for you then, and we go back to the original issue of whether SwiftPM's dependency on SQLite should be applied to llbuild also. I figured it was, since it cross-compiles fine for me, but as I said a couple weeks ago, I wasn't sure.

We'll need to dig into that next.

**Comment by Bo98** [comment]
Something to compare between us would be this verbose output:

```
/usr/bin/clang -target aarch64-unknown-linux-gnu -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -fmodules -fmodule-name=llbuildCore -I /root/swift-package-manager/.build/checkouts/swift-llbuild/lib/Core/include -I /root/swift-package-manager/.build/checkouts/swift-llbuild/lib/Basic/include -fmodule-map-file=/root/swift-package-manager/.build/aarch64-unknown-linux-gnu/debug/llbuildBasic.build/module.modulemap -I /root/swift-package-manager/.build/checkouts/swift-llbuild/lib/llvm/Support/include -fmodule-map-file=/root/swift-package-manager/.build/aarch64-unknown-linux-gnu/debug/llvmSupport.build/module.modulemap -I /root/swift-package-manager/.build/checkouts/swift-llbuild/lib/llvm/Demangle/include -fmodule-map-file=/root/swift-package-manager/.build/aarch64-unknown-linux-gnu/debug/llvmDemangle.build/module.modulemap -fmodules-cache-path=/root/swift-package-manager/.build/aarch64-unknown-linux-gnu/debug/ModuleCache -fPIC -fno-omit-frame-pointer -MD -MT dependencies -MF /root/swift-package-manager/.build/aarch64-unknown-linux-gnu/debug/llbuildCore.build/SQLiteBuildDB.cpp.d -std=c++14 -c /root/swift-package-manager/.build/checkouts/swift-llbuild/lib/Core/SQLiteBuildDB.cpp -o /root/swift-package-manager/.build/aarch64-unknown-linux-gnu/debug/llbuildCore.build/SQLiteBuildDB.cpp.o
```

Note that it's missing `-I/opt/prefix/include`.

**Review by p-linnane — APPROVED** [review]

**Comment by finagolfin** [comment]
> Where does your pkg-config --cflags sqlite3 point to and do you see those flags passed to the compiler?

I'll schedule a build tomorrow and check. It's possible that since the Termux build also sets `CFLAGS`, the llbuild dependency is fulfilled by that, while `--pkg-config-path` only applies to the SwiftPM dependency on SQLite. I will run a verbose build and let you know why it worked for me.

**Comment by finagolfin** [comment]
Alright, ran a verbose build that removed the `--pkg-config-path` flags, finagolfin/termux-packages@32fc996ec. It shows [`pkg-config` invoked](https://github.com/finagolfin/termux-packages/actions/runs/7994311244/job/21832063259#step:8:9916), [`SQLiteBuildDB.cpp.o` still building fine](https://github.com/finagolfin/termux-packages/actions/runs/7994311244/job/21832063259#step:8:10100) (implying it's getting that include directory from `CFLAGS` or elsewhere, not from `pkg-config`), and [the final link fails because it's missing the path to the cross-compiled SQLite library](https://github.com/finagolfin/termux-packages/actions/runs/7994311244/job/21832063259#step:8:11113), which `pkg-config` _did_ supply before I disabled it for this run.

It appears you are right that llbuild will require making its SQLite dependency explicit, and your previous 5.8 Homebrew build and my Termux builds happened to work for other reasons.

**Comment by Bo98** [comment]
Thanks for checking that. Indeed, final link seems to work as expected.

I think we can consider this being reported as https://github.com/apple/swift-llbuild/issues/901
