### PR TITLE
shogun: depend on openblas and do not build bindings 

### PR DESCRIPTION
**Pull request by jamiesnape**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Relates #39620.

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
It's still dying with:

```
/tmp/shogun-20190513-77368-1nxrg6s/shogun-6.1.3/build/src/interfaces/python/shogunPYTHON_wrap.cxx:640812:5: error: cannot initialize a member subobject of type 'ssizeargfunc' (aka '_object *(*)(_object *, long)') with an lvalue of type 'PyObject *(PyObject *, Py_ssize_t, bool)' (aka '_object *(_object *, long, bool)'): different number of parameters (2 vs 3)
    BoolVector_getitem,                       /* sq_item */
    ^~~~~~~~~~~~~~~~~~
```

**Comment by jamiesnape** [comment]
Another SWIG 4.0 problem, I think. I built using SWIG 3.0.12 with no errors. Since last stable version of shogun was so long ago, getting it to work with SWIG 4.0 may not be easy. I could put together a `swig@3` formula to use, if that would help?

**Comment by jamiesnape** [comment]
(There is a `swig@3.04` formula that appears to unused and maybe could be removed, if having too many versioned formulae is an issue.)

**Comment by fxcoudert** [comment]
Can we build shogun without bindings? If so, we should do it.

**Comment by jamiesnape** [comment]
Done.

**Comment by jamiesnape** [comment]
@fxcoudert Done. PTAL.

**Comment by zbeekman** [comment]
@jamiesnape, sorry to pile on here, but is it possible to drop the lapack dependency and place a dependency on OpenBLAS instead, which ships a LAPACK interface?

I wanted to do this in #39809 (See also #39226) but, TBH, the complexity of the shogun formula, and my lack of experience with shogun itself deterred me from attempting this.

AFAICT, there is no good reason to link to lapack when we can link against OpenBLAS like all the other dependencies and formulae that require BLAS/LAPACK support.

**Comment by jamiesnape** [comment]
@zbeekman Sure. I will look into it.

File: Formula/shogun.rb [hunk 1]
```diff
@@ -23,29 +15,10 @@ class Shogun < Formula
   depends_on "lapack" if MacOS.version >= :high_sierra
```
Comment (zbeekman) [inline Formula/shogun.rb]:
```suggestion
```

File: Formula/shogun.rb [hunk 2]
```diff
@@ -23,29 +15,10 @@ class Shogun < Formula
...
   depends_on "lzo"
   depends_on "nlopt"
```
Comment (zbeekman) [inline Formula/shogun.rb]:
```suggestion
  depends_on "nlopt"
  depends_on "openblas"
```

File: Formula/shogun.rb [hunk 3]
```diff
@@ -65,79 +38,68 @@ class Shogun < Formula
...
     end
 
-    libexec.install resource("jblas")
-
-    python_executable = Formula["python@2"].opt_bin/"python2"
-    python_prefix = Utils.popen_read("#{python_executable} -c 'import sys; print(sys.prefix)'").chomp
-    python_include = Utils.popen_read("#{python_executable} -c 'from distutils import sysconfig; print(sysconfig.get_python_inc(True))'").chomp
-    python_library = "#{python_prefix}/Python"
+    args = std_cmake_args + %w[
+      -DBUILD_EXAMPLES=OFF
```
Comment (zbeekman) [inline Formula/shogun.rb]:
```suggestion
      -DBLA_VENDOR=OpenBLAS
      -DBUILD_EXAMPLES=OFF
```

**Review by zbeekman — CHANGES_REQUESTED** [review]
@jamiesnape I think these are the changes that are needed in order to us OpenBLAS over accelerate.

File: Formula/shogun.rb (hunk 2 above)
Comment (zbeekman) [reply Formula/shogun.rb]: I did not intend to muck up the indentation, please double check.

File: Formula/shogun.rb (hunk 3 above)
Comment (zbeekman) [reply Formula/shogun.rb]: There is an audit that will check packages for linkage against Apple's Accelerate now, so without this change you may trigger an audit warning depending on which version of Homebrew/brew is deployed on our CI infra right now. And if no audit issue is raised now, one should be in the future.

From https://github.com/shogun-toolbox/shogun/issues/4629#issue-442781594
```
-- Found BLAS: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework  
-- Found Accelerate.framework using as BLAS/LAPACK backend.
-- Enabling Accelerate.framework as BLAS backend for Eigen.
```

Eigen should now be using OpenBLAS as a backend, but since it's a header only lib it just links against whatever implementation the build system provides, if I understand correctly.

**Comment by jamiesnape** [comment]
@zbeekman Looks to have worked.

**Review by zbeekman — APPROVED** [review]
LGTM!

**Comment by zbeekman** [comment]
We'll just have to wait for the gettext update to get through and this to run through CI before we can merge.

**Comment by zbeekman** [comment]
@BrewTestBot test this please

File: Formula/shogun.rb [hunk 4]
```diff
@@ -3,49 +3,22 @@ class Shogun < Formula
   homepage "http://www.shogun-toolbox.org/"
   url "http://shogun-toolbox.org/archives/shogun/releases/6.1/sources/shogun-6.1.3.tar.bz2"
   sha256 "57169dc8c05b216771c567b2ee2988f14488dd13f7d191ebc9d0703bead4c9e6"
-  revision 3
-
-  bottle do
-    sha256 "7f46d34b9fb84e45da8010cd796d28860a16dfa8ec3b4e3bae234cf5c9f3db4e" => :mojave
-    sha256 "e432dbe32889e4dc9bc2501a61934fe6f1ed5c13b613d79cb22c34a1d8543e99" => :high_sierra
-    sha256 "f9c0b2fdec633139f4187c3acf571a9e56ef627d417ff385583bc1c214d64647" => :sierra
-  end
```
Comment (zbeekman) [inline Formula/shogun.rb]: For future reference, please do not delete the `bottle do` block, this gets updated automatically.
