### PR TITLE
envoy: build with system GCC on Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Experimenting with some changes

### CODE REVIEW

File: Formula/envoy.rb [hunk 1]
```diff
@@ -65,11 +61,7 @@ def install
       --host_action_env=PATH=#{env_path}
     ]
 
-    if OS.linux?
-      # Disable extension `tcp_stats` which requires Linux headers >= 4.6
-      # It's a directive with absolute path `#include </usr/include/linux/tcp.h>`
-      args << "--//source/extensions/transport_sockets/tcp_stats:enabled=false"
```
Comment (cho-m) [inline Formula/envoy.rb:71]: Should have sufficient Linux headers in Ubuntu 22. Absolute path was fixed in Envoy 1.22.0 (https://github.com/envoyproxy/envoy/commit/cac6264861c009f94f4c897c5210b84e9d614626) so source build should hopefully work with Homebrew `linux-headers@5.15` on older Linux that installs Homebrew `glibc`

File: Formula/envoy.rb [hunk 2]
```diff
@@ -24,39 +24,35 @@ class Envoy < Formula
...
   end
 
   # https://github.com/envoyproxy/envoy/tree/main/bazel#supported-compiler-versions
   fails_with :gcc do
     version "8"
     cause "C++17 support and tcmalloc requirement"
   end
-  # GCC 10 build fails at external/com_google_absl/absl/container/internal/inlined_vector.h:448:5:
-  # error: '<anonymous>.absl::inlined_vector_internal::Storage<char, 128, std::allocator<char> >::data_'
-  # is used uninitialized in this function [-Werror=uninitialized]
```
Comment (cho-m) [inline Formula/envoy.rb:47]: Looks like GCC 10 issue still exists:
```
external/com_google_absl/absl/container/internal/inlined_vector.h:447:5: error: '<unnamed>.absl::InlinedVector<char, 128, std::allocator<char> >::storage_.absl::inlined_vector_internal::Storage<char, 128, std::allocator<char> >::data_' is used uninitialized [-Werror=uninitialized]
    447 |     data_ = other_storage.data_;
        |     ^~~~~
```

May see if there is a commit for newer abseil or try passing in `-Wno-uninitialized`

**Review by chenrui333 — APPROVED** [review]
