### PR TITLE
emscripten: fix Linux test when `sdl12-compat` is installed

### PR DESCRIPTION
**Pull request by cho-m**
Example failure seen in PR #113581:
```
cache:INFO: generating system asset: sysroot/lib/wasm32-emscripten/struct_info.json... (this will be cached in "/home/linuxbrew/.linuxbrew/Cellar/emscripten/3.1.26/libexec/cache/sysroot/lib/wasm32-emscripten/struct_info.json" for subsequent builds)
  In file included from /tmp/tmp0h2vr3jt.c:24:
  In file included from /home/linuxbrew/.linuxbrew/include/SDL/SDL_keyboard.h:32:
  /home/linuxbrew/.linuxbrew/include/SDL/SDL_keysym.h:252:5: error: redefinition of enumerator 'SDLK_LGUI'
      SDLK_LSUPER = 311,
      ^
  /home/linuxbrew/.linuxbrew/Cellar/emscripten/3.1.26/libexec/cache/sysroot/include/SDL/SDL_compat.h:266:21: note: expanded from macro 'SDLK_LSUPER'
  #define SDLK_LSUPER SDLK_LMETA
                      ^
```

---

Trying to repro Linux failure first and then try deleting CPATH next.

### CODE REVIEW

File: Formula/emscripten.rb [hunk 1]
```diff
@@ -31,6 +31,9 @@ class Emscripten < Formula
   depends_on "cmake" => :build
   depends_on "node"
   depends_on "python@3.11"
+  # FIXME: fake dependency to try to repro Linux failure
+  # /home/linuxbrew/.linuxbrew/include/SDL/SDL_keysym.h:252:5: error: redefinition of enumerator 'SDLK_LGUI'
+  depends_on "sdl12-compat"
```
Comment (cho-m) [inline Formula/emscripten.rb:36]: Reproduced with this, so going to try out some fixes.

File: Formula/emscripten.rb [hunk 2]
```diff
@@ -206,6 +209,8 @@ def caveats
   test do
     # We're targetting WASM, so we don't want to use the macOS SDK here.
     ENV.remove_macosxsdk if OS.mac?
+    # Avoid errors on Linux when other formulae like `sdl12-compat` are installed
+    ENV.delete "CPATH"
```
Comment (cho-m) [inline Formula/emscripten.rb:213]: Looks like this worked: https://github.com/Homebrew/homebrew-core/actions/runs/3596817081/jobs/6057988229#step:7:38

This is a no-op on macOS as `ENV.remove_macosxsdk` already deleted `CPATH`. Could put in `if ... else ...` but didn't seem necessary.

**Review by carlocab — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]
