### ISSUE TITLE
vim fails to build on 10.11.6

### ISSUE THREAD

**Issue by jiqiren** [Homebrew/homebrew-core#4838]
### Bug reports:

https://gist.github.com/d5504de8e783399c7fba765923896761

above is from this:
`brew gist-logs vim`

I just updated to xcode8, so probably related.

**Comment by tdsmith** [comment]
This one looks novel!

```
In file included from if_ruby.c:120:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^
1 error generated.
make[1]: *** [objects/if_ruby.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

Does `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/config.h` exist?

**Comment by jiqiren** [comment]
Nope! But it is in another path...

```
$ pwd
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0
Bryans-MacBook-Air:2.0 jiqiren$ find . -name config.h
./Headers/ruby/config.h
./usr/include/ruby-2.0.0/universal-darwin16/ruby/config.h
```

**Comment by mistydemeo** [comment]
This is an issue with Xcode 8 only shipping the 10.12 SDK. The Ruby headers are in an OS-specific path, and the recommended solution of using the 10.12 SDK to build on 10.11 doesn't work with it.

Unfortunately, to build vim you're going to need to install the CLT.

**Comment by jiqiren** [comment]
😞indeed, that fixes the issue! After xcode-select --install all is well.
