### PR TITLE
mavsdk 0.38.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
This is actually good now. The CI failure is
```
==> FAILED
Error: No available formula or cask with the name "autoconf".
```
Cf. https://github.com/Homebrew/brew/pull/10925

**Comment by bayandin** [comment]
> This is actually good now.

I'm not sure. Catalina for example fails because of:
```
/tmp/mavsdk-20210325-1418-1sgyr7x/src/core/tcp_connection.cpp:164:18: error: use of undeclared identifier 'MSG_NOSIGNAL'
    auto flags = MSG_NOSIGNAL;
                 ^
1 error generated.
```

**Comment by carlocab** [comment]
Whoops; I was pretty sure I looked at all of them 😅

**Comment by Bo98** [comment]
This is an upstream bug caused by https://github.com/mavlink/MAVSDK/commit/5d2424c8f2e24a1dd6bf8683461b46e25687716c. Making it check `#if defined(MSG_NOSIGNAL)` instead should fix the build.

**Comment by carlocab** [comment]
Not sure why they're not doing that in the first place...

**Comment by carlocab** [comment]
Patch fixed the Catalina build, but not Mojave:

```
error: 'path' is unavailable: introduced in macOS 10.15
```

**Comment by Bo98** [comment]
Requires a newer libc++ than the one shipped with Mojave, so that'll need to be `depends_on macos: :catalina`.

**Comment by carlocab** [comment]
I think we can try using the Xcode SDK here, actually. Let me give that a try first. If it doesn't work, I'll add the Catalina dependency.

**Comment by carlocab** [comment]
Nope, no luck with Xcode. `depends_on macos: :catalina` it is then.

**Review by carlocab — APPROVED** [review]
