### PR TITLE
python@3.8: apply upstream patch temporarily for macOS ≥10.16

### LINKED ISSUE #56791: Python 3.8 doesn't build on 11.0
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`python@3.8` was in the dependency tree of software I was installing, but failed to build from source on Big Sur.

## What happened (include command output)

Installation fails; logs here: https://gist.github.com/mistydemeo/658ea7401c00b2b8dccee9f067ac2c0e

Specifically, the error is here:

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.16.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.16.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.16.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration  -I./Include/internal  -I. -I./Include    -DPy_BUILD_CORE_BUILTIN  -DPy_BUILD_CORE_BUILTIN -I./Include/internal -c ./Modules/posixmodule.c -o Modules/posixmodule.o
./Modules/posixmodule.c:9141:20: error: variable has incomplete type 'struct sf_hdtr'
    struct sf_hdtr sf;
                   ^
./Modules/posixmodule.c:9141:12: note: forward declaration of 'struct sf_hdtr'
    struct sf_hdtr sf;
           ^
1 error generated.
```

This happened on macOS 11.0 beta 1 for Intel using the CLT.

## What you expected to happen

Build succeeds.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install python@3.8`

### PR DESCRIPTION
**Pull request by claui**
As [suggested](https://github.com/Homebrew/homebrew-core/issues/56791#issuecomment-649619460), applying the upstream patch for now, as the next minor release isn’t to be expected until mid-July.

The patch is to be removed from the formula once 3.8.4 is released.

Closes #56791.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by claui** [comment]
The 11.0 attribution was actually misleading: the root cause of the issue is the number `20` in Darwin 20.

So this PR actually fixes **both** macOS 10.16 and 11.0.

**Review by mistydemeo — APPROVED** [review]
👍 Thanks for this!
