### PR TITLE
asciidoc 8.6.10

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

This is [the final release](https://github.com/asciidoc/asciidoc/releases/tag/8.6.10) of asciidoc, which will die with Python 2 EOL. Users are encouraged to switch to Asciidoctor and Co.

### CODE REVIEW

**Comment by ilovezfs** [comment]
odd it's not posted to sourceforge or http://asciidoc.org/

do we need to update the homepage too?

**Comment by zmwangx** [comment]
> odd it's not posted to sourceforge or http://asciidoc.org/

Yeah, I guess they stopped to care?

You know what, I was just looking for something to test https://github.com/Homebrew/brew/pull/3416, that's all...

> do we need to update the homepage too?

To what?

**Comment by ilovezfs** [comment]
>To what?

I guess https://github.com/asciidoc/asciidoc

**Comment by zmwangx** [comment]
https://github.com/asciidoc/asciidoc also refers to http://asciidoc.org/ as the homepage.

**Comment by ilovezfs** [comment]
Yeah I see that. If we're leaving it the same, an upstream issue barking about it not being on the homepage or sourceforge would be nice.

**Comment by zmwangx** [comment]
Oh sure.

**Comment by ilovezfs** [comment]
thanks :)

**Comment by zmwangx** [comment]
I keep hitting this weird 127 return status when installing with brew:

```
a2x: ERROR: "/private/tmp/asciidoc-20171103-21900-1l60lw7/asciidoc-8.6.10/asciidoc.py" --backend docbook -a "a2x-format=manpage"  --doctype manpage  --out-file "/private/tmp/asciidoc-20171103-21900-1l60lw7/asciidoc-8.6.10/doc/a2x.1.xml" "/private/tmp/asciidoc-20171103-21900-1l60lw7/asciidoc-8.6.10/doc/a2x.1.txt" returned non-zero exit status 127
```

How can this fixed path not exist? Bot, see if you can reproduce...

**Comment by ilovezfs** [comment]
the shebang changed to python2

**Comment by zmwangx** [comment]
Oh yeah...

**Comment by zmwangx** [comment]
Note to self: use `HOMEBREW_ENV_FILTERING` with debrew.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
It looks like it actually has a hard build-time dependency on docbook-xsl unless you have network access and nothing flakes out. apjanke found in https://github.com/Homebrew/homebrew-core/pull/19468#issuecomment-337385123 that the docbook-xsl option is basically useless and just a shorthand for bringing the extra dependency along for the ride. So we should probably change
```
  depends_on "docbook-xsl" => :optional
```
to
```
  depends_on "docbook-xsl" => :build
```
and remove the option, and add `ENV["XML_CATALOG_FILES"] = etc/"xml/catalog"` to the top of the install method.

**Comment by zmwangx** [comment]
That probably makes sense, but does not seem to explain the CI build failures on 10.11 and 10.13 (and not 10.12).

**Comment by ilovezfs** [comment]
My current theory is it's random.

**Comment by zmwangx** [comment]
```
a2x: executing: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/private/tmp/asciidoc-20171103-52068-9e122z/asciidoc-8.6.10/docbook-xsl/manpage.xsl" "/private/tmp/asciidoc-20171103-52068-9e122z/asciidoc-8.6.10/doc/asciidoc.1.xml"

http://docbook.sourceforge.net/release/xsl/current/manpages/html-synop.xsl:1: parser error : Document is empty

^
compilation error: file http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl line 12 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/html-synop.xsl
http://docbook.sourceforge.net/release/xsl/current/manpages/lists.xsl:1: parser error : Document is empty

^
compilation error: file http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl line 38 element include
xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/lists.xsl
http://docbook.sourceforge.net/release/xsl/current/manpages/endnotes.xsl:1: parser error : Document is empty

^
compilation error: file http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl line 39 element include
xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/endnotes.xsl

a2x: chdir /private/tmp/asciidoc-20171103-52068-9e122z/asciidoc-8.6.10
make: *** [doc/asciidoc.1] Error 1
```

Okay you do need docbook-xsl. Then why the hell does it work on 10.12?

**Comment by ilovezfs** [comment]
It's got to be a network issue, I think. Because if you don't have docbook-xsl, and don't set `ENV["XML_CATALOG_FILES"] = etc/"xml/catalog"` it just pulls the info off of SourceForge or wherever.

**Comment by zmwangx** [comment]
The 10.12 VM should get a Flawless Networking Award.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
>You know what, I was just looking for something to test Homebrew/brew#3416, that's all...

lol. Well at least something good came of it :)

**Comment by zmwangx** [comment]
Any idea on how to deal with the `--with-docbook-xsl` option?

**Comment by ilovezfs** [comment]
We should just remove it. Anything that was previously doing
```
depends_on "asciidoc" => "with-docbook-xsl"
```
should just be doing
```
depends_on "asciidoc"
depends_on "docbook-xsl"
```
The option never should have been there.

File: Formula/asciidoc.rb [hunk 1]
```diff
@@ -14,20 +15,20 @@ class Asciidoc < Formula
...
-  head do
-    url "https://github.com/asciidoc/asciidoc.git"
-    depends_on "autoconf" => :build
-  end
-
   option "with-docbook-xsl", "Install DTDs to generate manpages"
 
+  depends_on "autoconf" => :build
+  depends_on "docbook-xsl" => :build
+
```
Comment (ilovezfs) [inline Formula/asciidoc.rb]: no blank line between dependency types :)

**Comment by zmwangx** [comment]
Sounds good.

> Anything that was previously doing `depends_on "asciidoc" => "with-docbook-xsl"`

IIRC several formulae were doing that, but I grepped just now and I couldn't find any.

**Comment by ilovezfs** [comment]
>IIRC several formulae were doing that, but I grepped just now and I couldn't find any.

You do recall correctly. https://github.com/Homebrew/homebrew-core/issues/13133 continues to work its magic.

File: Formula/asciidoc.rb [hunk 2]
```diff
@@ -14,20 +15,19 @@ class Asciidoc < Formula
     sha256 "fe63d108847b9b197ee4f853b52faa8eb6d5c3990cc9919567d799f1b3dbd674" => :mavericks
   end
 
-  head do
-    url "https://github.com/asciidoc/asciidoc.git"
-    depends_on "autoconf" => :build
-  end
-
   option "with-docbook-xsl", "Install DTDs to generate manpages"
```
Comment (ilovezfs) [inline Formula/asciidoc.rb]: this line should be deleted

**Comment by zmwangx** [comment]
> #13133

Good stuff, at least revdeps are now out of the scope of this PR.

**Comment by ilovezfs** [comment]
:capital_abcd: :man_health_worker:

**Comment by ilovezfs** [comment]
hurray for reproducible builds
```
   bottle do
     cellar :any_skip_relocation
-    sha256 "8210eb22d33a041cdeaa78b5a2e922e0c45b3140f68fad4e77e891df47973282" => :high_sierra
-    sha256 "0f6e983fd2e62ddc4c13e0028e76f2e206a83f9a7371f4158c0c7997ab14634c" => :sierra
-    sha256 "2e2ab0cd2462155296a05f8982b4d0c69b48db53ab26e49483c3fc116d955b67" => :el_capitan
-    sha256 "e460dd7a372d465bdb2e932c02fb1339e96b7e28f47c8f750ae0546e56e517f9" => :yosemite
-    sha256 "fe63d108847b9b197ee4f853b52faa8eb6d5c3990cc9919567d799f1b3dbd674" => :mavericks
+    sha256 "8e0a8af28d0f338a1850fa10a272cf76a8cefa7ac465a2faa2c1e9786b906939" => :high_sierra
+    sha256 "8e0a8af28d0f338a1850fa10a272cf76a8cefa7ac465a2faa2c1e9786b906939" => :sierra
+    sha256 "8e0a8af28d0f338a1850fa10a272cf76a8cefa7ac465a2faa2c1e9786b906939" => :el_capitan
   end
```
