### ISSUE TITLE
brew install gcc 6.1.0 fails becaus of jit-playback.c

### ISSUE THREAD

**Issue by duansai** [Homebrew/homebrew-core#1872]
### Bug reports:

In  jit-playback.c line 2474, the "ADD_ARG ("-Wl,-undefined,dynamic_lookup");" is added after the line:
"end add_arg".

Thus, I get the failure message of:

../../gcc/jit/jit-playback.c: In member function 'void gcc::jit::playback::context::invoke_external_driver(const char*, vec<char*>*)':
../../gcc/jit/jit-playback.c:2474:43: error: 'ADD_ARG' was not declared in this scope
   ADD_ARG ("-Wl,-undefined,dynamic_lookup");

attached please find the log file for building gcc (gcc.txt).
[gcc.txt](https://github.com/Homebrew/homebrew-core/files/309273/gcc.txt)

**Comment by UniqMartin** [comment]
Sorry, but you have not followed the requested steps in our [Troubleshooting Guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting). Please follow (all of) these steps and post the information here so we can help you with your problem. Thanks!

**Comment by ttilley** [comment]
gcc 6.1.10 fails to compile on 10.11

The homebrew package patches `jit-playback.c` to add exactly the line where the build fails: `ADD_ARG ("-Wl,-undefined,dynamic_lookup");'.
The patch is applied with a bit of fuzz: `Hunk #1 succeeded at 2465 with fuzz 2 (offset 49 lines)`.
Just 45 lines above the added `ADD_ARG` is `#undef ADD_ARG`.

So the patch no longer applies cleanly to this version of gcc. A build log gist isn't going to be half as clear as the above.

**Comment by ttilley** [comment]
I did indeed build gcc with `--with-jit` but this was more out of a habit to go nuts and enable ALL THE THINGS. ;)

This patch looks like it was actually accepted upstream in the gcc-5 branch, so it would be part of gcc 6.x. Looking at the `jit-playback.c` file there is an identical block about 55 or so lines above where the patch applies (and before the undef). Not being a gcc dev I can't say anything with complete confidence but it doesn't appear that at least the _second_ part of this patch (the one that patches `jit-playback.c`) is necessary.

**Comment by duansai** [comment]
After removing the patch in jit-playback.c and keeping the modifications in /gcc/jit/Make-lang.in, the installation of gcc 6.10 is successful. Thanks!

**Comment by RandomDSdevel** [comment]
Any progress on fixing this in GCC's formula for all users?  I may be having a similar issue myself.

**Comment by UniqMartin** [comment]
Thanks everyone for the input! Is any of you actually using the JIT functionality and can provide test code or suggestions to check that the JIT functionality will work as intended after adjusting the patch? I realize that adjusting the patch as suggested will fix the build error, but it would be nice to have a way to verify things beyond making sure the GCC build completes without error.

I would be even more grateful if anyone could run those checks themselves against GCC 5.3, fix the formula for 6.1, check with that version again, and then submit a pull request with the fix. Thanks!

@zbeekman Do you happen to have experience with GCC's JIT functionality and can advise on the issue that has been raised here?

**Comment by zbeekman** [comment]
@UniqMartin sorry, no experience with GCC's JIT... I'll do some very quick research now, but I make no promises...

**Comment by zbeekman** [comment]
Perhaps @davidmalcolm can comment, since he's the GCC JIT maintainer... or we could try to email the GCC JIT list: jit@gcc.gnu.org

**Comment by UniqMartin** [comment]
@zbeekman Thanks! This was really just a blind guess you might be familiar with this. Let's see if any of the mentioned or already involved people have any comments or can research this further. If not, I'll try to do my own research and/or contact the mailing list. (Might take some time, as I'm not affected myself.)

**Comment by davidmalcolm** [comment]
Yes, I'm the upstream gccjit maintainer.

I'm guessing the issue is to do with the patch you're applying downstream here:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb#L254

I believe I upstreamed that patch in this commit:
  https://github.com/gcc-mirror/gcc/commit/2d511d1ee03298d7a3bf8718eac823291a4c955d
and that it's in gcc 6.1 (and trunk), and in this backport to the gcc-5-branch:
  https://github.com/gcc-mirror/gcc/commit/2f88614ac80efbf606d2d9f4238bf6e9e096a16b

So the patch in your gcc.rb file should no longer be necessary.

Hope this is helpful

FWIW, I don't have an OS X box to hand, so I'm interested in hearing reports from people trying libgccjit on OS X.

**Comment by davidmalcolm** [comment]
Oops; I meant to say that the changes to jit-playback.c are upstream, and that that part of the patch should be dropped.

The changes to Make-lang.in here:
  https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb#L242
*are* still necessary, please keep that part.

**Comment by UniqMartin** [comment]
@davidmalcolm Thanks a lot for your input and for the confirmation on what can be dropped and what needs to be retained! ❤️ I'll fix our `gcc` formula in a minute.

**Comment by UniqMartin** [comment]
Pushed a fix to the formula in 891f9fdbdb8b82d1b006f8b98e87bfb05219a3f7. Everyone affected: Please `brew update` and try again.

**Comment by zbeekman** [comment]
FYI this [appears to be fixed on GCC trunk](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64089#c17) (`--HEAD`) and it looks like [it *may* be backported](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64089#c19) to other branches.

Expect a PR to skip applying it to `--HEAD` builds
