### PR TITLE
pgxnclient 1.3.1 (new formula)

### PR DESCRIPTION
**Pull request by ankane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Extension manager for Postgres

Notes
- For testing, all commands besides `--help` and `--version` require an internet connection
- The project has an [Ubuntu package](https://packages.ubuntu.com/focal/pgxnclient)

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

File: Formula/pgxnclient.rb [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+  url "https://github.com/pgxn/pgxnclient/archive/refs/tags/v1.3.1.tar.gz"
+  sha256 "5d711010b53f257c35e8cb2fe8f954567c736d9af528e0da32227fdcaefe4350"
+  license "BSD-3-Clause"
+
+  depends_on "python@3.9"
+
+  resource "six" do
+    url "https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz"
+    sha256 "30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259"
+  end
```
Comment (carlocab) [inline Formula/pgxnclient.rb:15]:
```suggestion
  depends_on "six"
```
There's a `six` formula this can use.

Comment (ankane) [reply Formula/pgxnclient.rb:15]: I originally did this, but `depends_on "six"` is in 1 formula, while `resource "six"` is in 159, so switched it for consistency.

Comment (carlocab) [reply Formula/pgxnclient.rb:15]: `six` is a newish formula, so we haven't gotten around to switching them yet. But they really should be switched at some point.

**Comment by ankane** [comment]
Looks like an internal error with Homebrew:

```txt
==> Determining pgxnclient bottle rebuild...
Error: undefined method `positive?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:291:in `extname'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:272:in `to_s'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:346:in `bottle_formula'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:100:in `block in bottle'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:99:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:99:in `bottle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by carlocab** [comment]
Oops. @Bo98, do you know about this?

**Comment by carlocab** [comment]
I think this happens only to new formulae, and probably caused by https://github.com/Homebrew/brew/pull/11293.

**Comment by Rylan12** [comment]
This should be good to rerun CI now that the brew PR has been merged. I'm on my phone so I can't do it right now.

**Review by carlocab — APPROVED** [review]
Thanks again, @ankane, and apologies for the delay here.

**Comment by ankane** [comment]
Thanks everyone!
