### PR TITLE
docker-machine-driver-xhyve: update to opam 2.x

### LINKED ISSUE #31740: docker-machine-driver-xhyve fails to build on macOS 10.14 Mojave
See #28817. Error is:

```
==> opam config exec -- make lib9p
vendor/lib9p/request.c:28:10: vendor/lib9p/pack.c:32:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
vendor/lib9p/connection.c:28:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
vendor/lib9p/log.c:28:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [vendor/build/lib9p/log.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
1 error generated.
make: *** [vendor/build/lib9p/connection.o] Error 1
make: *** [vendor/build/lib9p/request.o] Error 1
make: *** [vendor/build/lib9p/pack.o] Error 1
```

### PR DESCRIPTION
**Pull request by infrequentcoder**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Updates docker-machine-driver-xhyve to compile with opam 2.x on macOS Mojave by disabling sandboxing. Fixes #31740.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Build fails:

```
==> opam switch create 4.05.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ocaml-base-compiler.4.05.0] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/usr/local/Homebrew/Library/Homebrew/shims/mac/super/make world".

#=== ERROR while compiling ocaml-base-compiler.4.05.0 =========================#
# context              2.0.0 | macos/x86_64 |  | https://opam.ocaml.org#a5581236
# path                 ~/.opam/4.05.0/.opam-switch/build/ocaml-base-compiler.4.05.0
# command              /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make world
# exit-code            2
# env-file             ~/.opam/log/ocaml-base-compiler-78416-a71bb4.env
# output-file          ~/.opam/log/ocaml-base-compiler-78416-a71bb4.out
### output ###
# [...]
# ../../boot/ocamlrun ../../ocamlc -nostdlib -I ../../stdlib -I ../../otherlibs/unix -a -o stdlib.cma ../../stdlib/camlinternalFormatBasics.cmo pervasives.cmo ../../stdlib/array.cmo ../../stdlib/list.cmo ../../stdlib/char.cmo ../../stdlib/bytes.cmo ../../stdlib/string.cmo ../../stdlib/sys.cmo ../../stdlib/sort.cmo marshal.cmo ../../stdlib/obj.cmo ../../stdlib/int32.cmo ../../stdlib/int64.cmo ..[...]
# ../../boot/ocamlrun ../../tools/ocamlmklib -ocamlc '../../boot/ocamlrun ../../ocamlc -nostdlib -I ../../stdlib -I ../../otherlibs/unix' -o unix -linkall unix.cmo ../unix/unixLabels.cmo
# cc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE -Wall -I../../byterun  -I/usr/X11R6/include -c open.c
# In file included from open.c:19:
# ./libgraph.h:17:10: fatal error: 'X11/Xlib.h' file not found
# #include <X11/Xlib.h>
#          ^~~~~~~~~~~~
# 1 error generated.
# make[3]: *** [open.o] Error 1
# make[2]: *** [otherlibraries] Error 2
# make[1]: *** [all] Error 2
# make: *** [world] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.05.0
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─ 
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] n
```

Also: we already have a Homebrew ocaml compiler, we should use that and not download a new compiler.

**Comment by fxcoudert** [comment]
@jarrtt we have had to temporarily disable qcow2 support to restore the build: #33174
We would still welcome a PR that reenables qcow2 support by moving to opam 2, of course!

**Comment by fxcoudert** [comment]
I'm closing for now, please ask to reopen once you push things that work locally for you, or file a new PR. Thanks @jarrtt !
