### ISSUE TITLE
git-annex fails to build from source

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#17869]
`git-annex` currently [fails to build on all macOS versions from 10.10 to 10.13](https://jenkins.brew.sh/job/Homebrew%20Testing/161/). The error is:

```
[416 of 562] Compiling Command.ImportFeed ( Command/ImportFeed.hs, dist/dist-sandbox-c0ee19bc/build/git-annex/git-annex-tmp/Command/ImportFeed.o )

Command/ImportFeed.hs:139:61: error:
    • Couldn't match type ‘Data.Text.Internal.Text’ with ‘[Char]’
      Expected type: URLString
        Actual type: Text.Atom.Feed.URI
    • In the first argument of ‘Enclosure’, namely ‘enclosureurl’
      In the second argument of ‘($)’, namely ‘Enclosure enclosureurl’
      In the second argument of ‘($)’, namely
        ‘ToDownload f u i $ Enclosure enclosureurl’
```

The full logs (obtained on 10.13, but the error is the same on all macOS versions): https://gist.github.com/dcc8d9823bd50b7fca10d5cf8961e75d

**Comment by ilovezfs** [comment]
ok, I'll fix it :)
